#
# Automatically generated file; DO NOT EDIT.
# Camera SDK Platform Configuration
#

#
# General Setup
#
# CONFIG_SS528V100 is not set
# CONFIG_SS524V100 is not set
# CONFIG_SS626V100 is not set
export CONFIG_SS928V100=y
export CONFIG_OT_CHIP_TYPE=0x01090100
export CONFIG_OT_ARCH=ss928v100
export CONFIG_SUBCHIP_SS928V100=y
# CONFIG_SUBCHIP_SS000V100 is not set
export CONFIG_OT_SUBARCH=ss928v100
export CONFIG_OT_SUBCHIP_TYPE=0x01090100
export CONFIG_SMP=y
# CONFIG_AMP is not set
# CONFIG_UP is not set
export CONFIG_ARM_ARCH_TYPE=smp
# CONFIG_CPU_TYPE_SINGLE is not set
# CONFIG_CPU_TYPE_BIG_LITTLE is not set
# CONFIG_CPU_TYPE_MULTI_CORE is not set
export CONFIG_A55=y
export CONFIG_CPU_TYPE=a55
# CONFIG_VERSION_FPGA is not set
export CONFIG_VERSION_ASIC=y
export CONFIG_OT_FPGA=n
export CONFIG_LINUX_OS=y
# CONFIG_LITEOS_OS is not set
export CONFIG_OS_TYPE=linux
export CONFIG_PHYS_ADDR_BIT_WIDTH_64=y
# CONFIG_KERNEL_SPACE is not set
export CONFIG_USER_SPACE=y
export CONFIG_DRIVER_SPACE_TYPE=user_space
export CONFIG_LINUX_6_6_y=y
# CONFIG_LINUX_5_10_y is not set
# CONFIG_LINUX_4_19_y is not set
# CONFIG_LINUX_4_9_y is not set
export CONFIG_KERNEL_VERSION=linux-6.6.y
# CONFIG_KERNEL_AARCH64_MIX210 is not set
export CONFIG_KERNEL_AARCH64_LINUX_MUSL_LLVM1504=y
# CONFIG_KERNEL_AARCH64_V01C01_LINUX_MUSL is not set
export CONFIG_OT_CROSS=llvm-
export CONFIG_LIBC_TYPE=musl
export CONFIG_KERNEL_BIT=KERNEL_BIT_64
# CONFIG_USER_AARCH64_MIX210 is not set
export CONFIG_USER_AARCH64_LINUX_MUSL_LLVM1504=y
# CONFIG_USER_AARCH64_V01C01_LINUX_MUS is not set
export CONFIG_OT_CROSS_LIB=llvm-
export CONFIG_USER_BIT=USER_BIT_64
export CONFIG_LINUX_STYLE=y
# CONFIG_BOTH_STYLE is not set
export CONFIG_CODE_SYTLE=USE_LINUX_STYLE
export CONFIG_RELEASE_TYPE_RELEASE=y
# CONFIG_RELEASE_TYPE_DEBUG is not set
export CONFIG_OT_RLS_MODE=OT_RELEASE
export CONFIG_OT_PLATFORM_GEN8=y

#
# Media Modules Setup
#

#
# media audio config
#
export CONFIG_OT_AUDIO_SUPPORT=y
export CONFIG_OT_ACODEC_SUPPORT=y
export CONFIG_OT_ACODEC_VERSION=RemixV100
export CONFIG_OT_ACODEC_MAX_GAIN=56
export CONFIG_OT_ACODEC_MIN_GAIN=0
export CONFIG_OT_ACODEC_GAIN_STEP=3
export CONFIG_OT_ACODEC_FAST_POWER_SUPPORT=y
export CONFIG_OT_DOWNVQE_SUPPORT=y
export CONFIG_OT_TALKVQE_SUPPORT=y
export CONFIG_OT_RECORDVQE_SUPPORT=y
export CONFIG_OT_TALKVQEV2_SUPPORT=y
export CONFIG_OT_TALKVQEV2_WNR_SUPPORT=y
export CONFIG_OT_AUDIO_STATIC_REGISTER_SUPPORT=y
# CONFIG_OT_AUDIO_BCD_SUPPORT is not set
# CONFIG_OT_AUDIO_ALSA_SUPPORT is not set
# CONFIG_OT_AUDIO_ONLY_DRIVER_SUPPORT is not set

#
# media base config
#
export CONFIG_OT_VB_EXTPOOL_SUPPORT=y
# CONFIG_OT_VB_LOG_SUPPORT is not set
# CONFIG_OT_MDC_LOG_SUPPORT is not set
export CONFIG_OT_VB_SUPPLEMENT_MASK_SUPPORT=y
# CONFIG_OT_VB_ASYNC_SUPPORT is not set

#
# media chnl config
#
export CONFIG_OT_CHNL_SUPPORT=y

#
# media dis config
#
export CONFIG_OT_DIS_SUPPORT=y
export CONFIG_OT_DIS_SUBMIT_TO_VGS_SUPPORT=y

#
# media gdc config
#
export CONFIG_OT_GDC_SUPPORT=y
export CONFIG_OT_GDC_LOWDELAY_SUPPORT=y
export CONFIG_OT_GDC_FISHEYE_LMF_SUPPORT=y
export CONFIG_OT_GDC_FISHEYE_SUPPORT=y
# CONFIG_OT_GDC_NNIE_SHARE_RAM is not set
export CONFIG_OT_GDC_LDC_SUPPORT=y
export CONFIG_OT_GDC_LDC_V3_SUPPORT=y
export CONFIG_OT_GDC_SPREAD_SUPPORT=y

#
# media hdmi config
#
export CONFIG_OT_HDMI_SUPPORT=y

#
# media isp config
#
export CONFIG_OT_ISP_SUPPORT=y
export CONFIG_OT_ISP_AF_SUPPORT=y
export CONFIG_OT_ISP_CR_SUPPORT=y
export CONFIG_OT_ISP_PREGAMMA_SUPPORT=y
export CONFIG_OT_ISP_GCAC_SUPPORT=y
export CONFIG_OT_ISP_CA_SUPPORT=y
export CONFIG_OT_ISP_EDGEMARK_SUPPORT=y
export CONFIG_OT_ISP_HLC_SUPPORT=y
export CONFIG_OT_ISP_SPECAWB_SUPPORT=y
# CONFIG_OT_ISP_PQ_FOR_AI_SUPPORT is not set
export CONFIG_OT_ISP_DPC_STATIC_TABLE_SUPPORT=y
export CONFIG_OT_PQP_SUPPORT=y
export CONFIG_OT_ISP_HNR_SUPPORT=y

#
# media region config
#
export CONFIG_OT_REGION_SUPPORT=y
export CONFIG_OT_RGN_CORNER_RECT_SUPPORT=y
# CONFIG_OT_RGN_OVERLAP_SUPPORT is not set
# CONFIG_OT_RGN_POSITION_SORT_SUPPORT is not set
# CONFIG_OT_RGN_EXPORT_MODIFY_SUPPORT is not set

#
# media sys config
#
export CONFIG_OT_SYS_SUPPORT=y
export CONFIG_OT_SYS_SCALE_COEF_SUPPORT=y
export CONFIG_OT_SYS_SCALE_COEF_ONLINE_SUPPORT=y
export CONFIG_OT_SYS_SMMU_SUPPORT=y
# CONFIG_OT_SYS_MUTEX_REG_SUPPORT is not set

#
# media tde config
#
export CONFIG_OT_TDE_SUPPORT=y

#
# media vda config
#
# CONFIG_OT_VDA_SUPPORT is not set

#
# media vdec config
#
export CONFIG_OT_VDEC_SUPPORT=y
export CONFIG_OT_H265D_SUPPORT=y
export CONFIG_OT_H264D_SUPPORT=y
export CONFIG_OT_JPEGD_SUPPORT=y
# CONFIG_OT_VDEC_MDC_SUPPORT is not set
export CONFIG_OT_DEC_SHVC_SUPPORT=y
export CONFIG_VDEC_IP=VDEC_IP_VDH
# CONFIG_OT_JPEGD_RGB_OUTPUT_SUPPORT is not set
export CONFIG_OT_JPEGD_PROGRESSIVE=y
# CONFIG_OT_JPEGD_SOFT_BASELINE is not set
export CONFIG_VDEC_ROTATION_SUPPORT=y
# CONFIG_VDEC_TILE_ROTATION_SUPPORT is not set
export CONFIG_VDEC_USERPIC_SUPPORT=y
export CONFIG_VDEC_USERDATA_SUPPORT=y
export CONFIG_VDEC_LOWDELAY_SUPPORT=y
# CONFIG_OT_VDEC_QUICK_SCHEDULE_SUPPORT is not set

#
# media venc config
#
export CONFIG_OT_VENC_SUPPORT=y
export CONFIG_OT_H265E_SUPPORT=y
# CONFIG_OT_H265E_QUANTIZATION_SUPPORT is not set
export CONFIG_OT_H265E_USERDATA_SUPPORT=y
export CONFIG_OT_H265E_INTRA_REFRESH_SUPPORT=y
export CONFIG_OT_H264E_SUPPORT=y
# CONFIG_OT_H264E_QUANTIZATION_SUPPORT is not set
export CONFIG_OT_H264E_USERDATA_SUPPORT=y
export CONFIG_OT_H264E_INTRA_REFRESH_SUPPORT=y
export CONFIG_OT_JPEGE_SUPPORT=y
export CONFIG_OT_JPEGE_ROI_SUPPORT=y
export CONFIG_OT_MJPEGE_SUPPORT=y
export CONFIG_OT_JPEGE_MPF_DCF_SUPPORT=y
export CONFIG_OT_JPEGE_USERDATA_SUPPORT=y
export CONFIG_OT_VENC_LOWDELAY_SUPPORT=y
export CONFIG_OT_VENC_VPSSAUTO_SUPPORT=y
# CONFIG_OT_VENC_OVERLAYEX_SUPPORT is not set
export CONFIG_OT_VENC_FRAMEBUF_RECYCLE_SUPPORT=y
export CONFIG_OT_VENC_VGS_SUPPORT=y
export CONFIG_OT_VENC_SVC_SUPPORT=y
# CONFIG_OT_VENC_ADVSMARTP_SUPPORT is not set
export CONFIG_OT_VENC_SMARTP_SUPPORT=y
# CONFIG_OT_VENC_BIPREDB_SUPPORT is not set
export CONFIG_OT_VENC_DUALP_SUPPORT=y
export CONFIG_OT_VENC_RCNREF_SHARE_SUPPORT=y
export CONFIG_OT_VENC_DEBREATH_SUPPORT=y
export CONFIG_OT_VENC_SKIPREF_SUPPORT=y
export CONFIG_OT_VENC_SCENE0_SUPPORT=y
export CONFIG_OT_VENC_SCENE1_SUPPORT=y
export CONFIG_OT_VENC_SCENE2_SUPPORT=y
export CONFIG_OT_RC_AVBR_SUPPORT=y
export CONFIG_OT_RC_QPMAP_SUPPORT=y
export CONFIG_OT_RC_QVBR_SUPPORT=y
export CONFIG_OT_RC_CVBR_SUPPORT=y
export CONFIG_OT_VENC_COMPOSITE_SUPPORT=y
# CONFIG_OT_NEON_CODE_SUPPORT is not set

#
# media vgs config
#
export CONFIG_OT_VGS_SUPPORT=y
export CONFIG_OT_VGS_STITCH_SUPPORT=y
export CONFIG_OT_VGS_LUMA_STAT_SUPPORT=y
export CONFIG_OT_VGS_CORNER_RECT_SUPPORT=y
export CONFIG_OT_VGS_SHBD_SUPPORT=y
export CONFIG_OT_VGS_MCF_SUPPORT=y
export CONFIG_OT_VGS_LOW_DELAY_SUPPORT=y
export CONFIG_OT_VGS_FPD_SUPPORT=y
export CONFIG_OT_VGS_MULTI_CHN_SUPPORT=y
export CONFIG_OT_VGS_GME_SUPPORT=y
export CONFIG_OT_VGS_MOSAIC_ONLINE_SUPPORT=y
export CONFIG_OT_VGS_USER_ONLINE_SUPPORT=y

#
# media vi config
#
export CONFIG_OT_VI_SUPPORT=y
export CONFIG_OT_VI_ALL_SUPPORT=y
# CONFIG_OT_VI_XVR_SUPPORT is not set
export CONFIG_OT_VI_DEV_BAS=y
export CONFIG_OT_VI_DEV_SEND_FRAME=y
export CONFIG_OT_VI_DEV_GENERATE_TIMING=y
export CONFIG_OT_VI_DEV_GENERATE_DATA=y
export CONFIG_OT_VI_VIRT_PIPE=y
export CONFIG_OT_VI_PIPE_PRE_CROP=y
export CONFIG_OT_VI_PIPE_POST_CROP=y
export CONFIG_OT_VI_PIPE_DUMP_FRAME=y
export CONFIG_OT_VI_PIPE_DUMP_PRIVATE_DATA=y
export CONFIG_OT_VI_PIPE_BAS=y
export CONFIG_OT_VI_PIPE_SEND_FRAME=y
export CONFIG_OT_VI_PIPE_INTERRUPT_EN=y
export CONFIG_OT_VI_PIPE_LOW_DELAY=y
export CONFIG_OT_VI_PIPE_FRAME_INTERRUPT_TYPE=y
export CONFIG_OT_VI_PIPE_GET_COMPRESS_PARAM=y
export CONFIG_OT_VI_PIPE_USER_PIC=y
export CONFIG_OT_VI_PIPE_FPN=y
export CONFIG_OT_VI_PIPE_IR_ASSIST_NR=y
export CONFIG_OT_VI_PIPE_BNR=y
export CONFIG_OT_VI_PIPE_HNR=y
export CONFIG_OT_VI_CHN_LOW_DELAY=y
export CONFIG_OT_VI_CHN_DIS=y
export CONFIG_OT_VI_CHN_ROTATION=y
export CONFIG_OT_VI_CHN_LDC=y
export CONFIG_OT_VI_CHN_SPREAD=y
export CONFIG_OT_VI_CHN_RGN_LUMA=y
export CONFIG_OT_VI_CHN_FOV_CORRECTION=y
export CONFIG_OT_VI_CHN_FISHEYE=y
export CONFIG_OT_VI_EXT_CHN=y
export CONFIG_OT_VI_STITCH_GRP=y
export CONFIG_OT_VI_PTS=y

#
# media vo config
#
export CONFIG_OT_VO_SUPPORT=y
export CONFIG_OT_VO_HD=y
export CONFIG_OT_VO_VPSS_AUTO=y
export CONFIG_OT_VO_PLAY_CTL=y
export CONFIG_OT_VO_LUMA=y
export CONFIG_OT_VO_COVER_OSD_SUPPORT=y
export CONFIG_OT_VO_CORNER_RECT_SUPPORT=y
export CONFIG_OT_VO_VIRTDEV_SUPPORT=y
export CONFIG_OT_VO_VGS=y
export CONFIG_OT_VO_GRAPH=y
export CONFIG_OT_VO_BATCH=y
# CONFIG_OT_VO_WBC is not set
# CONFIG_OT_VO_CASCADE is not set
export CONFIG_OT_VO_LOW_DELAY=y
export CONFIG_OT_VO_BORDER_BY_COVER=y
export CONFIG_OT_VO_CVBS=y
# CONFIG_OT_VO_VGA is not set
export CONFIG_OT_VO_RGB=y
export CONFIG_OT_VO_BT1120=y
export CONFIG_OT_VO_MIPI=y
export CONFIG_OT_VO_HDMI=y
# CONFIG_OT_VO_HDMI1 is not set
# CONFIG_OT_VO_LESS_BUF is not set
# CONFIG_OT_VO_USER_NOTIFY is not set
export CONFIG_OT_VO_DEV_BYPASS=y
# CONFIG_OT_VO_LAYER_ASPECT_RATIO is not set
# CONFIG_OT_VO_CHN_ASPECT_RATIO is not set
# CONFIG_OT_VO_QUICK_SCHEDULE_SUPPORT is not set
export CONFIG_OT_VO_EXPORT_FUNCTION=y
# CONFIG_OT_VO_VPSS_2QUERY_DEPTH is not set
# CONFIG_OT_VO_BT1120_DUAL_EDGE is not set
export CONFIG_OT_VO_FB_SEPARATE=y

#
# media vpss config
#
export CONFIG_OT_VPSS_SUPPORT=y
export CONFIG_OT_VPSS_ONLINE_SUPPORT=y
export CONFIG_OT_VPSS_SLAVE_SUPPORT=y
export CONFIG_OT_VPSS_3DNR_SUPPORT=y
export CONFIG_OT_VPSS_3DNR_GAMMA_SUPPORT=y
export CONFIG_OT_VPSS_3DNR_BNR_LINKAGE_SUPPORT=y
export CONFIG_OT_VPSS_3DNR_DELAY_MODE_SUPPORT=y
export CONFIG_OT_VPSS_AUTO_SUPPORT=y
export CONFIG_OT_VPSS_BACKUP_SUPPORT=y
export CONFIG_OT_VPSS_COVER_SUPPORT=y
export CONFIG_OT_VPSS_MOSAIC_SUPPORT=y
export CONFIG_OT_VPSS_DELAY_SUPPORT=y
export CONFIG_OT_VPSS_2SCALE_SUPPORT=y
export CONFIG_OT_VPSS_VGS_GRP_SUPPORT=y
export CONFIG_OT_VPSS_BUFFER_REUSE_SUPPORT=y
export CONFIG_OT_VPSS_LOW_DELAY_SUPPORT=y
export CONFIG_OT_VPSS_IPC_SUPPORT=y
export CONFIG_OT_VPSS_EXT_CHN_SUPPORT=y
export CONFIG_OT_VPSS_CHN_CROP_SUPPORT=y
export CONFIG_OT_VPSS_MCF_SUPPORT=y
export CONFIG_OT_VPSS_CHN_LDC_SUPPORT=y
export CONFIG_OT_VPSS_CHN_SPREAD_SUPPORT=y
export CONFIG_OT_VPSS_2DOF_SUPPORT=y

#
# media avs config
#
# CONFIG_OT_AVS_SUPPORT is not set

#
# media vpp config
#
export CONFIG_OT_VPP_SUPPORT=y
export CONFIG_OT_VPP_FOV_CORRECTION_SUPPORT=y
export CONFIG_OT_VPP_BNR_SUPPORT=y
export CONFIG_OT_VPP_VI_SUPPORT=y
export CONFIG_OT_VPP_COVEREX_RATIO_SUPPORT=y

#
# media dcc config
#
# CONFIG_OT_DCC_SUPPORT is not set

#
# media uvc config
#
# CONFIG_OT_UVC_SUPPORT is not set

#
# media suhd config
#
# CONFIG_OT_SUHD_SUPPORT is not set

#
# media aiv config
#
export CONFIG_OT_AIV_SUPPORT=y

#
# media irq config
#
export CONFIG_OT_IRQ_SUPPORT=y

#
# media proc config
#
export CONFIG_OT_PROC_SUPPORT=y

#
# Device Driver Setup
#

#
# drv config
#
export CONFIG_DRV=y
export CONFIG_EXTDRV=y
export CONFIG_INTERDRV=y
export CONFIG_OT_USER=y
export CONFIG_MIPI_TX=y
export CONFIG_MIPI_RX=y
export CONFIG_OT_IR=y
export CONFIG_OT_LSADC=y
export CONFIG_OT_WDG=y
export CONFIG_OT_SYSCFG=y

#
# Component Setup
#

#
# Component security_subsys Config
#
export CONFIG_OT_SECURITY_SUBSYS_SUPPORT=y
export CONFIG_OT_CIPHER_SUPPORT=y
export CONFIG_OT_OTP_SUPPORT=y
export CONFIG_OT_KLAD_SUPPORT=y

#
# Component gfbg Config
#
export CONFIG_OT_GFBG_SUPPORT=y
# CONFIG_GFBG_DPU_V1 is not set
# CONFIG_GFBG_DPU_V2 is not set
export CONFIG_GFBG_DPU_V3=y

#
# Component ot_syslink Config
#
# CONFIG_OT_OT_SYSLINK_SUPPORT is not set

#
# Component pciv Config
#
export CONFIG_OT_PCIV_SUPPORT=y

#
# Component avs lut Config
#
# CONFIG_OT_AVS_LUT_SUPPORT is not set

#
# Component avs convert Config
#
# CONFIG_OT_AVS_CONVERT_SUPPORT is not set

#
# Component pos_query Config
#
# CONFIG_OT_POS_QUERY_SUPPORT is not set

#
# Component snap Config
#
export CONFIG_OT_SNAP_SUPPORT=y

#
# Component photo Config
#
# CONFIG_OT_PHOTO_SUPPORT is not set

#
# Component heif Config
#
# CONFIG_OT_HEIF_SUPPORT is not set

#
# Component svp Config
#
export CONFIG_OT_SVP_SUPPORT=y
# CONFIG_OT_SVP_DSP is not set
export CONFIG_OT_SVP_IVE=y
export CONFIG_OT_SVP_IVE_CSC=y
export CONFIG_OT_SVP_IVE_FILTER_AND_CSC=y
export CONFIG_OT_SVP_IVE_NCC=y
export CONFIG_OT_SVP_IVE_LBP=y
export CONFIG_OT_SVP_IVE_NORM_GRAD=y
export CONFIG_OT_SVP_IVE_ST_CANDI_CORNER=y
export CONFIG_OT_SVP_IVE_RESIZE=y
export CONFIG_OT_SVP_IVE_PERSP_TRANS=y
export CONFIG_OT_SVP_IVE_KCF=y
export CONFIG_OT_SVP_IVE_HOG=y
export CONFIG_OT_SVP_MD=y
export CONFIG_OT_SVP_MAU=y
# CONFIG_OT_SVP_NPU_V1R1 is not set
# CONFIG_OT_SVP_NPU_V1R1_COMPILE is not set
export CONFIG_OT_SVP_NPU_V2R1=y
export CONFIG_OT_SVP_DPU_RECT=y
export CONFIG_OT_SVP_DPU_MATCH=y

#
# Component motionfusion config
#
export CONFIG_OT_MOTIONFUSION_SUPPORT=y

#
# Component mcf Config
#
# CONFIG_OT_MCF_SUPPORT is not set

#
# Component securec Config
#
export CONFIG_OT_SECUREC_SUPPORT=y
# CONFIG_OT_SECUREC_KERNEL_SUPPORT is not set

#
# Component aiv Config
#

#
# Debug Config
#
export CONFIG_OT_GDB_NO=y
# CONFIG_OT_GDB_YES is not set
export CONFIG_OT_GDB=n
export CONFIG_OT_PROC_SHOW_SUPPORT=y
export CONFIG_OT_LOG_TRACE_SUPPORT=y
export CONFIG_OT_LOG_TRACE_ALL=y
# CONFIG_OT_LOG_TRACE_ERR is not set
# CONFIG_OT_LOG_TRACE_WARN is not set
# CONFIG_OT_LOG_TRACE_INFO is not set
export CONFIG_OT_LOG_TRACE_LEVEL=7

#
# Test Config
#
