# Describe the include path, using the full path

# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_SYS_ROOT)/mkp/src/sys_bind.c
SRCS += $(CBB_SYS_ROOT)/mkp/src/sys_ext.c