/*
 * nand_yaffs_c4.c — on-board C4 image-compat test
 * (YAFFS2_BINARY_LIB_PORTING_PLAN.md C4-②, decision E).
 *
 * Proves the fbb production image format is mountable by the CLOSED
 * prebuilt archive running on this port: an embedded fbb mkyaffs2image
 * sample volume (third_party/yaffs2/include/c4_fixture.h, generated by
 * third_party/yaffs2/tools/gen_c4_fixture.sh) is written into the /boot
 * volume through the SAME mtd free-stream interface the closed archive
 * itself uses (mtd->write_oob with the combined data+spare page buffer,
 * i.e. the on-flash layout including the 2-byte BBM), then mounted and
 * every sample file is read back and compared byte-for-byte.
 *
 * Flow (all /boot indices refer to volume part 0):
 *   1. VFS umount /boot (adapter yaffs_unmount + yaffs_end pair)
 *   2. erase the whole /boot span via g_nand_mtd->erase (per-block kick)
 *   3. write the 11 fixture pages via mtd->write_oob at the volume's first
 *      erase block (the image is generated from page 0 of a volume)
 *   4. mount /boot — the closed archive scans and mounts the fbb image
 *   5. open/read/compare hello.txt / pattern.bin (3 chunks) / subdir/nested.txt
 *   6. leave the image volume mounted: the NEXT boot remounts it (a free
 *      second-pass proof that the image survives a reset) — the smoke test
 *      rebuilds its own files on top (O_CREAT).
 */
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <unistd.h>

#include "los_printf.h"
#include "debug_print.h"    /* PRINT (fmc compat macro) */
#include "linux/mtd/mtd.h"
#include "mtd_partition.h"
#include "nand_yaffs_bridge.h"
#include "watchdog.h"

#include "c4_fixture.h"

#define C4_VOL_PART 0 /* /boot */

static int c4_check_file(const char *path, const unsigned char *expect, unsigned len)
{
    static unsigned char buf[C4_PATTERN_LEN];
    int fd = open(path, O_RDONLY);
    ssize_t n;

    if (fd < 0) {
        PRINT("nand_c4: open %s FAIL errno=%d\n", path, errno);
        return 1;
    }
    n = read(fd, buf, len);
    (void)close(fd);
    if (n != (ssize_t)len) {
        PRINT("nand_c4: read %s short (%d/%u)\n", path, (int)n, len);
        return 1;
    }
    if (memcmp(buf, expect, len) != 0) {
        PRINT("nand_c4: %s content MISMATCH\n", path);
        return 1;
    }
    PRINT("nand_c4: %s ok (%u bytes)\n", path, len);
    return 0;
}

int nand_yaffs_c4_test(void)
{
    const mtd_partition *part = nand_yaffs_get_part(C4_VOL_PART);
    struct mtd_info *mtd = nand_yaffs_get_mtd();
    uint32_t pages_per_block;
    uint32_t base_page;
    uint32_t blk;
    int p;
    int fails = 0;

    if ((part == NULL) || (mtd == NULL)) {
        PRINT("nand_c4: no /boot partition or mtd\n");
        return 1;
    }

    /* 1. umount /boot so the raw writes do not fight the live fs */
    if (nand_yaffs_umount(C4_VOL_PART) != 0) {
        PRINT("nand_c4: umount /boot FAIL\n");
        return 1;
    }

    /* 2. erase the whole /boot span (mirrors a production burn) */
    PRINT("nand_c4: erasing /boot blocks %u..%u\n",
          part->start_block, part->end_block);
    for (blk = part->start_block; blk <= part->end_block; blk++) {
        struct erase_info opts;
        int ret;

        uapi_watchdog_kick();
        if (mtd->block_isbad(mtd, (loff_t)((uint64_t)blk * mtd->erasesize)) == 1) {
            continue;
        }
        (void)memset_s(&opts, sizeof(opts), 0, sizeof(opts));
        opts.addr = (uint64_t)blk * mtd->erasesize;
        opts.len = mtd->erasesize;
        opts.mtd = mtd;
        ret = mtd->erase(mtd, &opts);
        if (ret != 0) {
            PRINT("nand_c4: erase blk %u fail ret=%d\n", blk, ret);
            ++fails;
        }
        if (((blk - part->start_block) % 16U) == 0U) {
            uapi_watchdog_kick();
        }
    }
    if (fails != 0) {
        PRINT("nand_c4: erase failures, abort\n");
        (void)nand_yaffs_mount(C4_VOL_PART, NULL);
        return 1;
    }

    /* 3. write the fixture pages at the volume's first erase block: the
     * mtd free stream (write_oob combined buffer) IS the on-flash layout
     * the production burner produces — BBM + packedtags2 + tags ECC */
    pages_per_block = mtd->erasesize / mtd->writesize;
    base_page = part->start_block * pages_per_block;
    for (p = 0; p < C4_IMAGE_PAGES; p++) {
        size_t retlen = 0;
        loff_t addr = (loff_t)((uint64_t)(base_page + (uint32_t)p) * mtd->writesize);
        int ret;

        uapi_watchdog_kick();
        ret = mtd->write_oob(mtd, addr, mtd->writesize + mtd->oobsize,
                             &retlen,
                             (const char *)&g_c4_image[(uint32_t)p * C4_PAGE_SIZE]);
        /*
         * fbb nand_write_oob leaves *retlen untouched (unused(retlen),
         * fbb-verbatim): ret==0 plus the step-5 byte-exact readback is the
         * real proof, so retlen is NOT checked here. Evidence (fpu board
         * round 1): all 11 pages returned ret=0 retlen=0 while the data
         * provably landed on flash (the remount reported "1 blocks to be
         * sorted" — exactly the 11-page partial fixture block).
         */
        if (ret != 0) {
            PRINT("nand_c4: write page %d fail ret=%d retlen=%u\n",
                  p, ret, (unsigned)retlen);
            ++fails;
        }
    }
    if (fails != 0) {
        PRINT("nand_c4: image write failures\n");
        (void)nand_yaffs_mount(C4_VOL_PART, NULL);
        return 1;
    }
    PRINT("nand_c4: %u image pages written @page %u\n", C4_IMAGE_PAGES, base_page);

    /* 4. mount the fbb image with the CLOSED archive */
    if (nand_yaffs_mount(C4_VOL_PART, NULL) != 0) {
        PRINT("nand_c4: MOUNT of fbb image FAIL (format incompatible)\n");
        return 1;
    }
    PRINT("nand_c4: fbb image MOUNTED by closed archive\n");

    /* 5. byte-exact content compare of every sample file */
    fails += c4_check_file("/boot/hello.txt", g_c4_hello, C4_HELLO_LEN);
    fails += c4_check_file("/boot/pattern.bin", g_c4_pattern, C4_PATTERN_LEN);
    fails += c4_check_file("/boot/subdir/nested.txt", g_c4_nested, C4_NESTED_LEN);

    /* 6. image stays mounted — next boot re-mounts it across reset */
    if (fails == 0) {
        PRINT("nand_c4: PASS (fbb image compat proven end to end)\n");
    } else {
        PRINT("nand_c4: FAIL (%d)\n", fails);
    }
    return fails;
}
