# Copyright (C) 2024 HiHope Open Source Organization .
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/lite/config/component/lite_component.gni")
import("//test/xts/tools/lite/hctest/hctest_opt_args.gni")

declare_args() {
  build_ws63_sdk_open = false
  enable_hos_vendor_wifiiot_xts = false
  enable_oh_device_lite_auth = true
  build_ws63_mode = "normal"
  enable_product_config_patch = false
}

build_env = "BUILD_WS63_MODE=${build_ws63_mode} ENABLE_PRODUCT_CONFIG_PATCH=${enable_product_config_patch}"
if (build_xts) {
  build_env += " BUILD_XTS=1"
}
build_env += " XTS_OVERLAY_ARG=${xts_overlay} HCTEST_RODATA_OPT_ARG=${hctest_rodata_opt}"
group("nearllink_sdk") {
  deps = [ ":sdk" ]
}

build_ext_component("run_sdk_build") {
  exec_path = rebase_path(".", root_build_dir)
  outdir = rebase_path(root_out_dir)
  command ="env $build_env bash hm_build.sh $outdir $build_ws63_sdk_open"

  #  command = "python3 build.py -c ws63-liteos-app"
  #  if (host_os == "win") {
  #    command = "bash hm_build.sh $outdir win"
  #  } else {
  #    command = "bash hm_build.sh $outdir linux"
  #  }
  deps = [
    ":sdk",
    "//build/lite:ohos"
  ]
  if (enable_oh_device_lite_auth) {
    deps += ["//base/security/device_auth/frameworks/deviceauth_lite:hichainsdk"]
  }
  if (enable_hos_vendor_wifiiot_xts) {
    deps += [ "//build/lite/config/subsystem/xts:xts" ]
  }
}

lite_component("sdk") {
  features = []

  deps = [
    "//build/lite/config/component/cJSON:cjson_static",
    "//device/soc/hisilicon/ws63v100/adapter/hals/communication/ble_lite",
    "//device/soc/hisilicon/ws63v100/adapter/hals/communication/sle_lite",
    "//device/soc/hisilicon/ws63v100/adapter/hals/communication/wifi_lite/wifiservice",
    "//device/soc/hisilicon/ws63v100/adapter/hals/utils/kv_store:kv_store",

    #   "//device/soc/hisilicon/ws63v100/adapter/kal",
  ]
}
