#!/bin/bash
set -e
product_out_dir="$1"
build_ws63_sdk_open="$2"
# XTS overlay isolation (mirrors hi3861 sdk_liteos/hm_build.sh): turn the
# GN-forwarded env vars (XTS_OVERLAY_ARG / HCTEST_RODATA_OPT_ARG) into the
# link-script preprocessor defines consumed by build_linker.cmake.
# XTS_OVERLAY_ENABLE gates the OVERLAY block + .bss EXCLUDE_FILE in linker.prelds;
# HCTEST_NEW_RUNNER gates the .xts_init KEEP blocks (active when either overlay
# or rodata_opt is on, since the shared hctest.c RunAllXtsTests + .xts_init
# mechanism needs them in both cases). Exported so the python3 build.py / cmake
# subprocess inherits them.
if [ "$XTS_OVERLAY_ARG" = "true" ]; then
    export XTS_OVERLAY_ENABLE=true
fi
if [ "$XTS_OVERLAY_ARG" = "true" ] || [ "$HCTEST_RODATA_OPT_ARG" = "true" ]; then
    export HCTEST_NEW_RUNNER=true
fi
# prebuild #
CROOT=$(pwd)

OUTPUT_SRC_DIR=$CROOT/output/ws63/fwpkg
OUTPUT_DST_DIR=$1

OHOS_LIBS_DIR=$CROOT/interim_binary/ws63/libs/ohos/ws63-liteos-app
OHOS_LIBS_XTS_DIR=$CROOT/interim_binary/ws63/libs/ohos/ws63-liteos-xts

rm $OHOS_LIBS_DIR -rf
rm $OHOS_LIBS_XTS_DIR -rf

mkdir -p $OHOS_LIBS_DIR
mkdir -p $OHOS_LIBS_XTS_DIR

find $OUTPUT_DST_DIR/libs/ -name '*.a' -exec cp "{}" $OHOS_LIBS_XTS_DIR  \;
find $OUTPUT_DST_DIR/libs/ -name '*.a' -exec cp "{}" $OHOS_LIBS_DIR  \;
# Copy source-switch marker file (generated by OHOS GN write_file) to interim for SDK cmake dual-gate
cp $OUTPUT_DST_DIR/mbedtls_ohos_switch.marker $OHOS_LIBS_XTS_DIR/ 2>/dev/null || true
cp $OUTPUT_DST_DIR/mbedtls_ohos_switch.marker $OHOS_LIBS_DIR/ 2>/dev/null || true


# build #
echo "build ws63 sdk = $build_ws63_sdk_open"
if [ "$build_ws63_sdk_open" = "true" ]; then
    export build_ws63_sdk_open=true
    echo "export build_ws63_sdk_open=true "
fi

# XTS test module list
ALL_XTS_MODULES=(
    "ActsBootstrapTest"
    "ActsHuksHalFunctionTest"
    "ActsDfxFuncTest"
    "ActsHieventLiteTest"
    "ActsSamgrTest"
    "ActsUpdaterFuncTest"
    "ActsDeviceAttestTest"
)

# Per-module re-link: replace other modules' .a with empty ones, let CMake re-link+sign
relink_and_copy_bin() {
    local module_name="$1"
    local build_dir="$CROOT/output/ws63/acore/ws63-liteos-xts"
    local testcases_dir="$OUTPUT_DST_DIR/suites/acts/testcases"
    local libs_dir="$CROOT/interim_binary/ws63/libs/ohos/ws63-liteos-xts"
    local backup_dir=$(mktemp -d)

    # Backup and replace other modules' .a files with empty ones
    for other_module in "${ALL_XTS_MODULES[@]}"; do
        if [ "$other_module" != "$module_name" ]; then
            local a_file="$libs_dir/libmodule_${other_module}.a"
            if [ -f "$a_file" ]; then
                cp "$a_file" "$backup_dir/"
                rm -f "$a_file"
                ar rcs "$a_file"
            fi
        fi
    done

    # Force re-link by deleting .elf and .bin (CMake will detect missing files)
    cd "$build_dir"
    rm -f ws63-liteos-xts.elf ws63-liteos-xts.bin ws63-liteos-xts-sign.bin ws63-liteos-xts_rom.bin

    # Use CMake's own build system to re-link, objcopy, and sign
    make WS63_GENERAT_SIGNBIN 2>&1
    local make_ret=$?

    # Restore original .a files
    for other_module in "${ALL_XTS_MODULES[@]}"; do
        if [ "$other_module" != "$module_name" ]; then
            local a_file="$libs_dir/libmodule_${other_module}.a"
            if [ -f "$backup_dir/libmodule_${other_module}.a" ]; then
                cp "$backup_dir/libmodule_${other_module}.a" "$a_file"
            fi
        fi
    done
    rm -rf "$backup_dir"

    if [ $make_ret -ne 0 ]; then
        echo "Error: make failed for $module_name (ret=$make_ret)"
        cd "$CROOT"
        return 1
    fi

    # Generate .fwpkg (full firmware package with updated app partition)
    cd "$CROOT"
    local fwpkg_dir="$CROOT/output/ws63/fwpkg/ws63-liteos-xts"
    rm -rf "$fwpkg_dir"
    python3 tools/pkg/packet.py ws63 ws63-liteos-xts ''
    local pkt_ret=$?
    if [ $pkt_ret -ne 0 ]; then
        echo "Error: packet.py failed for $module_name (ret=$pkt_ret)"
        return 1
    fi

    # Copy .fwpkg to testcases directory and update .json config
    local fwpkg_file="$fwpkg_dir/ws63-liteos-xts_all.fwpkg"
    if [ -f "$fwpkg_file" ]; then
        echo "  [$module_name] Generated .fwpkg: $(ls -la "$fwpkg_file" | awk '{print $5}') bytes"
        find "$testcases_dir" -name "${module_name}.json" | while read json_file; do
            local dir=$(dirname "$json_file")
            # Copy .fwpkg
            cp "$fwpkg_file" "$dir/${module_name}.fwpkg"
            echo "  Copied .fwpkg to $dir/${module_name}.fwpkg"
            # Update .json: change burn_file from .bin to .fwpkg
            sed -i "s/${module_name}.bin/${module_name}.fwpkg/g" "$json_file"
            echo "  Updated $json_file to reference .fwpkg"
        done
    else
        echo "Error: .fwpkg not found for $module_name"
        return 1
    fi

    cd "$CROOT"
}

if [[ "$product_out_dir" == *xts* ]]; then
    # Step 1: Single full build with all test modules
    python3 build.py -c ws63-liteos-xts

    # Step 2: Per-module re-link (a few seconds per module)
    for module_name in "${ALL_XTS_MODULES[@]}"; do
        echo "============================================"
        echo "Re-linking module: $module_name"
        echo "============================================"
        relink_and_copy_bin "$module_name"
    done
    # Step 3: Restore full build (all modules) and generate complete fwpkg
    echo "============================================"
    echo "Restoring full build with all test modules"
    echo "============================================"
    cd "$CROOT/output/ws63/acore/ws63-liteos-xts"
    rm -f ws63-liteos-xts.elf ws63-liteos-xts.bin ws63-liteos-xts-sign.bin ws63-liteos-xts_rom.bin
    make WS63_GENERAT_SIGNBIN 2>&1
    full_make_ret=$?
    cd "$CROOT"
    if [ $full_make_ret -ne 0 ]; then
        echo "Warning: Full rebuild failed, keeping last module's fwpkg"
    else
        rm -rf "$CROOT/output/ws63/fwpkg/ws63-liteos-xts"
        python3 tools/pkg/packet.py ws63 ws63-liteos-xts ''
        echo "Full XTS fwpkg restored successfully."
    fi

    echo "All per-module .fwpkg files generated successfully."
else
    python3 build.py -c ws63-liteos-app
fi

if [ "$build_ws63_sdk_open" = "true" ]; then
echo "build ws63 sdk"
target_file="sdk.tar.gz"
cd ../../../../../
rm -rf sdk_temp
mkdir -p sdk_temp

echo "copy drivers to $sdk_temp"
cp -rf drivers applications  base  vendor .gn build.py  commonlibrary  device  ide  kernel   test   third_party arkcompiler  build  build.sh  developtools   domains  foundation  interface  napi_generator  productdefine  sdk_temp

find sdk_temp -name ".git" -type d -exec rm -rf {} \; || true
find sdk_temp/device/soc/hisilicon/ws63v100/src/open_source/mbedtls -type f -name "*.c" -delete
find sdk_temp/device/soc/hisilicon/ws63v100/src/open_source/lwip -type f -name "*.c" -delete
find sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS -type f -name "*.c" -delete
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/arch/riscv/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/compat/cmsis/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/compat/linux/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/drivers/base/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/drivers/interrupt/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/fs/compat/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/fs/vfs/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/base/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/extended/console/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/extended/cpup/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/kernel/init/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/libc/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/liteos_libc/arch/riscv32/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/liteos_libc/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/targets/CMakeLists.txt
echo "" > sdk_temp/device/soc/hisilicon/ws63v100/src/kernel/liteos/liteos_v208.5.0/Huawei_LiteOS/lib/libm/CMakeLists.txt

tar --warning=no-file-changed -zcvf $target_file sdk_temp
fi

#
# after build #
if [ ! -d $OUTPUT_DST_DIR ]; then
   mkdir $OUTPUT_DST_DIR
fi
cp $OUTPUT_SRC_DIR/* $OUTPUT_DST_DIR/ -rf

