GFBG_SRC +=drv/adp/gfbg_vou_drv.c
GFBG_SRC +=drv/adp/gfbg_blit.c
GFBG_SRC +=drv/adp/gfbg_vou_graphics.c
GFBG_SRC +=drv/adp/gfbg_graphics_drv.c
GFBG_SRC +=drv/adp/gfbg_graphic_hal.c
GFBG_SRC +=drv/adp/gfbg_comm.c
GFBG_SRC +=drv/adp/gfbg_rotate.c
ifneq ($(findstring $(OT_ARCH), ss524v100 ss528v100),)
GFBG_SRC +=drv/adp/gfbg_rotate_vgs.c
else
GFBG_SRC +=drv/adp/gfbg_rotate_tde.c
endif


