/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_lp_ctl_ulp_b_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_LP_CTL_ULP_B_RB_REG_OFFSET_FIELD_H__
#define __3322_LP_CTL_ULP_B_RB_REG_OFFSET_FIELD_H__

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_ID_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_ID_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_ID_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG1_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG1_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG1_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG2_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG2_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG2_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG3_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG3_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG3_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG4_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG4_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG4_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG5_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG5_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG5_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG6_LEN	        16
#define	LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG6_OFFSET	        0
#define LP_CTL_ULP_B_RB_LP_CTL_ULP_B_GP_REG6_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_CLR_ULP_VALID_LEN	        1
#define	LP_CTL_ULP_B_RB_SYS_TICK_CLR_ULP_VALID_OFFSET	        4
#define LP_CTL_ULP_B_RB_SYS_TICK_CLR_ULP_VALID_MASK    		0x10
#define	LP_CTL_ULP_B_RB_SYS_TICK_STZ_ULP_LEN	        1
#define	LP_CTL_ULP_B_RB_SYS_TICK_STZ_ULP_OFFSET	        1
#define LP_CTL_ULP_B_RB_SYS_TICK_STZ_ULP_MASK    		0x2
#define	LP_CTL_ULP_B_RB_SYS_TICK_FRZ_ULP_LEN	        1
#define	LP_CTL_ULP_B_RB_SYS_TICK_FRZ_ULP_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_FRZ_ULP_MASK    		0x1

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_0_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_0_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_0_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_1_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_1_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_1_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_2_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_2_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_2_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_3_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_3_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_ULP_3_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_0_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_0_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_0_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_1_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_1_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_1_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_2_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_2_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_2_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_3_LEN	        16
#define	LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_3_OFFSET	        0
#define LP_CTL_ULP_B_RB_SYS_TICK_VALUE_THR_3_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_POWER_MODE_SEL_LEN	        2
#define	LP_CTL_ULP_B_RB_POWER_MODE_SEL_OFFSET	        0
#define LP_CTL_ULP_B_RB_POWER_MODE_SEL_MASK    		0x3

#define	LP_CTL_ULP_B_RB_RE_PWR_TIME_GEAR_LEN	        2
#define	LP_CTL_ULP_B_RB_RE_PWR_TIME_GEAR_OFFSET	        11
#define LP_CTL_ULP_B_RB_RE_PWR_TIME_GEAR_MASK    		0x1800
#define	LP_CTL_ULP_B_RB_POWER_ON_TIME_GEAR_LEN	        3
#define	LP_CTL_ULP_B_RB_POWER_ON_TIME_GEAR_OFFSET	        0
#define LP_CTL_ULP_B_RB_POWER_ON_TIME_GEAR_MASK    		0x7

#define	LP_CTL_ULP_B_RB_PMU1_100US_GRM_TIME_CFG_LEN	        4
#define	LP_CTL_ULP_B_RB_PMU1_100US_GRM_TIME_CFG_OFFSET	        10
#define LP_CTL_ULP_B_RB_PMU1_100US_GRM_TIME_CFG_MASK    		0x3C00
#define	LP_CTL_ULP_B_RB_PMU1_1MS_GRM_TIME_CFG_LEN	        10
#define	LP_CTL_ULP_B_RB_PMU1_1MS_GRM_TIME_CFG_OFFSET	        0
#define LP_CTL_ULP_B_RB_PMU1_1MS_GRM_TIME_CFG_MASK    		0x3FF

#define	LP_CTL_ULP_B_RB_PMU1_80MS_GRM_TIME_CFG_LEN	        12
#define	LP_CTL_ULP_B_RB_PMU1_80MS_GRM_TIME_CFG_OFFSET	        0
#define LP_CTL_ULP_B_RB_PMU1_80MS_GRM_TIME_CFG_MASK    		0xFFF

#define	LP_CTL_ULP_B_RB_ULP_HRESET_MODE_SEL_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_HRESET_MODE_SEL_OFFSET	        0
#define LP_CTL_ULP_B_RB_ULP_HRESET_MODE_SEL_MASK    		0x1

#define	LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_BYPASS_LEN	        1
#define	LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_BYPASS_OFFSET	        1
#define LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_BYPASS_MASK    		0x2
#define	LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_CG_EN_LEN	        1
#define	LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_CG_EN_OFFSET	        0
#define LP_CTL_ULP_B_RB_RTC_CLKIN_GLITCH_RM_CG_EN_MASK    		0x1

#define	LP_CTL_ULP_B_RB_PDACK_TIMEOUT_CFG_LEN	        8
#define	LP_CTL_ULP_B_RB_PDACK_TIMEOUT_CFG_OFFSET	        0
#define LP_CTL_ULP_B_RB_PDACK_TIMEOUT_CFG_MASK    		0xFF

#define	LP_CTL_ULP_B_RB_PWRON_VBUS_TIME_CFG_SOC_LEN	        16
#define	LP_CTL_ULP_B_RB_PWRON_VBUS_TIME_CFG_SOC_OFFSET	        0
#define LP_CTL_ULP_B_RB_PWRON_VBUS_TIME_CFG_SOC_MASK    		0xFFFF

#define	LP_CTL_ULP_B_RB_ULP_REBOOT_CNT_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_REBOOT_CNT_CLR_OFFSET	        0
#define LP_CTL_ULP_B_RB_ULP_REBOOT_CNT_CLR_MASK    		0x1

#define	LP_CTL_ULP_B_RB_FSM_CUR_STATE_LEN	        3
#define	LP_CTL_ULP_B_RB_FSM_CUR_STATE_OFFSET	        0
#define LP_CTL_ULP_B_RB_FSM_CUR_STATE_MASK    		0x7

#define	LP_CTL_ULP_B_RB_DEBUG_MODE_DET_ORG_LEN	        1
#define	LP_CTL_ULP_B_RB_DEBUG_MODE_DET_ORG_OFFSET	        1
#define LP_CTL_ULP_B_RB_DEBUG_MODE_DET_ORG_MASK    		0x2
#define	LP_CTL_ULP_B_RB_DEBUG_MODE_DET_RESULT_LEN	        1
#define	LP_CTL_ULP_B_RB_DEBUG_MODE_DET_RESULT_OFFSET	        0
#define LP_CTL_ULP_B_RB_DEBUG_MODE_DET_RESULT_MASK    		0x1

#define	LP_CTL_ULP_B_RB_JTAG_MODE_DET_ORG_LEN	        1
#define	LP_CTL_ULP_B_RB_JTAG_MODE_DET_ORG_OFFSET	        1
#define LP_CTL_ULP_B_RB_JTAG_MODE_DET_ORG_MASK    		0x2
#define	LP_CTL_ULP_B_RB_JTAG_MODE_DET_RESULT_LEN	        1
#define	LP_CTL_ULP_B_RB_JTAG_MODE_DET_RESULT_OFFSET	        0
#define LP_CTL_ULP_B_RB_JTAG_MODE_DET_RESULT_MASK    		0x1

#define	LP_CTL_ULP_B_RB_RC_XO_CLKA_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_RC_XO_CLKA_STS_OFFSET	        1
#define LP_CTL_ULP_B_RB_RC_XO_CLKA_STS_MASK    		0x2
#define	LP_CTL_ULP_B_RB_RC_XO_CLKB_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_RC_XO_CLKB_STS_OFFSET	        0
#define LP_CTL_ULP_B_RB_RC_XO_CLKB_STS_MASK    		0x1

#define	LP_CTL_ULP_B_RB_RC_PCLKLP_CLKA_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_RC_PCLKLP_CLKA_STS_OFFSET	        1
#define LP_CTL_ULP_B_RB_RC_PCLKLP_CLKA_STS_MASK    		0x2
#define	LP_CTL_ULP_B_RB_RC_PCLKLP_CLKB_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_RC_PCLKLP_CLKB_STS_OFFSET	        0
#define LP_CTL_ULP_B_RB_RC_PCLKLP_CLKB_STS_MASK    		0x1

#define	LP_CTL_ULP_B_RB_GPIO_BUS_CUR_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_GPIO_BUS_CUR_STS_OFFSET	        0
#define LP_CTL_ULP_B_RB_GPIO_BUS_CUR_STS_MASK    		0x1

#define	LP_CTL_ULP_B_RB_BUCK0_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_EN_STS_OFFSET	        10
#define LP_CTL_ULP_B_RB_BUCK0_EN_STS_MASK    		0x400
#define	LP_CTL_ULP_B_RB_SHIP_MODE_FLAG_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_SHIP_MODE_FLAG_STS_OFFSET	        9
#define LP_CTL_ULP_B_RB_SHIP_MODE_FLAG_STS_MASK    		0x200
#define	LP_CTL_ULP_B_RB_IOLDO4_EN_ECO_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_IOLDO4_EN_ECO_STS_OFFSET	        8
#define LP_CTL_ULP_B_RB_IOLDO4_EN_ECO_STS_MASK    		0x100
#define	LP_CTL_ULP_B_RB_BUCK1_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_EN_STS_OFFSET	        7
#define LP_CTL_ULP_B_RB_BUCK1_EN_STS_MASK    		0x80
#define	LP_CTL_ULP_B_RB_ULVO_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_ULVO_EN_STS_OFFSET	        6
#define LP_CTL_ULP_B_RB_ULVO_EN_STS_MASK    		0x40
#define	LP_CTL_ULP_B_RB_OVP_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_OVP_EN_STS_OFFSET	        5
#define LP_CTL_ULP_B_RB_OVP_EN_STS_MASK    		0x20
#define	LP_CTL_ULP_B_RB_LPREF_IBG_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_LPREF_IBG_EN_STS_OFFSET	        4
#define LP_CTL_ULP_B_RB_LPREF_IBG_EN_STS_MASK    		0x10
#define	LP_CTL_ULP_B_RB_LPREF_BUF_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_LPREF_BUF_EN_STS_OFFSET	        3
#define LP_CTL_ULP_B_RB_LPREF_BUF_EN_STS_MASK    		0x8
#define	LP_CTL_ULP_B_RB_LPREF_BG_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_LPREF_BG_EN_STS_OFFSET	        2
#define LP_CTL_ULP_B_RB_LPREF_BG_EN_STS_MASK    		0x4
#define	LP_CTL_ULP_B_RB_AON_TO_ULP_ISO_EN_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_AON_TO_ULP_ISO_EN_STS_OFFSET	        1
#define LP_CTL_ULP_B_RB_AON_TO_ULP_ISO_EN_STS_MASK    		0x2
#define	LP_CTL_ULP_B_RB_RST_DBB_TMP_N_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_RST_DBB_TMP_N_STS_OFFSET	        0
#define LP_CTL_ULP_B_RB_RST_DBB_TMP_N_STS_MASK    		0x1

#define	LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_CLR_OFFSET	        15
#define LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_CLR_MASK    		0x8000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_CLR_OFFSET	        14
#define LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_CLR_MASK    		0x4000
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_CLR_OFFSET	        13
#define LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_CLR_MASK    		0x2000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_CLR_OFFSET	        12
#define LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_CLR_MASK    		0x1000
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_CLR_OFFSET	        11
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_CLR_MASK    		0x800
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_CLR_OFFSET	        10
#define LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_CLR_MASK    		0x400
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_CLR_OFFSET	        9
#define LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_CLR_MASK    		0x200
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_CLR_OFFSET	        8
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_CLR_MASK    		0x100
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_CLR_OFFSET	        7
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_CLR_MASK    		0x80
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_CLR_OFFSET	        6
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_CLR_MASK    		0x40
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_CLR_OFFSET	        5
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_CLR_MASK    		0x20
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_CLR_OFFSET	        4
#define LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_CLR_MASK    		0x10
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_CLR_OFFSET	        3
#define LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_CLR_MASK    		0x8
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_CLR_OFFSET	        2
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_CLR_MASK    		0x4
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_CLR_OFFSET	        1
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_CLR_MASK    		0x2
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_CLR_OFFSET	        0
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_CLR_MASK    		0x1

#define	LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_OFFSET	        15
#define LP_CTL_ULP_B_RB_BUCK0_SCP_STICK_MASK    		0x8000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_OFFSET	        14
#define LP_CTL_ULP_B_RB_BUCK0_OCP_STICK_MASK    		0x4000
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_OFFSET	        13
#define LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_STICK_MASK    		0x2000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_OFFSET	        12
#define LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_STICK_MASK    		0x1000
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_OFFSET	        11
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_STICK_MASK    		0x800
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_OFFSET	        10
#define LP_CTL_ULP_B_RB_BUCK1_SCP_STICK_MASK    		0x400
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_OFFSET	        9
#define LP_CTL_ULP_B_RB_BUCK1_OCP_STICK_MASK    		0x200
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_OFFSET	        8
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_STICK_MASK    		0x100
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_OFFSET	        7
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_STICK_MASK    		0x80
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_OFFSET	        6
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_STICK_MASK    		0x40
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_OFFSET	        5
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_STICK_MASK    		0x20
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_OFFSET	        4
#define LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_STICK_MASK    		0x10
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_OFFSET	        3
#define LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_STICK_MASK    		0x8
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_OFFSET	        2
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_STICK_MASK    		0x4
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_OFFSET	        1
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_STICK_MASK    		0x2
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_OFFSET	        0
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_STICK_MASK    		0x1

#define	LP_CTL_ULP_B_RB_BUCK0_SCP_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_OFFSET	        15
#define LP_CTL_ULP_B_RB_BUCK0_SCP_MASK    		0x8000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_OFFSET	        14
#define LP_CTL_ULP_B_RB_BUCK0_OCP_MASK    		0x4000
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_OFFSET	        13
#define LP_CTL_ULP_B_RB_BUCK0_SCP_GRM_MASK    		0x2000
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_OFFSET	        12
#define LP_CTL_ULP_B_RB_BUCK0_OCP_GRM_MASK    		0x1000
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_OFFSET	        11
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_MASK    		0x800
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_OFFSET	        10
#define LP_CTL_ULP_B_RB_BUCK1_SCP_MASK    		0x400
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_OFFSET	        9
#define LP_CTL_ULP_B_RB_BUCK1_OCP_MASK    		0x200
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_OFFSET	        8
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_MASK    		0x100
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_OFFSET	        7
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_MASK    		0x80
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_OFFSET	        6
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_MASK    		0x40
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_OFFSET	        5
#define LP_CTL_ULP_B_RB_D_PMU_IOLDO4_OCP_GRM_MASK    		0x20
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_OFFSET	        4
#define LP_CTL_ULP_B_RB_BUCK1_SCP_GRM_MASK    		0x10
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_OFFSET	        3
#define LP_CTL_ULP_B_RB_BUCK1_OCP_GRM_MASK    		0x8
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_OFFSET	        2
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_FILTER_OUT_GRM_MASK    		0x4
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_OFFSET	        1
#define LP_CTL_ULP_B_RB_D_PMU_UVLO_OUT_GRM_MASK    		0x2
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_LEN	        1
#define	LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_OFFSET	        0
#define LP_CTL_ULP_B_RB_D_PMU_OVP_OUT_GRM_MASK    		0x1

#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_CLR_OFFSET	        10
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_CLR_MASK    		0x400
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_CLR_OFFSET	        9
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_CLR_MASK    		0x200
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_INV_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_INV_STICK_CLR_OFFSET	        8
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_INV_STICK_CLR_MASK    		0x100
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_OFFSET	        7
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_INV_STS_STICK_MASK    		0x80
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_OFFSET	        6
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_STICK_MASK    		0x40
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_INV_STS_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_INV_STS_STICK_OFFSET	        5
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_INV_STS_STICK_MASK    		0x20
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_STS_OFFSET	        4
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_LONG_GRM_STS_MASK    		0x10
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_OFFSET	        3
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_GRM_STS_MASK    		0x8
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_OFFSET	        2
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_GRM_STS_MASK    		0x4
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_STS_OFFSET	        1
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_V_STS_MASK    		0x2
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_STS_LEN	        1
#define	LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_STS_OFFSET	        0
#define LP_CTL_ULP_B_RB_PMU_ULP_RST_REQ_STS_MASK    		0x1

#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_CLR_OFFSET	        11
#define LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_CLR_MASK    		0x800
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_CLR_OFFSET	        10
#define LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_CLR_MASK    		0x400
#define	LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_CLR_OFFSET	        9
#define LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_CLR_MASK    		0x200
#define	LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_CLR_LEN	        1
#define	LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_CLR_OFFSET	        8
#define LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_CLR_MASK    		0x100
#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_OFFSET	        7
#define LP_CTL_ULP_B_RB_ULP_PD_ACK_STICK_MASK    		0x80
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_OFFSET	        6
#define LP_CTL_ULP_B_RB_ULP_PD_REQUEST_STICK_MASK    		0x40
#define	LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_OFFSET	        5
#define LP_CTL_ULP_B_RB_HRESET_N_INV_STICK_MASK    		0x20
#define	LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_LEN	        1
#define	LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_OFFSET	        4
#define LP_CTL_ULP_B_RB_PWR_HOLD_INV_STICK_MASK    		0x10
#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_ACK_OFFSET	        3
#define LP_CTL_ULP_B_RB_ULP_PD_ACK_MASK    		0x8
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_LEN	        1
#define	LP_CTL_ULP_B_RB_ULP_PD_REQUEST_OFFSET	        2
#define LP_CTL_ULP_B_RB_ULP_PD_REQUEST_MASK    		0x4
#define	LP_CTL_ULP_B_RB_HRESET_N_LEN	        1
#define	LP_CTL_ULP_B_RB_HRESET_N_OFFSET	        1
#define LP_CTL_ULP_B_RB_HRESET_N_MASK    		0x2
#define	LP_CTL_ULP_B_RB_PWR_HOLD_LEN	        1
#define	LP_CTL_ULP_B_RB_PWR_HOLD_OFFSET	        0
#define LP_CTL_ULP_B_RB_PWR_HOLD_MASK    		0x1

#endif // __3322_LP_CTL_ULP_B_RB_REG_OFFSET_FIELD_H__
