/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_pmu2_cmu_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_PMU2_CMU_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_PMU2_CMU_CTL_RB_REG_OFFSET_FIELD_H__

#define	PMU2_CMU_CTL_RB_PMU2_CMU_CTL_ID_LEN	        16
#define	PMU2_CMU_CTL_RB_PMU2_CMU_CTL_ID_OFFSET	        0
#define PMU2_CMU_CTL_RB_PMU2_CMU_CTL_ID_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_PMU2_GP_REG0_LEN	        16
#define	PMU2_CMU_CTL_RB_PMU2_GP_REG0_OFFSET	        0
#define PMU2_CMU_CTL_RB_PMU2_GP_REG0_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_PMU2_GP_REG1_LEN	        16
#define	PMU2_CMU_CTL_RB_PMU2_GP_REG1_OFFSET	        0
#define PMU2_CMU_CTL_RB_PMU2_GP_REG1_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_FBDIV_TARGET_LEN	        12
#define	PMU2_CMU_CTL_RB_FBDIV_TARGET_OFFSET	        0
#define PMU2_CMU_CTL_RB_FBDIV_TARGET_MASK    		0xFFF

#define	PMU2_CMU_CTL_RB_FRAC_TARGET_H_LEN	        8
#define	PMU2_CMU_CTL_RB_FRAC_TARGET_H_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_TARGET_H_MASK    		0xFF

#define	PMU2_CMU_CTL_RB_FRAC_TARGET_L_LEN	        16
#define	PMU2_CMU_CTL_RB_FRAC_TARGET_L_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_TARGET_L_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_FBDIV_SEL_LEN	        1
#define	PMU2_CMU_CTL_RB_FBDIV_SEL_OFFSET	        0
#define PMU2_CMU_CTL_RB_FBDIV_SEL_MASK    		0x1

#define	PMU2_CMU_CTL_RB_FRAC_SEL_LEN	        1
#define	PMU2_CMU_CTL_RB_FRAC_SEL_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_SEL_MASK    		0x1

#define	PMU2_CMU_CTL_RB_PLL_CFG_VLD_LEN	        1
#define	PMU2_CMU_CTL_RB_PLL_CFG_VLD_OFFSET	        0
#define PMU2_CMU_CTL_RB_PLL_CFG_VLD_MASK    		0x1

#define	PMU2_CMU_CTL_RB_FRAC_STEP_H_LEN	        8
#define	PMU2_CMU_CTL_RB_FRAC_STEP_H_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_STEP_H_MASK    		0xFF

#define	PMU2_CMU_CTL_RB_FRAC_STEP_L_LEN	        16
#define	PMU2_CMU_CTL_RB_FRAC_STEP_L_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_STEP_L_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_FBDIV_STS_LEN	        12
#define	PMU2_CMU_CTL_RB_FBDIV_STS_OFFSET	        0
#define PMU2_CMU_CTL_RB_FBDIV_STS_MASK    		0xFFF

#define	PMU2_CMU_CTL_RB_FRAC_STS_H_LEN	        8
#define	PMU2_CMU_CTL_RB_FRAC_STS_H_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_STS_H_MASK    		0xFF

#define	PMU2_CMU_CTL_RB_FRAC_STS_L_LEN	        16
#define	PMU2_CMU_CTL_RB_FRAC_STS_L_OFFSET	        0
#define PMU2_CMU_CTL_RB_FRAC_STS_L_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_EFUSE_CLK_EN_LEN	        1
#define	PMU2_CMU_CTL_RB_EFUSE_CLK_EN_OFFSET	        0
#define PMU2_CMU_CTL_RB_EFUSE_CLK_EN_MASK    		0x1

#define	PMU2_CMU_CTL_RB_AON_ICM_2X1S2_ICM_AUTO_PRIORITY_LEN	        2
#define	PMU2_CMU_CTL_RB_AON_ICM_2X1S2_ICM_AUTO_PRIORITY_OFFSET	        2
#define PMU2_CMU_CTL_RB_AON_ICM_2X1S2_ICM_AUTO_PRIORITY_MASK    		0xC
#define	PMU2_CMU_CTL_RB_AON_ICM_2X1S1_ICM_AUTO_PRIORITY_LEN	        2
#define	PMU2_CMU_CTL_RB_AON_ICM_2X1S1_ICM_AUTO_PRIORITY_OFFSET	        0
#define PMU2_CMU_CTL_RB_AON_ICM_2X1S1_ICM_AUTO_PRIORITY_MASK    		0x3

#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_LEN	        1
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_OFFSET	        3
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_MASK    		0x8
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_CLR_LEN	        1
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_CLR_OFFSET	        2
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_SUCCESS_CLR_MASK    		0x4
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_DONE_LEN	        1
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_DONE_OFFSET	        1
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_DONE_MASK    		0x2
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_CLR_LEN	        1
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_CLR_OFFSET	        0
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_CLR_MASK    		0x1

#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_H_LEN	        3
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_H_OFFSET	        0
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_H_MASK    		0x7

#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_L_LEN	        16
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_L_OFFSET	        0
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_L_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_H_LEN	        3
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_H_OFFSET	        0
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_H_MASK    		0x7

#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_L_LEN	        16
#define	PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_L_OFFSET	        0
#define PMU2_CMU_CTL_RB_FAST_XO_INIT_CNT_TARGET_L_MASK    		0xFFFF

#define	PMU2_CMU_CTL_RB_CFG_PMU2CMU_PLL_SSCG_CLKEN_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_PMU2CMU_PLL_SSCG_CLKEN_OFFSET	        8
#define PMU2_CMU_CTL_RB_CFG_PMU2CMU_PLL_SSCG_CLKEN_MASK    		0x100
#define	PMU2_CMU_CTL_RB_AON_AHB_HREADY_MUX_LEN	        1
#define	PMU2_CMU_CTL_RB_AON_AHB_HREADY_MUX_OFFSET	        7
#define PMU2_CMU_CTL_RB_AON_AHB_HREADY_MUX_MASK    		0x80
#define	PMU2_CMU_CTL_RB_AON_AUTO_CG_BYPASS_EN_LEN	        1
#define	PMU2_CMU_CTL_RB_AON_AUTO_CG_BYPASS_EN_OFFSET	        6
#define PMU2_CMU_CTL_RB_AON_AUTO_CG_BYPASS_EN_MASK    		0x40
#define	PMU2_CMU_CTL_RB_CFG_GLBM_SOFT_RST_AEFUSE_BOOT_N_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_GLBM_SOFT_RST_AEFUSE_BOOT_N_OFFSET	        5
#define PMU2_CMU_CTL_RB_CFG_GLBM_SOFT_RST_AEFUSE_BOOT_N_MASK    		0x20
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_XO_CNT_CLKEN_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_XO_CNT_CLKEN_OFFSET	        3
#define PMU2_CMU_CTL_RB_CFG_GLBM_FAST_XO_CNT_CLKEN_MASK    		0x8
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_RTC_SEL_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_RTC_SEL_OFFSET	        2
#define PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_RTC_SEL_MASK    		0x4
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_32M_SEL_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_32M_SEL_OFFSET	        1
#define PMU2_CMU_CTL_RB_CFG_GLBM_FAST_CLKIN_32M_SEL_MASK    		0x2
#define	PMU2_CMU_CTL_RB_CFG_GLBM_AEFUSE_CLKEN_LEN	        1
#define	PMU2_CMU_CTL_RB_CFG_GLBM_AEFUSE_CLKEN_OFFSET	        0
#define PMU2_CMU_CTL_RB_CFG_GLBM_AEFUSE_CLKEN_MASK    		0x1

#endif // __3322_PMU2_CMU_CTL_RB_REG_OFFSET_FIELD_H__
