/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_m_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_M_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_M_CTL_RB_REG_OFFSET_FIELD_H__

#define	M_CTL_RB_M_CTL_ID_LEN	        16
#define	M_CTL_RB_M_CTL_ID_OFFSET	        0
#define M_CTL_RB_M_CTL_ID_MASK    		0xFFFF

#define	M_CTL_RB_M_GP_REG0_LEN	        16
#define	M_CTL_RB_M_GP_REG0_OFFSET	        0
#define M_CTL_RB_M_GP_REG0_MASK    		0xFFFF

#define	M_CTL_RB_M_GP_REG1_LEN	        16
#define	M_CTL_RB_M_GP_REG1_OFFSET	        0
#define M_CTL_RB_M_GP_REG1_MASK    		0xFFFF

#define	M_CTL_RB_M_GP_REG2_LEN	        16
#define	M_CTL_RB_M_GP_REG2_OFFSET	        0
#define M_CTL_RB_M_GP_REG2_MASK    		0xFFFF

#define	M_CTL_RB_M_GP_REG3_LEN	        16
#define	M_CTL_RB_M_GP_REG3_OFFSET	        0
#define M_CTL_RB_M_GP_REG3_MASK    		0xFFFF

#define	M_CTL_RB_D2M_INT1_EN_LEN	        1
#define	M_CTL_RB_D2M_INT1_EN_OFFSET	        3
#define M_CTL_RB_D2M_INT1_EN_MASK    		0x8
#define	M_CTL_RB_D2M_INT0_EN_LEN	        1
#define	M_CTL_RB_D2M_INT0_EN_OFFSET	        2
#define M_CTL_RB_D2M_INT0_EN_MASK    		0x4
#define	M_CTL_RB_B2M_INT1_EN_LEN	        1
#define	M_CTL_RB_B2M_INT1_EN_OFFSET	        1
#define M_CTL_RB_B2M_INT1_EN_MASK    		0x2
#define	M_CTL_RB_B2M_INT0_EN_LEN	        1
#define	M_CTL_RB_B2M_INT0_EN_OFFSET	        0
#define M_CTL_RB_B2M_INT0_EN_MASK    		0x1

#define	M_CTL_RB_D2M_INT1_LEN	        1
#define	M_CTL_RB_D2M_INT1_OFFSET	        3
#define M_CTL_RB_D2M_INT1_MASK    		0x8
#define	M_CTL_RB_D2M_INT0_LEN	        1
#define	M_CTL_RB_D2M_INT0_OFFSET	        2
#define M_CTL_RB_D2M_INT0_MASK    		0x4
#define	M_CTL_RB_B2M_INT1_LEN	        1
#define	M_CTL_RB_B2M_INT1_OFFSET	        1
#define M_CTL_RB_B2M_INT1_MASK    		0x2
#define	M_CTL_RB_B2M_INT0_LEN	        1
#define	M_CTL_RB_B2M_INT0_OFFSET	        0
#define M_CTL_RB_B2M_INT0_MASK    		0x1

#define	M_CTL_RB_MCU_TE_INT_AON_STS_LEN	        1
#define	M_CTL_RB_MCU_TE_INT_AON_STS_OFFSET	        5
#define M_CTL_RB_MCU_TE_INT_AON_STS_MASK    		0x20
#define	M_CTL_RB_DSI_TE_AGPIO_INT_STS_LEN	        1
#define	M_CTL_RB_DSI_TE_AGPIO_INT_STS_OFFSET	        4
#define M_CTL_RB_DSI_TE_AGPIO_INT_STS_MASK    		0x10
#define	M_CTL_RB_D2M_INT1_STS_LEN	        1
#define	M_CTL_RB_D2M_INT1_STS_OFFSET	        3
#define M_CTL_RB_D2M_INT1_STS_MASK    		0x8
#define	M_CTL_RB_D2M_INT0_STS_LEN	        1
#define	M_CTL_RB_D2M_INT0_STS_OFFSET	        2
#define M_CTL_RB_D2M_INT0_STS_MASK    		0x4
#define	M_CTL_RB_B2M_INT1_STS_LEN	        1
#define	M_CTL_RB_B2M_INT1_STS_OFFSET	        1
#define M_CTL_RB_B2M_INT1_STS_MASK    		0x2
#define	M_CTL_RB_B2M_INT0_STS_LEN	        1
#define	M_CTL_RB_B2M_INT0_STS_OFFSET	        0
#define M_CTL_RB_B2M_INT0_STS_MASK    		0x1

#define	M_CTL_RB_D2M_INT1_CLR_LEN	        1
#define	M_CTL_RB_D2M_INT1_CLR_OFFSET	        3
#define M_CTL_RB_D2M_INT1_CLR_MASK    		0x8
#define	M_CTL_RB_D2M_INT0_CLR_LEN	        1
#define	M_CTL_RB_D2M_INT0_CLR_OFFSET	        2
#define M_CTL_RB_D2M_INT0_CLR_MASK    		0x4
#define	M_CTL_RB_B2M_INT1_CLR_LEN	        1
#define	M_CTL_RB_B2M_INT1_CLR_OFFSET	        1
#define M_CTL_RB_B2M_INT1_CLR_MASK    		0x2
#define	M_CTL_RB_B2M_INT0_CLR_LEN	        1
#define	M_CTL_RB_B2M_INT0_CLR_OFFSET	        0
#define M_CTL_RB_B2M_INT0_CLR_MASK    		0x1

#define	M_CTL_RB_M2D_INT1_CLR_STICK_STS_LEN	        1
#define	M_CTL_RB_M2D_INT1_CLR_STICK_STS_OFFSET	        3
#define M_CTL_RB_M2D_INT1_CLR_STICK_STS_MASK    		0x8
#define	M_CTL_RB_M2D_INT0_CLR_STICK_STS_LEN	        1
#define	M_CTL_RB_M2D_INT0_CLR_STICK_STS_OFFSET	        2
#define M_CTL_RB_M2D_INT0_CLR_STICK_STS_MASK    		0x4
#define	M_CTL_RB_M2B_INT1_CLR_STICK_STS_LEN	        1
#define	M_CTL_RB_M2B_INT1_CLR_STICK_STS_OFFSET	        1
#define M_CTL_RB_M2B_INT1_CLR_STICK_STS_MASK    		0x2
#define	M_CTL_RB_M2B_INT0_CLR_STICK_STS_LEN	        1
#define	M_CTL_RB_M2B_INT0_CLR_STICK_STS_OFFSET	        0
#define M_CTL_RB_M2B_INT0_CLR_STICK_STS_MASK    		0x1

#define	M_CTL_RB_M2D_INT1_SET_LEN	        1
#define	M_CTL_RB_M2D_INT1_SET_OFFSET	        3
#define M_CTL_RB_M2D_INT1_SET_MASK    		0x8
#define	M_CTL_RB_M2D_INT0_SET_LEN	        1
#define	M_CTL_RB_M2D_INT0_SET_OFFSET	        2
#define M_CTL_RB_M2D_INT0_SET_MASK    		0x4
#define	M_CTL_RB_M2B_INT1_SET_LEN	        1
#define	M_CTL_RB_M2B_INT1_SET_OFFSET	        1
#define M_CTL_RB_M2B_INT1_SET_MASK    		0x2
#define	M_CTL_RB_M2B_INT0_SET_LEN	        1
#define	M_CTL_RB_M2B_INT0_SET_OFFSET	        0
#define M_CTL_RB_M2B_INT0_SET_MASK    		0x1

#define	M_CTL_RB_CFG_M_DSP2MEM_X2X_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_DSP2MEM_X2X_CLKEN_OFFSET	        15
#define M_CTL_RB_CFG_M_DSP2MEM_X2X_CLKEN_MASK    		0x8000
#define	M_CTL_RB_CFG_M_MEM_BUS_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_MEM_BUS_CLKEN_OFFSET	        14
#define M_CTL_RB_CFG_M_MEM_BUS_CLKEN_MASK    		0x4000
#define	M_CTL_RB_CFG_M_X2H_MEM_BUS_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_X2H_MEM_BUS_CLKEN_OFFSET	        13
#define M_CTL_RB_CFG_M_X2H_MEM_BUS_CLKEN_MASK    		0x2000
#define	M_CTL_RB_CFG_M_SEC_P2P_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_SEC_P2P_CLKEN_OFFSET	        12
#define M_CTL_RB_CFG_M_SEC_P2P_CLKEN_MASK    		0x1000
#define	M_CTL_RB_CFG_M_DIAG_P2P_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_DIAG_P2P_CLKEN_OFFSET	        11
#define M_CTL_RB_CFG_M_DIAG_P2P_CLKEN_MASK    		0x800
#define	M_CTL_RB_CFG_M_HS_SUB_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_HS_SUB_CLKEN_OFFSET	        10
#define M_CTL_RB_CFG_M_HS_SUB_CLKEN_MASK    		0x400
#define	M_CTL_RB_CFG_M_TRIGGER_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_TRIGGER_CLKEN_OFFSET	        9
#define M_CTL_RB_CFG_M_TRIGGER_CLKEN_MASK    		0x200
#define	M_CTL_RB_CFG_M_GLB_CLKEN_MEM_BUS_LEN	        1
#define	M_CTL_RB_CFG_M_GLB_CLKEN_MEM_BUS_OFFSET	        8
#define M_CTL_RB_CFG_M_GLB_CLKEN_MEM_BUS_MASK    		0x100
#define	M_CTL_RB_PWM_CLKEN_LEN	        1
#define	M_CTL_RB_PWM_CLKEN_OFFSET	        7
#define M_CTL_RB_PWM_CLKEN_MASK    		0x80
#define	M_CTL_RB_CFG_M_SEC_BUS_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_SEC_BUS_CLKEN_OFFSET	        6
#define M_CTL_RB_CFG_M_SEC_BUS_CLKEN_MASK    		0x40
#define	M_CTL_RB_M_GPIO_PERP_CLKEN_LEN	        1
#define	M_CTL_RB_M_GPIO_PERP_CLKEN_OFFSET	        5
#define M_CTL_RB_M_GPIO_PERP_CLKEN_MASK    		0x20
#define	M_CTL_RB_CFG_M_SCE_KM_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_SCE_KM_CLKEN_OFFSET	        4
#define M_CTL_RB_CFG_M_SCE_KM_CLKEN_MASK    		0x10
#define	M_CTL_RB_M_GPIO_CLKEN_LEN	        1
#define	M_CTL_RB_M_GPIO_CLKEN_OFFSET	        3
#define M_CTL_RB_M_GPIO_CLKEN_MASK    		0x8
#define	M_CTL_RB_CFG_M_SEC_PKE_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_SEC_PKE_CLKEN_OFFSET	        2
#define M_CTL_RB_CFG_M_SEC_PKE_CLKEN_MASK    		0x4
#define	M_CTL_RB_MDIAG_CLKEN_LEN	        1
#define	M_CTL_RB_MDIAG_CLKEN_OFFSET	        1
#define M_CTL_RB_MDIAG_CLKEN_MASK    		0x2
#define	M_CTL_RB_SDIO_CFG_APB_PCLK_EN_LEN	        1
#define	M_CTL_RB_SDIO_CFG_APB_PCLK_EN_OFFSET	        0
#define M_CTL_RB_SDIO_CFG_APB_PCLK_EN_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CFG_CLKEN_LEN	        1
#define	M_CTL_RB_AUX_ADC_CFG_CLKEN_OFFSET	        14
#define M_CTL_RB_AUX_ADC_CFG_CLKEN_MASK    		0x4000
#define	M_CTL_RB_CFG_M_XIP_BUS_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_XIP_BUS_CLKEN_OFFSET	        13
#define M_CTL_RB_CFG_M_XIP_BUS_CLKEN_MASK    		0x2000
#define	M_CTL_RB_I2C3_CLKEN_LEN	        1
#define	M_CTL_RB_I2C3_CLKEN_OFFSET	        12
#define M_CTL_RB_I2C3_CLKEN_MASK    		0x1000
#define	M_CTL_RB_UART_H1_CLKEN_LEN	        1
#define	M_CTL_RB_UART_H1_CLKEN_OFFSET	        11
#define M_CTL_RB_UART_H1_CLKEN_MASK    		0x800
#define	M_CTL_RB_MEM_HS_GPIO_PERP_CLKEN_LEN	        1
#define	M_CTL_RB_MEM_HS_GPIO_PERP_CLKEN_OFFSET	        9
#define M_CTL_RB_MEM_HS_GPIO_PERP_CLKEN_MASK    		0x200
#define	M_CTL_RB_I2C2_CLKEN_LEN	        1
#define	M_CTL_RB_I2C2_CLKEN_OFFSET	        8
#define M_CTL_RB_I2C2_CLKEN_MASK    		0x100
#define	M_CTL_RB_I2C1_CLKEN_LEN	        1
#define	M_CTL_RB_I2C1_CLKEN_OFFSET	        7
#define M_CTL_RB_I2C1_CLKEN_MASK    		0x80
#define	M_CTL_RB_I2C0_CLKEN_LEN	        1
#define	M_CTL_RB_I2C0_CLKEN_OFFSET	        6
#define M_CTL_RB_I2C0_CLKEN_MASK    		0x40
#define	M_CTL_RB_UART_L0_CLKEN_LEN	        1
#define	M_CTL_RB_UART_L0_CLKEN_OFFSET	        5
#define M_CTL_RB_UART_L0_CLKEN_MASK    		0x20
#define	M_CTL_RB_UART_H0_CLKEN_LEN	        1
#define	M_CTL_RB_UART_H0_CLKEN_OFFSET	        4
#define M_CTL_RB_UART_H0_CLKEN_MASK    		0x10
#define	M_CTL_RB_MEM_HS_GPIO_CLKEN_LEN	        1
#define	M_CTL_RB_MEM_HS_GPIO_CLKEN_OFFSET	        3
#define M_CTL_RB_MEM_HS_GPIO_CLKEN_MASK    		0x8
#define	M_CTL_RB_SPI0_MS_CLKEN_LEN	        1
#define	M_CTL_RB_SPI0_MS_CLKEN_OFFSET	        2
#define M_CTL_RB_SPI0_MS_CLKEN_MASK    		0x4
#define	M_CTL_RB_SPI1_M_CLKEN_LEN	        1
#define	M_CTL_RB_SPI1_M_CLKEN_OFFSET	        1
#define M_CTL_RB_SPI1_M_CLKEN_MASK    		0x2
#define	M_CTL_RB_MTIMER_CLKEN_LEN	        1
#define	M_CTL_RB_MTIMER_CLKEN_OFFSET	        0
#define M_CTL_RB_MTIMER_CLKEN_MASK    		0x1

#define	M_CTL_RB_CFG_CLK_CRC_PCLKEN_LEN	        1
#define	M_CTL_RB_CFG_CLK_CRC_PCLKEN_OFFSET	        7
#define M_CTL_RB_CFG_CLK_CRC_PCLKEN_MASK    		0x80
#define	M_CTL_RB_CFG_M_BUS_SLV_PRT_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_BUS_SLV_PRT_CLKEN_OFFSET	        6
#define M_CTL_RB_CFG_M_BUS_SLV_PRT_CLKEN_MASK    		0x40
#define	M_CTL_RB_CFG_M_M_DAP_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_M_DAP_CLKEN_OFFSET	        5
#define M_CTL_RB_CFG_M_M_DAP_CLKEN_MASK    		0x20

#define	M_CTL_RB_CFG_M_MCPU_SOFT_RST_PULSE_WIDTH_LEN	        8
#define	M_CTL_RB_CFG_M_MCPU_SOFT_RST_PULSE_WIDTH_OFFSET	        8
#define M_CTL_RB_CFG_M_MCPU_SOFT_RST_PULSE_WIDTH_MASK    		0xFF00
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_SYS_TRG_PULSE_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_SYS_TRG_PULSE_OFFSET	        3
#define M_CTL_RB_CFG_M_SOFT_RST_MCPU_SYS_TRG_PULSE_MASK    		0x8
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_POR_TRG_PULSE_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_POR_TRG_PULSE_OFFSET	        2
#define M_CTL_RB_CFG_M_SOFT_RST_MCPU_POR_TRG_PULSE_MASK    		0x4
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_DBG_TRG_PULSE_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_MCPU_DBG_TRG_PULSE_OFFSET	        1
#define M_CTL_RB_CFG_M_SOFT_RST_MCPU_DBG_TRG_PULSE_MASK    		0x2
#define	M_CTL_RB_CFG_M_SOFT_RST_MCU_BUS_TRG_PULSE_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_MCU_BUS_TRG_PULSE_OFFSET	        0
#define M_CTL_RB_CFG_M_SOFT_RST_MCU_BUS_TRG_PULSE_MASK    		0x1

#define	M_CTL_RB_SOFT_RST_HPM_N_LEN	        1
#define	M_CTL_RB_SOFT_RST_HPM_N_OFFSET	        14
#define M_CTL_RB_SOFT_RST_HPM_N_MASK    		0x4000
#define	M_CTL_RB_CFG_M_SOFT_RST_DAP_N_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_DAP_N_OFFSET	        13
#define M_CTL_RB_CFG_M_SOFT_RST_DAP_N_MASK    		0x2000
#define	M_CTL_RB_CFG_M_SOFT_RST_X2H_MEM_BUS_N_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_X2H_MEM_BUS_N_OFFSET	        11
#define M_CTL_RB_CFG_M_SOFT_RST_X2H_MEM_BUS_N_MASK    		0x800
#define	M_CTL_RB_CFG_M_SOFT_RST_XIP_BUS_N_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_XIP_BUS_N_OFFSET	        9
#define M_CTL_RB_CFG_M_SOFT_RST_XIP_BUS_N_MASK    		0x200
#define	M_CTL_RB_SOFT_RST_MEM_HS_GPIO_N_LEN	        1
#define	M_CTL_RB_SOFT_RST_MEM_HS_GPIO_N_OFFSET	        8
#define M_CTL_RB_SOFT_RST_MEM_HS_GPIO_N_MASK    		0x100
#define	M_CTL_RB_SOFT_RST_MDIAG_N_LEN	        1
#define	M_CTL_RB_SOFT_RST_MDIAG_N_OFFSET	        4
#define M_CTL_RB_SOFT_RST_MDIAG_N_MASK    		0x10
#define	M_CTL_RB_CFG_M_SOFT_RST_AUX_ADC_N_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_AUX_ADC_N_OFFSET	        2
#define M_CTL_RB_CFG_M_SOFT_RST_AUX_ADC_N_MASK    		0x4
#define	M_CTL_RB_CFG_M_SOFT_RST_GMMU_RAM_N_LEN	        1
#define	M_CTL_RB_CFG_M_SOFT_RST_GMMU_RAM_N_OFFSET	        1
#define M_CTL_RB_CFG_M_SOFT_RST_GMMU_RAM_N_MASK    		0x2

#define	M_CTL_RB_SOFT_RST_PWM_N_LEN	        1
#define	M_CTL_RB_SOFT_RST_PWM_N_OFFSET	        0
#define M_CTL_RB_SOFT_RST_PWM_N_MASK    		0x1

#define	M_CTL_RB_MCU_MAIN_DFS_S7_CLEAR_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S7_CLEAR_OFFSET	        11
#define M_CTL_RB_MCU_MAIN_DFS_S7_CLEAR_MASK    		0x800
#define	M_CTL_RB_MCU_MAIN_DFS_S7_EN_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S7_EN_OFFSET	        10
#define M_CTL_RB_MCU_MAIN_DFS_S7_EN_MASK    		0x400
#define	M_CTL_RB_MCU_MAIN_DFS_S5_CLEAR_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S5_CLEAR_OFFSET	        7
#define M_CTL_RB_MCU_MAIN_DFS_S5_CLEAR_MASK    		0x80
#define	M_CTL_RB_MCU_MAIN_DFS_S5_EN_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S5_EN_OFFSET	        6
#define M_CTL_RB_MCU_MAIN_DFS_S5_EN_MASK    		0x40
#define	M_CTL_RB_MCU_MAIN_DFS_S4_CLEAR_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S4_CLEAR_OFFSET	        5
#define M_CTL_RB_MCU_MAIN_DFS_S4_CLEAR_MASK    		0x20
#define	M_CTL_RB_MCU_MAIN_DFS_S4_EN_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S4_EN_OFFSET	        4
#define M_CTL_RB_MCU_MAIN_DFS_S4_EN_MASK    		0x10
#define	M_CTL_RB_MCU_MAIN_DFS_S3_CLEAR_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S3_CLEAR_OFFSET	        3
#define M_CTL_RB_MCU_MAIN_DFS_S3_CLEAR_MASK    		0x8
#define	M_CTL_RB_MCU_MAIN_DFS_S3_EN_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S3_EN_OFFSET	        2
#define M_CTL_RB_MCU_MAIN_DFS_S3_EN_MASK    		0x4
#define	M_CTL_RB_MCU_MAIN_DFS_S1_CLEAR_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S1_CLEAR_OFFSET	        1
#define M_CTL_RB_MCU_MAIN_DFS_S1_CLEAR_MASK    		0x2
#define	M_CTL_RB_MCU_MAIN_DFS_S1_EN_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S1_EN_OFFSET	        0
#define M_CTL_RB_MCU_MAIN_DFS_S1_EN_MASK    		0x1

#define	M_CTL_RB_MCU_MAIN_DFS_S7_OVERTIME_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S7_OVERTIME_OFFSET	        5
#define M_CTL_RB_MCU_MAIN_DFS_S7_OVERTIME_MASK    		0x20
#define	M_CTL_RB_MCU_MAIN_DFS_S5_OVERTIME_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S5_OVERTIME_OFFSET	        3
#define M_CTL_RB_MCU_MAIN_DFS_S5_OVERTIME_MASK    		0x8
#define	M_CTL_RB_MCU_MAIN_DFS_S4_OVERTIME_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S4_OVERTIME_OFFSET	        2
#define M_CTL_RB_MCU_MAIN_DFS_S4_OVERTIME_MASK    		0x4
#define	M_CTL_RB_MCU_MAIN_DFS_S3_OVERTIME_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S3_OVERTIME_OFFSET	        1
#define M_CTL_RB_MCU_MAIN_DFS_S3_OVERTIME_MASK    		0x2
#define	M_CTL_RB_MCU_MAIN_DFS_S1_OVERTIME_LEN	        1
#define	M_CTL_RB_MCU_MAIN_DFS_S1_OVERTIME_OFFSET	        0
#define M_CTL_RB_MCU_MAIN_DFS_S1_OVERTIME_MASK    		0x1

#define	M_CTL_RB_MCU_MAIN_AHB_OT_DELAY_LEN	        16
#define	M_CTL_RB_MCU_MAIN_AHB_OT_DELAY_OFFSET	        0
#define M_CTL_RB_MCU_MAIN_AHB_OT_DELAY_MASK    		0xFFFF

#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_EN_OFFSET	        9
#define M_CTL_RB_CFG_M_AUX_ADC_DIV_EN_MASK    		0x200
#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_LOAD_EN_LEN	        1
#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_LOAD_EN_OFFSET	        8
#define M_CTL_RB_CFG_M_AUX_ADC_DIV_LOAD_EN_MASK    		0x100
#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_NUM_LEN	        8
#define	M_CTL_RB_CFG_M_AUX_ADC_DIV_NUM_OFFSET	        0
#define M_CTL_RB_CFG_M_AUX_ADC_DIV_NUM_MASK    		0xFF

#define	M_CTL_RB_SOFT_RST_N_M2D_INT1_LEN	        1
#define	M_CTL_RB_SOFT_RST_N_M2D_INT1_OFFSET	        7
#define M_CTL_RB_SOFT_RST_N_M2D_INT1_MASK    		0x80
#define	M_CTL_RB_SOFT_RST_N_M2D_INT0_LEN	        1
#define	M_CTL_RB_SOFT_RST_N_M2D_INT0_OFFSET	        6
#define M_CTL_RB_SOFT_RST_N_M2D_INT0_MASK    		0x40
#define	M_CTL_RB_SOFT_RST_N_M2B_INT1_LEN	        1
#define	M_CTL_RB_SOFT_RST_N_M2B_INT1_OFFSET	        1
#define M_CTL_RB_SOFT_RST_N_M2B_INT1_MASK    		0x2
#define	M_CTL_RB_SOFT_RST_N_M2B_INT0_LEN	        1
#define	M_CTL_RB_SOFT_RST_N_M2B_INT0_OFFSET	        0
#define M_CTL_RB_SOFT_RST_N_M2B_INT0_MASK    		0x1

#define	M_CTL_RB_MONITOR_TCM_ADDR0_L_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR0_L_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR0_L_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR1_L_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR1_L_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR1_L_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR2_L_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR2_L_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR2_L_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR3_L_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR3_L_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR3_L_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR0_H_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR0_H_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR0_H_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR1_H_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR1_H_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR1_H_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR2_H_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR2_H_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR2_H_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MONITOR_TCM_ADDR3_H_LEN	        32
#define	M_CTL_RB_MONITOR_TCM_ADDR3_H_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR3_H_MASK    		0xFFFFFFFF

#define	M_CTL_RB_TCM_REC_ADDR_LEN	        32
#define	M_CTL_RB_TCM_REC_ADDR_OFFSET	        0
#define M_CTL_RB_TCM_REC_ADDR_MASK    		0xFFFFFFFF

#define	M_CTL_RB_TCM_REC_PC_LEN	        32
#define	M_CTL_RB_TCM_REC_PC_OFFSET	        0
#define M_CTL_RB_TCM_REC_PC_MASK    		0xFFFFFFFF

#define	M_CTL_RB_TCM_REC_LR_LEN	        32
#define	M_CTL_RB_TCM_REC_LR_OFFSET	        0
#define M_CTL_RB_TCM_REC_LR_MASK    		0xFFFFFFFF

#define	M_CTL_RB_TCM_REC_SP_LEN	        32
#define	M_CTL_RB_TCM_REC_SP_OFFSET	        0
#define M_CTL_RB_TCM_REC_SP_MASK    		0xFFFFFFFF

#define	M_CTL_RB_TCM_MONITOR_INT_MASK_LEN	        1
#define	M_CTL_RB_TCM_MONITOR_INT_MASK_OFFSET	        10
#define M_CTL_RB_TCM_MONITOR_INT_MASK_MASK    		0x400
#define	M_CTL_RB_TCM_MONITOR_INT_CLR_LEN	        1
#define	M_CTL_RB_TCM_MONITOR_INT_CLR_OFFSET	        9
#define M_CTL_RB_TCM_MONITOR_INT_CLR_MASK    		0x200
#define	M_CTL_RB_CPUTCM_MONITOR_EN_LEN	        1
#define	M_CTL_RB_CPUTCM_MONITOR_EN_OFFSET	        8
#define M_CTL_RB_CPUTCM_MONITOR_EN_MASK    		0x100
#define	M_CTL_RB_MONITOR_TCM_ADDR_EN_LEN	        8
#define	M_CTL_RB_MONITOR_TCM_ADDR_EN_OFFSET	        0
#define M_CTL_RB_MONITOR_TCM_ADDR_EN_MASK    		0xFF

#define	M_CTL_RB_TCM_REC_WR_LEN	        1
#define	M_CTL_RB_TCM_REC_WR_OFFSET	        12
#define M_CTL_RB_TCM_REC_WR_MASK    		0x1000
#define	M_CTL_RB_TCM_REC_MASTER_LEN	        4
#define	M_CTL_RB_TCM_REC_MASTER_OFFSET	        8
#define M_CTL_RB_TCM_REC_MASTER_MASK    		0xF00
#define	M_CTL_RB_TCM_MONITOR_INT_STS_LEN	        8
#define	M_CTL_RB_TCM_MONITOR_INT_STS_OFFSET	        0
#define M_CTL_RB_TCM_MONITOR_INT_STS_MASK    		0xFF

#define	M_CTL_RB_CFG_M_MCU_BUS_LOAD_DIV_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_MCU_BUS_LOAD_DIV_CLKEN_OFFSET	        3
#define M_CTL_RB_CFG_M_MCU_BUS_LOAD_DIV_CLKEN_MASK    		0x8
#define	M_CTL_RB_CFG_M_MCU_BUS_DIV_NUM_LEN	        3
#define	M_CTL_RB_CFG_M_MCU_BUS_DIV_NUM_OFFSET	        0
#define M_CTL_RB_CFG_M_MCU_BUS_DIV_NUM_MASK    		0x7

#define	M_CTL_RB_MCU_IRQ_SYNC_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_MCU_IRQ_SYNC_CLK_FORCE_ON_OFFSET	        27
#define M_CTL_RB_MCU_IRQ_SYNC_CLK_FORCE_ON_MASK    		0x8000000
#define	M_CTL_RB_MEM_MAIN_AXI_GLB_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MEM_MAIN_AXI_GLB_CG_BYPASS_OFFSET	        26
#define M_CTL_RB_MEM_MAIN_AXI_GLB_CG_BYPASS_MASK    		0x4000000
#define	M_CTL_RB_MEM_CLK_FORCE_ON_DTCMRAM_LEN	        1
#define	M_CTL_RB_MEM_CLK_FORCE_ON_DTCMRAM_OFFSET	        25
#define M_CTL_RB_MEM_CLK_FORCE_ON_DTCMRAM_MASK    		0x2000000
#define	M_CTL_RB_MCU_MICMS1_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS1_AUTO_CG_BYPASS_OFFSET	        24
#define M_CTL_RB_MCU_MICMS1_AUTO_CG_BYPASS_MASK    		0x1000000
#define	M_CTL_RB_MCPU_PERP_AXI_GLB_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCPU_PERP_AXI_GLB_CG_BYPASS_OFFSET	        23
#define M_CTL_RB_MCPU_PERP_AXI_GLB_CG_BYPASS_MASK    		0x800000
#define	M_CTL_RB_MCU_MICMS2_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS2_AUTO_CG_BYPASS_OFFSET	        22
#define M_CTL_RB_MCU_MICMS2_AUTO_CG_BYPASS_MASK    		0x400000
#define	M_CTL_RB_MEM_CLK_FORCE_ON_ITCMRAM_LEN	        1
#define	M_CTL_RB_MEM_CLK_FORCE_ON_ITCMRAM_OFFSET	        21
#define M_CTL_RB_MEM_CLK_FORCE_ON_ITCMRAM_MASK    		0x200000
#define	M_CTL_RB_MCU_EXT_APB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_EXT_APB_AUTO_CG_BYPASS_OFFSET	        20
#define M_CTL_RB_MCU_EXT_APB_AUTO_CG_BYPASS_MASK    		0x100000
#define	M_CTL_RB_MCU_PERP_AXI_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_AUTO_CG_BYPASS_OFFSET	        19
#define M_CTL_RB_MCU_PERP_AXI_AUTO_CG_BYPASS_MASK    		0x80000
#define	M_CTL_RB_MCU_PERP_A2X_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_PERP_A2X_AUTO_CG_BYPASS_OFFSET	        18
#define M_CTL_RB_MCU_PERP_A2X_AUTO_CG_BYPASS_MASK    		0x40000
#define	M_CTL_RB_MCPU_MDMA_A2X_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCPU_MDMA_A2X_AUTO_CG_BYPASS_OFFSET	        17
#define M_CTL_RB_MCPU_MDMA_A2X_AUTO_CG_BYPASS_MASK    		0x20000
#define	M_CTL_RB_MCU_SEC2MCU_EH2H_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_SEC2MCU_EH2H_AUTO_CG_BYPASS_OFFSET	        16
#define M_CTL_RB_MCU_SEC2MCU_EH2H_AUTO_CG_BYPASS_MASK    		0x10000
#define	M_CTL_RB_MCU_MICMS7_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS7_AUTO_CG_BYPASS_OFFSET	        15
#define M_CTL_RB_MCU_MICMS7_AUTO_CG_BYPASS_MASK    		0x8000
#define	M_CTL_RB_MEM_CLK_FORCE_ON_ITCMROM_LEN	        1
#define	M_CTL_RB_MEM_CLK_FORCE_ON_ITCMROM_OFFSET	        14
#define M_CTL_RB_MEM_CLK_FORCE_ON_ITCMROM_MASK    		0x4000
#define	M_CTL_RB_MCU_MICMS5_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS5_AUTO_CG_BYPASS_OFFSET	        13
#define M_CTL_RB_MCU_MICMS5_AUTO_CG_BYPASS_MASK    		0x2000
#define	M_CTL_RB_MCU_MICMS4_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS4_AUTO_CG_BYPASS_OFFSET	        12
#define M_CTL_RB_MCU_MICMS4_AUTO_CG_BYPASS_MASK    		0x1000
#define	M_CTL_RB_MCU_MICMS3_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MICMS3_AUTO_CG_BYPASS_OFFSET	        11
#define M_CTL_RB_MCU_MICMS3_AUTO_CG_BYPASS_MASK    		0x800
#define	M_CTL_RB_MCU_H5_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_H5_AHB_AUTO_CG_BYPASS_OFFSET	        10
#define M_CTL_RB_MCU_H5_AHB_AUTO_CG_BYPASS_MASK    		0x400
#define	M_CTL_RB_MCU_H4_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_H4_AHB_AUTO_CG_BYPASS_OFFSET	        9
#define M_CTL_RB_MCU_H4_AHB_AUTO_CG_BYPASS_MASK    		0x200
#define	M_CTL_RB_MCU_H3_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_H3_AHB_AUTO_CG_BYPASS_OFFSET	        8
#define M_CTL_RB_MCU_H3_AHB_AUTO_CG_BYPASS_MASK    		0x100
#define	M_CTL_RB_MCU_H2_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_H2_AHB_AUTO_CG_BYPASS_OFFSET	        7
#define M_CTL_RB_MCU_H2_AHB_AUTO_CG_BYPASS_MASK    		0x80
#define	M_CTL_RB_MCU_H1_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_H1_AHB_AUTO_CG_BYPASS_OFFSET	        6
#define M_CTL_RB_MCU_H1_AHB_AUTO_CG_BYPASS_MASK    		0x40
#define	M_CTL_RB_MCU_CFG_AHB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_CFG_AHB_AUTO_CG_BYPASS_OFFSET	        5
#define M_CTL_RB_MCU_CFG_AHB_AUTO_CG_BYPASS_MASK    		0x20
#define	M_CTL_RB_MCU_MCU2COM_EH2H_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MCU2COM_EH2H_AUTO_CG_BYPASS_OFFSET	        4
#define M_CTL_RB_MCU_MCU2COM_EH2H_AUTO_CG_BYPASS_MASK    		0x10
#define	M_CTL_RB_MCU_COM2MCU_EH2H_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_COM2MCU_EH2H_AUTO_CG_BYPASS_OFFSET	        3
#define M_CTL_RB_MCU_COM2MCU_EH2H_AUTO_CG_BYPASS_MASK    		0x8
#define	M_CTL_RB_MEM_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_MEM_CLK_FORCE_ON_OFFSET	        2
#define M_CTL_RB_MEM_CLK_FORCE_ON_MASK    		0x4
#define	M_CTL_RB_MCU_MCU2AON_H2H_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MCU2AON_H2H_AUTO_CG_BYPASS_OFFSET	        1
#define M_CTL_RB_MCU_MCU2AON_H2H_AUTO_CG_BYPASS_MASK    		0x2
#define	M_CTL_RB_MCU_PERP_APB_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_PERP_APB_AUTO_CG_BYPASS_OFFSET	        0
#define M_CTL_RB_MCU_PERP_APB_AUTO_CG_BYPASS_MASK    		0x1

#define	M_CTL_RB_MCU_BUS_S_PRT_CFG_PGCG_EN_LEN	        12
#define	M_CTL_RB_MCU_BUS_S_PRT_CFG_PGCG_EN_OFFSET	        0
#define M_CTL_RB_MCU_BUS_S_PRT_CFG_PGCG_EN_MASK    		0xFFF

#define	M_CTL_RB_MCU_BUS_CFG_CLKEN_LEN	        6
#define	M_CTL_RB_MCU_BUS_CFG_CLKEN_OFFSET	        6
#define M_CTL_RB_MCU_BUS_CFG_CLKEN_MASK    		0xFC0
#define	M_CTL_RB_MCU_BUS_S_SOFT_RST_N_LEN	        6
#define	M_CTL_RB_MCU_BUS_S_SOFT_RST_N_OFFSET	        0
#define M_CTL_RB_MCU_BUS_S_SOFT_RST_N_MASK    		0x3F

#define	M_CTL_RB_SDMA_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_SDMA_RST_SOFT_N_OFFSET	        2
#define M_CTL_RB_SDMA_RST_SOFT_N_MASK    		0x4
#define	M_CTL_RB_MDMA_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_MDMA_RST_SOFT_N_OFFSET	        1
#define M_CTL_RB_MDMA_RST_SOFT_N_MASK    		0x2
#define	M_CTL_RB_TIMER_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_TIMER_RST_SOFT_N_OFFSET	        0
#define M_CTL_RB_TIMER_RST_SOFT_N_MASK    		0x1

#define	M_CTL_RB_MTOP0_CUR_STS_LEN	        3
#define	M_CTL_RB_MTOP0_CUR_STS_OFFSET	        0
#define M_CTL_RB_MTOP0_CUR_STS_MASK    		0x7

#define	M_CTL_RB_UART_H1_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_UART_H1_RST_SOFT_N_OFFSET	        7
#define M_CTL_RB_UART_H1_RST_SOFT_N_MASK    		0x80
#define	M_CTL_RB_M_GPIO_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_M_GPIO_RST_SOFT_N_OFFSET	        5
#define M_CTL_RB_M_GPIO_RST_SOFT_N_MASK    		0x20
#define	M_CTL_RB_I2C3_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_I2C3_RST_SOFT_N_OFFSET	        3
#define M_CTL_RB_I2C3_RST_SOFT_N_MASK    		0x8
#define	M_CTL_RB_I2C2_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_I2C2_RST_SOFT_N_OFFSET	        2
#define M_CTL_RB_I2C2_RST_SOFT_N_MASK    		0x4
#define	M_CTL_RB_I2C1_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_I2C1_RST_SOFT_N_OFFSET	        1
#define M_CTL_RB_I2C1_RST_SOFT_N_MASK    		0x2
#define	M_CTL_RB_I2C0_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_I2C0_RST_SOFT_N_OFFSET	        0
#define M_CTL_RB_I2C0_RST_SOFT_N_MASK    		0x1

#define	M_CTL_RB_MTOP1_CUR_STS_LEN	        7
#define	M_CTL_RB_MTOP1_CUR_STS_OFFSET	        0
#define M_CTL_RB_MTOP1_CUR_STS_MASK    		0x7F

#define	M_CTL_RB_SPI0_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_SPI0_RST_SOFT_N_OFFSET	        1
#define M_CTL_RB_SPI0_RST_SOFT_N_MASK    		0x2
#define	M_CTL_RB_SPI1_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_SPI1_RST_SOFT_N_OFFSET	        0
#define M_CTL_RB_SPI1_RST_SOFT_N_MASK    		0x1

#define	M_CTL_RB_UART_L0_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_UART_L0_RST_SOFT_N_OFFSET	        1
#define M_CTL_RB_UART_L0_RST_SOFT_N_MASK    		0x2
#define	M_CTL_RB_UART_H0_RST_SOFT_N_LEN	        1
#define	M_CTL_RB_UART_H0_RST_SOFT_N_OFFSET	        0
#define M_CTL_RB_UART_H0_RST_SOFT_N_MASK    		0x1

#define	M_CTL_RB_MTOP3_CUR_STS_LEN	        3
#define	M_CTL_RB_MTOP3_CUR_STS_OFFSET	        0
#define M_CTL_RB_MTOP3_CUR_STS_MASK    		0x7

#define	M_CTL_RB_UART_H1_AUTOCG_BYPASS_LEN	        1
#define	M_CTL_RB_UART_H1_AUTOCG_BYPASS_OFFSET	        9
#define M_CTL_RB_UART_H1_AUTOCG_BYPASS_MASK    		0x200
#define	M_CTL_RB_UART_L0_AUTOCG_BYPASS_LEN	        1
#define	M_CTL_RB_UART_L0_AUTOCG_BYPASS_OFFSET	        8
#define M_CTL_RB_UART_L0_AUTOCG_BYPASS_MASK    		0x100
#define	M_CTL_RB_UART_H0_AUTOCG_BYPASS_LEN	        1
#define	M_CTL_RB_UART_H0_AUTOCG_BYPASS_OFFSET	        7
#define M_CTL_RB_UART_H0_AUTOCG_BYPASS_MASK    		0x80
#define	M_CTL_RB_MCU_SDMA_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_SDMA_AUTO_CG_BYPASS_OFFSET	        6
#define M_CTL_RB_MCU_SDMA_AUTO_CG_BYPASS_MASK    		0x40
#define	M_CTL_RB_MCU_MDMA_AUTO_CG_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MDMA_AUTO_CG_BYPASS_OFFSET	        5
#define M_CTL_RB_MCU_MDMA_AUTO_CG_BYPASS_MASK    		0x20
#define	M_CTL_RB_SPI0_CG_BYPASS_EN_LEN	        1
#define	M_CTL_RB_SPI0_CG_BYPASS_EN_OFFSET	        3
#define M_CTL_RB_SPI0_CG_BYPASS_EN_MASK    		0x8
#define	M_CTL_RB_SPI1_CG_BYPASS_EN_LEN	        1
#define	M_CTL_RB_SPI1_CG_BYPASS_EN_OFFSET	        2
#define M_CTL_RB_SPI1_CG_BYPASS_EN_MASK    		0x4
#define	M_CTL_RB_MCU_SDMA_HRDATA_EN_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_SDMA_HRDATA_EN_BYPASS_OFFSET	        1
#define M_CTL_RB_MCU_SDMA_HRDATA_EN_BYPASS_MASK    		0x2
#define	M_CTL_RB_MCU_MDMA_HRDATA_EN_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_MDMA_HRDATA_EN_BYPASS_OFFSET	        0
#define M_CTL_RB_MCU_MDMA_HRDATA_EN_BYPASS_MASK    		0x1

#define	M_CTL_RB_MTOP4_CUR_STS_LEN	        2
#define	M_CTL_RB_MTOP4_CUR_STS_OFFSET	        0
#define M_CTL_RB_MTOP4_CUR_STS_MASK    		0x3

#define	M_CTL_RB_MDAM_H2X_CACTIVE_LEN	        1
#define	M_CTL_RB_MDAM_H2X_CACTIVE_OFFSET	        13
#define M_CTL_RB_MDAM_H2X_CACTIVE_MASK    		0x2000
#define	M_CTL_RB_MAIN_AXI_S8_CACTIVE_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S8_CACTIVE_OFFSET	        12
#define M_CTL_RB_MAIN_AXI_S8_CACTIVE_MASK    		0x1000
#define	M_CTL_RB_MCU_PERP_A2X_CSYSREQ_LEN	        1
#define	M_CTL_RB_MCU_PERP_A2X_CSYSREQ_OFFSET	        11
#define M_CTL_RB_MCU_PERP_A2X_CSYSREQ_MASK    		0x800
#define	M_CTL_RB_MAIN_AXI_S1_CACTIVE_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S1_CACTIVE_OFFSET	        10
#define M_CTL_RB_MAIN_AXI_S1_CACTIVE_MASK    		0x400
#define	M_CTL_RB_MAXI2MAHB_AX2H_CSYSACK_LEN	        1
#define	M_CTL_RB_MAXI2MAHB_AX2H_CSYSACK_OFFSET	        9
#define M_CTL_RB_MAXI2MAHB_AX2H_CSYSACK_MASK    		0x200
#define	M_CTL_RB_MDMA_H2X_CSYSACK_LEN	        1
#define	M_CTL_RB_MDMA_H2X_CSYSACK_OFFSET	        8
#define M_CTL_RB_MDMA_H2X_CSYSACK_MASK    		0x100
#define	M_CTL_RB_MAIN_AXI_S8_CSYSACK_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S8_CSYSACK_OFFSET	        7
#define M_CTL_RB_MAIN_AXI_S8_CSYSACK_MASK    		0x80
#define	M_CTL_RB_MAIN_AXI_S2_CSYSACK_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S2_CSYSACK_OFFSET	        6
#define M_CTL_RB_MAIN_AXI_S2_CSYSACK_MASK    		0x40
#define	M_CTL_RB_MAIN_AXI_S1_CSYSACK_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S1_CSYSACK_OFFSET	        5
#define M_CTL_RB_MAIN_AXI_S1_CSYSACK_MASK    		0x20
#define	M_CTL_RB_MDMA_H2X_CSYSREQ_LEN	        1
#define	M_CTL_RB_MDMA_H2X_CSYSREQ_OFFSET	        3
#define M_CTL_RB_MDMA_H2X_CSYSREQ_MASK    		0x8
#define	M_CTL_RB_MAIN_AXI_S8_CSYSREQ_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S8_CSYSREQ_OFFSET	        2
#define M_CTL_RB_MAIN_AXI_S8_CSYSREQ_MASK    		0x4
#define	M_CTL_RB_MAIN_AXI_S2_CSYSREQ_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S2_CSYSREQ_OFFSET	        1
#define M_CTL_RB_MAIN_AXI_S2_CSYSREQ_MASK    		0x2
#define	M_CTL_RB_MAIN_AXI_S1_CSYSREQ_LEN	        1
#define	M_CTL_RB_MAIN_AXI_S1_CSYSREQ_OFFSET	        0
#define M_CTL_RB_MAIN_AXI_S1_CSYSREQ_MASK    		0x1

#define	M_CTL_RB_PERP_A2X_BUSY_STATUS_LEN	        1
#define	M_CTL_RB_PERP_A2X_BUSY_STATUS_OFFSET	        14
#define M_CTL_RB_PERP_A2X_BUSY_STATUS_MASK    		0x4000
#define	M_CTL_RB_MDMA_A2X_BUSY_STATUS_LEN	        1
#define	M_CTL_RB_MDMA_A2X_BUSY_STATUS_OFFSET	        12
#define M_CTL_RB_MDMA_A2X_BUSY_STATUS_MASK    		0x1000
#define	M_CTL_RB_PERP_AXI_AW_ERR_INT_RAW_STS_LEN	        1
#define	M_CTL_RB_PERP_AXI_AW_ERR_INT_RAW_STS_OFFSET	        11
#define M_CTL_RB_PERP_AXI_AW_ERR_INT_RAW_STS_MASK    		0x800
#define	M_CTL_RB_PERP_AXI_AR_ERR_INT_RAW_STS_LEN	        1
#define	M_CTL_RB_PERP_AXI_AR_ERR_INT_RAW_STS_OFFSET	        10
#define M_CTL_RB_PERP_AXI_AR_ERR_INT_RAW_STS_MASK    		0x400
#define	M_CTL_RB_MCPU_SEC_A2X_CACTIVE_LEN	        1
#define	M_CTL_RB_MCPU_SEC_A2X_CACTIVE_OFFSET	        9
#define M_CTL_RB_MCPU_SEC_A2X_CACTIVE_MASK    		0x200
#define	M_CTL_RB_SDIO_M_AH2X_CACTIVE_LEN	        1
#define	M_CTL_RB_SDIO_M_AH2X_CACTIVE_OFFSET	        8
#define M_CTL_RB_SDIO_M_AH2X_CACTIVE_MASK    		0x100
#define	M_CTL_RB_PERP_AXI_AR_ERR_STS_VLD_LEN	        1
#define	M_CTL_RB_PERP_AXI_AR_ERR_STS_VLD_OFFSET	        7
#define M_CTL_RB_PERP_AXI_AR_ERR_STS_VLD_MASK    		0x80
#define	M_CTL_RB_PERP_AXI_AW_ERR_STS_VLD_LEN	        1
#define	M_CTL_RB_PERP_AXI_AW_ERR_STS_VLD_OFFSET	        6
#define M_CTL_RB_PERP_AXI_AW_ERR_STS_VLD_MASK    		0x40
#define	M_CTL_RB_SDIO_M_AH2X_CSYSACK_LEN	        1
#define	M_CTL_RB_SDIO_M_AH2X_CSYSACK_OFFSET	        4
#define M_CTL_RB_SDIO_M_AH2X_CSYSACK_MASK    		0x10

#define	M_CTL_RB_MEM_MONITOR_INT_PC_LEN	        32
#define	M_CTL_RB_MEM_MONITOR_INT_PC_OFFSET	        0
#define M_CTL_RB_MEM_MONITOR_INT_PC_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MEM_MONITOR_INT_LR_LEN	        32
#define	M_CTL_RB_MEM_MONITOR_INT_LR_OFFSET	        0
#define M_CTL_RB_MEM_MONITOR_INT_LR_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MEM_MONITOR_INT_SP_LEN	        32
#define	M_CTL_RB_MEM_MONITOR_INT_SP_OFFSET	        0
#define M_CTL_RB_MEM_MONITOR_INT_SP_MASK    		0xFFFFFFFF

#define	M_CTL_RB_ACCESS_MEM_INT_OR_CLR_LEN	        1
#define	M_CTL_RB_ACCESS_MEM_INT_OR_CLR_OFFSET	        0
#define M_CTL_RB_ACCESS_MEM_INT_OR_CLR_MASK    		0x1

#define	M_CTL_RB_EH2H_C2G_INTR_LEN	        1
#define	M_CTL_RB_EH2H_C2G_INTR_OFFSET	        7
#define M_CTL_RB_EH2H_C2G_INTR_MASK    		0x80
#define	M_CTL_RB_EH2H_G2C_INTR_LEN	        1
#define	M_CTL_RB_EH2H_G2C_INTR_OFFSET	        6
#define M_CTL_RB_EH2H_G2C_INTR_MASK    		0x40
#define	M_CTL_RB_EH2H_C2S_INTR_LEN	        1
#define	M_CTL_RB_EH2H_C2S_INTR_OFFSET	        5
#define M_CTL_RB_EH2H_C2S_INTR_MASK    		0x20
#define	M_CTL_RB_EH2H_S2C_INTR_LEN	        1
#define	M_CTL_RB_EH2H_S2C_INTR_OFFSET	        4
#define M_CTL_RB_EH2H_S2C_INTR_MASK    		0x10
#define	M_CTL_RB_MAIN_AHB_COM_EH2H_LEN	        1
#define	M_CTL_RB_MAIN_AHB_COM_EH2H_OFFSET	        3
#define M_CTL_RB_MAIN_AHB_COM_EH2H_MASK    		0x8
#define	M_CTL_RB_BTOP_BUS_COM_EH2H_LEN	        1
#define	M_CTL_RB_BTOP_BUS_COM_EH2H_OFFSET	        2
#define M_CTL_RB_BTOP_BUS_COM_EH2H_MASK    		0x4
#define	M_CTL_RB_COM_BTOP_BUS_EH2H_LEN	        1
#define	M_CTL_RB_COM_BTOP_BUS_EH2H_OFFSET	        1
#define M_CTL_RB_COM_BTOP_BUS_EH2H_MASK    		0x2
#define	M_CTL_RB_COM_MAIN_AHB_EH2H_LEN	        1
#define	M_CTL_RB_COM_MAIN_AHB_EH2H_OFFSET	        0
#define M_CTL_RB_COM_MAIN_AHB_EH2H_MASK    		0x1

#define	M_CTL_RB_EH2H_BRG_INT_CLR_LEN	        1
#define	M_CTL_RB_EH2H_BRG_INT_CLR_OFFSET	        0
#define M_CTL_RB_EH2H_BRG_INT_CLR_MASK    		0x1

#define	M_CTL_RB_EH2H_BRG_INT_EN_LEN	        1
#define	M_CTL_RB_EH2H_BRG_INT_EN_OFFSET	        0
#define M_CTL_RB_EH2H_BRG_INT_EN_MASK    		0x1

#define	M_CTL_RB_CFG_CRC_PSTRB_SEL_LEN	        1
#define	M_CTL_RB_CFG_CRC_PSTRB_SEL_OFFSET	        7
#define M_CTL_RB_CFG_CRC_PSTRB_SEL_MASK    		0x80
#define	M_CTL_RB_SEC_CRC_PPROT_LEN	        3
#define	M_CTL_RB_SEC_CRC_PPROT_OFFSET	        4
#define M_CTL_RB_SEC_CRC_PPROT_MASK    		0x70
#define	M_CTL_RB_SEC_CRC_PSTRB_LEN	        4
#define	M_CTL_RB_SEC_CRC_PSTRB_OFFSET	        0
#define M_CTL_RB_SEC_CRC_PSTRB_MASK    		0xF

#define	M_CTL_RB_MCU_MDMA_A2X_HINCR_WBCNT_M_LEN	        4
#define	M_CTL_RB_MCU_MDMA_A2X_HINCR_WBCNT_M_OFFSET	        8
#define M_CTL_RB_MCU_MDMA_A2X_HINCR_WBCNT_M_MASK    		0xF00
#define	M_CTL_RB_MCU_PERP_A2X_HINCR_WBCNT_M_LEN	        4
#define	M_CTL_RB_MCU_PERP_A2X_HINCR_WBCNT_M_OFFSET	        4
#define M_CTL_RB_MCU_PERP_A2X_HINCR_WBCNT_M_MASK    		0xF0

#define	M_CTL_RB_MCU_MDMA_A2X_HINCR_RBCNT_M_LEN	        4
#define	M_CTL_RB_MCU_MDMA_A2X_HINCR_RBCNT_M_OFFSET	        8
#define M_CTL_RB_MCU_MDMA_A2X_HINCR_RBCNT_M_MASK    		0xF00
#define	M_CTL_RB_MCU_PERP_A2X_HINCR_RBCNT_M_LEN	        4
#define	M_CTL_RB_MCU_PERP_A2X_HINCR_RBCNT_M_OFFSET	        4
#define M_CTL_RB_MCU_PERP_A2X_HINCR_RBCNT_M_MASK    		0xF0

#define	M_CTL_RB_UART_H1_TRX_CFG_LEN	        1
#define	M_CTL_RB_UART_H1_TRX_CFG_OFFSET	        3
#define M_CTL_RB_UART_H1_TRX_CFG_MASK    		0x8
#define	M_CTL_RB_UART_H0_TRX_CFG_LEN	        1
#define	M_CTL_RB_UART_H0_TRX_CFG_OFFSET	        2
#define M_CTL_RB_UART_H0_TRX_CFG_MASK    		0x4
#define	M_CTL_RB_UART_L0_TRX_CFG_MCU_LEN	        1
#define	M_CTL_RB_UART_L0_TRX_CFG_MCU_OFFSET	        1
#define M_CTL_RB_UART_L0_TRX_CFG_MCU_MASK    		0x2

#define	M_CTL_RB_RFSHD_SP_RAM_TMOD_LEN	        16
#define	M_CTL_RB_RFSHD_SP_RAM_TMOD_OFFSET	        0
#define M_CTL_RB_RFSHD_SP_RAM_TMOD_MASK    		0xFFFF

#define	M_CTL_RB_RFSHS_SP_RAM_TMOD_LEN	        16
#define	M_CTL_RB_RFSHS_SP_RAM_TMOD_OFFSET	        0
#define M_CTL_RB_RFSHS_SP_RAM_TMOD_MASK    		0xFFFF

#define	M_CTL_RB_RASHD_SP_RAM_TMOD_LEN	        16
#define	M_CTL_RB_RASHD_SP_RAM_TMOD_OFFSET	        0
#define M_CTL_RB_RASHD_SP_RAM_TMOD_MASK    		0xFFFF

#define	M_CTL_RB_RASHS_SP_RAM_TMOD_LEN	        16
#define	M_CTL_RB_RASHS_SP_RAM_TMOD_OFFSET	        0
#define M_CTL_RB_RASHS_SP_RAM_TMOD_MASK    		0xFFFF

#define	M_CTL_RB_MCU_SYS_HPM_SHIFT_LEN	        2
#define	M_CTL_RB_MCU_SYS_HPM_SHIFT_OFFSET	        6
#define M_CTL_RB_MCU_SYS_HPM_SHIFT_MASK    		0xC0
#define	M_CTL_RB_MCU_SYS_HPM_DIV_LEN	        6
#define	M_CTL_RB_MCU_SYS_HPM_DIV_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_DIV_MASK    		0x3F

#define	M_CTL_RB_MCU_SYS_HPM_CG_EN_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_CG_EN_OFFSET	        14
#define M_CTL_RB_MCU_SYS_HPM_CG_EN_MASK    		0x4000
#define	M_CTL_RB_MCU_SYS_HPM_CLR_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_CLR_OFFSET	        13
#define M_CTL_RB_MCU_SYS_HPM_CLR_MASK    		0x2000
#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_EN_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_EN_OFFSET	        12
#define M_CTL_RB_MCU_SYS_HPM_MONITOR_EN_MASK    		0x1000
#define	M_CTL_RB_MCU_SYS_HPM_BYPASS_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_BYPASS_OFFSET	        11
#define M_CTL_RB_MCU_SYS_HPM_BYPASS_MASK    		0x800
#define	M_CTL_RB_MCU_SYS_HPM_EN_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_EN_OFFSET	        10
#define M_CTL_RB_MCU_SYS_HPM_EN_MASK    		0x400
#define	M_CTL_RB_MCU_SYS_HPM_OFFSET_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_OFFSET_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_OFFSET_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_PC_VALID_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_PC_VALID_OFFSET	        10
#define M_CTL_RB_MCU_SYS_HPM_PC_VALID_MASK    		0x400
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD0_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD0_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_PC_RECORD0_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_UP_WARNING_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_UP_WARNING_OFFSET	        11
#define M_CTL_RB_MCU_SYS_HPM_UP_WARNING_MASK    		0x800
#define	M_CTL_RB_MCU_SYS_HPM_LOW_WARNING_LEN	        1
#define	M_CTL_RB_MCU_SYS_HPM_LOW_WARNING_OFFSET	        10
#define M_CTL_RB_MCU_SYS_HPM_LOW_WARNING_MASK    		0x400
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD1_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD1_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_PC_RECORD1_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD2_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD2_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_PC_RECORD2_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD3_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_PC_RECORD3_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_PC_RECORD3_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_UPLIMIT_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_UPLIMIT_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_UPLIMIT_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_LOWLIMIT_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_LOWLIMIT_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_LOWLIMIT_MASK    		0x3FF

#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_LEN	        8
#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_OFFSET	        8
#define M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_MASK    		0xFF00
#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_FINE_LEN	        8
#define	M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_FINE_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_MONITOR_PERIOD_FINE_MASK    		0xFF

#define	M_CTL_RB_MCU_SYS_HPM_RCC_LEN	        10
#define	M_CTL_RB_MCU_SYS_HPM_RCC_OFFSET	        0
#define M_CTL_RB_MCU_SYS_HPM_RCC_MASK    		0x3FF

#define	M_CTL_RB_MCPU_MEM_ROM_CTRL_LEN	        7
#define	M_CTL_RB_MCPU_MEM_ROM_CTRL_OFFSET	        0
#define M_CTL_RB_MCPU_MEM_ROM_CTRL_MASK    		0x7F

#define	M_CTL_RB_SDMA_CLKEN_NOR_LEN	        1
#define	M_CTL_RB_SDMA_CLKEN_NOR_OFFSET	        1
#define M_CTL_RB_SDMA_CLKEN_NOR_MASK    		0x2
#define	M_CTL_RB_MDMA_CLKEN_NOR_LEN	        1
#define	M_CTL_RB_MDMA_CLKEN_NOR_OFFSET	        0
#define M_CTL_RB_MDMA_CLKEN_NOR_MASK    		0x1

#define	M_CTL_RB_SECMEM_PWR_MOD_RT1N_LEN	        1
#define	M_CTL_RB_SECMEM_PWR_MOD_RT1N_OFFSET	        2
#define M_CTL_RB_SECMEM_PWR_MOD_RT1N_MASK    		0x4
#define	M_CTL_RB_TRACE_PWR_MOD_RT1N_LEN	        1
#define	M_CTL_RB_TRACE_PWR_MOD_RT1N_OFFSET	        1
#define M_CTL_RB_TRACE_PWR_MOD_RT1N_MASK    		0x2
#define	M_CTL_RB_CACHE_PWR_MOD_RT1N_LEN	        1
#define	M_CTL_RB_CACHE_PWR_MOD_RT1N_OFFSET	        0
#define M_CTL_RB_CACHE_PWR_MOD_RT1N_MASK    		0x1

#define	M_CTL_RB_MCU_SYS_TICK_FRZ_D_LEN	        1
#define	M_CTL_RB_MCU_SYS_TICK_FRZ_D_OFFSET	        0
#define M_CTL_RB_MCU_SYS_TICK_FRZ_D_MASK    		0x1

#define	M_CTL_RB_MCU_SYS_TICK_VALUE_D_0_LEN	        32
#define	M_CTL_RB_MCU_SYS_TICK_VALUE_D_0_OFFSET	        0
#define M_CTL_RB_MCU_SYS_TICK_VALUE_D_0_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MCU_SYS_TICK_VALUE_D_1_LEN	        32
#define	M_CTL_RB_MCU_SYS_TICK_VALUE_D_1_OFFSET	        0
#define M_CTL_RB_MCU_SYS_TICK_VALUE_D_1_MASK    		0xFFFFFFFF

#define	M_CTL_RB_MCU_ROM_TMOD_SEL_REG_LEN	        1
#define	M_CTL_RB_MCU_ROM_TMOD_SEL_REG_OFFSET	        1
#define M_CTL_RB_MCU_ROM_TMOD_SEL_REG_MASK    		0x2
#define	M_CTL_RB_MCU_SP_RAM_EMA_SEL_REG_LEN	        1
#define	M_CTL_RB_MCU_SP_RAM_EMA_SEL_REG_OFFSET	        0
#define M_CTL_RB_MCU_SP_RAM_EMA_SEL_REG_MASK    		0x1

#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_EN_OFFSET	        4
#define M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_EN_MASK    		0x10
#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_LOAD_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_LOAD_DIV_EN_OFFSET	        3
#define M_CTL_RB_CFG_M_CLK_TCXO_CNT_LOAD_DIV_EN_MASK    		0x8
#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_NUM_LEN	        3
#define	M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_NUM_OFFSET	        0
#define M_CTL_RB_CFG_M_CLK_TCXO_CNT_DIV_NUM_MASK    		0x7

#define	M_CTL_RB_CFG_M_UART_LO_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_UART_LO_DIV_EN_OFFSET	        4
#define M_CTL_RB_CFG_M_UART_LO_DIV_EN_MASK    		0x10
#define	M_CTL_RB_CFG_M_UART_LO_LOAD_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_UART_LO_LOAD_DIV_EN_OFFSET	        3
#define M_CTL_RB_CFG_M_UART_LO_LOAD_DIV_EN_MASK    		0x8
#define	M_CTL_RB_CFG_M_UART_LO_DIV_NUM_LEN	        3
#define	M_CTL_RB_CFG_M_UART_LO_DIV_NUM_OFFSET	        0
#define M_CTL_RB_CFG_M_UART_LO_DIV_NUM_MASK    		0x7

#define	M_CTL_RB_SMDMA_INT_EN_LEN	        1
#define	M_CTL_RB_SMDMA_INT_EN_OFFSET	        5
#define M_CTL_RB_SMDMA_INT_EN_MASK    		0x20
#define	M_CTL_RB_MDMA_INT_EN_LEN	        1
#define	M_CTL_RB_MDMA_INT_EN_OFFSET	        4
#define M_CTL_RB_MDMA_INT_EN_MASK    		0x10
#define	M_CTL_RB_CWDT_INT_EN_LEN	        1
#define	M_CTL_RB_CWDT_INT_EN_OFFSET	        1
#define M_CTL_RB_CWDT_INT_EN_MASK    		0x2

#define	M_CTL_RB_SMDMA_INT_RAW_STS_LEN	        1
#define	M_CTL_RB_SMDMA_INT_RAW_STS_OFFSET	        5
#define M_CTL_RB_SMDMA_INT_RAW_STS_MASK    		0x20
#define	M_CTL_RB_MDMA_INT_RAW_STS_LEN	        1
#define	M_CTL_RB_MDMA_INT_RAW_STS_OFFSET	        4
#define M_CTL_RB_MDMA_INT_RAW_STS_MASK    		0x10
#define	M_CTL_RB_CWDT_INT_RAW_STS_LEN	        1
#define	M_CTL_RB_CWDT_INT_RAW_STS_OFFSET	        1
#define M_CTL_RB_CWDT_INT_RAW_STS_MASK    		0x2

#define	M_CTL_RB_SMDMA_INT_STS_LEN	        1
#define	M_CTL_RB_SMDMA_INT_STS_OFFSET	        5
#define M_CTL_RB_SMDMA_INT_STS_MASK    		0x20
#define	M_CTL_RB_MDMA_INT_STS_LEN	        1
#define	M_CTL_RB_MDMA_INT_STS_OFFSET	        4
#define M_CTL_RB_MDMA_INT_STS_MASK    		0x10
#define	M_CTL_RB_CWDT_INT_STS_LEN	        1
#define	M_CTL_RB_CWDT_INT_STS_OFFSET	        1
#define M_CTL_RB_CWDT_INT_STS_MASK    		0x2

#define	M_CTL_RB_MCPU_PCLR_OK_INT_EN_LEN	        1
#define	M_CTL_RB_MCPU_PCLR_OK_INT_EN_OFFSET	        0
#define M_CTL_RB_MCPU_PCLR_OK_INT_EN_MASK    		0x1

#define	M_CTL_RB_MCU_IO_TEST_IN_LEN	        14
#define	M_CTL_RB_MCU_IO_TEST_IN_OFFSET	        0
#define M_CTL_RB_MCU_IO_TEST_IN_MASK    		0x3FFF

#define	M_CTL_RB_MCU_IO_TEST_OUT_LEN	        14
#define	M_CTL_RB_MCU_IO_TEST_OUT_OFFSET	        0
#define M_CTL_RB_MCU_IO_TEST_OUT_MASK    		0x3FFF

#define	M_CTL_RB_MCU_IO_TEST_OEN_LEN	        14
#define	M_CTL_RB_MCU_IO_TEST_OEN_OFFSET	        0
#define M_CTL_RB_MCU_IO_TEST_OEN_MASK    		0x3FFF

#define	M_CTL_RB_MCPU0_WAIT_LEN	        1
#define	M_CTL_RB_MCPU0_WAIT_OFFSET	        0
#define M_CTL_RB_MCPU0_WAIT_MASK    		0x1

#define	M_CTL_RB_MCU_SPI0_CS_MODE_LEN	        1
#define	M_CTL_RB_MCU_SPI0_CS_MODE_OFFSET	        4
#define M_CTL_RB_MCU_SPI0_CS_MODE_MASK    		0x10
#define	M_CTL_RB_MCU_SPI1_CS_MODE_LEN	        1
#define	M_CTL_RB_MCU_SPI1_CS_MODE_OFFSET	        3
#define M_CTL_RB_MCU_SPI1_CS_MODE_MASK    		0x8
#define	M_CTL_RB_SPI0_MS_SLAVE_MODE_LEN	        1
#define	M_CTL_RB_SPI0_MS_SLAVE_MODE_OFFSET	        1
#define M_CTL_RB_SPI0_MS_SLAVE_MODE_MASK    		0x2
#define	M_CTL_RB_SPI1_MS_SLAVE_MODE_LEN	        1
#define	M_CTL_RB_SPI1_MS_SLAVE_MODE_OFFSET	        0
#define M_CTL_RB_SPI1_MS_SLAVE_MODE_MASK    		0x1

#define	M_CTL_RB_I2C3_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_I2C3_CLK_FORCE_ON_OFFSET	        3
#define M_CTL_RB_I2C3_CLK_FORCE_ON_MASK    		0x8
#define	M_CTL_RB_I2C2_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_I2C2_CLK_FORCE_ON_OFFSET	        2
#define M_CTL_RB_I2C2_CLK_FORCE_ON_MASK    		0x4
#define	M_CTL_RB_I2C1_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_I2C1_CLK_FORCE_ON_OFFSET	        1
#define M_CTL_RB_I2C1_CLK_FORCE_ON_MASK    		0x2
#define	M_CTL_RB_I2C0_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_I2C0_CLK_FORCE_ON_OFFSET	        0
#define M_CTL_RB_I2C0_CLK_FORCE_ON_MASK    		0x1

#define	M_CTL_RB_PWM_CLK_FORCE_ON_LEN	        1
#define	M_CTL_RB_PWM_CLK_FORCE_ON_OFFSET	        0
#define M_CTL_RB_PWM_CLK_FORCE_ON_MASK    		0x1

#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M4_LEN	        3
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M4_OFFSET	        9
#define M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M4_MASK    		0xE00
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M3_LEN	        3
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M3_OFFSET	        6
#define M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M3_MASK    		0x1C0
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M2_LEN	        3
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M2_OFFSET	        3
#define M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M2_MASK    		0x38
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M1_LEN	        3
#define	M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M1_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_MST_PRIORITY_M1_MASK    		0x7

#define	M_CTL_RB_MCU_PERP_AXI_SLV_PRIORITY_S1_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_SLV_PRIORITY_S1_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_SLV_PRIORITY_S1_MASK    		0x1

#define	M_CTL_RB_MCU_AHB_S1_ICM_PRIORITY_LEN	        8
#define	M_CTL_RB_MCU_AHB_S1_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S1_ICM_PRIORITY_MASK    		0xFF

#define	M_CTL_RB_MCU_AHB_S2_ICM_PRIORITY_LEN	        6
#define	M_CTL_RB_MCU_AHB_S2_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S2_ICM_PRIORITY_MASK    		0x3F

#define	M_CTL_RB_MCU_AHB_S3_ICM_PRIORITY_LEN	        6
#define	M_CTL_RB_MCU_AHB_S3_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S3_ICM_PRIORITY_MASK    		0x3F

#define	M_CTL_RB_MCU_AHB_S4_ICM_PRIORITY_LEN	        8
#define	M_CTL_RB_MCU_AHB_S4_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S4_ICM_PRIORITY_MASK    		0xFF

#define	M_CTL_RB_MCU_AHB_S5_ICM_PRIORITY_LEN	        6
#define	M_CTL_RB_MCU_AHB_S5_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S5_ICM_PRIORITY_MASK    		0x3F

#define	M_CTL_RB_MCU_AHB_S7_ICM_PRIORITY_LEN	        6
#define	M_CTL_RB_MCU_AHB_S7_ICM_PRIORITY_OFFSET	        0
#define M_CTL_RB_MCU_AHB_S7_ICM_PRIORITY_MASK    		0x3F

#define	M_CTL_RB_CAN_DMA_SEL_LEN	        1
#define	M_CTL_RB_CAN_DMA_SEL_OFFSET	        0
#define M_CTL_RB_CAN_DMA_SEL_MASK    		0x1

#define	M_CTL_RB_MCU_EH2H_ERROR_RESP_LEN	        2
#define	M_CTL_RB_MCU_EH2H_ERROR_RESP_OFFSET	        0
#define M_CTL_RB_MCU_EH2H_ERROR_RESP_MASK    		0x3

#define	M_CTL_RB_MCU_EH2H_ERROR_RESP_CLR_LEN	        1
#define	M_CTL_RB_MCU_EH2H_ERROR_RESP_CLR_OFFSET	        0
#define M_CTL_RB_MCU_EH2H_ERROR_RESP_CLR_MASK    		0x1

#define	M_CTL_RB_MCU_PERP_AXI_AR_ERR_INT_CLR_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_AR_ERR_INT_CLR_OFFSET	        3
#define M_CTL_RB_MCU_PERP_AXI_AR_ERR_INT_CLR_MASK    		0x8
#define	M_CTL_RB_MCU_PERP_AXI_AW_ERR_INT_CLR_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_AW_ERR_INT_CLR_OFFSET	        2
#define M_CTL_RB_MCU_PERP_AXI_AW_ERR_INT_CLR_MASK    		0x4
#define	M_CTL_RB_MCU_PERP_AXI_ERR_MINITOR_ENABLE_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_ERR_MINITOR_ENABLE_OFFSET	        1
#define M_CTL_RB_MCU_PERP_AXI_ERR_MINITOR_ENABLE_MASK    		0x2
#define	M_CTL_RB_MCU_PERP_AXI_GLB_AXI_MINITOR_ENABLE_LEN	        1
#define	M_CTL_RB_MCU_PERP_AXI_GLB_AXI_MINITOR_ENABLE_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_GLB_AXI_MINITOR_ENABLE_MASK    		0x1

#define	M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_L_LEN	        16
#define	M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_L_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_L_MASK    		0xFFFF

#define	M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_H_LEN	        16
#define	M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_H_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_AWADDR_ERR_STS_H_MASK    		0xFFFF

#define	M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_L_LEN	        16
#define	M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_L_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_L_MASK    		0xFFFF

#define	M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_H_LEN	        16
#define	M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_H_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_ARADDR_ERR_STS_H_MASK    		0xFFFF

#define	M_CTL_RB_MCU_PERP_AXI_AWID_ERR_STS_LEN	        11
#define	M_CTL_RB_MCU_PERP_AXI_AWID_ERR_STS_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_AWID_ERR_STS_MASK    		0x7FF

#define	M_CTL_RB_MCU_PERP_AXI_ARID_ERR_STS_LEN	        11
#define	M_CTL_RB_MCU_PERP_AXI_ARID_ERR_STS_OFFSET	        0
#define M_CTL_RB_MCU_PERP_AXI_ARID_ERR_STS_MASK    		0x7FF

#define	M_CTL_RB_AUX_ADC_RSTN_LEN	        1
#define	M_CTL_RB_AUX_ADC_RSTN_OFFSET	        4
#define M_CTL_RB_AUX_ADC_RSTN_MASK    		0x10
#define	M_CTL_RB_AUX_ADC_PD_LEN	        1
#define	M_CTL_RB_AUX_ADC_PD_OFFSET	        3
#define M_CTL_RB_AUX_ADC_PD_MASK    		0x8
#define	M_CTL_RB_AUX_ADC_CH_GT_LEN	        1
#define	M_CTL_RB_AUX_ADC_CH_GT_OFFSET	        2
#define M_CTL_RB_AUX_ADC_CH_GT_MASK    		0x4
#define	M_CTL_RB_AUX_ADC_CLK_GT_LEN	        1
#define	M_CTL_RB_AUX_ADC_CLK_GT_OFFSET	        1
#define M_CTL_RB_AUX_ADC_CLK_GT_MASK    		0x2
#define	M_CTL_RB_AUX_ADC_ISO18_LEN	        1
#define	M_CTL_RB_AUX_ADC_ISO18_OFFSET	        0
#define M_CTL_RB_AUX_ADC_ISO18_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CH_SINGLE_SEL_LEN	        8
#define	M_CTL_RB_AUX_ADC_CH_SINGLE_SEL_OFFSET	        5
#define M_CTL_RB_AUX_ADC_CH_SINGLE_SEL_MASK    		0x1FE0

#define	M_CTL_RB_AUX_ADC_ENG_FLAG_LEN	        1
#define	M_CTL_RB_AUX_ADC_ENG_FLAG_OFFSET	        0
#define M_CTL_RB_AUX_ADC_ENG_FLAG_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_DOUT_LEN	        12
#define	M_CTL_RB_AUX_ADC_DOUT_OFFSET	        0
#define M_CTL_RB_AUX_ADC_DOUT_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_REG_L_LEN	        16
#define	M_CTL_RB_AUX_ADC_REG_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_REG_L_MASK    		0xFFFF

#define	M_CTL_RB_AUX_ADC_REG_H_LEN	        16
#define	M_CTL_RB_AUX_ADC_REG_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_REG_H_MASK    		0xFFFF

#define	M_CTL_RB_AUX_ADC_CS_LEN	        1
#define	M_CTL_RB_AUX_ADC_CS_OFFSET	        4
#define M_CTL_RB_AUX_ADC_CS_MASK    		0x10
#define	M_CTL_RB_AUX_ADC_CS_MAN_SEL_LEN	        1
#define	M_CTL_RB_AUX_ADC_CS_MAN_SEL_OFFSET	        3
#define M_CTL_RB_AUX_ADC_CS_MAN_SEL_MASK    		0x8
#define	M_CTL_RB_AUX_ADC_CS_MAN_LEN	        1
#define	M_CTL_RB_AUX_ADC_CS_MAN_OFFSET	        2
#define M_CTL_RB_AUX_ADC_CS_MAN_MASK    		0x4
#define	M_CTL_RB_AUX_ADC_CS_SEL_LEN	        1
#define	M_CTL_RB_AUX_ADC_CS_SEL_OFFSET	        1
#define M_CTL_RB_AUX_ADC_CS_SEL_MASK    		0x2
#define	M_CTL_RB_AUX_ADC_CS_RB_LEN	        1
#define	M_CTL_RB_AUX_ADC_CS_RB_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CS_RB_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_EOC_FLAG_STICK_LEN	        1
#define	M_CTL_RB_AUX_ADC_EOC_FLAG_STICK_OFFSET	        15
#define M_CTL_RB_AUX_ADC_EOC_FLAG_STICK_MASK    		0x8000
#define	M_CTL_RB_AUX_ADC_DOUT_STICK_LEN	        12
#define	M_CTL_RB_AUX_ADC_DOUT_STICK_OFFSET	        0
#define M_CTL_RB_AUX_ADC_DOUT_STICK_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_STICK_CLR_LEN	        1
#define	M_CTL_RB_AUX_ADC_STICK_CLR_OFFSET	        0
#define M_CTL_RB_AUX_ADC_STICK_CLR_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CALI_EN_LEN	        1
#define	M_CTL_RB_AUX_ADC_CALI_EN_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_EN_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CALI_AVG_SEL_LEN	        2
#define	M_CTL_RB_AUX_ADC_CALI_AVG_SEL_OFFSET	        2
#define M_CTL_RB_AUX_ADC_CALI_AVG_SEL_MASK    		0xC
#define	M_CTL_RB_AUX_ADC_CALI_DIS_SEL_LEN	        2
#define	M_CTL_RB_AUX_ADC_CALI_DIS_SEL_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_DIS_SEL_MASK    		0x3

#define	M_CTL_RB_AUX_ADC_CALI_PERIOD_LEN	        16
#define	M_CTL_RB_AUX_ADC_CALI_PERIOD_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_PERIOD_MASK    		0xFFFF

#define	M_CTL_RB_AUX_ADC_CALI_CFG_SYNC_LEN	        1
#define	M_CTL_RB_AUX_ADC_CALI_CFG_SYNC_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_CFG_SYNC_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CALI_DONE_LEN	        1
#define	M_CTL_RB_AUX_ADC_CALI_DONE_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_DONE_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_CALI_DOUT_LEN	        12
#define	M_CTL_RB_AUX_ADC_CALI_DOUT_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_DOUT_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_CALI_BYP_LEN	        1
#define	M_CTL_RB_AUX_ADC_CALI_BYP_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_BYP_MASK    		0x1

#define	M_CTL_RB_AUX_ADC_SCAN_EN_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_OFFSET	        12
#define M_CTL_RB_AUX_ADC_SCAN_EN_MASK    		0x1000
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_DIS_SEL2_LEN	        3
#define	M_CTL_RB_AUX_ADC_SCAN_DIS_SEL2_OFFSET	        13
#define M_CTL_RB_AUX_ADC_SCAN_DIS_SEL2_MASK    		0xE000
#define	M_CTL_RB_AUX_ADC_SCAN_FREQ_LEN	        3
#define	M_CTL_RB_AUX_ADC_SCAN_FREQ_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_FREQ_MASK    		0x7

#define	M_CTL_RB_AUX_ADC_SCAN_AVG_SEL2_LEN	        2
#define	M_CTL_RB_AUX_ADC_SCAN_AVG_SEL2_OFFSET	        14
#define M_CTL_RB_AUX_ADC_SCAN_AVG_SEL2_MASK    		0xC000
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_MODE_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_MODE_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_TRIG_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_TRIG_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_TH10_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH10_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH10_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH10_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH10_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH10_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH11_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH11_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH11_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH11_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH11_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH11_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH4_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH4_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH4_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH4_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH4_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH4_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH5_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH5_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH5_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH5_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH5_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH5_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH6_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH6_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH6_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH6_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH6_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH6_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH7_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH7_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH7_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH7_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH7_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH7_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH8_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH8_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH8_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH8_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH8_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH8_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH9_L_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH9_L_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH9_L_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH9_H_LEN	        12
#define	M_CTL_RB_AUX_ADC_SCAN_TH9_H_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH9_H_MASK    		0xFFF

#define	M_CTL_RB_AUX_ADC_SCAN_TH11_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH11_PTR_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_TH11_PTR_MASK    		0x7F00
#define	M_CTL_RB_AUX_ADC_SCAN_TH10_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH10_PTR_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH10_PTR_MASK    		0x7F

#define	M_CTL_RB_AUX_ADC_SCAN_TH5_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH5_PTR_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_TH5_PTR_MASK    		0x7F00
#define	M_CTL_RB_AUX_ADC_SCAN_TH4_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH4_PTR_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH4_PTR_MASK    		0x7F

#define	M_CTL_RB_AUX_ADC_SCAN_TH7_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH7_PTR_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_TH7_PTR_MASK    		0x7F00
#define	M_CTL_RB_AUX_ADC_SCAN_TH6_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH6_PTR_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH6_PTR_MASK    		0x7F

#define	M_CTL_RB_AUX_ADC_SCAN_TH9_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH9_PTR_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_TH9_PTR_MASK    		0x7F00
#define	M_CTL_RB_AUX_ADC_SCAN_TH8_PTR_LEN	        7
#define	M_CTL_RB_AUX_ADC_SCAN_TH8_PTR_OFFSET	        0
#define M_CTL_RB_AUX_ADC_SCAN_TH8_PTR_MASK    		0x7F

#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_INT_EN_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_INT_STAT_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH11_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH11_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH11_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH10_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH10_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH10_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH9_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH9_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH9_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH8_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH8_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH8_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH7_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH7_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH7_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH6_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH6_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH6_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH5_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH5_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH5_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH4_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH4_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_INT_CLR_CH4_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH11_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH11_EXT_OFFSET	        11
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH11_EXT_MASK    		0x800
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH10_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH10_EXT_OFFSET	        10
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH10_EXT_MASK    		0x400
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH9_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH9_EXT_OFFSET	        9
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH9_EXT_MASK    		0x200
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH8_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH8_EXT_OFFSET	        8
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH8_EXT_MASK    		0x100
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH7_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH7_EXT_OFFSET	        7
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH7_EXT_MASK    		0x80
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH6_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH6_EXT_OFFSET	        6
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH6_EXT_MASK    		0x40
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH5_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH5_EXT_OFFSET	        5
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH5_EXT_MASK    		0x20
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH4_EXT_LEN	        1
#define	M_CTL_RB_AUX_ADC_SCAN_EN_CH4_EXT_OFFSET	        4
#define M_CTL_RB_AUX_ADC_SCAN_EN_CH4_EXT_MASK    		0x10

#define	M_CTL_RB_AUX_ADC_CALI_OFFSET2_LEN	        14
#define	M_CTL_RB_AUX_ADC_CALI_OFFSET2_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_OFFSET2_MASK    		0x3FFF

#define	M_CTL_RB_AUX_ADC_CALI_GAIN2_LEN	        13
#define	M_CTL_RB_AUX_ADC_CALI_GAIN2_OFFSET	        0
#define M_CTL_RB_AUX_ADC_CALI_GAIN2_MASK    		0x1FFF

#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_0_LEN	        16
#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_0_OFFSET	        0
#define M_CTL_RB_SDIO_DEBUG_SIGNALS_0_MASK    		0xFFFF

#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_1_LEN	        16
#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_1_OFFSET	        0
#define M_CTL_RB_SDIO_DEBUG_SIGNALS_1_MASK    		0xFFFF

#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_2_LEN	        16
#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_2_OFFSET	        0
#define M_CTL_RB_SDIO_DEBUG_SIGNALS_2_MASK    		0xFFFF

#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_3_LEN	        16
#define	M_CTL_RB_SDIO_DEBUG_SIGNALS_3_OFFSET	        0
#define M_CTL_RB_SDIO_DEBUG_SIGNALS_3_MASK    		0xFFFF

#define	M_CTL_RB_STAT_EN_LEN	        1
#define	M_CTL_RB_STAT_EN_OFFSET	        15
#define M_CTL_RB_STAT_EN_MASK    		0x8000
#define	M_CTL_RB_GRM_TIME_CFG_LEN	        12
#define	M_CTL_RB_GRM_TIME_CFG_OFFSET	        0
#define M_CTL_RB_GRM_TIME_CFG_MASK    		0xFFF

#define	M_CTL_RB_STAT_POS_CNT_LEN	        16
#define	M_CTL_RB_STAT_POS_CNT_OFFSET	        0
#define M_CTL_RB_STAT_POS_CNT_MASK    		0xFFFF

#define	M_CTL_RB_STAT_NEG_CNT_LEN	        16
#define	M_CTL_RB_STAT_NEG_CNT_OFFSET	        0
#define M_CTL_RB_STAT_NEG_CNT_MASK    		0xFFFF

#define	M_CTL_RB_CFG_M_SD_BUS_DIV_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_SD_BUS_DIV_CLKEN_OFFSET	        1
#define M_CTL_RB_CFG_M_SD_BUS_DIV_CLKEN_MASK    		0x2
#define	M_CTL_RB_CFG_M_HS_SUB_BUS_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_HS_SUB_BUS_CLKEN_OFFSET	        0
#define M_CTL_RB_CFG_M_HS_SUB_BUS_CLKEN_MASK    		0x1

#define	M_CTL_RB_M_TCXO_CNT_VALUE_VALID_LEN	        1
#define	M_CTL_RB_M_TCXO_CNT_VALUE_VALID_OFFSET	        4
#define M_CTL_RB_M_TCXO_CNT_VALUE_VALID_MASK    		0x10
#define	M_CTL_RB_M_TCXO_CNT_EN_LEN	        1
#define	M_CTL_RB_M_TCXO_CNT_EN_OFFSET	        2
#define M_CTL_RB_M_TCXO_CNT_EN_MASK    		0x4
#define	M_CTL_RB_M_TCXO_CNT_CLR_LEN	        1
#define	M_CTL_RB_M_TCXO_CNT_CLR_OFFSET	        1
#define M_CTL_RB_M_TCXO_CNT_CLR_MASK    		0x2
#define	M_CTL_RB_M_TCXO_CNT_REFRESH_LEN	        1
#define	M_CTL_RB_M_TCXO_CNT_REFRESH_OFFSET	        0
#define M_CTL_RB_M_TCXO_CNT_REFRESH_MASK    		0x1

#define	M_CTL_RB_M_TCXO_CNT_VALUE_0_LEN	        32
#define	M_CTL_RB_M_TCXO_CNT_VALUE_0_OFFSET	        0
#define M_CTL_RB_M_TCXO_CNT_VALUE_0_MASK    		0xFFFFFFFF

#define	M_CTL_RB_M_TCXO_CNT_VALUE_1_LEN	        32
#define	M_CTL_RB_M_TCXO_CNT_VALUE_1_OFFSET	        0
#define M_CTL_RB_M_TCXO_CNT_VALUE_1_MASK    		0xFFFFFFFF

#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_VALID_LEN	        1
#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_VALID_OFFSET	        4
#define M_CTL_RB_RPT_MCU_TE_INT_CNT_VALID_MASK    		0x10
#define	M_CTL_RB_CFG_DSI_TE_AGPIO_MASK_LEN	        1
#define	M_CTL_RB_CFG_DSI_TE_AGPIO_MASK_OFFSET	        3
#define M_CTL_RB_CFG_DSI_TE_AGPIO_MASK_MASK    		0x8
#define	M_CTL_RB_CFG_MCU_TE_INT_AON_MASK_LEN	        1
#define	M_CTL_RB_CFG_MCU_TE_INT_AON_MASK_OFFSET	        2
#define M_CTL_RB_CFG_MCU_TE_INT_AON_MASK_MASK    		0x4
#define	M_CTL_RB_CFG_MCU_TE_INT_CNT_VALID_CLR_LEN	        1
#define	M_CTL_RB_CFG_MCU_TE_INT_CNT_VALID_CLR_OFFSET	        1
#define M_CTL_RB_CFG_MCU_TE_INT_CNT_VALID_CLR_MASK    		0x2
#define	M_CTL_RB_CFG_MCU_TE_INT_CNT_EN_LEN	        1
#define	M_CTL_RB_CFG_MCU_TE_INT_CNT_EN_OFFSET	        0
#define M_CTL_RB_CFG_MCU_TE_INT_CNT_EN_MASK    		0x1

#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_0_LEN	        32
#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_0_OFFSET	        0
#define M_CTL_RB_RPT_MCU_TE_INT_CNT_0_MASK    		0xFFFFFFFF

#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_1_LEN	        32
#define	M_CTL_RB_RPT_MCU_TE_INT_CNT_1_OFFSET	        0
#define M_CTL_RB_RPT_MCU_TE_INT_CNT_1_MASK    		0xFFFFFFFF

#define	M_CTL_RB_DIO_HW_CG_BYPASS_LEN	        1
#define	M_CTL_RB_DIO_HW_CG_BYPASS_OFFSET	        2
#define M_CTL_RB_DIO_HW_CG_BYPASS_MASK    		0x4
#define	M_CTL_RB_DIO_RW_CG_BYPASS_LEN	        1
#define	M_CTL_RB_DIO_RW_CG_BYPASS_OFFSET	        1
#define M_CTL_RB_DIO_RW_CG_BYPASS_MASK    		0x2
#define	M_CTL_RB_PWM_HW_CG_EN_LEN	        1
#define	M_CTL_RB_PWM_HW_CG_EN_OFFSET	        0
#define M_CTL_RB_PWM_HW_CG_EN_MASK    		0x1

#define	M_CTL_RB_VIDEO_PREADY_DFS_OVER_TIME_LEN	        16
#define	M_CTL_RB_VIDEO_PREADY_DFS_OVER_TIME_OFFSET	        0
#define M_CTL_RB_VIDEO_PREADY_DFS_OVER_TIME_MASK    		0xFFFF

#define	M_CTL_RB_MCU_AHB_HREADY_MUX_LEN	        1
#define	M_CTL_RB_MCU_AHB_HREADY_MUX_OFFSET	        1
#define M_CTL_RB_MCU_AHB_HREADY_MUX_MASK    		0x2
#define	M_CTL_RB_MCU_CFGAHB_HREADY_MUX_LEN	        1
#define	M_CTL_RB_MCU_CFGAHB_HREADY_MUX_OFFSET	        0
#define M_CTL_RB_MCU_CFGAHB_HREADY_MUX_MASK    		0x1

#define	M_CTL_RB_VIDEO_PREADY_DFS_INT_RAW_LEN	        1
#define	M_CTL_RB_VIDEO_PREADY_DFS_INT_RAW_OFFSET	        2
#define M_CTL_RB_VIDEO_PREADY_DFS_INT_RAW_MASK    		0x4
#define	M_CTL_RB_VIDEO_PREADY_DFS_REF_CLR_LEN	        1
#define	M_CTL_RB_VIDEO_PREADY_DFS_REF_CLR_OFFSET	        1
#define M_CTL_RB_VIDEO_PREADY_DFS_REF_CLR_MASK    		0x2
#define	M_CTL_RB_VIDEO_PREADY_DFS_REF_LEN	        1
#define	M_CTL_RB_VIDEO_PREADY_DFS_REF_OFFSET	        0
#define M_CTL_RB_VIDEO_PREADY_DFS_REF_MASK    		0x1

#define	M_CTL_RB_CFG_M_CLK_TRNG_SAMPLE_DIV_CLKEN_LEN	        1
#define	M_CTL_RB_CFG_M_CLK_TRNG_SAMPLE_DIV_CLKEN_OFFSET	        5
#define M_CTL_RB_CFG_M_CLK_TRNG_SAMPLE_DIV_CLKEN_MASK    		0x20
#define	M_CTL_RB_CFG_M_TRNG_SAMPLE_LOAD_DIV_EN_LEN	        1
#define	M_CTL_RB_CFG_M_TRNG_SAMPLE_LOAD_DIV_EN_OFFSET	        4
#define M_CTL_RB_CFG_M_TRNG_SAMPLE_LOAD_DIV_EN_MASK    		0x10
#define	M_CTL_RB_CFG_M_TRNG_SAMPLE_DIV_NUM_LEN	        4
#define	M_CTL_RB_CFG_M_TRNG_SAMPLE_DIV_NUM_OFFSET	        0
#define M_CTL_RB_CFG_M_TRNG_SAMPLE_DIV_NUM_MASK    		0xF

#define	M_CTL_RB_IO_IN_DOUBLE_EXCP_HDLR_LEN	        1
#define	M_CTL_RB_IO_IN_DOUBLE_EXCP_HDLR_OFFSET	        8
#define M_CTL_RB_IO_IN_DOUBLE_EXCP_HDLR_MASK    		0x100
#define	M_CTL_RB_IO_IN_ASYNC_EXCP_HDLR_LEN	        1
#define	M_CTL_RB_IO_IN_ASYNC_EXCP_HDLR_OFFSET	        7
#define M_CTL_RB_IO_IN_ASYNC_EXCP_HDLR_MASK    		0x80
#define	M_CTL_RB_IO_CORE_TES_LEN	        1
#define	M_CTL_RB_IO_CORE_TES_OFFSET	        6
#define M_CTL_RB_IO_CORE_TES_MASK    		0x40
#define	M_CTL_RB_IO_CORE_MODE_LEN	        1
#define	M_CTL_RB_IO_CORE_MODE_OFFSET	        5
#define M_CTL_RB_IO_CORE_MODE_MASK    		0x20
#define	M_CTL_RB_IN_NMI_HDLR_LEN	        1
#define	M_CTL_RB_IN_NMI_HDLR_OFFSET	        4
#define M_CTL_RB_IN_NMI_HDLR_MASK    		0x10
#define	M_CTL_RB_DEBUG_MODE_LEN	        1
#define	M_CTL_RB_DEBUG_MODE_OFFSET	        3
#define M_CTL_RB_DEBUG_MODE_MASK    		0x8
#define	M_CTL_RB_AHBS_STORE_IDLE_LEN	        1
#define	M_CTL_RB_AHBS_STORE_IDLE_OFFSET	        2
#define M_CTL_RB_AHBS_STORE_IDLE_MASK    		0x4
#define	M_CTL_RB_MCPU_OTP_DEBUG_LEN	        1
#define	M_CTL_RB_MCPU_OTP_DEBUG_OFFSET	        1
#define M_CTL_RB_MCPU_OTP_DEBUG_MASK    		0x2
#define	M_CTL_RB_IO_DM_CLK_OFF_N_LEN	        1
#define	M_CTL_RB_IO_DM_CLK_OFF_N_OFFSET	        0
#define M_CTL_RB_IO_DM_CLK_OFF_N_MASK    		0x1

#define	M_CTL_RB_TRNG_RING_EN_LEN	        1
#define	M_CTL_RB_TRNG_RING_EN_OFFSET	        0
#define M_CTL_RB_TRNG_RING_EN_MASK    		0x1

#endif // __3322_M_CTL_RB_REG_OFFSET_FIELD_H__
