/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_video_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_VIDEO_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_VIDEO_CTL_RB_REG_OFFSET_FIELD_H__

#define	VIDEO_CTL_RB_VIDEO_CTL_ID_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_CTL_ID_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_CTL_ID_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_GP_REG0_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_GP_REG0_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_GP_REG0_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_GP_REG1_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_GP_REG1_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_GP_REG1_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_GP_REG2_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_GP_REG2_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_GP_REG2_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_GP_REG3_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_GP_REG3_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_GP_REG3_MASK    		0xFFFF

#define	VIDEO_CTL_RB_CFG_JPGE_SOFT_RST_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_JPGE_SOFT_RST_N_OFFSET	        3
#define VIDEO_CTL_RB_CFG_JPGE_SOFT_RST_N_MASK    		0x8
#define	VIDEO_CTL_RB_JPGE_CKEN_LEN	        1
#define	VIDEO_CTL_RB_JPGE_CKEN_OFFSET	        2
#define VIDEO_CTL_RB_JPGE_CKEN_MASK    		0x4
#define	VIDEO_CTL_RB_JPGD_SOFT_RST_REQ_LEN	        1
#define	VIDEO_CTL_RB_JPGD_SOFT_RST_REQ_OFFSET	        1
#define VIDEO_CTL_RB_JPGD_SOFT_RST_REQ_MASK    		0x2
#define	VIDEO_CTL_RB_JPGD_CKEN_LEN	        1
#define	VIDEO_CTL_RB_JPGD_CKEN_OFFSET	        0
#define VIDEO_CTL_RB_JPGD_CKEN_MASK    		0x1

#define	VIDEO_CTL_RB_VDH_ALL_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_VDH_ALL_SRST_REQ_OFFSET	        3
#define VIDEO_CTL_RB_VDH_ALL_SRST_REQ_MASK    		0x8
#define	VIDEO_CTL_RB_VDH_SCD_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_VDH_SCD_SRST_REQ_OFFSET	        2
#define VIDEO_CTL_RB_VDH_SCD_SRST_REQ_MASK    		0x4
#define	VIDEO_CTL_RB_VDH_MFD_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_VDH_MFD_SRST_REQ_OFFSET	        1
#define VIDEO_CTL_RB_VDH_MFD_SRST_REQ_MASK    		0x2
#define	VIDEO_CTL_RB_VDH_BPD_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_VDH_BPD_SRST_REQ_OFFSET	        0
#define VIDEO_CTL_RB_VDH_BPD_SRST_REQ_MASK    		0x1

#define	VIDEO_CTL_RB_VDH_ALL_SRST_OK_LEN	        1
#define	VIDEO_CTL_RB_VDH_ALL_SRST_OK_OFFSET	        3
#define VIDEO_CTL_RB_VDH_ALL_SRST_OK_MASK    		0x8
#define	VIDEO_CTL_RB_VDH_SCD_SRST_OK_LEN	        1
#define	VIDEO_CTL_RB_VDH_SCD_SRST_OK_OFFSET	        2
#define VIDEO_CTL_RB_VDH_SCD_SRST_OK_MASK    		0x4
#define	VIDEO_CTL_RB_VDH_MFD_SRST_OK_LEN	        1
#define	VIDEO_CTL_RB_VDH_MFD_SRST_OK_OFFSET	        1
#define VIDEO_CTL_RB_VDH_MFD_SRST_OK_MASK    		0x2
#define	VIDEO_CTL_RB_VDH_BPD_SRST_OK_LEN	        1
#define	VIDEO_CTL_RB_VDH_BPD_SRST_OK_OFFSET	        0
#define VIDEO_CTL_RB_VDH_BPD_SRST_OK_MASK    		0x1

#define	VIDEO_CTL_RB_VDH_BUSY_LEN	        1
#define	VIDEO_CTL_RB_VDH_BUSY_OFFSET	        0
#define VIDEO_CTL_RB_VDH_BUSY_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_VIDEO_MJPGE_DIV_DENOM_LEN	        3
#define	VIDEO_CTL_RB_CFG_VIDEO_MJPGE_DIV_DENOM_OFFSET	        1
#define VIDEO_CTL_RB_CFG_VIDEO_MJPGE_DIV_DENOM_MASK    		0xE
#define	VIDEO_CTL_RB_CFG_VIDEO_MJPGE_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_MJPGE_LOAD_DIV_EN_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_MJPGE_LOAD_DIV_EN_MASK    		0x1

#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CLKEN_OFFSET	        8
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_CLKEN_MASK    		0x100
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M1_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M1_OFFSET	        7
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M1_MASK    		0x80
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M2_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M2_OFFSET	        6
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_M2_MASK    		0x40
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSREQ_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSREQ_OFFSET	        5
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSREQ_MASK    		0x20
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_S1_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_S1_OFFSET	        4
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_PRIORITY_S1_MASK    		0x10
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_SELF_GLB_CG_BYPASS_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_SELF_GLB_CG_BYPASS_OFFSET	        3
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_SELF_GLB_CG_BYPASS_MASK    		0x8
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_AUTO_CG_BYPASS_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_AUTO_CG_BYPASS_OFFSET	        2
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_AUTO_CG_BYPASS_MASK    		0x4
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSACK_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSACK_OFFSET	        1
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_CSYSACK_MASK    		0x2
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CATIVE_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_2TO1_AXI_CATIVE_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_2TO1_AXI_CATIVE_MASK    		0x1

#define	VIDEO_CTL_RB_LOAD_EN_LEN	        1
#define	VIDEO_CTL_RB_LOAD_EN_OFFSET	        6
#define VIDEO_CTL_RB_LOAD_EN_MASK    		0x40
#define	VIDEO_CTL_RB_SKIP_CFG_LEN	        5
#define	VIDEO_CTL_RB_SKIP_CFG_OFFSET	        1
#define VIDEO_CTL_RB_SKIP_CFG_MASK    		0x3E
#define	VIDEO_CTL_RB_CLEAR_SUM_LEN	        1
#define	VIDEO_CTL_RB_CLEAR_SUM_OFFSET	        0
#define VIDEO_CTL_RB_CLEAR_SUM_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_MJPGE_APB_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MJPGE_APB_CLKEN_OFFSET	        14
#define VIDEO_CTL_RB_CFG_MJPGE_APB_CLKEN_MASK    		0x4000
#define	VIDEO_CTL_RB_CFG_MJPGE_AXI_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MJPGE_AXI_CLKEN_OFFSET	        13
#define VIDEO_CTL_RB_CFG_MJPGE_AXI_CLKEN_MASK    		0x2000
#define	VIDEO_CTL_RB_CFG_VIDEO_DSP_SUB_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DSP_SUB_CLKEN_OFFSET	        12
#define VIDEO_CTL_RB_CFG_VIDEO_DSP_SUB_CLKEN_MASK    		0x1000
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_CLKEN_OFFSET	        11
#define VIDEO_CTL_RB_CFG_VIDEO_VDH_CLKEN_MASK    		0x800
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_AXI_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_AXI_CLKEN_OFFSET	        10
#define VIDEO_CTL_RB_CFG_VIDEO_VAU_AXI_CLKEN_MASK    		0x400
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_APB_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_APB_CLKEN_OFFSET	        9
#define VIDEO_CTL_RB_CFG_VIDEO_VAU_APB_CLKEN_MASK    		0x200
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_PPC_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_PPC_CLKEN_OFFSET	        8
#define VIDEO_CTL_RB_CFG_VIDEO_VAU_PPC_CLKEN_MASK    		0x100
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_AXI_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_AXI_CLKEN_OFFSET	        7
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_AXI_CLKEN_MASK    		0x80
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_APB_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_APB_CLKEN_OFFSET	        6
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_APB_CLKEN_MASK    		0x40
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_VO_HD0_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_VO_HD0_CLKEN_OFFSET	        5
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_VO_HD0_CLKEN_MASK    		0x20
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_CFG_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_CFG_CLKEN_OFFSET	        4
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_CFG_CLKEN_MASK    		0x10
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_HD0_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_HD0_CLKEN_OFFSET	        3
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_HD0_CLKEN_MASK    		0x8
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_AXI_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_AXI_CLKEN_OFFSET	        2
#define VIDEO_CTL_RB_CFG_VIDEO_JPGD_AXI_CLKEN_MASK    		0x4
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_APB_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_APB_CLKEN_OFFSET	        1
#define VIDEO_CTL_RB_CFG_VIDEO_JPGD_APB_CLKEN_MASK    		0x2
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_PPC_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_JPGD_PPC_CLKEN_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_JPGD_PPC_CLKEN_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_EN_OFFSET	        4
#define VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_EN_MASK    		0x10
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_LOAD_DIV_EN_OFFSET	        3
#define VIDEO_CTL_RB_CFG_VIDEO_VDH_LOAD_DIV_EN_MASK    		0x8
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_DENOM_LEN	        3
#define	VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_DENOM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_VDH_DIV_DENOM_MASK    		0x7

#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_LOAD_DIV_EN_OFFSET	        13
#define VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_LOAD_DIV_EN_MASK    		0x2000
#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_NUM_LEN	        13
#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_NUM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_NUM_MASK    		0x1FFF

#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_DENOM_LEN	        13
#define	VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_DENOM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_VO_HD0_DIV_DENOM_MASK    		0x1FFF

#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_LOAD_DIV_EN_OFFSET	        13
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_LOAD_DIV_EN_MASK    		0x2000
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_DENOM_LEN	        13
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_DENOM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_DENOM_MASK    		0x1FFF

#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_VIDEO_AXI2TO1_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_VIDEO_AXI2TO1_N_OFFSET	        4
#define VIDEO_CTL_RB_CFG_VIDEO_SOFT_VIDEO_AXI2TO1_N_MASK    		0x10
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_JPGD_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_JPGD_N_OFFSET	        3
#define VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_JPGD_N_MASK    		0x8
#define	VIDEO_CTL_RB_CFG_VAU_SOFT_RST_SYS_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_VAU_SOFT_RST_SYS_N_OFFSET	        2
#define VIDEO_CTL_RB_CFG_VAU_SOFT_RST_SYS_N_MASK    		0x4
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_SYS_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_SYS_N_OFFSET	        1
#define VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_SYS_N_MASK    		0x2
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_H264_N_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_H264_N_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_SOFT_RST_H264_N_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_LOAD_DIV_EN_OFFSET	        3
#define VIDEO_CTL_RB_CFG_VIDEO_VAU_LOAD_DIV_EN_MASK    		0x8
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_DIV_DENOM_LEN	        3
#define	VIDEO_CTL_RB_CFG_VIDEO_VAU_DIV_DENOM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_VAU_DIV_DENOM_MASK    		0x7

#define	VIDEO_CTL_RB_CFG_MIPI_PCS_TX_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPI_PCS_TX_SRST_REQ_OFFSET	        2
#define VIDEO_CTL_RB_CFG_MIPI_PCS_TX_SRST_REQ_MASK    		0x4
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_SRST_REQ_OFFSET	        1
#define VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_SRST_REQ_MASK    		0x2
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_CKEN_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_MIPITX_APB_CKEN_MASK    		0x1

#define	VIDEO_CTL_RB_DPU_PPROT_LEN	        3
#define	VIDEO_CTL_RB_DPU_PPROT_OFFSET	        0
#define VIDEO_CTL_RB_DPU_PPROT_MASK    		0x7

#define	VIDEO_CTL_RB_VAU_PPROT_LEN	        3
#define	VIDEO_CTL_RB_VAU_PPROT_OFFSET	        0
#define VIDEO_CTL_RB_VAU_PPROT_MASK    		0x7

#define	VIDEO_CTL_RB_DPU_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_DPU_SRST_REQ_OFFSET	        1
#define VIDEO_CTL_RB_DPU_SRST_REQ_MASK    		0x2
#define	VIDEO_CTL_RB_VAU_SRST_REQ_LEN	        1
#define	VIDEO_CTL_RB_VAU_SRST_REQ_OFFSET	        0
#define VIDEO_CTL_RB_VAU_SRST_REQ_MASK    		0x1

#define	VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_L_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_L_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_L_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_H_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_H_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_TP_RAM_TMOD_H_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VAU_PWR_MOD_LEN	        1
#define	VIDEO_CTL_RB_VAU_PWR_MOD_OFFSET	        8
#define VIDEO_CTL_RB_VAU_PWR_MOD_MASK    		0x100
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LEN	        1
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_OFFSET	        7
#define VIDEO_CTL_RB_H264_JPGD_PWR_MOD_MASK    		0x80
#define	VIDEO_CTL_RB_VDM_PWR_MOD_LEN	        1
#define	VIDEO_CTL_RB_VDM_PWR_MOD_OFFSET	        6
#define VIDEO_CTL_RB_VDM_PWR_MOD_MASK    		0x40
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_LEN	        1
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_OFFSET	        5
#define VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_MASK    		0x20
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_DS_LEN	        2
#define	VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_DS_OFFSET	        3
#define VIDEO_CTL_RB_H264_JPGD_PWR_MOD_LS_DS_MASK    		0x18
#define	VIDEO_CTL_RB_VDM_PWR_MOD_LS_LEN	        1
#define	VIDEO_CTL_RB_VDM_PWR_MOD_LS_OFFSET	        2
#define VIDEO_CTL_RB_VDM_PWR_MOD_LS_MASK    		0x4
#define	VIDEO_CTL_RB_VDM_PWR_MOD_LS_DS_LEN	        2
#define	VIDEO_CTL_RB_VDM_PWR_MOD_LS_DS_OFFSET	        0
#define VIDEO_CTL_RB_VDM_PWR_MOD_LS_DS_MASK    		0x3

#define	VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_LEN	        1
#define	VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_OFFSET	        1
#define VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_MASK    		0x2
#define	VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_SEL_LEN	        1
#define	VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_SEL_OFFSET	        0
#define VIDEO_CTL_RB_SOC2MIPI_ULPS_FLG_SEL_MASK    		0x1

#define	VIDEO_CTL_RB_VIDEO_DEBUG_CTRL_LEN	        1
#define	VIDEO_CTL_RB_VIDEO_DEBUG_CTRL_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_DEBUG_CTRL_MASK    		0x1

#define	VIDEO_CTL_RB_VIDEO_HC_RAM_TMOD_LEN	        10
#define	VIDEO_CTL_RB_VIDEO_HC_RAM_TMOD_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_HC_RAM_TMOD_MASK    		0x3FF

#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HH_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HH_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HH_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HL_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HL_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_HL_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LH_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LH_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LH_MASK    		0xFFFF

#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LL_LEN	        16
#define	VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LL_OFFSET	        0
#define VIDEO_CTL_RB_VIDEO_SP_RAM_TMOD_LL_MASK    		0xFFFF

#define	VIDEO_CTL_RB_CFG_VIDEO_MIPI_LANEBYTE_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPI_LANEBYTE_CKEN_OFFSET	        12
#define VIDEO_CTL_RB_CFG_VIDEO_MIPI_LANEBYTE_CKEN_MASK    		0x1000
#define	VIDEO_CTL_RB_CFG_LANEBYTE_CNT_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_LANEBYTE_CNT_CKEN_OFFSET	        11
#define VIDEO_CTL_RB_CFG_LANEBYTE_CNT_CKEN_MASK    		0x800
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_CLKEN_OFFSET	        10
#define VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_CLKEN_MASK    		0x400
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_CLKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_CLKEN_OFFSET	        9
#define VIDEO_CTL_RB_CFG_MIPITX_XTAL_CLKEN_MASK    		0x200
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_NUM_LEN	        3
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_NUM_OFFSET	        6
#define VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_NUM_MASK    		0x1C0
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_DENOM_LEN	        4
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_DENOM_OFFSET	        2
#define VIDEO_CTL_RB_CFG_MIPITX_XTAL_DIV_DENOM_MASK    		0x3C
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_XTAL_LOAD_DIV_EN_OFFSET	        1
#define VIDEO_CTL_RB_CFG_MIPITX_XTAL_LOAD_DIV_EN_MASK    		0x2
#define	VIDEO_CTL_RB_CFG_MIPI_APHY_OCC_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPI_APHY_OCC_CKEN_OFFSET	        0
#define VIDEO_CTL_RB_CFG_MIPI_APHY_OCC_CKEN_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_LANEBYTE_SEL_LEN	        1
#define	VIDEO_CTL_RB_CFG_LANEBYTE_SEL_OFFSET	        6
#define VIDEO_CTL_RB_CFG_LANEBYTE_SEL_MASK    		0x40
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_SSC_CKSEL_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_SSC_CKSEL_OFFSET	        5
#define VIDEO_CTL_RB_CFG_MIPITX_APHY_SSC_CKSEL_MASK    		0x20
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_ADFB_CKSEL_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_ADFB_CKSEL_OFFSET	        4
#define VIDEO_CTL_RB_CFG_MIPITX_APHY_ADFB_CKSEL_MASK    		0x10
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_ADREF_CKSEL_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_APHY_ADREF_CKSEL_OFFSET	        3
#define VIDEO_CTL_RB_CFG_MIPITX_APHY_ADREF_CKSEL_MASK    		0x8
#define	VIDEO_CTL_RB_CFG_MIPITX_SSC_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_SSC_CKEN_OFFSET	        2
#define VIDEO_CTL_RB_CFG_MIPITX_SSC_CKEN_MASK    		0x4
#define	VIDEO_CTL_RB_CFG_MIPITX_ADFB_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_ADFB_CKEN_OFFSET	        1
#define VIDEO_CTL_RB_CFG_MIPITX_ADFB_CKEN_MASK    		0x2
#define	VIDEO_CTL_RB_CFG_MIPITX_ADREF_CKEN_LEN	        1
#define	VIDEO_CTL_RB_CFG_MIPITX_ADREF_CKEN_OFFSET	        0
#define VIDEO_CTL_RB_CFG_MIPITX_ADREF_CKEN_MASK    		0x1

#define	VIDEO_CTL_RB_MIPITX_PWR_DWN_REQ_LEN	        1
#define	VIDEO_CTL_RB_MIPITX_PWR_DWN_REQ_OFFSET	        0
#define VIDEO_CTL_RB_MIPITX_PWR_DWN_REQ_MASK    		0x1

#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_LOAD_DIV_EN_LEN	        1
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_LOAD_DIV_EN_OFFSET	        10
#define VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_LOAD_DIV_EN_MASK    		0x400
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_NUM_LEN	        5
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_NUM_OFFSET	        5
#define VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_NUM_MASK    		0x3E0
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_DEDOM_LEN	        5
#define	VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_DEDOM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_MIPIDFT_DIV_DEDOM_MASK    		0x1F

#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_NUM_LEN	        13
#define	VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_NUM_OFFSET	        0
#define VIDEO_CTL_RB_CFG_VIDEO_DPU_PPC_DIV_NUM_MASK    		0x1FFF

#endif // __3322_VIDEO_CTL_RB_REG_OFFSET_FIELD_H__
