/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_com_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_COM_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_COM_CTL_RB_REG_OFFSET_FIELD_H__

#define	COM_CTL_RB_COM_CTL_ID_LEN	        16
#define	COM_CTL_RB_COM_CTL_ID_OFFSET	        0
#define COM_CTL_RB_COM_CTL_ID_MASK    		0xFFFF

#define	COM_CTL_RB_COM_GP_REG0_LEN	        16
#define	COM_CTL_RB_COM_GP_REG0_OFFSET	        0
#define COM_CTL_RB_COM_GP_REG0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_GP_REG1_LEN	        16
#define	COM_CTL_RB_COM_GP_REG1_OFFSET	        0
#define COM_CTL_RB_COM_GP_REG1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_GP_REG2_LEN	        16
#define	COM_CTL_RB_COM_GP_REG2_OFFSET	        0
#define COM_CTL_RB_COM_GP_REG2_MASK    		0xFFFF

#define	COM_CTL_RB_COM_GP_REG3_LEN	        16
#define	COM_CTL_RB_COM_GP_REG3_OFFSET	        0
#define COM_CTL_RB_COM_GP_REG3_MASK    		0xFFFF

#define	COM_CTL_RB_CODEC_DIG_REG_RW_L_LEN	        16
#define	COM_CTL_RB_CODEC_DIG_REG_RW_L_OFFSET	        0
#define COM_CTL_RB_CODEC_DIG_REG_RW_L_MASK    		0xFFFF

#define	COM_CTL_RB_CODEC_DIG_REG_RW_H_LEN	        16
#define	COM_CTL_RB_CODEC_DIG_REG_RW_H_OFFSET	        0
#define COM_CTL_RB_CODEC_DIG_REG_RW_H_MASK    		0xFFFF

#define	COM_CTL_RB_CODEC_DIG_REG0_RO_LEN	        8
#define	COM_CTL_RB_CODEC_DIG_REG0_RO_OFFSET	        0
#define COM_CTL_RB_CODEC_DIG_REG0_RO_MASK    		0xFF

#define	COM_CTL_RB_HIFI_PFAULTINFO_ST_L_LEN	        16
#define	COM_CTL_RB_HIFI_PFAULTINFO_ST_L_OFFSET	        0
#define COM_CTL_RB_HIFI_PFAULTINFO_ST_L_MASK    		0xFFFF

#define	COM_CTL_RB_HIFI_PFAULTINFO_ST_H_LEN	        16
#define	COM_CTL_RB_HIFI_PFAULTINFO_ST_H_OFFSET	        0
#define COM_CTL_RB_HIFI_PFAULTINFO_ST_H_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_D2C_CACTIVE_LEN	        1
#define	COM_CTL_RB_COM_AHB_D2C_CACTIVE_OFFSET	        9
#define COM_CTL_RB_COM_AHB_D2C_CACTIVE_MASK    		0x200
#define	COM_CTL_RB_COM_AHB_C2D_CACTIVE_LEN	        1
#define	COM_CTL_RB_COM_AHB_C2D_CACTIVE_OFFSET	        8
#define COM_CTL_RB_COM_AHB_C2D_CACTIVE_MASK    		0x100
#define	COM_CTL_RB_COM_AHB_D2C_CSYACK_LEN	        1
#define	COM_CTL_RB_COM_AHB_D2C_CSYACK_OFFSET	        5
#define COM_CTL_RB_COM_AHB_D2C_CSYACK_MASK    		0x20
#define	COM_CTL_RB_COM_AHB_C2D_CSYSACK_LEN	        1
#define	COM_CTL_RB_COM_AHB_C2D_CSYSACK_OFFSET	        4
#define COM_CTL_RB_COM_AHB_C2D_CSYSACK_MASK    		0x10
#define	COM_CTL_RB_COM_AHB_D2C_CSYSREQ_LEN	        1
#define	COM_CTL_RB_COM_AHB_D2C_CSYSREQ_OFFSET	        1
#define COM_CTL_RB_COM_AHB_D2C_CSYSREQ_MASK    		0x2
#define	COM_CTL_RB_COM_AHB_C2D_CSYSREQ_LEN	        1
#define	COM_CTL_RB_COM_AHB_C2D_CSYSREQ_OFFSET	        0
#define COM_CTL_RB_COM_AHB_C2D_CSYSREQ_MASK    		0x1

#define	COM_CTL_RB_COM_MEM_LS_LEN	        4
#define	COM_CTL_RB_COM_MEM_LS_OFFSET	        0
#define COM_CTL_RB_COM_MEM_LS_MASK    		0xF

#define	COM_CTL_RB_COM_AHB_S6_ICM_PRIORITY_LEN	        2
#define	COM_CTL_RB_COM_AHB_S6_ICM_PRIORITY_OFFSET	        14
#define COM_CTL_RB_COM_AHB_S6_ICM_PRIORITY_MASK    		0xC000
#define	COM_CTL_RB_COM_AHB_S5_ICM_PRIORITY_LEN	        6
#define	COM_CTL_RB_COM_AHB_S5_ICM_PRIORITY_OFFSET	        8
#define COM_CTL_RB_COM_AHB_S5_ICM_PRIORITY_MASK    		0x3F00
#define	COM_CTL_RB_COM_AHB_S4_ICM_PRIORITY_LEN	        2
#define	COM_CTL_RB_COM_AHB_S4_ICM_PRIORITY_OFFSET	        6
#define COM_CTL_RB_COM_AHB_S4_ICM_PRIORITY_MASK    		0xC0
#define	COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_H_LEN	        2
#define	COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_H_OFFSET	        4
#define COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_H_MASK    		0x30
#define	COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_H_LEN	        2
#define	COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_H_OFFSET	        2
#define COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_H_MASK    		0xC

#define	COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_L_LEN	        16
#define	COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_L_OFFSET	        0
#define COM_CTL_RB_COM_AHB_S2_ICM_PRIORITY_L_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_L_LEN	        16
#define	COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_L_OFFSET	        0
#define COM_CTL_RB_COM_AHB_S3_ICM_PRIORITY_L_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_L_LEN	        16
#define	COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_L_OFFSET	        0
#define COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_L_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_S10_ICM_PRIORITY_LEN	        2
#define	COM_CTL_RB_COM_AHB_S10_ICM_PRIORITY_OFFSET	        4
#define COM_CTL_RB_COM_AHB_S10_ICM_PRIORITY_MASK    		0x30
#define	COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_H_LEN	        2
#define	COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_H_OFFSET	        0
#define COM_CTL_RB_COM_AHB_S7_ICM_PRIORITY_H_MASK    		0x3

#define	COM_CTL_RB_CFG_COM_BUS_C2D_D2C_N_LEN	        1
#define	COM_CTL_RB_CFG_COM_BUS_C2D_D2C_N_OFFSET	        1
#define COM_CTL_RB_CFG_COM_BUS_C2D_D2C_N_MASK    		0x2
#define	COM_CTL_RB_CFG_COM_C2D_A2X_HSEL_SEL_LEN	        1
#define	COM_CTL_RB_CFG_COM_C2D_A2X_HSEL_SEL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_C2D_A2X_HSEL_SEL_MASK    		0x1

#define	COM_CTL_RB_COM_AHB_HREADY_MUX_LEN	        1
#define	COM_CTL_RB_COM_AHB_HREADY_MUX_OFFSET	        15
#define COM_CTL_RB_COM_AHB_HREADY_MUX_MASK    		0x8000
#define	COM_CTL_RB_COM_A2C_AH2H_AUTO_CG_BYPASS_EN_LEN	        1
#define	COM_CTL_RB_COM_A2C_AH2H_AUTO_CG_BYPASS_EN_OFFSET	        13
#define COM_CTL_RB_COM_A2C_AH2H_AUTO_CG_BYPASS_EN_MASK    		0x2000
#define	COM_CTL_RB_COM_C2A_AH2H_AUTO_CG_BYPASS_EN_LEN	        1
#define	COM_CTL_RB_COM_C2A_AH2H_AUTO_CG_BYPASS_EN_OFFSET	        12
#define COM_CTL_RB_COM_C2A_AH2H_AUTO_CG_BYPASS_EN_MASK    		0x1000
#define	COM_CTL_RB_COM_COM2NPU_H2H_AUTO_CG_BYPASS_LEN	        1
#define	COM_CTL_RB_COM_COM2NPU_H2H_AUTO_CG_BYPASS_OFFSET	        10
#define COM_CTL_RB_COM_COM2NPU_H2H_AUTO_CG_BYPASS_MASK    		0x400
#define	COM_CTL_RB_COM_AHBS6_EH2H_AUTO_CG_BYPASS_LEN	        1
#define	COM_CTL_RB_COM_AHBS6_EH2H_AUTO_CG_BYPASS_OFFSET	        7
#define COM_CTL_RB_COM_AHBS6_EH2H_AUTO_CG_BYPASS_MASK    		0x80
#define	COM_CTL_RB_COM_AHBM2_EH2H_AUTO_CG_BYPASS_LEN	        1
#define	COM_CTL_RB_COM_AHBM2_EH2H_AUTO_CG_BYPASS_OFFSET	        6
#define COM_CTL_RB_COM_AHBM2_EH2H_AUTO_CG_BYPASS_MASK    		0x40
#define	COM_CTL_RB_COM_MEM_CLK_FORCE_ON_LEN	        1
#define	COM_CTL_RB_COM_MEM_CLK_FORCE_ON_OFFSET	        5
#define COM_CTL_RB_COM_MEM_CLK_FORCE_ON_MASK    		0x20

#define	COM_CTL_RB_CFG_COM_XO_DLL2_PH_SEL_LEN	        2
#define	COM_CTL_RB_CFG_COM_XO_DLL2_PH_SEL_OFFSET	        1
#define COM_CTL_RB_CFG_COM_XO_DLL2_PH_SEL_MASK    		0x6
#define	COM_CTL_RB_CFG_COM_XO_DLL2_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_XO_DLL2_CLKEN_OFFSET	        0
#define COM_CTL_RB_CFG_COM_XO_DLL2_CLKEN_MASK    		0x1

#define	COM_CTL_RB_CFG_COM_BUS_MONITOR_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_BUS_MONITOR_CLKEN_OFFSET	        6
#define COM_CTL_RB_CFG_COM_BUS_MONITOR_CLKEN_MASK    		0x40
#define	COM_CTL_RB_CFG_COM_BUS_SLV_PRT_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_BUS_SLV_PRT_CLKEN_OFFSET	        5
#define COM_CTL_RB_CFG_COM_BUS_SLV_PRT_CLKEN_MASK    		0x20
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_DIAG_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_DIAG_CLKEN_OFFSET	        4
#define COM_CTL_RB_CFG_COM_FNPLL_VCO_DIAG_CLKEN_MASK    		0x10
#define	COM_CTL_RB_CFG_COM_SDIOM_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_SDIOM_CLKEN_OFFSET	        3
#define COM_CTL_RB_CFG_COM_SDIOM_CLKEN_MASK    		0x8
#define	COM_CTL_RB_CFG_COM_EMMC_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_EMMC_CLKEN_OFFSET	        2
#define COM_CTL_RB_CFG_COM_EMMC_CLKEN_MASK    		0x4
#define	COM_CTL_RB_CFG_COM_XIP_QSPI2_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_XIP_QSPI2_CLKEN_OFFSET	        1
#define COM_CTL_RB_CFG_COM_XIP_QSPI2_CLKEN_MASK    		0x2
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_SEC_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_SEC_OFFSET	        0
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_SEC_MASK    		0x1

#define	COM_CTL_RB_CFG_COM_FNPLL_DIAG_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_FNPLL_DIAG_CLKEN_OFFSET	        15
#define COM_CTL_RB_CFG_COM_FNPLL_DIAG_CLKEN_MASK    		0x8000
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_CAN_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_CAN_OFFSET	        14
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_CAN_MASK    		0x4000
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_NPU_CORE_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_NPU_CORE_OFFSET	        13
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_NPU_CORE_MASK    		0x2000
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_CODEC_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_CODEC_OFFSET	        12
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_CODEC_MASK    		0x1000
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_HIFI_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_HIFI_OFFSET	        11
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_HIFI_MASK    		0x800
#define	COM_CTL_RB_CFG_COM_FNPLL_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_FNPLL_CLKEN_OFFSET	        10
#define COM_CTL_RB_CFG_COM_FNPLL_CLKEN_MASK    		0x400
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_USB_BUS_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_USB_BUS_OFFSET	        9
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_USB_BUS_MASK    		0x200
#define	COM_CTL_RB_CFG_COM_BUS_DSP_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_BUS_DSP_CLKEN_OFFSET	        8
#define COM_CTL_RB_CFG_COM_BUS_DSP_CLKEN_MASK    		0x100
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_XIP_QSPI_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_XIP_QSPI_OFFSET	        7
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_XIP_QSPI_MASK    		0x80
#define	COM_CTL_RB_CFG_COM_HPM_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_HPM_CLKEN_OFFSET	        6
#define COM_CTL_RB_CFG_COM_HPM_CLKEN_MASK    		0x40
#define	COM_CTL_RB_CFG_COM_UART_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_UART_CLKEN_OFFSET	        5
#define COM_CTL_RB_CFG_COM_UART_CLKEN_MASK    		0x20
#define	COM_CTL_RB_CFG_COM_DPU_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_DPU_CLKEN_OFFSET	        4
#define COM_CTL_RB_CFG_COM_DPU_CLKEN_MASK    		0x10
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_SPI_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_SPI_OFFSET	        3
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_SPI_MASK    		0x8
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_UART_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_UART_OFFSET	        2
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_UART_MASK    		0x4
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_LS_LEN	        1
#define	COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_LS_OFFSET	        1
#define COM_CTL_RB_CFG_COM_GLB_CLKEN_MCU_PERP_LS_MASK    		0x2
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_CLKEN_LEN	        1
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_CLKEN_OFFSET	        0
#define COM_CTL_RB_CFG_COM_FNPLL_VCO_CLKEN_MASK    		0x1

#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH0_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_MCU_CORE_CH0_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_MCU_CORE_CH_SEL_STS_LEN	        2
#define	COM_CTL_RB_MCU_CORE_CH_SEL_STS_OFFSET	        12
#define COM_CTL_RB_MCU_CORE_CH_SEL_STS_MASK    		0x3000
#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH1_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH1_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_MCU_CORE_CH1_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_MCU_PERP_LS_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_MCU_PERP_LS_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_MCU_PERP_LS_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_MCU_PERP_UART_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_MCU_PERP_UART_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_MCU_PERP_UART_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_MCU_PERP_SPI_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_MCU_PERP_SPI_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_MCU_PERP_SPI_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_COM_BUS_CH0_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_COM_BUS_CH0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_COM_BUS_CH0_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_COM_BUS_CH_SEL_STS_LEN	        2
#define	COM_CTL_RB_COM_BUS_CH_SEL_STS_OFFSET	        12
#define COM_CTL_RB_COM_BUS_CH_SEL_STS_MASK    		0x3000
#define	COM_CTL_RB_CFG_COM_COM_BUS_CH1_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_COM_BUS_CH1_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_COM_BUS_CH1_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_SDIOM_CR_CTRL_LEN	        12
#define	COM_CTL_RB_CFG_COM_SDIOM_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_SDIOM_CR_CTRL_MASK    		0xFFF

#define	COM_CTL_RB_CFG_COM_NPU_CORE_SCR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_NPU_CORE_SCR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_NPU_CORE_SCR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_SEC_SCR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_SEC_SCR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_SEC_SCR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_XIP_QSPI_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_XIP_QSPI_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_XIP_QSPI_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_EMMC_CR_CTRL_LEN	        12
#define	COM_CTL_RB_CFG_COM_EMMC_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_EMMC_CR_CTRL_MASK    		0xFFF

#define	COM_CTL_RB_CFG_COM_HIFI_CH0_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_HIFI_CH0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_HIFI_CH0_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_HIFI_CH_SEL_STS_LEN	        2
#define	COM_CTL_RB_HIFI_CH_SEL_STS_OFFSET	        12
#define COM_CTL_RB_HIFI_CH_SEL_STS_MASK    		0x3000
#define	COM_CTL_RB_CFG_COM_HIFI_CH1_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_HIFI_CH1_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_HIFI_CH1_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_CODEC_CH0_CR_CTRL_LEN	        12
#define	COM_CTL_RB_CFG_COM_CODEC_CH0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_CODEC_CH0_CR_CTRL_MASK    		0xFFF

#define	COM_CTL_RB_CODEC_CH_SEL_STS_LEN	        2
#define	COM_CTL_RB_CODEC_CH_SEL_STS_OFFSET	        12
#define COM_CTL_RB_CODEC_CH_SEL_STS_MASK    		0x3000
#define	COM_CTL_RB_CFG_COM_CODEC_CH1_CR_CTRL_LEN	        12
#define	COM_CTL_RB_CFG_COM_CODEC_CH1_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_CODEC_CH1_CR_CTRL_MASK    		0xFFF

#define	COM_CTL_RB_CFG_COM_PAD_CLK_OUT_0_CR_CTRL_LEN	        14
#define	COM_CTL_RB_CFG_COM_PAD_CLK_OUT_0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_PAD_CLK_OUT_0_CR_CTRL_MASK    		0x3FFF

#define	COM_CTL_RB_CFG_COM_PAD_CLK_OUT_1_CR_CTRL_LEN	        14
#define	COM_CTL_RB_CFG_COM_PAD_CLK_OUT_1_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_PAD_CLK_OUT_1_CR_CTRL_MASK    		0x3FFF

#define	COM_CTL_RB_CFG_COM_CAN_SCR_CTRL_LEN	        11
#define	COM_CTL_RB_CFG_COM_CAN_SCR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_CAN_SCR_CTRL_MASK    		0x7FF

#define	COM_CTL_RB_CFG_COM_XIP_OPI0_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_XIP_OPI0_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_XIP_OPI0_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_QSPI2_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_QSPI2_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_QSPI2_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_DPU_CR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_DPU_CR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_DPU_CR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_USB_BUS_SCR_CTRL_LEN	        9
#define	COM_CTL_RB_CFG_COM_USB_BUS_SCR_CTRL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_USB_BUS_SCR_CTRL_MASK    		0x1FF

#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_DIV_LEN	        3
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_DIV_OFFSET	        4
#define COM_CTL_RB_CFG_COM_FNPLL_VCO_DIV_MASK    		0x70
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_PSRAM_DIV_LEN	        3
#define	COM_CTL_RB_CFG_COM_FNPLL_VCO_PSRAM_DIV_OFFSET	        0
#define COM_CTL_RB_CFG_COM_FNPLL_VCO_PSRAM_DIV_MASK    		0x7

#define	COM_CTL_RB_COM_AHB_MONITOR_CLKEN_0_LEN	        1
#define	COM_CTL_RB_COM_AHB_MONITOR_CLKEN_0_OFFSET	        1
#define COM_CTL_RB_COM_AHB_MONITOR_CLKEN_0_MASK    		0x2
#define	COM_CTL_RB_COM_AHB_MONITOR_EN_0_LEN	        1
#define	COM_CTL_RB_COM_AHB_MONITOR_EN_0_OFFSET	        0
#define COM_CTL_RB_COM_AHB_MONITOR_EN_0_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_0_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_0_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_0_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_0_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_0_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_0_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_STS_0_LEN	        8
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_STS_0_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_STS_0_MASK    		0xFF

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_0_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_0_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_0_MASK    		0x1

#define	COM_CTL_RB_COM_REC_ADDR_L_0_LEN	        16
#define	COM_CTL_RB_COM_REC_ADDR_L_0_OFFSET	        0
#define COM_CTL_RB_COM_REC_ADDR_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_REC_ADDR_H_0_LEN	        16
#define	COM_CTL_RB_COM_REC_ADDR_H_0_OFFSET	        0
#define COM_CTL_RB_COM_REC_ADDR_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_REC_ID_0_LEN	        2
#define	COM_CTL_RB_COM_REC_ID_0_OFFSET	        8
#define COM_CTL_RB_COM_REC_ID_0_MASK    		0x300
#define	COM_CTL_RB_COM_REC_WR_0_LEN	        1
#define	COM_CTL_RB_COM_REC_WR_0_OFFSET	        0
#define COM_CTL_RB_COM_REC_WR_0_MASK    		0x1

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_0_LEN	        8
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_0_MASK    		0xFF

#define	COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_0_LEN	        16
#define	COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_0_OFFSET	        0
#define COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_0_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_0_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_0_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_MONITOR_CLKEN_1_LEN	        1
#define	COM_CTL_RB_COM_AHB_MONITOR_CLKEN_1_OFFSET	        1
#define COM_CTL_RB_COM_AHB_MONITOR_CLKEN_1_MASK    		0x2
#define	COM_CTL_RB_COM_AHB_MONITOR_EN_1_LEN	        1
#define	COM_CTL_RB_COM_AHB_MONITOR_EN_1_OFFSET	        0
#define COM_CTL_RB_COM_AHB_MONITOR_EN_1_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_1_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_1_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_1_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_1_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_1_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_MASK_1_MASK    		0x1

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_STS_1_LEN	        8
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_STS_1_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_STS_1_MASK    		0xFF

#define	COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_1_LEN	        1
#define	COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_1_OFFSET	        0
#define COM_CTL_RB_COM_ACCESS_MEM_INT_CLR_1_MASK    		0x1

#define	COM_CTL_RB_COM_REC_ADDR_L_1_LEN	        16
#define	COM_CTL_RB_COM_REC_ADDR_L_1_OFFSET	        0
#define COM_CTL_RB_COM_REC_ADDR_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_REC_ADDR_H_1_LEN	        16
#define	COM_CTL_RB_COM_REC_ADDR_H_1_OFFSET	        0
#define COM_CTL_RB_COM_REC_ADDR_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_REC_ID_1_LEN	        2
#define	COM_CTL_RB_COM_REC_ID_1_OFFSET	        8
#define COM_CTL_RB_COM_REC_ID_1_MASK    		0x300
#define	COM_CTL_RB_COM_REC_WR_1_LEN	        1
#define	COM_CTL_RB_COM_REC_WR_1_OFFSET	        0
#define COM_CTL_RB_COM_REC_WR_1_MASK    		0x1

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_1_LEN	        8
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR_EN_1_MASK    		0xFF

#define	COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_1_LEN	        16
#define	COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_1_OFFSET	        0
#define COM_CTL_RB_COM_CFG_PKT_MONITOR_INT_DLY_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_L_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR0_H_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_L_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR1_H_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_L_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR2_H_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_L_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_L_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_1_LEN	        16
#define	COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_1_OFFSET	        0
#define COM_CTL_RB_COM_MONITOR_MEM_ADDR3_H_H_1_MASK    		0xFFFF

#define	COM_CTL_RB_COM_DFS_S10_EN_LEN	        1
#define	COM_CTL_RB_COM_DFS_S10_EN_OFFSET	        9
#define COM_CTL_RB_COM_DFS_S10_EN_MASK    		0x200
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_CFG_PRTC_EN_LEN	        1
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_CFG_PRTC_EN_OFFSET	        7
#define COM_CTL_RB_COM_H4_AHB_S1_PRT_CFG_PRTC_EN_MASK    		0x80
#define	COM_CTL_RB_COM_DFS_S6_EN_LEN	        1
#define	COM_CTL_RB_COM_DFS_S6_EN_OFFSET	        6
#define COM_CTL_RB_COM_DFS_S6_EN_MASK    		0x40
#define	COM_CTL_RB_COM_DFS_S5_EN_LEN	        1
#define	COM_CTL_RB_COM_DFS_S5_EN_OFFSET	        5
#define COM_CTL_RB_COM_DFS_S5_EN_MASK    		0x20
#define	COM_CTL_RB_COM_DFS_S4_EN_LEN	        1
#define	COM_CTL_RB_COM_DFS_S4_EN_OFFSET	        4
#define COM_CTL_RB_COM_DFS_S4_EN_MASK    		0x10
#define	COM_CTL_RB_COM_AUTO_CG_BYPASS_EN_LEN	        1
#define	COM_CTL_RB_COM_AUTO_CG_BYPASS_EN_OFFSET	        0
#define COM_CTL_RB_COM_AUTO_CG_BYPASS_EN_MASK    		0x1

#define	COM_CTL_RB_COM_AHB_OT_DELAY_LEN	        16
#define	COM_CTL_RB_COM_AHB_OT_DELAY_OFFSET	        0
#define COM_CTL_RB_COM_AHB_OT_DELAY_MASK    		0xFFFF

#define	COM_CTL_RB_COM_AHB_S10_TIME_OUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S10_TIME_OUT_STS_OFFSET	        8
#define COM_CTL_RB_COM_AHB_S10_TIME_OUT_STS_MASK    		0x100
#define	COM_CTL_RB_COM_AHB_S9_TIMEOUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S9_TIMEOUT_STS_OFFSET	        7
#define COM_CTL_RB_COM_AHB_S9_TIMEOUT_STS_MASK    		0x80
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_STS_RPT_LEN	        1
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_STS_RPT_OFFSET	        6
#define COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_STS_RPT_MASK    		0x40
#define	COM_CTL_RB_COM_AHB_S6_TIMEOUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S6_TIMEOUT_STS_OFFSET	        5
#define COM_CTL_RB_COM_AHB_S6_TIMEOUT_STS_MASK    		0x20
#define	COM_CTL_RB_COM_AHB_S5_TIMEOUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S5_TIMEOUT_STS_OFFSET	        4
#define COM_CTL_RB_COM_AHB_S5_TIMEOUT_STS_MASK    		0x10
#define	COM_CTL_RB_COM_AHB_S4_TIMEOUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S4_TIMEOUT_STS_OFFSET	        3
#define COM_CTL_RB_COM_AHB_S4_TIMEOUT_STS_MASK    		0x8
#define	COM_CTL_RB_COM_AHB_S1_TIMEOUT_STS_LEN	        1
#define	COM_CTL_RB_COM_AHB_S1_TIMEOUT_STS_OFFSET	        0
#define COM_CTL_RB_COM_AHB_S1_TIMEOUT_STS_MASK    		0x1

#define	COM_CTL_RB_COM_DFS_S10_TIMEOUT_CLR_LEN	        1
#define	COM_CTL_RB_COM_DFS_S10_TIMEOUT_CLR_OFFSET	        8
#define COM_CTL_RB_COM_DFS_S10_TIMEOUT_CLR_MASK    		0x100
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_CLR_LEN	        1
#define	COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_CLR_OFFSET	        6
#define COM_CTL_RB_COM_H4_AHB_S1_PRT_TIMEOUT_CLR_MASK    		0x40
#define	COM_CTL_RB_COM_DFS_S6_TIMEOUT_CLR_LEN	        1
#define	COM_CTL_RB_COM_DFS_S6_TIMEOUT_CLR_OFFSET	        5
#define COM_CTL_RB_COM_DFS_S6_TIMEOUT_CLR_MASK    		0x20
#define	COM_CTL_RB_COM_DFS_S5_TIMEOUT_CLR_LEN	        1
#define	COM_CTL_RB_COM_DFS_S5_TIMEOUT_CLR_OFFSET	        4
#define COM_CTL_RB_COM_DFS_S5_TIMEOUT_CLR_MASK    		0x10
#define	COM_CTL_RB_COM_DFS_S4_TIMEOUT_CLR_LEN	        1
#define	COM_CTL_RB_COM_DFS_S4_TIMEOUT_CLR_OFFSET	        3
#define COM_CTL_RB_COM_DFS_S4_TIMEOUT_CLR_MASK    		0x8

#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH_SEL_LEN	        1
#define	COM_CTL_RB_CFG_COM_MCU_CORE_CH_SEL_OFFSET	        3
#define COM_CTL_RB_CFG_COM_MCU_CORE_CH_SEL_MASK    		0x8
#define	COM_CTL_RB_CFG_COM_CODEC_CH_SEL_LEN	        1
#define	COM_CTL_RB_CFG_COM_CODEC_CH_SEL_OFFSET	        2
#define COM_CTL_RB_CFG_COM_CODEC_CH_SEL_MASK    		0x4
#define	COM_CTL_RB_CFG_COM_HIFI_CH_SEL_LEN	        1
#define	COM_CTL_RB_CFG_COM_HIFI_CH_SEL_OFFSET	        1
#define COM_CTL_RB_CFG_COM_HIFI_CH_SEL_MASK    		0x2
#define	COM_CTL_RB_CFG_COM_COM_BUS_CH_SEL_LEN	        1
#define	COM_CTL_RB_CFG_COM_COM_BUS_CH_SEL_OFFSET	        0
#define COM_CTL_RB_CFG_COM_COM_BUS_CH_SEL_MASK    		0x1

#define	COM_CTL_RB_COM_UART_TRX_CFG_LEN	        1
#define	COM_CTL_RB_COM_UART_TRX_CFG_OFFSET	        3
#define COM_CTL_RB_COM_UART_TRX_CFG_MASK    		0x8
#define	COM_CTL_RB_COM_UART_SOFT_RST_N_LEN	        1
#define	COM_CTL_RB_COM_UART_SOFT_RST_N_OFFSET	        2
#define COM_CTL_RB_COM_UART_SOFT_RST_N_MASK    		0x4
#define	COM_CTL_RB_COM_UART_CLKEN_LEN	        1
#define	COM_CTL_RB_COM_UART_CLKEN_OFFSET	        1
#define COM_CTL_RB_COM_UART_CLKEN_MASK    		0x2
#define	COM_CTL_RB_COM_UART_AUTO_CG_BYPASS_EN_LEN	        1
#define	COM_CTL_RB_COM_UART_AUTO_CG_BYPASS_EN_OFFSET	        0
#define COM_CTL_RB_COM_UART_AUTO_CG_BYPASS_EN_MASK    		0x1

#define	COM_CTL_RB_NPU_MEM_RET1N_LEN	        1
#define	COM_CTL_RB_NPU_MEM_RET1N_OFFSET	        0
#define COM_CTL_RB_NPU_MEM_RET1N_MASK    		0x1

#endif // __3322_COM_CTL_RB_REG_OFFSET_FIELD_H__
