/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_tee_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_TEE_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_TEE_CTL_RB_REG_OFFSET_FIELD_H__

#define	TEE_CTL_RB_TEE_CTL_ID_LEN	        16
#define	TEE_CTL_RB_TEE_CTL_ID_OFFSET	        0
#define TEE_CTL_RB_TEE_CTL_ID_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_GP_REG0_LEN	        16
#define	TEE_CTL_RB_TEE_GP_REG0_OFFSET	        0
#define TEE_CTL_RB_TEE_GP_REG0_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_GP_REG1_LEN	        16
#define	TEE_CTL_RB_TEE_GP_REG1_OFFSET	        0
#define TEE_CTL_RB_TEE_GP_REG1_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_GP_REG2_LEN	        16
#define	TEE_CTL_RB_TEE_GP_REG2_OFFSET	        0
#define TEE_CTL_RB_TEE_GP_REG2_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_GP_REG3_LEN	        16
#define	TEE_CTL_RB_TEE_GP_REG3_OFFSET	        0
#define TEE_CTL_RB_TEE_GP_REG3_MASK    		0xFFFF

#define	TEE_CTL_RB_MCPU_TDM_LEN	        1
#define	TEE_CTL_RB_MCPU_TDM_OFFSET	        1
#define TEE_CTL_RB_MCPU_TDM_MASK    		0x2
#define	TEE_CTL_RB_SOFT_SOC_TEE_ENABLE_LEN	        1
#define	TEE_CTL_RB_SOFT_SOC_TEE_ENABLE_OFFSET	        0
#define TEE_CTL_RB_SOFT_SOC_TEE_ENABLE_MASK    		0x1

#define	TEE_CTL_RB_ITCM_APC_ENHANCE_EN_LEN	        1
#define	TEE_CTL_RB_ITCM_APC_ENHANCE_EN_OFFSET	        1
#define TEE_CTL_RB_ITCM_APC_ENHANCE_EN_MASK    		0x2
#define	TEE_CTL_RB_REGION_APC_EN_LEN	        1
#define	TEE_CTL_RB_REGION_APC_EN_OFFSET	        0
#define TEE_CTL_RB_REGION_APC_EN_MASK    		0x1

#define	TEE_CTL_RB_ITCM_APC_ERR_CLR_LEN	        1
#define	TEE_CTL_RB_ITCM_APC_ERR_CLR_OFFSET	        14
#define TEE_CTL_RB_ITCM_APC_ERR_CLR_MASK    		0x4000
#define	TEE_CTL_RB_ITCM_APC_RD_ERR_STS_LEN	        1
#define	TEE_CTL_RB_ITCM_APC_RD_ERR_STS_OFFSET	        13
#define TEE_CTL_RB_ITCM_APC_RD_ERR_STS_MASK    		0x2000
#define	TEE_CTL_RB_ITCM_APC_WR_ERR_STS_LEN	        1
#define	TEE_CTL_RB_ITCM_APC_WR_ERR_STS_OFFSET	        12
#define TEE_CTL_RB_ITCM_APC_WR_ERR_STS_MASK    		0x1000
#define	TEE_CTL_RB_ITCM_END_ADDR_LEN	        5
#define	TEE_CTL_RB_ITCM_END_ADDR_OFFSET	        5
#define TEE_CTL_RB_ITCM_END_ADDR_MASK    		0x3E0
#define	TEE_CTL_RB_ITCM_START_ADDR_LEN	        5
#define	TEE_CTL_RB_ITCM_START_ADDR_OFFSET	        0
#define TEE_CTL_RB_ITCM_START_ADDR_MASK    		0x1F

#define	TEE_CTL_RB_DTCM_APC_ERR_CLR_LEN	        1
#define	TEE_CTL_RB_DTCM_APC_ERR_CLR_OFFSET	        14
#define TEE_CTL_RB_DTCM_APC_ERR_CLR_MASK    		0x4000
#define	TEE_CTL_RB_DTCM_APC_RD_ERR_STS_LEN	        1
#define	TEE_CTL_RB_DTCM_APC_RD_ERR_STS_OFFSET	        13
#define TEE_CTL_RB_DTCM_APC_RD_ERR_STS_MASK    		0x2000
#define	TEE_CTL_RB_DTCM_APC_WR_ERR_STS_LEN	        1
#define	TEE_CTL_RB_DTCM_APC_WR_ERR_STS_OFFSET	        12
#define TEE_CTL_RB_DTCM_APC_WR_ERR_STS_MASK    		0x1000
#define	TEE_CTL_RB_DTCM_END_ADDR_LEN	        5
#define	TEE_CTL_RB_DTCM_END_ADDR_OFFSET	        5
#define TEE_CTL_RB_DTCM_END_ADDR_MASK    		0x3E0
#define	TEE_CTL_RB_DTCM_START_ADDR_LEN	        5
#define	TEE_CTL_RB_DTCM_START_ADDR_OFFSET	        0
#define TEE_CTL_RB_DTCM_START_ADDR_MASK    		0x1F

#define	TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_L_LEN	        16
#define	TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_L_OFFSET	        0
#define TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_L_MASK    		0xFFFF

#define	TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_H_LEN	        16
#define	TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_H_OFFSET	        0
#define TEE_CTL_RB_ITCM_APC_WR_ERR_ADDR_H_MASK    		0xFFFF

#define	TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_L_LEN	        16
#define	TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_L_OFFSET	        0
#define TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_L_MASK    		0xFFFF

#define	TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_H_LEN	        16
#define	TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_H_OFFSET	        0
#define TEE_CTL_RB_ITCM_APC_RD_ERR_ADDR_H_MASK    		0xFFFF

#define	TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_L_LEN	        16
#define	TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_L_OFFSET	        0
#define TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_L_MASK    		0xFFFF

#define	TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_H_LEN	        16
#define	TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_H_OFFSET	        0
#define TEE_CTL_RB_DTCM_APC_WR_ERR_ADDR_H_MASK    		0xFFFF

#define	TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_L_LEN	        16
#define	TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_L_OFFSET	        0
#define TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_L_MASK    		0xFFFF

#define	TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_H_LEN	        16
#define	TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_H_OFFSET	        0
#define TEE_CTL_RB_DTCM_APC_RD_ERR_ADDR_H_MASK    		0xFFFF

#define	TEE_CTL_RB_EFUSE_PROT_CHECK_FAIL_LEN	        1
#define	TEE_CTL_RB_EFUSE_PROT_CHECK_FAIL_OFFSET	        5
#define TEE_CTL_RB_EFUSE_PROT_CHECK_FAIL_MASK    		0x20
#define	TEE_CTL_RB_EFUSE_TZPC_PROT_CFG_LEN	        1
#define	TEE_CTL_RB_EFUSE_TZPC_PROT_CFG_OFFSET	        4
#define TEE_CTL_RB_EFUSE_TZPC_PROT_CFG_MASK    		0x10
#define	TEE_CTL_RB_SPI1_PROT_CHECK_FAIL_LEN	        1
#define	TEE_CTL_RB_SPI1_PROT_CHECK_FAIL_OFFSET	        3
#define TEE_CTL_RB_SPI1_PROT_CHECK_FAIL_MASK    		0x8
#define	TEE_CTL_RB_SPI1_TZPC_PROT_CFG_LEN	        1
#define	TEE_CTL_RB_SPI1_TZPC_PROT_CFG_OFFSET	        2
#define TEE_CTL_RB_SPI1_TZPC_PROT_CFG_MASK    		0x4
#define	TEE_CTL_RB_SPI0_PROT_CHECK_FAIL_LEN	        1
#define	TEE_CTL_RB_SPI0_PROT_CHECK_FAIL_OFFSET	        1
#define TEE_CTL_RB_SPI0_PROT_CHECK_FAIL_MASK    		0x2
#define	TEE_CTL_RB_SPI0_TZPC_PROT_CFG_LEN	        1
#define	TEE_CTL_RB_SPI0_TZPC_PROT_CFG_OFFSET	        0
#define TEE_CTL_RB_SPI0_TZPC_PROT_CFG_MASK    		0x1

#define	TEE_CTL_RB_TEE_START_PC_LOCK_LEN	        1
#define	TEE_CTL_RB_TEE_START_PC_LOCK_OFFSET	        0
#define TEE_CTL_RB_TEE_START_PC_LOCK_MASK    		0x1

#define	TEE_CTL_RB_TEE_START_PC_H_LEN	        16
#define	TEE_CTL_RB_TEE_START_PC_H_OFFSET	        0
#define TEE_CTL_RB_TEE_START_PC_H_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_START_PC_L_LEN	        16
#define	TEE_CTL_RB_TEE_START_PC_L_OFFSET	        0
#define TEE_CTL_RB_TEE_START_PC_L_MASK    		0xFFFF

#define	TEE_CTL_RB_M_SDMA_HPROT_LEN	        1
#define	TEE_CTL_RB_M_SDMA_HPROT_OFFSET	        1
#define TEE_CTL_RB_M_SDMA_HPROT_MASK    		0x2
#define	TEE_CTL_RB_MDMA_HPROT_LEN	        1
#define	TEE_CTL_RB_MDMA_HPROT_OFFSET	        0
#define TEE_CTL_RB_MDMA_HPROT_MASK    		0x1

#define	TEE_CTL_RB_ROM_HIDE_ERR_ADDR_LEN	        16
#define	TEE_CTL_RB_ROM_HIDE_ERR_ADDR_OFFSET	        0
#define TEE_CTL_RB_ROM_HIDE_ERR_ADDR_MASK    		0xFFFF

#define	TEE_CTL_RB_ROM_HIDE_ERR_STS_LEN	        1
#define	TEE_CTL_RB_ROM_HIDE_ERR_STS_OFFSET	        7
#define TEE_CTL_RB_ROM_HIDE_ERR_STS_MASK    		0x80
#define	TEE_CTL_RB_ROM_HIDE_ERR_CLR_LEN	        1
#define	TEE_CTL_RB_ROM_HIDE_ERR_CLR_OFFSET	        6
#define TEE_CTL_RB_ROM_HIDE_ERR_CLR_MASK    		0x40
#define	TEE_CTL_RB_SWD_EN_REG_LOCK_STS_LEN	        1
#define	TEE_CTL_RB_SWD_EN_REG_LOCK_STS_OFFSET	        5
#define TEE_CTL_RB_SWD_EN_REG_LOCK_STS_MASK    		0x20
#define	TEE_CTL_RB_SWD_EN_REG_LOCK_LEN	        1
#define	TEE_CTL_RB_SWD_EN_REG_LOCK_OFFSET	        4
#define TEE_CTL_RB_SWD_EN_REG_LOCK_MASK    		0x10
#define	TEE_CTL_RB_SWD_EN_REG_STS_LEN	        1
#define	TEE_CTL_RB_SWD_EN_REG_STS_OFFSET	        3
#define TEE_CTL_RB_SWD_EN_REG_STS_MASK    		0x8
#define	TEE_CTL_RB_SWD_EN_REG_LEN	        1
#define	TEE_CTL_RB_SWD_EN_REG_OFFSET	        2
#define TEE_CTL_RB_SWD_EN_REG_MASK    		0x4
#define	TEE_CTL_RB_BOOTROM_HIDE_EN_STS_LEN	        1
#define	TEE_CTL_RB_BOOTROM_HIDE_EN_STS_OFFSET	        1
#define TEE_CTL_RB_BOOTROM_HIDE_EN_STS_MASK    		0x2
#define	TEE_CTL_RB_BOOTROM_HIDE_EN_LEN	        1
#define	TEE_CTL_RB_BOOTROM_HIDE_EN_OFFSET	        0
#define TEE_CTL_RB_BOOTROM_HIDE_EN_MASK    		0x1

#define	TEE_CTL_RB_TEE_DEEPSLEEP_VOTE_LEN	        1
#define	TEE_CTL_RB_TEE_DEEPSLEEP_VOTE_OFFSET	        0
#define TEE_CTL_RB_TEE_DEEPSLEEP_VOTE_MASK    		0x1

#define	TEE_CTL_RB_CFG_TEE_TIMER_INT_CLR_LEN	        1
#define	TEE_CTL_RB_CFG_TEE_TIMER_INT_CLR_OFFSET	        1
#define TEE_CTL_RB_CFG_TEE_TIMER_INT_CLR_MASK    		0x2
#define	TEE_CTL_RB_CFG_TEE_TIMER_EN_LEN	        1
#define	TEE_CTL_RB_CFG_TEE_TIMER_EN_OFFSET	        0
#define TEE_CTL_RB_CFG_TEE_TIMER_EN_MASK    		0x1

#define	TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_H_LEN	        16
#define	TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_H_OFFSET	        0
#define TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_H_MASK    		0xFFFF

#define	TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_L_LEN	        16
#define	TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_L_OFFSET	        0
#define TEE_CTL_RB_CFG_TEE_TIMER_LEVEL_L_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_H_LEN	        16
#define	TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_H_OFFSET	        0
#define TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_H_MASK    		0xFFFF

#define	TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_L_LEN	        16
#define	TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_L_OFFSET	        0
#define TEE_CTL_RB_TEE_TIMER_CURRENT_VALUE_L_MASK    		0xFFFF

#define	TEE_CTL_RB_CFG_QSPI_DIAG_EN_LEN	        1
#define	TEE_CTL_RB_CFG_QSPI_DIAG_EN_OFFSET	        0
#define TEE_CTL_RB_CFG_QSPI_DIAG_EN_MASK    		0x1

#endif // __3322_TEE_CTL_RB_REG_OFFSET_FIELD_H__
