/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_hs_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_HS_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_HS_CTL_RB_REG_OFFSET_FIELD_H__

#define	HS_CTL_RB_HS_CTL_ID_LEN	        16
#define	HS_CTL_RB_HS_CTL_ID_OFFSET	        0
#define HS_CTL_RB_HS_CTL_ID_MASK    		0xFFFF

#define	HS_CTL_RB_HS_GP_REG0_LEN	        16
#define	HS_CTL_RB_HS_GP_REG0_OFFSET	        0
#define HS_CTL_RB_HS_GP_REG0_MASK    		0xFFFF

#define	HS_CTL_RB_HS_GP_REG1_LEN	        16
#define	HS_CTL_RB_HS_GP_REG1_OFFSET	        0
#define HS_CTL_RB_HS_GP_REG1_MASK    		0xFFFF

#define	HS_CTL_RB_HS_GP_REG2_LEN	        16
#define	HS_CTL_RB_HS_GP_REG2_OFFSET	        0
#define HS_CTL_RB_HS_GP_REG2_MASK    		0xFFFF

#define	HS_CTL_RB_HS_GP_REG3_LEN	        16
#define	HS_CTL_RB_HS_GP_REG3_OFFSET	        0
#define HS_CTL_RB_HS_GP_REG3_MASK    		0xFFFF

#define	HS_CTL_RB_CFG_HS_SOFT_RST_FMC_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_FMC_N_OFFSET	        8
#define HS_CTL_RB_CFG_HS_SOFT_RST_FMC_N_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_SOFT_RST_EMMC_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_EMMC_N_OFFSET	        4
#define HS_CTL_RB_CFG_HS_SOFT_RST_EMMC_N_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_SOFT_RST_SDIO_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_SDIO_N_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SOFT_RST_SDIO_N_MASK    		0x1

#define	HS_CTL_RB_ECO_CFG_HS_VICAP_CLK_INV_EN_LEN	        1
#define	HS_CTL_RB_ECO_CFG_HS_VICAP_CLK_INV_EN_OFFSET	        12
#define HS_CTL_RB_ECO_CFG_HS_VICAP_CLK_INV_EN_MASK    		0x1000
#define	HS_CTL_RB_CFG_HS_FMC_BUS_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_FMC_BUS_CLKEN_OFFSET	        8
#define HS_CTL_RB_CFG_HS_FMC_BUS_CLKEN_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_EMMC_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_EMMC_CLKEN_OFFSET	        4
#define HS_CTL_RB_CFG_HS_EMMC_CLKEN_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_SDIO_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_SDIO_CLKEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SDIO_CLKEN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_SD_BUS_DIV_DENOM_LEN	        5
#define	HS_CTL_RB_CFG_HS_SD_BUS_DIV_DENOM_OFFSET	        4
#define HS_CTL_RB_CFG_HS_SD_BUS_DIV_DENOM_MASK    		0x1F0
#define	HS_CTL_RB_CFG_HS_SD_BUS_LOAD_DIV_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_SD_BUS_LOAD_DIV_EN_OFFSET	        1
#define HS_CTL_RB_CFG_HS_SD_BUS_LOAD_DIV_EN_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_SD_BUS_DIV_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_SD_BUS_DIV_EN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SD_BUS_DIV_EN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_SOFT_RST_CAN_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_CAN_N_OFFSET	        4
#define HS_CTL_RB_CFG_HS_SOFT_RST_CAN_N_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_CAN_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_CAN_CLKEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_CAN_CLKEN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_FMC_DIV_NUM_LEN	        3
#define	HS_CTL_RB_CFG_HS_FMC_DIV_NUM_OFFSET	        4
#define HS_CTL_RB_CFG_HS_FMC_DIV_NUM_MASK    		0x70
#define	HS_CTL_RB_CFG_HS_FMC_LOAD_DIV_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_FMC_LOAD_DIV_EN_OFFSET	        1
#define HS_CTL_RB_CFG_HS_FMC_LOAD_DIV_EN_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_FMC_DIV_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_FMC_DIV_CLKEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_FMC_DIV_CLKEN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_SOFT_RST_FMC_POR_PULSE_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_FMC_POR_PULSE_N_OFFSET	        8
#define HS_CTL_RB_CFG_HS_SOFT_RST_FMC_POR_PULSE_N_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_FMC_SOFT_RST_PULSE_WIDTH_LEN	        8
#define	HS_CTL_RB_CFG_HS_FMC_SOFT_RST_PULSE_WIDTH_OFFSET	        0
#define HS_CTL_RB_CFG_HS_FMC_SOFT_RST_PULSE_WIDTH_MASK    		0xFF

#define	HS_CTL_RB_CFG_HS_SUB_SP_RAM_POWER_MODE_LEN	        1
#define	HS_CTL_RB_CFG_HS_SUB_SP_RAM_POWER_MODE_OFFSET	        4
#define HS_CTL_RB_CFG_HS_SUB_SP_RAM_POWER_MODE_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_SUB_TP_RAM_POWER_MODE_LEN	        1
#define	HS_CTL_RB_CFG_HS_SUB_TP_RAM_POWER_MODE_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SUB_TP_RAM_POWER_MODE_MASK    		0x1

#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M4_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M4_OFFSET	        10
#define HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M4_MASK    		0xC00
#define	HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S2_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S2_OFFSET	        8
#define HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S2_MASK    		0x300
#define	HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S1_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S1_OFFSET	        6
#define HS_CTL_RB_SDIO_M_AXI_SLV_PRIORITY_S1_MASK    		0xC0
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M3_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M3_OFFSET	        4
#define HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M3_MASK    		0x30
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M2_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M2_OFFSET	        2
#define HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M2_MASK    		0xC
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M1_LEN	        2
#define	HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M1_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_MST_PRIORITY_M1_MASK    		0x3

#define	HS_CTL_RB_SDIO_USB2AXI_X2X_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_AUTO_CG_BYPASS_OFFSET	        10
#define HS_CTL_RB_SDIO_USB2AXI_X2X_AUTO_CG_BYPASS_MASK    		0x400
#define	HS_CTL_RB_SDIO_SDIO2USB_H2H_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2USB_H2H_AUTO_CG_BYPASS_OFFSET	        9
#define HS_CTL_RB_SDIO_SDIO2USB_H2H_AUTO_CG_BYPASS_MASK    		0x200
#define	HS_CTL_RB_SDIO_CFG_APB_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_CFG_APB_AUTO_CG_BYPASS_OFFSET	        8
#define HS_CTL_RB_SDIO_CFG_APB_AUTO_CG_BYPASS_MASK    		0x100
#define	HS_CTL_RB_SDIO_CFG_AHB_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_CFG_AHB_AUTO_CG_BYPASS_OFFSET	        7
#define HS_CTL_RB_SDIO_CFG_AHB_AUTO_CG_BYPASS_MASK    		0x80
#define	HS_CTL_RB_SDIO_AHBCFG_H2H_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_AHBCFG_H2H_AUTO_CG_BYPASS_OFFSET	        6
#define HS_CTL_RB_SDIO_AHBCFG_H2H_AUTO_CG_BYPASS_MASK    		0x40
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_AUTO_CG_BYPASS_OFFSET	        5
#define HS_CTL_RB_SDIO_SDIO2AXI_X2X_AUTO_CG_BYPASS_MASK    		0x20
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_AUTO_CG_BYPASS_OFFSET	        4
#define HS_CTL_RB_SDIO_EMMC2AXI_X2X_AUTO_CG_BYPASS_MASK    		0x10
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_AUTO_CG_BYPASS_OFFSET	        3
#define HS_CTL_RB_SDIO_SDIO2MCU_X2H_AUTO_CG_BYPASS_MASK    		0x8
#define	HS_CTL_RB_SDIO_FMC_A2X_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_FMC_A2X_AUTO_CG_BYPASS_OFFSET	        2
#define HS_CTL_RB_SDIO_FMC_A2X_AUTO_CG_BYPASS_MASK    		0x4
#define	HS_CTL_RB_SDIO_M_AXI_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AUTO_CG_BYPASS_OFFSET	        1
#define HS_CTL_RB_SDIO_M_AXI_AUTO_CG_BYPASS_MASK    		0x2
#define	HS_CTL_RB_SDIO_M_AXI_GLB_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_GLB_CG_BYPASS_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_GLB_CG_BYPASS_MASK    		0x1

#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_RAW_STATUS_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_RAW_STATUS_OFFSET	        5
#define HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_RAW_STATUS_MASK    		0x20
#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_RAW_STATUS_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_RAW_STATUS_OFFSET	        4
#define HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_RAW_STATUS_MASK    		0x10
#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_CLR_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_CLR_OFFSET	        3
#define HS_CTL_RB_SDIO_M_AXI_AR_ERR_INT_CLR_MASK    		0x8
#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_CLR_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_CLR_OFFSET	        2
#define HS_CTL_RB_SDIO_M_AXI_AW_ERR_INT_CLR_MASK    		0x4
#define	HS_CTL_RB_SDIO_M_AXI_ERR_MINITOR_ENABLE_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_ERR_MINITOR_ENABLE_OFFSET	        1
#define HS_CTL_RB_SDIO_M_AXI_ERR_MINITOR_ENABLE_MASK    		0x2
#define	HS_CTL_RB_SDIO_M_AXI_GLB_AXI_MINITOR_ENABLE_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_GLB_AXI_MINITOR_ENABLE_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_GLB_AXI_MINITOR_ENABLE_MASK    		0x1

#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_STS_VLD_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AW_ERR_STS_VLD_OFFSET	        15
#define HS_CTL_RB_SDIO_M_AXI_AW_ERR_STS_VLD_MASK    		0x8000
#define	HS_CTL_RB_SDIO_M_AXI_AWID_ERR_STS_LEN	        7
#define	HS_CTL_RB_SDIO_M_AXI_AWID_ERR_STS_OFFSET	        8
#define HS_CTL_RB_SDIO_M_AXI_AWID_ERR_STS_MASK    		0x7F00
#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_STS_VLD_LEN	        1
#define	HS_CTL_RB_SDIO_M_AXI_AR_ERR_STS_VLD_OFFSET	        7
#define HS_CTL_RB_SDIO_M_AXI_AR_ERR_STS_VLD_MASK    		0x80
#define	HS_CTL_RB_SDIO_M_AXI_ARID_ERR_STS_LEN	        7
#define	HS_CTL_RB_SDIO_M_AXI_ARID_ERR_STS_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_ARID_ERR_STS_MASK    		0x7F

#define	HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_L_LEN	        16
#define	HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_L_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_L_MASK    		0xFFFF

#define	HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_H_LEN	        16
#define	HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_H_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_AWADDR_ERR_STS_H_MASK    		0xFFFF

#define	HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_L_LEN	        16
#define	HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_L_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_L_MASK    		0xFFFF

#define	HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_H_LEN	        16
#define	HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_H_OFFSET	        0
#define HS_CTL_RB_SDIO_M_AXI_ARADDR_ERR_STS_H_MASK    		0xFFFF

#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CACTIVE_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CACTIVE_OFFSET	        8
#define HS_CTL_RB_SDIO_SDIO2AXI_X2X_CACTIVE_MASK    		0x100
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSACK_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSACK_OFFSET	        4
#define HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSACK_MASK    		0x10
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSREQ_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSREQ_OFFSET	        0
#define HS_CTL_RB_SDIO_SDIO2AXI_X2X_CSYSREQ_MASK    		0x1

#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CACTIVE_LEN	        1
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CACTIVE_OFFSET	        8
#define HS_CTL_RB_SDIO_EMMC2AXI_X2X_CACTIVE_MASK    		0x100
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSACK_LEN	        1
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSACK_OFFSET	        4
#define HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSACK_MASK    		0x10
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSREQ_LEN	        1
#define	HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSREQ_OFFSET	        0
#define HS_CTL_RB_SDIO_EMMC2AXI_X2X_CSYSREQ_MASK    		0x1

#define	HS_CTL_RB_SDIO_FMC_A2X_CACTIVE_LEN	        1
#define	HS_CTL_RB_SDIO_FMC_A2X_CACTIVE_OFFSET	        8
#define HS_CTL_RB_SDIO_FMC_A2X_CACTIVE_MASK    		0x100
#define	HS_CTL_RB_SDIO_FMC_A2X_CSYSACK_LEN	        1
#define	HS_CTL_RB_SDIO_FMC_A2X_CSYSACK_OFFSET	        4
#define HS_CTL_RB_SDIO_FMC_A2X_CSYSACK_MASK    		0x10
#define	HS_CTL_RB_SDIO_FMC_A2X_CSYSREQ_LEN	        1
#define	HS_CTL_RB_SDIO_FMC_A2X_CSYSREQ_OFFSET	        0
#define HS_CTL_RB_SDIO_FMC_A2X_CSYSREQ_MASK    		0x1

#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CACTIVE_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CACTIVE_OFFSET	        8
#define HS_CTL_RB_SDIO_SDIO2MCU_X2H_CACTIVE_MASK    		0x100
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSACK_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSACK_OFFSET	        4
#define HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSACK_MASK    		0x10
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSREQ_LEN	        1
#define	HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSREQ_OFFSET	        0
#define HS_CTL_RB_SDIO_SDIO2MCU_X2H_CSYSREQ_MASK    		0x1

#define	HS_CTL_RB_SDIO_CFG_AHB_HREADY_MUX_LEN	        1
#define	HS_CTL_RB_SDIO_CFG_AHB_HREADY_MUX_OFFSET	        0
#define HS_CTL_RB_SDIO_CFG_AHB_HREADY_MUX_MASK    		0x1

#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CACTIVE_LEN	        1
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CACTIVE_OFFSET	        8
#define HS_CTL_RB_SDIO_USB2AXI_X2X_CACTIVE_MASK    		0x100
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSACK_LEN	        1
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSACK_OFFSET	        4
#define HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSACK_MASK    		0x10
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSREQ_LEN	        1
#define	HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSREQ_OFFSET	        0
#define HS_CTL_RB_SDIO_USB2AXI_X2X_CSYSREQ_MASK    		0x1

#define	HS_CTL_RB_SDIO_TUNING_COARSE_MODE_LEN	        3
#define	HS_CTL_RB_SDIO_TUNING_COARSE_MODE_OFFSET	        12
#define HS_CTL_RB_SDIO_TUNING_COARSE_MODE_MASK    		0x7000
#define	HS_CTL_RB_SDIO_CCLK_ORI_DIV_NUM_LEN	        8
#define	HS_CTL_RB_SDIO_CCLK_ORI_DIV_NUM_OFFSET	        4
#define HS_CTL_RB_SDIO_CCLK_ORI_DIV_NUM_MASK    		0xFF0
#define	HS_CTL_RB_SDIO_CCLK_ORI_LOAD_DIV_EN_LEN	        1
#define	HS_CTL_RB_SDIO_CCLK_ORI_LOAD_DIV_EN_OFFSET	        1
#define HS_CTL_RB_SDIO_CCLK_ORI_LOAD_DIV_EN_MASK    		0x2
#define	HS_CTL_RB_SDIO_CCLK_ORI_DIV_EN_LEN	        1
#define	HS_CTL_RB_SDIO_CCLK_ORI_DIV_EN_OFFSET	        0
#define HS_CTL_RB_SDIO_CCLK_ORI_DIV_EN_MASK    		0x1

#define	HS_CTL_RB_SDIO_HOST_RX_CLK_INV_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_HOST_RX_CLK_INV_SEL_OFFSET	        13
#define HS_CTL_RB_SDIO_HOST_RX_CLK_INV_SEL_MASK    		0x2000
#define	HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_LEN	        7
#define	HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_OFFSET	        4
#define HS_CTL_RB_SDIO_TUNING_CCLK_RX_SEL_MASK    		0x7F0
#define	HS_CTL_RB_SDIO_SAMPLE_CCLK_RX_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_SAMPLE_CCLK_RX_SEL_OFFSET	        0
#define HS_CTL_RB_SDIO_SAMPLE_CCLK_RX_SEL_MASK    		0x1

#define	HS_CTL_RB_SDIO_HOST_CARD_CLK_INV_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_HOST_CARD_CLK_INV_SEL_OFFSET	        13
#define HS_CTL_RB_SDIO_HOST_CARD_CLK_INV_SEL_MASK    		0x2000
#define	HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_LEN	        3
#define	HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_OFFSET	        4
#define HS_CTL_RB_SDIO_TUNING_CARD_CLK_SEL_MASK    		0x70
#define	HS_CTL_RB_SDIO_SAMPLE_CARD_CLK_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_SAMPLE_CARD_CLK_SEL_OFFSET	        0
#define HS_CTL_RB_SDIO_SAMPLE_CARD_CLK_SEL_MASK    		0x1

#define	HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_LEN	        5
#define	HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_OFFSET	        4
#define HS_CTL_RB_SDIO_TUNING_CLK_DS_SEL_MASK    		0x1F0
#define	HS_CTL_RB_SDIO_SAMPLE_CLK_DS_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_SAMPLE_CLK_DS_SEL_OFFSET	        0
#define HS_CTL_RB_SDIO_SAMPLE_CLK_DS_SEL_MASK    		0x1

#define	HS_CTL_RB_SDIO_DFX_TZPC_LEN	        1
#define	HS_CTL_RB_SDIO_DFX_TZPC_OFFSET	        0
#define HS_CTL_RB_SDIO_DFX_TZPC_MASK    		0x1

#define	HS_CTL_RB_SDIO_TUNING_BCLK_90_SEL_LEN	        1
#define	HS_CTL_RB_SDIO_TUNING_BCLK_90_SEL_OFFSET	        1
#define HS_CTL_RB_SDIO_TUNING_BCLK_90_SEL_MASK    		0x2
#define	HS_CTL_RB_SDIO_CLK2CARD_ON_DELAY_EN_LEN	        1
#define	HS_CTL_RB_SDIO_CLK2CARD_ON_DELAY_EN_OFFSET	        0
#define HS_CTL_RB_SDIO_CLK2CARD_ON_DELAY_EN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_LEN	        3
#define	HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_OFFSET	        4
#define HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_MASK    		0x70
#define	HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_SEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_SEL_OFFSET	        0
#define HS_CTL_RB_CFG_HS_EMMC_CLK2CARD_ON_DELAY_SW_SEL_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_LEN	        3
#define	HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_OFFSET	        4
#define HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_MASK    		0x70
#define	HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_SEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_SEL_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SDIO_CLK2CARD_ON_DELAY_SW_SEL_MASK    		0x1

#define	HS_CTL_RB_EMMC_TUNING_COARSE_MODE_LEN	        3
#define	HS_CTL_RB_EMMC_TUNING_COARSE_MODE_OFFSET	        12
#define HS_CTL_RB_EMMC_TUNING_COARSE_MODE_MASK    		0x7000
#define	HS_CTL_RB_EMMC_CCLK_ORI_DIV_NUM_LEN	        8
#define	HS_CTL_RB_EMMC_CCLK_ORI_DIV_NUM_OFFSET	        4
#define HS_CTL_RB_EMMC_CCLK_ORI_DIV_NUM_MASK    		0xFF0
#define	HS_CTL_RB_EMMC_CCLK_ORI_LOAD_DIV_EN_LEN	        1
#define	HS_CTL_RB_EMMC_CCLK_ORI_LOAD_DIV_EN_OFFSET	        1
#define HS_CTL_RB_EMMC_CCLK_ORI_LOAD_DIV_EN_MASK    		0x2
#define	HS_CTL_RB_EMMC_CCLK_ORI_DIV_EN_LEN	        1
#define	HS_CTL_RB_EMMC_CCLK_ORI_DIV_EN_OFFSET	        0
#define HS_CTL_RB_EMMC_CCLK_ORI_DIV_EN_MASK    		0x1

#define	HS_CTL_RB_EMMC_HOST_RX_CLK_INV_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_HOST_RX_CLK_INV_SEL_OFFSET	        13
#define HS_CTL_RB_EMMC_HOST_RX_CLK_INV_SEL_MASK    		0x2000
#define	HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_LEN	        7
#define	HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_OFFSET	        4
#define HS_CTL_RB_EMMC_TUNING_CCLK_RX_SEL_MASK    		0x7F0
#define	HS_CTL_RB_EMMC_SAMPLE_CCLK_RX_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_SAMPLE_CCLK_RX_SEL_OFFSET	        0
#define HS_CTL_RB_EMMC_SAMPLE_CCLK_RX_SEL_MASK    		0x1

#define	HS_CTL_RB_EMMC_HOST_CARD_CLK_INV_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_HOST_CARD_CLK_INV_SEL_OFFSET	        13
#define HS_CTL_RB_EMMC_HOST_CARD_CLK_INV_SEL_MASK    		0x2000
#define	HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_LEN	        3
#define	HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_OFFSET	        4
#define HS_CTL_RB_EMMC_TUNING_CARD_CLK_SEL_MASK    		0x70
#define	HS_CTL_RB_EMMC_SAMPLE_CARD_CLK_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_SAMPLE_CARD_CLK_SEL_OFFSET	        0
#define HS_CTL_RB_EMMC_SAMPLE_CARD_CLK_SEL_MASK    		0x1

#define	HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_UPDATA_LEN	        1
#define	HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_UPDATA_OFFSET	        12
#define HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_UPDATA_MASK    		0x1000
#define	HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_LEN	        5
#define	HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_OFFSET	        4
#define HS_CTL_RB_EMMC_TUNING_CLK_DS_SEL_MASK    		0x1F0
#define	HS_CTL_RB_EMMC_SAMPLE_CLK_DS_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_SAMPLE_CLK_DS_SEL_OFFSET	        0
#define HS_CTL_RB_EMMC_SAMPLE_CLK_DS_SEL_MASK    		0x1

#define	HS_CTL_RB_EMMC_DFX_TZPC_LEN	        1
#define	HS_CTL_RB_EMMC_DFX_TZPC_OFFSET	        0
#define HS_CTL_RB_EMMC_DFX_TZPC_MASK    		0x1

#define	HS_CTL_RB_EMMC_TUNING_BCLK_90_SEL_LEN	        1
#define	HS_CTL_RB_EMMC_TUNING_BCLK_90_SEL_OFFSET	        1
#define HS_CTL_RB_EMMC_TUNING_BCLK_90_SEL_MASK    		0x2
#define	HS_CTL_RB_EMMC_CLK2CARD_ON_DELAY_EN_LEN	        1
#define	HS_CTL_RB_EMMC_CLK2CARD_ON_DELAY_EN_OFFSET	        0
#define HS_CTL_RB_EMMC_CLK2CARD_ON_DELAY_EN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_FMC_WDT_RSTEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_FMC_WDT_RSTEN_OFFSET	        8
#define HS_CTL_RB_CFG_HS_FMC_WDT_RSTEN_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_EMMC_WDT_RSTEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_EMMC_WDT_RSTEN_OFFSET	        4
#define HS_CTL_RB_CFG_HS_EMMC_WDT_RSTEN_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_SDIO_WDT_RSTEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_SDIO_WDT_RSTEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SDIO_WDT_RSTEN_MASK    		0x1

#define	HS_CTL_RB_USB_APB_CUR_STS_LEN	        1
#define	HS_CTL_RB_USB_APB_CUR_STS_OFFSET	        8
#define HS_CTL_RB_USB_APB_CUR_STS_MASK    		0x100
#define	HS_CTL_RB_EMMC_CUR_STS_LEN	        1
#define	HS_CTL_RB_EMMC_CUR_STS_OFFSET	        4
#define HS_CTL_RB_EMMC_CUR_STS_MASK    		0x10
#define	HS_CTL_RB_SDIO_CUR_STS_LEN	        1
#define	HS_CTL_RB_SDIO_CUR_STS_OFFSET	        0
#define HS_CTL_RB_SDIO_CUR_STS_MASK    		0x1

#define	HS_CTL_RB_VBUS_VALID_SEL_LEN	        1
#define	HS_CTL_RB_VBUS_VALID_SEL_OFFSET	        1
#define HS_CTL_RB_VBUS_VALID_SEL_MASK    		0x2
#define	HS_CTL_RB_USBC_VBUSVALID_LEN	        1
#define	HS_CTL_RB_USBC_VBUSVALID_OFFSET	        0
#define HS_CTL_RB_USBC_VBUSVALID_MASK    		0x1

#define	HS_CTL_RB_VBUS_IN_LEN	        1
#define	HS_CTL_RB_VBUS_IN_OFFSET	        0
#define HS_CTL_RB_VBUS_IN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_POWER_MODE_LEN	        3
#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_POWER_MODE_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB_SP_RAM_POWER_MODE_MASK    		0x7

#define	HS_CTL_RB_CFG_USB_APB_PCLK_EN_LEN	        1
#define	HS_CTL_RB_CFG_USB_APB_PCLK_EN_OFFSET	        0
#define HS_CTL_RB_CFG_USB_APB_PCLK_EN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_USBPHY_APB_AUTO_CG_BYPASS_LEN	        1
#define	HS_CTL_RB_CFG_HS_USBPHY_APB_AUTO_CG_BYPASS_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USBPHY_APB_AUTO_CG_BYPASS_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_LOAD_DIV_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_LOAD_DIV_EN_OFFSET	        5
#define HS_CTL_RB_CFG_HS_USBPHY_BUS_LOAD_DIV_EN_MASK    		0x20
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_DENOM_LEN	        4
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_DENOM_OFFSET	        1
#define HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_DENOM_MASK    		0x1E
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_EN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USBPHY_BUS_DIV_EN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_H_LEN	        16
#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_H_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_H_MASK    		0xFFFF

#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_MH_LEN	        16
#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_MH_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_MH_MASK    		0xFFFF

#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_ML_LEN	        16
#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_ML_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_ML_MASK    		0xFFFF

#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_L_LEN	        16
#define	HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_L_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB_SP_RAM_TMOD_L_MASK    		0xFFFF

#define	HS_CTL_RB_USB_CTRL_CFG_L_LEN	        16
#define	HS_CTL_RB_USB_CTRL_CFG_L_OFFSET	        0
#define HS_CTL_RB_USB_CTRL_CFG_L_MASK    		0xFFFF

#define	HS_CTL_RB_USB_CTRL_CFG_H_LEN	        16
#define	HS_CTL_RB_USB_CTRL_CFG_H_OFFSET	        0
#define HS_CTL_RB_USB_CTRL_CFG_H_MASK    		0xFFFF

#define	HS_CTL_RB_USB_CTRL_DBG_L_LEN	        16
#define	HS_CTL_RB_USB_CTRL_DBG_L_OFFSET	        0
#define HS_CTL_RB_USB_CTRL_DBG_L_MASK    		0xFFFF

#define	HS_CTL_RB_USB_CTRL_DBG_H_LEN	        16
#define	HS_CTL_RB_USB_CTRL_DBG_H_OFFSET	        0
#define HS_CTL_RB_USB_CTRL_DBG_H_MASK    		0xFFFF

#define	HS_CTL_RB_CFG_HS_USB2_FREECLK_CKSEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_USB2_FREECLK_CKSEL_OFFSET	        12
#define HS_CTL_RB_CFG_HS_USB2_FREECLK_CKSEL_MASK    		0x1000
#define	HS_CTL_RB_CFG_HS_USB2_UTMI_CKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USB2_UTMI_CKEN_OFFSET	        8
#define HS_CTL_RB_CFG_HS_USB2_UTMI_CKEN_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_USB2_REF_CKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USB2_REF_CKEN_OFFSET	        5
#define HS_CTL_RB_CFG_HS_USB2_REF_CKEN_MASK    		0x20
#define	HS_CTL_RB_CFG_HS_USB2_BUS_CKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USB2_BUS_CKEN_OFFSET	        4
#define HS_CTL_RB_CFG_HS_USB2_BUS_CKEN_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_USB2_RESET_REQ_LEN	        1
#define	HS_CTL_RB_CFG_HS_USB2_RESET_REQ_OFFSET	        0
#define HS_CTL_RB_CFG_HS_USB2_RESET_REQ_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_USBPHY_BUS_CLKEN_OFFSET	        5
#define HS_CTL_RB_CFG_HS_USBPHY_BUS_CLKEN_MASK    		0x20
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_UTMI_RST_REQ_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_UTMI_RST_REQ_OFFSET	        3
#define HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_UTMI_RST_REQ_MASK    		0x8
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_PRST_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_PRST_N_OFFSET	        2
#define HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_PRST_N_MASK    		0x4
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_POR_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_POR_N_OFFSET	        1
#define HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_POR_N_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_SYS_COM_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_SYS_COM_N_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SOFT_RST_USBPHY_SYS_COM_N_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_SEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_SEL_OFFSET	        12
#define HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_SEL_MASK    		0x1000
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_DATA_DIAG_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_DATA_DIAG_EN_OFFSET	        11
#define HS_CTL_RB_CFG_HS_DIAG_SDIO_DATA_DIAG_EN_MASK    		0x800
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CARD_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CARD_CLKEN_OFFSET	        10
#define HS_CTL_RB_CFG_HS_DIAG_SDIO_CARD_CLKEN_MASK    		0x400
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_TX_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_TX_CLKEN_OFFSET	        9
#define HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_TX_CLKEN_MASK    		0x200
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_RX_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_RX_CLKEN_OFFSET	        8
#define HS_CTL_RB_CFG_HS_DIAG_SDIO_CCLK_RX_CLKEN_MASK    		0x100
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_DATA_DIAG_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_DATA_DIAG_EN_OFFSET	        7
#define HS_CTL_RB_CFG_HS_DIAG_EMMC_DATA_DIAG_EN_MASK    		0x80
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_DS_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_DS_CLKEN_OFFSET	        6
#define HS_CTL_RB_CFG_HS_DIAG_EMMC_DS_CLKEN_MASK    		0x40
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CARD_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CARD_CLKEN_OFFSET	        5
#define HS_CTL_RB_CFG_HS_DIAG_EMMC_CARD_CLKEN_MASK    		0x20
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_TX_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_TX_CLKEN_OFFSET	        4
#define HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_TX_CLKEN_MASK    		0x10
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_RX_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_RX_CLKEN_OFFSET	        3
#define HS_CTL_RB_CFG_HS_DIAG_EMMC_CCLK_RX_CLKEN_MASK    		0x8
#define	HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_EN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_EN_OFFSET	        2
#define HS_CTL_RB_CFG_HS_DIAG_USB_DIAG_DATA_EN_MASK    		0x4
#define	HS_CTL_RB_CFG_HS_DIAG_USB_UTMI_CLK_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_USB_UTMI_CLK_CLKEN_OFFSET	        1
#define HS_CTL_RB_CFG_HS_DIAG_USB_UTMI_CLK_CLKEN_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_DIAG_USB_60M_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_DIAG_USB_60M_CLKEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_DIAG_USB_60M_CLKEN_MASK    		0x1

#define	HS_CTL_RB_HS_PERP_RFSHD_SP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RFSHD_SP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RFSHD_SP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_HS_PERP_RFSHS_SP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RFSHS_SP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RFSHS_SP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_HS_PERP_RASHD_SP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RASHD_SP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RASHD_SP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_HS_PERP_RASHS_SP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RASHS_SP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RASHS_SP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_HS_PERP_RFTHD_TP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RFTHD_TP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RFTHD_TP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_HS_PERP_RATHUD_TP_RAM_TMOD_LEN	        16
#define	HS_CTL_RB_HS_PERP_RATHUD_TP_RAM_TMOD_OFFSET	        0
#define HS_CTL_RB_HS_PERP_RATHUD_TP_RAM_TMOD_MASK    		0xFFFF

#define	HS_CTL_RB_CAN_DIAG_MUX_LEN	        5
#define	HS_CTL_RB_CAN_DIAG_MUX_OFFSET	        11
#define HS_CTL_RB_CAN_DIAG_MUX_MASK    		0xF800
#define	HS_CTL_RB_CAN_ARB_HW_SEL_LEN	        1
#define	HS_CTL_RB_CAN_ARB_HW_SEL_OFFSET	        10
#define HS_CTL_RB_CAN_ARB_HW_SEL_MASK    		0x400
#define	HS_CTL_RB_CAN_ARB_HW_EN_LEN	        1
#define	HS_CTL_RB_CAN_ARB_HW_EN_OFFSET	        9
#define HS_CTL_RB_CAN_ARB_HW_EN_MASK    		0x200
#define	HS_CTL_RB_M_CAN_FIX_A_LEN	        1
#define	HS_CTL_RB_M_CAN_FIX_A_OFFSET	        8
#define HS_CTL_RB_M_CAN_FIX_A_MASK    		0x100
#define	HS_CTL_RB_M_CAN_FIX_B_LEN	        1
#define	HS_CTL_RB_M_CAN_FIX_B_OFFSET	        7
#define HS_CTL_RB_M_CAN_FIX_B_MASK    		0x80
#define	HS_CTL_RB_M_CAN_FIX_EN_LEN	        1
#define	HS_CTL_RB_M_CAN_FIX_EN_OFFSET	        6
#define HS_CTL_RB_M_CAN_FIX_EN_MASK    		0x40
#define	HS_CTL_RB_M_CAN_CLKSTOP_ACK_LEN	        1
#define	HS_CTL_RB_M_CAN_CLKSTOP_ACK_OFFSET	        5
#define HS_CTL_RB_M_CAN_CLKSTOP_ACK_MASK    		0x20
#define	HS_CTL_RB_M_CAN_CLKSTOP_REQ_LEN	        1
#define	HS_CTL_RB_M_CAN_CLKSTOP_REQ_OFFSET	        4
#define HS_CTL_RB_M_CAN_CLKSTOP_REQ_MASK    		0x10
#define	HS_CTL_RB_M_CAN_CLK_EN_HW_LEN	        1
#define	HS_CTL_RB_M_CAN_CLK_EN_HW_OFFSET	        3
#define HS_CTL_RB_M_CAN_CLK_EN_HW_MASK    		0x8
#define	HS_CTL_RB_M_CAN_DIS_MORD_LEN	        1
#define	HS_CTL_RB_M_CAN_DIS_MORD_OFFSET	        2
#define HS_CTL_RB_M_CAN_DIS_MORD_MASK    		0x4

#define	HS_CTL_RB_M_CAN_IR_H_LEN	        16
#define	HS_CTL_RB_M_CAN_IR_H_OFFSET	        0
#define HS_CTL_RB_M_CAN_IR_H_MASK    		0xFFFF

#define	HS_CTL_RB_M_CAN_IR_L_LEN	        16
#define	HS_CTL_RB_M_CAN_IR_L_OFFSET	        0
#define HS_CTL_RB_M_CAN_IR_L_MASK    		0xFFFF

#define	HS_CTL_RB_M_CAN_TXBRP_H_LEN	        16
#define	HS_CTL_RB_M_CAN_TXBRP_H_OFFSET	        0
#define HS_CTL_RB_M_CAN_TXBRP_H_MASK    		0xFFFF

#define	HS_CTL_RB_M_CAN_TXBRP_L_LEN	        16
#define	HS_CTL_RB_M_CAN_TXBRP_L_OFFSET	        0
#define HS_CTL_RB_M_CAN_TXBRP_L_MASK    		0xFFFF

#define	HS_CTL_RB_M_CAN_RXFD_LEN	        1
#define	HS_CTL_RB_M_CAN_RXFD_OFFSET	        3
#define HS_CTL_RB_M_CAN_RXFD_MASK    		0x8
#define	HS_CTL_RB_M_CAN_TXFD_LEN	        1
#define	HS_CTL_RB_M_CAN_TXFD_OFFSET	        2
#define HS_CTL_RB_M_CAN_TXFD_MASK    		0x4
#define	HS_CTL_RB_M_CAN_ACT_TX_LEN	        1
#define	HS_CTL_RB_M_CAN_ACT_TX_OFFSET	        1
#define HS_CTL_RB_M_CAN_ACT_TX_MASK    		0x2
#define	HS_CTL_RB_M_CAN_CCE_LEN	        1
#define	HS_CTL_RB_M_CAN_CCE_OFFSET	        0
#define HS_CTL_RB_M_CAN_CCE_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_VICAP_PAD_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_VICAP_PAD_CLKEN_OFFSET	        2
#define HS_CTL_RB_CFG_HS_VICAP_PAD_CLKEN_MASK    		0x4
#define	HS_CTL_RB_CFG_HS_VICAP_BUS_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_VICAP_BUS_CLKEN_OFFSET	        1
#define HS_CTL_RB_CFG_HS_VICAP_BUS_CLKEN_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_VICAP_CLKEN_LEN	        1
#define	HS_CTL_RB_CFG_HS_VICAP_CLKEN_OFFSET	        0
#define HS_CTL_RB_CFG_HS_VICAP_CLKEN_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_VICAP_CLK_MUX_SEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_VICAP_CLK_MUX_SEL_OFFSET	        0
#define HS_CTL_RB_CFG_HS_VICAP_CLK_MUX_SEL_MASK    		0x1

#define	HS_CTL_RB_VICAP_SOFTRST_STATE_LEN	        1
#define	HS_CTL_RB_VICAP_SOFTRST_STATE_OFFSET	        3
#define HS_CTL_RB_VICAP_SOFTRST_STATE_MASK    		0x8
#define	HS_CTL_RB_CFG_HS_VICAP_SRST_REQ_LEN	        1
#define	HS_CTL_RB_CFG_HS_VICAP_SRST_REQ_OFFSET	        2
#define HS_CTL_RB_CFG_HS_VICAP_SRST_REQ_MASK    		0x4
#define	HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_VI_0_REQ_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_VI_0_REQ_OFFSET	        1
#define HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_VI_0_REQ_MASK    		0x2
#define	HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_SYS_COM_N_LEN	        1
#define	HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_SYS_COM_N_OFFSET	        0
#define HS_CTL_RB_CFG_HS_SOFT_RST_VICAP_SYS_COM_N_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_AXI_2TO1_MUX_SEL_LEN	        1
#define	HS_CTL_RB_CFG_HS_AXI_2TO1_MUX_SEL_OFFSET	        0
#define HS_CTL_RB_CFG_HS_AXI_2TO1_MUX_SEL_MASK    		0x1

#define	HS_CTL_RB_CFG_HS_VICAP_TP_RAM_POWER_MODE_LEN	        3
#define	HS_CTL_RB_CFG_HS_VICAP_TP_RAM_POWER_MODE_OFFSET	        4
#define HS_CTL_RB_CFG_HS_VICAP_TP_RAM_POWER_MODE_MASK    		0x70
#define	HS_CTL_RB_CFG_HS_VICAP_SP_RAM_POWER_MODE_LEN	        3
#define	HS_CTL_RB_CFG_HS_VICAP_SP_RAM_POWER_MODE_OFFSET	        0
#define HS_CTL_RB_CFG_HS_VICAP_SP_RAM_POWER_MODE_MASK    		0x7

#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_0_LEN	        16
#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_0_OFFSET	        0
#define HS_CTL_RB_VICAP_SYS_TICK_VALUE_0_MASK    		0xFFFF

#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_1_LEN	        16
#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_1_OFFSET	        0
#define HS_CTL_RB_VICAP_SYS_TICK_VALUE_1_MASK    		0xFFFF

#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_2_LEN	        16
#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_2_OFFSET	        0
#define HS_CTL_RB_VICAP_SYS_TICK_VALUE_2_MASK    		0xFFFF

#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_3_LEN	        16
#define	HS_CTL_RB_VICAP_SYS_TICK_VALUE_3_OFFSET	        0
#define HS_CTL_RB_VICAP_SYS_TICK_VALUE_3_MASK    		0xFFFF

#endif // __3322_HS_CTL_RB_REG_OFFSET_FIELD_H__
