/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_glb_ctl_m_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_GLB_CTL_M_RB_REG_OFFSET_FIELD_H__
#define __3322_GLB_CTL_M_RB_REG_OFFSET_FIELD_H__

#define	GLB_CTL_M_RB_GLB_CTL_M_ID_LEN	        16
#define	GLB_CTL_M_RB_GLB_CTL_M_ID_OFFSET	        0
#define GLB_CTL_M_RB_GLB_CTL_M_ID_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_M_PC_L_LEN	        16
#define	GLB_CTL_M_RB_CFG_M_PC_L_OFFSET	        0
#define GLB_CTL_M_RB_CFG_M_PC_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_M_PC_H_LEN	        16
#define	GLB_CTL_M_RB_CFG_M_PC_H_OFFSET	        0
#define GLB_CTL_M_RB_CFG_M_PC_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_CTL_CHIP_NAME_LEN	        16
#define	GLB_CTL_M_RB_GLB_CTL_CHIP_NAME_OFFSET	        0
#define GLB_CTL_M_RB_GLB_CTL_CHIP_NAME_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_GP_M_REG0_LEN	        16
#define	GLB_CTL_M_RB_GLB_GP_M_REG0_OFFSET	        0
#define GLB_CTL_M_RB_GLB_GP_M_REG0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_GP_M_REG1_LEN	        16
#define	GLB_CTL_M_RB_GLB_GP_M_REG1_OFFSET	        0
#define GLB_CTL_M_RB_GLB_GP_M_REG1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_GP_M_REG2_LEN	        16
#define	GLB_CTL_M_RB_GLB_GP_M_REG2_OFFSET	        0
#define GLB_CTL_M_RB_GLB_GP_M_REG2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_GP_M_REG3_LEN	        16
#define	GLB_CTL_M_RB_GLB_GP_M_REG3_OFFSET	        0
#define GLB_CTL_M_RB_GLB_GP_M_REG3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_B_SYS_RST_STS_LEN	        16
#define	GLB_CTL_M_RB_B_SYS_RST_STS_OFFSET	        0
#define GLB_CTL_M_RB_B_SYS_RST_STS_MASK    		0xFFFF

#define	GLB_CTL_M_RB_M_SYS_RST_STS_LEN	        16
#define	GLB_CTL_M_RB_M_SYS_RST_STS_OFFSET	        0
#define GLB_CTL_M_RB_M_SYS_RST_STS_MASK    		0xFFFF

#define	GLB_CTL_M_RB_D_SYS_RST_STS_LEN	        16
#define	GLB_CTL_M_RB_D_SYS_RST_STS_OFFSET	        0
#define GLB_CTL_M_RB_D_SYS_RST_STS_MASK    		0xFFFF

#define	GLB_CTL_M_RB_B_CORE_DOUBLE_EXCEPT_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_B_CORE_DOUBLE_EXCEPT_STICK_CLR_OFFSET	        12
#define GLB_CTL_M_RB_B_CORE_DOUBLE_EXCEPT_STICK_CLR_MASK    		0x1000
#define	GLB_CTL_M_RB_MDMA_INT_STS_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_MDMA_INT_STS_STICK_CLR_OFFSET	        9
#define GLB_CTL_M_RB_MDMA_INT_STS_STICK_CLR_MASK    		0x200
#define	GLB_CTL_M_RB_SMDMA_INT_STS_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_SMDMA_INT_STS_STICK_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SMDMA_INT_STS_STICK_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_DWDT_1_SYS_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_DWDT_1_SYS_RST_STICK_CLR_OFFSET	        7
#define GLB_CTL_M_RB_DWDT_1_SYS_RST_STICK_CLR_MASK    		0x80
#define	GLB_CTL_M_RB_BWDT_SYS_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_BWDT_SYS_RST_STICK_CLR_OFFSET	        6
#define GLB_CTL_M_RB_BWDT_SYS_RST_STICK_CLR_MASK    		0x40
#define	GLB_CTL_M_RB_MWDT_SYS_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_MWDT_SYS_RST_STICK_CLR_OFFSET	        5
#define GLB_CTL_M_RB_MWDT_SYS_RST_STICK_CLR_MASK    		0x20
#define	GLB_CTL_M_RB_DWDT_0_SYS_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_DWDT_0_SYS_RST_STICK_CLR_OFFSET	        4
#define GLB_CTL_M_RB_DWDT_0_SYS_RST_STICK_CLR_MASK    		0x10
#define	GLB_CTL_M_RB_B_SOFT_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_B_SOFT_RST_STICK_CLR_OFFSET	        3
#define GLB_CTL_M_RB_B_SOFT_RST_STICK_CLR_MASK    		0x8
#define	GLB_CTL_M_RB_M_SOFT_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_M_SOFT_RST_STICK_CLR_OFFSET	        2
#define GLB_CTL_M_RB_M_SOFT_RST_STICK_CLR_MASK    		0x4
#define	GLB_CTL_M_RB_D_SOFT_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_D_SOFT_RST_STICK_CLR_OFFSET	        1
#define GLB_CTL_M_RB_D_SOFT_RST_STICK_CLR_MASK    		0x2
#define	GLB_CTL_M_RB_C_SOFT_RST_STICK_CLR_LEN	        1
#define	GLB_CTL_M_RB_C_SOFT_RST_STICK_CLR_OFFSET	        0
#define GLB_CTL_M_RB_C_SOFT_RST_STICK_CLR_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_LOCK_LEN	        1
#define	GLB_CTL_M_RB_CFG_LOCK_OFFSET	        0
#define GLB_CTL_M_RB_CFG_LOCK_MASK    		0x1

#define	GLB_CTL_M_RB_LOCK_VAL0_LEN	        16
#define	GLB_CTL_M_RB_LOCK_VAL0_OFFSET	        0
#define GLB_CTL_M_RB_LOCK_VAL0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_LOCK_VAL1_LEN	        16
#define	GLB_CTL_M_RB_LOCK_VAL1_OFFSET	        0
#define GLB_CTL_M_RB_LOCK_VAL1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_LOCK_VAL2_LEN	        16
#define	GLB_CTL_M_RB_LOCK_VAL2_OFFSET	        0
#define GLB_CTL_M_RB_LOCK_VAL2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_LOCK_VAL3_LEN	        16
#define	GLB_CTL_M_RB_LOCK_VAL3_OFFSET	        0
#define GLB_CTL_M_RB_LOCK_VAL3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLK_DIVEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLK_DIVEN_OFFSET	        12
#define GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLK_DIVEN_MASK    		0x1000
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLKEN_OFFSET	        11
#define GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_CLKEN_MASK    		0x800
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_DIV_NUM_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_DIV_NUM_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_DIV_NUM_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLK_DIV_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLK_DIV_EN_OFFSET	        10
#define GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLK_DIV_EN_MASK    		0x400
#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLKEN_OFFSET	        9
#define GLB_CTL_M_RB_CFG_GLBM_HF_32K_CLKEN_MASK    		0x200
#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_DIV_NUM_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_HF_32K_DIV_NUM_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_HF_32K_DIV_NUM_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_BTGLP_XO_32K_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_BTGLP_XO_32K_SEL_OFFSET	        12
#define GLB_CTL_M_RB_CFG_GLBM_BTGLP_XO_32K_SEL_MASK    		0x1000
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKB_STS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKB_STS_OFFSET	        11
#define GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKB_STS_MASK    		0x800
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKA_STS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKA_STS_OFFSET	        10
#define GLB_CTL_M_RB_CFG_GLBM_A32M_MX_CLKA_STS_MASK    		0x400
#define	GLB_CTL_M_RB_CFG_GLBM_XO_32K_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_XO_32K_SEL_OFFSET	        9
#define GLB_CTL_M_RB_CFG_GLBM_XO_32K_SEL_MASK    		0x200
#define	GLB_CTL_M_RB_CFG_GLBM_XO_RC_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_XO_RC_SEL_OFFSET	        8
#define GLB_CTL_M_RB_CFG_GLBM_XO_RC_SEL_MASK    		0x100
#define	GLB_CTL_M_RB_CFG_AUTO_SNIFF_XO_RC_HW_SEL_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_AUTO_SNIFF_XO_RC_HW_SEL_EN_OFFSET	        6
#define GLB_CTL_M_RB_CFG_AUTO_SNIFF_XO_RC_HW_SEL_EN_MASK    		0x40
#define	GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_1_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_1_OFFSET	        5
#define GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_1_MASK    		0x20
#define	GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_0_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_0_OFFSET	        4
#define GLB_CTL_M_RB_CFG_GLBM_CLK_TEST_SEL_0_MASK    		0x10
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_SEL_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_A32M_COMMON_SEL_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_CLK_COMMON_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_A32M_CLK_COMMON_CLKEN_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_A32M_CLK_COMMON_CLKEN_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_CODEC_PAD_XO_MX_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_CODEC_PAD_XO_MX_CLKEN_OFFSET	        3
#define GLB_CTL_M_RB_CFG_GLBM_CODEC_PAD_XO_MX_CLKEN_MASK    		0x8
#define	GLB_CTL_M_RB_CFG_GLBM_CLOCK_TEST_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_CLOCK_TEST_CLKEN_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_CLOCK_TEST_CLKEN_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_PWM_CLK_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_PWM_CLK_SEL_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_PWM_CLK_SEL_MASK    		0x1

#define	GLB_CTL_M_RB_DFT_TOP_DATA_ISO_EN_LEN	        1
#define	GLB_CTL_M_RB_DFT_TOP_DATA_ISO_EN_OFFSET	        1
#define GLB_CTL_M_RB_DFT_TOP_DATA_ISO_EN_MASK    		0x2
#define	GLB_CTL_M_RB_DFT_TOP_PWR_EN_LEN	        1
#define	GLB_CTL_M_RB_DFT_TOP_PWR_EN_OFFSET	        0
#define GLB_CTL_M_RB_DFT_TOP_PWR_EN_MASK    		0x1

#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_STS_LEN	        1
#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_STS_OFFSET	        9
#define GLB_CTL_M_RB_USB_VBUS_IN_INTR_STS_MASK    		0x200
#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_CLR_LEN	        1
#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_CLR_OFFSET	        8
#define GLB_CTL_M_RB_USB_VBUS_IN_INTR_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_MASK_LEN	        1
#define	GLB_CTL_M_RB_USB_VBUS_IN_INTR_MASK_OFFSET	        7
#define GLB_CTL_M_RB_USB_VBUS_IN_INTR_MASK_MASK    		0x80
#define	GLB_CTL_M_RB_USB_VBUS_IN_WAKE_EN_LEN	        1
#define	GLB_CTL_M_RB_USB_VBUS_IN_WAKE_EN_OFFSET	        6
#define GLB_CTL_M_RB_USB_VBUS_IN_WAKE_EN_MASK    		0x40
#define	GLB_CTL_M_RB_USB_VBUS_IN_GRM_TIME_LEN	        6
#define	GLB_CTL_M_RB_USB_VBUS_IN_GRM_TIME_OFFSET	        0
#define GLB_CTL_M_RB_USB_VBUS_IN_GRM_TIME_MASK    		0x3F

#define	GLB_CTL_M_RB_CFG_B_SYS_SLP_CLKEN_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_B_SYS_SLP_CLKEN_EN_OFFSET	        1
#define GLB_CTL_M_RB_CFG_B_SYS_SLP_CLKEN_EN_MASK    		0x2

#define	GLB_CTL_M_RB_CFG_GLBM_XO_RC_32M_CLKEN_TMP_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_XO_RC_32M_CLKEN_TMP_OFFSET	        12
#define GLB_CTL_M_RB_CFG_GLBM_XO_RC_32M_CLKEN_TMP_MASK    		0x1000
#define	GLB_CTL_M_RB_CFG_GLBM_COM_AON_DIAG_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_COM_AON_DIAG_CLKEN_OFFSET	        11
#define GLB_CTL_M_RB_CFG_GLBM_COM_AON_DIAG_CLKEN_MASK    		0x800
#define	GLB_CTL_M_RB_CFG_GLBM_SDIOTM_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SDIOTM_CLKEN_OFFSET	        10
#define GLB_CTL_M_RB_CFG_GLBM_SDIOTM_CLKEN_MASK    		0x400
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_32K_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_32K_CLKEN_OFFSET	        9
#define GLB_CTL_M_RB_CFG_GLBM_GLB_32K_CLKEN_MASK    		0x200
#define	GLB_CTL_M_RB_CFG_GLBM_BT_32M_XO_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_BT_32M_XO_SEL_OFFSET	        8
#define GLB_CTL_M_RB_CFG_GLBM_BT_32M_XO_SEL_MASK    		0x100
#define	GLB_CTL_M_RB_CFG_GLBM_GPIO_LOAD_DIV_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_GPIO_LOAD_DIV_EN_OFFSET	        7
#define GLB_CTL_M_RB_CFG_GLBM_GPIO_LOAD_DIV_EN_MASK    		0x80
#define	GLB_CTL_M_RB_CFG_GLBM_GPIO_CLK_DIV_NUM_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_GPIO_CLK_DIV_NUM_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_GPIO_CLK_DIV_NUM_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKB_STS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKB_STS_OFFSET	        11
#define GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKB_STS_MASK    		0x800
#define	GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKA_STS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKA_STS_OFFSET	        10
#define GLB_CTL_M_RB_CFG_GLBM_SSI_32M_32K_MX_CLKA_STS_MASK    		0x400

#define	GLB_CTL_M_RB_HI6535_PWR_HOLD_LEN	        16
#define	GLB_CTL_M_RB_HI6535_PWR_HOLD_OFFSET	        0
#define GLB_CTL_M_RB_HI6535_PWR_HOLD_MASK    		0xFFFF

#define	GLB_CTL_M_RB_HI6535_PWR_HOLD_HW_SEL_LEN	        16
#define	GLB_CTL_M_RB_HI6535_PWR_HOLD_HW_SEL_OFFSET	        0
#define GLB_CTL_M_RB_HI6535_PWR_HOLD_HW_SEL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_FLASH_PWR_AON_LABEL_LEN	        16
#define	GLB_CTL_M_RB_FLASH_PWR_AON_LABEL_OFFSET	        0
#define GLB_CTL_M_RB_FLASH_PWR_AON_LABEL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_32M_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_32M_CLKEN_OFFSET	        6
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_32M_CLKEN_MASK    		0x40
#define	GLB_CTL_M_RB_CFG_GLBM_BTGLP_32K_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_BTGLP_32K_CLKEN_OFFSET	        5
#define GLB_CTL_M_RB_CFG_GLBM_BTGLP_32K_CLKEN_MASK    		0x20
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_FON_COM_BUS_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_FON_COM_BUS_CLKEN_OFFSET	        4
#define GLB_CTL_M_RB_CFG_GLBM_GLB_FON_COM_BUS_CLKEN_MASK    		0x10
#define	GLB_CTL_M_RB_CFG_GLBM_COM_AON_BUS_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_COM_AON_BUS_CLKEN_OFFSET	        3
#define GLB_CTL_M_RB_CFG_GLBM_COM_AON_BUS_CLKEN_MASK    		0x8
#define	GLB_CTL_M_RB_CFG_GLBM_32K_CLKCALI_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_32K_CLKCALI_CLKEN_OFFSET	        2
#define GLB_CTL_M_RB_CFG_GLBM_32K_CLKCALI_CLKEN_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_FON_MCU_BUS_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_GLB_FON_MCU_BUS_CLKEN_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_GLB_FON_MCU_BUS_CLKEN_MASK    		0x2

#define	GLB_CTL_M_RB_AON_BUS_CLKDIV_EN_LEN	        1
#define	GLB_CTL_M_RB_AON_BUS_CLKDIV_EN_OFFSET	        8
#define GLB_CTL_M_RB_AON_BUS_CLKDIV_EN_MASK    		0x100
#define	GLB_CTL_M_RB_AON_BUS_CLK_EN_LEN	        1
#define	GLB_CTL_M_RB_AON_BUS_CLK_EN_OFFSET	        7
#define GLB_CTL_M_RB_AON_BUS_CLK_EN_MASK    		0x80
#define	GLB_CTL_M_RB_AON_BUS_DIV_NUM_LEN	        4
#define	GLB_CTL_M_RB_AON_BUS_DIV_NUM_OFFSET	        0
#define GLB_CTL_M_RB_AON_BUS_DIV_NUM_MASK    		0xF

#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLK_SEL_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLK_SEL_OFFSET	        9
#define GLB_CTL_M_RB_CFG_GLBM_STM_CLK_SEL_MASK    		0x200
#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLKEN_OFFSET	        8
#define GLB_CTL_M_RB_CFG_GLBM_STM_CLKEN_MASK    		0x100
#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLK_DIV_NUM_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_STM_CLK_DIV_NUM_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_STM_CLK_DIV_NUM_MASK    		0xFE
#define	GLB_CTL_M_RB_CFG_GLBM_STM_LOAD_DIV_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_STM_LOAD_DIV_EN_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_STM_LOAD_DIV_EN_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_TGLP_AON_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_TGLP_AON_N_OFFSET	        9
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_TGLP_AON_N_MASK    		0x200
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_VIDEO_TE_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_VIDEO_TE_N_OFFSET	        6
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_VIDEO_TE_N_MASK    		0x40
#define	GLB_CTL_M_RB_BWDT_SYS_RST_PC_DIS_LEN	        1
#define	GLB_CTL_M_RB_BWDT_SYS_RST_PC_DIS_OFFSET	        2
#define GLB_CTL_M_RB_BWDT_SYS_RST_PC_DIS_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_GLBM_RST_CODEC_HW_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_RST_CODEC_HW_BYPASS_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_RST_CODEC_HW_BYPASS_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_RST_NPU_HW_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_RST_NPU_HW_BYPASS_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_RST_NPU_HW_BYPASS_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_COM_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CPU_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CPU_N_OFFSET	        2
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CPU_N_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_B_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_CODEC_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_CODEC_LGC_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_CODEC_LGC_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_VAU_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_VAU_LGC_N_OFFSET	        3
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_VAU_LGC_N_MASK    		0x8
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_H264_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_H264_LGC_N_OFFSET	        2
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_H264_LGC_N_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_DISPLAY_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CPU_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CPU_N_OFFSET	        2
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CPU_N_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_MCU_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_SDIO_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_LGC_N_OFFSET	        1
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_LGC_N_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_CRG_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_CRG_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_XIP_SUB_CRG_N_MASK    		0x1

#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_L_LEN	        16
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_L_OFFSET	        0
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_H_LEN	        16
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_H_OFFSET	        0
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAIN_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_L_LEN	        16
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_L_OFFSET	        0
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_H_LEN	        16
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_H_OFFSET	        0
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_DATAOUT_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_FUNC_BIST_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_FUNC_BIST_CLKEN_OFFSET	        15
#define GLB_CTL_M_RB_CFG_GLBM_FUNC_BIST_CLKEN_MASK    		0x8000
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_RST_N_LEN	        1
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_RST_N_OFFSET	        3
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_RST_N_MASK    		0x8
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_ENABLE_LEN	        1
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_ENABLE_OFFSET	        2
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_ENABLE_MASK    		0x4
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_WRITEEN_LEN	        1
#define	GLB_CTL_M_RB_DFT_FUNC_MBIST_WRITEEN_OFFSET	        1
#define GLB_CTL_M_RB_DFT_FUNC_MBIST_WRITEEN_MASK    		0x2
#define	GLB_CTL_M_RB_DFT_SMS_FUNC_MBIST_MODE_LEN	        1
#define	GLB_CTL_M_RB_DFT_SMS_FUNC_MBIST_MODE_OFFSET	        0
#define GLB_CTL_M_RB_DFT_SMS_FUNC_MBIST_MODE_MASK    		0x1

#define	GLB_CTL_M_RB_MBUS_CLKEN_NOR_LEN	        1
#define	GLB_CTL_M_RB_MBUS_CLKEN_NOR_OFFSET	        0
#define GLB_CTL_M_RB_MBUS_CLKEN_NOR_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_NPU_LGC_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_NPU_LGC_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_GLB_NPU_LGC_N_MASK    		0x1

#define	GLB_CTL_M_RB_ULP_AON_AUTO_CG_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_ULP_AON_AUTO_CG_BYPASS_OFFSET	        0
#define GLB_CTL_M_RB_ULP_AON_AUTO_CG_BYPASS_MASK    		0x1

#define	GLB_CTL_M_RB_PSRAM_RAM_POWER_RET1N_LEN	        1
#define	GLB_CTL_M_RB_PSRAM_RAM_POWER_RET1N_OFFSET	        1
#define GLB_CTL_M_RB_PSRAM_RAM_POWER_RET1N_MASK    		0x2
#define	GLB_CTL_M_RB_DIAG_MEM_POWER_RET1N_LEN	        1
#define	GLB_CTL_M_RB_DIAG_MEM_POWER_RET1N_OFFSET	        0
#define GLB_CTL_M_RB_DIAG_MEM_POWER_RET1N_MASK    		0x1

#define	GLB_CTL_M_RB_AON_WDT_CORE_WAIT_LEN	        1
#define	GLB_CTL_M_RB_AON_WDT_CORE_WAIT_OFFSET	        0
#define GLB_CTL_M_RB_AON_WDT_CORE_WAIT_MASK    		0x1

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_0_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_0_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_1_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_1_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_2_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_2_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_3_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_3_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_4_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_4_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_4_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_5_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_5_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_5_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_6_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_6_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_6_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_7_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_7_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_7_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_8_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_8_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_8_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_9_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_9_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_9_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_10_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_10_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_10_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_11_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_11_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_11_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_12_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_12_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_12_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_13_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_13_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_13_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_14_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_14_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_14_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_15_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_15_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_15_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_16_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_16_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_16_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_17_LEN	        16
#define	GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_17_OFFSET	        0
#define GLB_CTL_M_RB_GP_REG_NOWDT_RST_REG_17_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GPIO_CLK_EN_LEN	        7
#define	GLB_CTL_M_RB_GPIO_CLK_EN_OFFSET	        7
#define GLB_CTL_M_RB_GPIO_CLK_EN_MASK    		0x3F80
#define	GLB_CTL_M_RB_GPIO_RST_SOFT_N_LEN	        7
#define	GLB_CTL_M_RB_GPIO_RST_SOFT_N_OFFSET	        0
#define GLB_CTL_M_RB_GPIO_RST_SOFT_N_MASK    		0x7F

#define	GLB_CTL_M_RB_RTC_PERP_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_RTC_PERP_CLKEN_OFFSET	        2
#define GLB_CTL_M_RB_RTC_PERP_CLKEN_MASK    		0x4
#define	GLB_CTL_M_RB_RTC_PCLK_EN_LEN	        1
#define	GLB_CTL_M_RB_RTC_PCLK_EN_OFFSET	        1
#define GLB_CTL_M_RB_RTC_PCLK_EN_MASK    		0x2
#define	GLB_CTL_M_RB_RTC_RST_SOFT_N_LEN	        1
#define	GLB_CTL_M_RB_RTC_RST_SOFT_N_OFFSET	        0
#define GLB_CTL_M_RB_RTC_RST_SOFT_N_MASK    		0x1

#define	GLB_CTL_M_RB_WDT_CUR_STS_LEN	        1
#define	GLB_CTL_M_RB_WDT_CUR_STS_OFFSET	        1
#define GLB_CTL_M_RB_WDT_CUR_STS_MASK    		0x2
#define	GLB_CTL_M_RB_WDT_SOFT_RST_N_LEN	        1
#define	GLB_CTL_M_RB_WDT_SOFT_RST_N_OFFSET	        0
#define GLB_CTL_M_RB_WDT_SOFT_RST_N_MASK    		0x1

#define	GLB_CTL_M_RB_GPIO_CUR_STS_LEN	        7
#define	GLB_CTL_M_RB_GPIO_CUR_STS_OFFSET	        8
#define GLB_CTL_M_RB_GPIO_CUR_STS_MASK    		0x7F00
#define	GLB_CTL_M_RB_RTC_EN_STS_LEN	        4
#define	GLB_CTL_M_RB_RTC_EN_STS_OFFSET	        4
#define GLB_CTL_M_RB_RTC_EN_STS_MASK    		0xF0
#define	GLB_CTL_M_RB_RTC_CUR_STS_LEN	        1
#define	GLB_CTL_M_RB_RTC_CUR_STS_OFFSET	        0
#define GLB_CTL_M_RB_RTC_CUR_STS_MASK    		0x1

#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_0_LEN	        16
#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_0_OFFSET	        0
#define GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_1_LEN	        16
#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_1_OFFSET	        0
#define GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_2_LEN	        16
#define	GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_2_OFFSET	        0
#define GLB_CTL_M_RB_PINMUX_AON_GPIO_SEL_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_NPU_MEM_CG_MASK_LEN	        1
#define	GLB_CTL_M_RB_NPU_MEM_CG_MASK_OFFSET	        15
#define GLB_CTL_M_RB_NPU_MEM_CG_MASK_MASK    		0x8000
#define	GLB_CTL_M_RB_AIC_CORE_IDLE_LEN	        1
#define	GLB_CTL_M_RB_AIC_CORE_IDLE_OFFSET	        14
#define GLB_CTL_M_RB_AIC_CORE_IDLE_MASK    		0x4000
#define	GLB_CTL_M_RB_AIC_IDLE_LEN	        1
#define	GLB_CTL_M_RB_AIC_IDLE_OFFSET	        13
#define GLB_CTL_M_RB_AIC_IDLE_MASK    		0x2000
#define	GLB_CTL_M_RB_NPU_AIC_RST_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_NPU_AIC_RST_BYPASS_OFFSET	        11
#define GLB_CTL_M_RB_NPU_AIC_RST_BYPASS_MASK    		0x800

#define	GLB_CTL_M_RB_NPU_INTR_EN_MCPU_LEN	        5
#define	GLB_CTL_M_RB_NPU_INTR_EN_MCPU_OFFSET	        0
#define GLB_CTL_M_RB_NPU_INTR_EN_MCPU_MASK    		0x1F

#define	GLB_CTL_M_RB_CFG_UART_BCOEX_TRX_SW_LEN	        1
#define	GLB_CTL_M_RB_CFG_UART_BCOEX_TRX_SW_OFFSET	        5
#define GLB_CTL_M_RB_CFG_UART_BCOEX_TRX_SW_MASK    		0x20
#define	GLB_CTL_M_RB_CFG_UART_H0_TRX_SW_LEN	        1
#define	GLB_CTL_M_RB_CFG_UART_H0_TRX_SW_OFFSET	        4
#define GLB_CTL_M_RB_CFG_UART_H0_TRX_SW_MASK    		0x10
#define	GLB_CTL_M_RB_CFG_UART_L0_TRX_SW_LEN	        1
#define	GLB_CTL_M_RB_CFG_UART_L0_TRX_SW_OFFSET	        3
#define GLB_CTL_M_RB_CFG_UART_L0_TRX_SW_MASK    		0x8
#define	GLB_CTL_M_RB_G_STM_EN_LEN	        1
#define	GLB_CTL_M_RB_G_STM_EN_OFFSET	        2
#define GLB_CTL_M_RB_G_STM_EN_MASK    		0x4

#define	GLB_CTL_M_RB_SEM0_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM0_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM0_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM0_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM0_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM0_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM0_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM0_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM0_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM0_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM0_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM0_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM1_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM1_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM1_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM1_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM1_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM1_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM1_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM1_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM1_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM1_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM1_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM1_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM2_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM2_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM2_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM2_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM2_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM2_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM2_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM2_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM2_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM2_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM2_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM2_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM3_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM3_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM3_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM3_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM3_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM3_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM3_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM3_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM3_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM3_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM3_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM3_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM4_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM4_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM4_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM4_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM4_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM4_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM4_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM4_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM4_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM4_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM4_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM4_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM5_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM5_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM5_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM5_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM5_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM5_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM5_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM5_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM5_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM5_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM5_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM5_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM6_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM6_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM6_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM6_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM6_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM6_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM6_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM6_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM6_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM6_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM6_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM6_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_SEM7_STS_LEN	        4
#define	GLB_CTL_M_RB_SEM7_STS_OFFSET	        8
#define GLB_CTL_M_RB_SEM7_STS_MASK    		0xF00
#define	GLB_CTL_M_RB_SEM7_SET_LEN	        4
#define	GLB_CTL_M_RB_SEM7_SET_OFFSET	        0
#define GLB_CTL_M_RB_SEM7_SET_MASK    		0xF

#define	GLB_CTL_M_RB_SEM7_FORCE_CLR_LEN	        1
#define	GLB_CTL_M_RB_SEM7_FORCE_CLR_OFFSET	        8
#define GLB_CTL_M_RB_SEM7_FORCE_CLR_MASK    		0x100
#define	GLB_CTL_M_RB_SEM7_SUB_CLR_LEN	        4
#define	GLB_CTL_M_RB_SEM7_SUB_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SEM7_SUB_CLR_MASK    		0xF

#define	GLB_CTL_M_RB_AON_PWM_CUR_STS_LEN	        1
#define	GLB_CTL_M_RB_AON_PWM_CUR_STS_OFFSET	        5
#define GLB_CTL_M_RB_AON_PWM_CUR_STS_MASK    		0x20
#define	GLB_CTL_M_RB_CFG_AON_PWM_DIO_HW_CG_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_CFG_AON_PWM_DIO_HW_CG_BYPASS_OFFSET	        4
#define GLB_CTL_M_RB_CFG_AON_PWM_DIO_HW_CG_BYPASS_MASK    		0x10
#define	GLB_CTL_M_RB_CFG_AON_PWM_DIO_RW_CG_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_CFG_AON_PWM_DIO_RW_CG_BYPASS_OFFSET	        3
#define GLB_CTL_M_RB_CFG_AON_PWM_DIO_RW_CG_BYPASS_MASK    		0x8
#define	GLB_CTL_M_RB_CFG_AON_PWM_HW_CG_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_AON_PWM_HW_CG_EN_OFFSET	        2
#define GLB_CTL_M_RB_CFG_AON_PWM_HW_CG_EN_MASK    		0x4
#define	GLB_CTL_M_RB_CFG_AON_PWM_CLKEN_LEN	        1
#define	GLB_CTL_M_RB_CFG_AON_PWM_CLKEN_OFFSET	        1
#define GLB_CTL_M_RB_CFG_AON_PWM_CLKEN_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_AON_PWM_SOFT_RST_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_AON_PWM_SOFT_RST_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_AON_PWM_SOFT_RST_N_MASK    		0x1

#define	GLB_CTL_M_RB_DAP_ID_L_LEN	        16
#define	GLB_CTL_M_RB_DAP_ID_L_OFFSET	        0
#define GLB_CTL_M_RB_DAP_ID_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_DAP_ID_H_LEN	        16
#define	GLB_CTL_M_RB_DAP_ID_H_OFFSET	        0
#define GLB_CTL_M_RB_DAP_ID_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GLB_WDT_RST_OFF_LEN	        1
#define	GLB_CTL_M_RB_GLB_WDT_RST_OFF_OFFSET	        5
#define GLB_CTL_M_RB_GLB_WDT_RST_OFF_MASK    		0x20
#define	GLB_CTL_M_RB_SYS_SOFT_RST_OFF_LEN	        1
#define	GLB_CTL_M_RB_SYS_SOFT_RST_OFF_OFFSET	        4
#define GLB_CTL_M_RB_SYS_SOFT_RST_OFF_MASK    		0x10
#define	GLB_CTL_M_RB_GLB_WDT_RST_OFF_CLR_LEN	        1
#define	GLB_CTL_M_RB_GLB_WDT_RST_OFF_CLR_OFFSET	        1
#define GLB_CTL_M_RB_GLB_WDT_RST_OFF_CLR_MASK    		0x2
#define	GLB_CTL_M_RB_SYS_SOFT_RST_OFF_CLR_LEN	        1
#define	GLB_CTL_M_RB_SYS_SOFT_RST_OFF_CLR_OFFSET	        0
#define GLB_CTL_M_RB_SYS_SOFT_RST_OFF_CLR_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_RELSE_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_RELSE_OFFSET	        6
#define GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_RELSE_MASK    		0x40
#define	GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_OFFSET	        5
#define GLB_CTL_M_RB_CFG_GLB_SOFT_RST_DAP_DIS_FON_MASK    		0x20
#define	GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_RELSE_LEN	        1
#define	GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_RELSE_OFFSET	        4
#define GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_RELSE_MASK    		0x10
#define	GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_LEN	        1
#define	GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_OFFSET	        3
#define GLB_CTL_M_RB_WDT_RST_N_OUT_DIS_FON_MASK    		0x8
#define	GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_RELSE_LEN	        1
#define	GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_RELSE_OFFSET	        2
#define GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_RELSE_MASK    		0x4
#define	GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_LEN	        1
#define	GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_OFFSET	        1
#define GLB_CTL_M_RB_SYS_SOFT_RST_N_OUT_DIS_FON_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_SYS_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_SYS_N_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SOFT_RST_SYS_N_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_GLBM_WDT_RST_WIDTH_LEN	        8
#define	GLB_CTL_M_RB_CFG_GLBM_WDT_RST_WIDTH_OFFSET	        8
#define GLB_CTL_M_RB_CFG_GLBM_WDT_RST_WIDTH_MASK    		0xFF00
#define	GLB_CTL_M_RB_CFG_GLBM_SYS_SOFT_RST_WIDTH_LEN	        8
#define	GLB_CTL_M_RB_CFG_GLBM_SYS_SOFT_RST_WIDTH_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_SYS_SOFT_RST_WIDTH_MASK    		0xFF

#define	GLB_CTL_M_RB_MAD_INT_EN_LEN	        1
#define	GLB_CTL_M_RB_MAD_INT_EN_OFFSET	        0
#define GLB_CTL_M_RB_MAD_INT_EN_MASK    		0x1

#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_AGPIO0_CTRL_IE_SLP_VAL_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_HGPIO0_CTRL_IE_SLP_VAL_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_HGPIO0_CTRL_IE_SLP_VAL_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_HGPIO0_CTRL_IE_SLP_VAL_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_MGPIO0_CTRL_IE_SLP_VAL_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_S_EGPIO0_CTRL_IE_SLP_VAL_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_EN_LEN	        1
#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_EN_OFFSET	        4
#define GLB_CTL_M_RB_CFG_DEBUG_MODE_EN_MASK    		0x10
#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_LEN	        1
#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_OFFSET	        1
#define GLB_CTL_M_RB_CFG_DEBUG_MODE_MASK    		0x2
#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_STS_LEN	        1
#define	GLB_CTL_M_RB_CFG_DEBUG_MODE_STS_OFFSET	        0
#define GLB_CTL_M_RB_CFG_DEBUG_MODE_STS_MASK    		0x1

#define	GLB_CTL_M_RB_CLK_32K_DET_VAL_LEN	        13
#define	GLB_CTL_M_RB_CLK_32K_DET_VAL_OFFSET	        0
#define GLB_CTL_M_RB_CLK_32K_DET_VAL_MASK    		0x1FFF

#define	GLB_CTL_M_RB_CLK_32K_DET_DONE_STS_LEN	        1
#define	GLB_CTL_M_RB_CLK_32K_DET_DONE_STS_OFFSET	        5
#define GLB_CTL_M_RB_CLK_32K_DET_DONE_STS_MASK    		0x20
#define	GLB_CTL_M_RB_CLK_32K_DET_DOING_STS_LEN	        1
#define	GLB_CTL_M_RB_CLK_32K_DET_DOING_STS_OFFSET	        4
#define GLB_CTL_M_RB_CLK_32K_DET_DOING_STS_MASK    		0x10
#define	GLB_CTL_M_RB_ERR_FLAG_LEN	        1
#define	GLB_CTL_M_RB_ERR_FLAG_OFFSET	        3
#define GLB_CTL_M_RB_ERR_FLAG_MASK    		0x8
#define	GLB_CTL_M_RB_ERR_FLAG_CLR_LEN	        1
#define	GLB_CTL_M_RB_ERR_FLAG_CLR_OFFSET	        2
#define GLB_CTL_M_RB_ERR_FLAG_CLR_MASK    		0x4
#define	GLB_CTL_M_RB_CLK_32K_DET_EN_LEN	        1
#define	GLB_CTL_M_RB_CLK_32K_DET_EN_OFFSET	        1
#define GLB_CTL_M_RB_CLK_32K_DET_EN_MASK    		0x2
#define	GLB_CTL_M_RB_CLK_TRACE_EN_LEN	        1
#define	GLB_CTL_M_RB_CLK_TRACE_EN_OFFSET	        0
#define GLB_CTL_M_RB_CLK_TRACE_EN_MASK    		0x1

#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_L_LEN	        16
#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_L_OFFSET	        0
#define GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_H_LEN	        16
#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_H_OFFSET	        0
#define GLB_CTL_M_RB_CLK_32K_GOLD_RES_LOW_LIMIT_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_L_LEN	        16
#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_L_OFFSET	        0
#define GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_H_LEN	        16
#define	GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_H_OFFSET	        0
#define GLB_CTL_M_RB_CLK_32K_GOLD_RES_HIGH_LIMIT_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_XO32K_DET_STS_ORG_LEN	        1
#define	GLB_CTL_M_RB_XO32K_DET_STS_ORG_OFFSET	        6
#define GLB_CTL_M_RB_XO32K_DET_STS_ORG_MASK    		0x40
#define	GLB_CTL_M_RB_XO32K_DET_VAL_LEN	        1
#define	GLB_CTL_M_RB_XO32K_DET_VAL_OFFSET	        5
#define GLB_CTL_M_RB_XO32K_DET_VAL_MASK    		0x20
#define	GLB_CTL_M_RB_XO32K_DET_SEL_LEN	        4
#define	GLB_CTL_M_RB_XO32K_DET_SEL_OFFSET	        1
#define GLB_CTL_M_RB_XO32K_DET_SEL_MASK    		0x1E
#define	GLB_CTL_M_RB_XO32K_DET_EN_LEN	        1
#define	GLB_CTL_M_RB_XO32K_DET_EN_OFFSET	        0
#define GLB_CTL_M_RB_XO32K_DET_EN_MASK    		0x1

#define	GLB_CTL_M_RB_MCU_INT_CLR_LEN	        1
#define	GLB_CTL_M_RB_MCU_INT_CLR_OFFSET	        3
#define GLB_CTL_M_RB_MCU_INT_CLR_MASK    		0x8
#define	GLB_CTL_M_RB_MCU_INT_EN_LEN	        1
#define	GLB_CTL_M_RB_MCU_INT_EN_OFFSET	        2
#define GLB_CTL_M_RB_MCU_INT_EN_MASK    		0x4
#define	GLB_CTL_M_RB_TE_INT_CLR_LEN	        1
#define	GLB_CTL_M_RB_TE_INT_CLR_OFFSET	        1
#define GLB_CTL_M_RB_TE_INT_CLR_MASK    		0x2
#define	GLB_CTL_M_RB_TE_INT_EN_LEN	        1
#define	GLB_CTL_M_RB_TE_INT_EN_OFFSET	        0
#define GLB_CTL_M_RB_TE_INT_EN_MASK    		0x1

#define	GLB_CTL_M_RB_TE_INT_START_CNT_VAL_LEN	        16
#define	GLB_CTL_M_RB_TE_INT_START_CNT_VAL_OFFSET	        0
#define GLB_CTL_M_RB_TE_INT_START_CNT_VAL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_TE_INT_STOP_CNT_VAL_LEN	        16
#define	GLB_CTL_M_RB_TE_INT_STOP_CNT_VAL_OFFSET	        0
#define GLB_CTL_M_RB_TE_INT_STOP_CNT_VAL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCU_INT_START_CNT_VAL_LEN	        16
#define	GLB_CTL_M_RB_MCU_INT_START_CNT_VAL_OFFSET	        0
#define GLB_CTL_M_RB_MCU_INT_START_CNT_VAL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCU_INT_STOP_CNT_VAL_LEN	        16
#define	GLB_CTL_M_RB_MCU_INT_STOP_CNT_VAL_OFFSET	        0
#define GLB_CTL_M_RB_MCU_INT_STOP_CNT_VAL_MASK    		0xFFFF

#define	GLB_CTL_M_RB_TE_INT_TE_CNT_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_TE_INT_TE_CNT_BYPASS_OFFSET	        14
#define GLB_CTL_M_RB_TE_INT_TE_CNT_BYPASS_MASK    		0x4000
#define	GLB_CTL_M_RB_TE_INT_TE_CNT_VAL_LEN	        6
#define	GLB_CTL_M_RB_TE_INT_TE_CNT_VAL_OFFSET	        8
#define GLB_CTL_M_RB_TE_INT_TE_CNT_VAL_MASK    		0x3F00
#define	GLB_CTL_M_RB_MCU_INT_TE_CNT_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_MCU_INT_TE_CNT_BYPASS_OFFSET	        6
#define GLB_CTL_M_RB_MCU_INT_TE_CNT_BYPASS_MASK    		0x40
#define	GLB_CTL_M_RB_MCU_INT_TE_CNT_VAL_LEN	        6
#define	GLB_CTL_M_RB_MCU_INT_TE_CNT_VAL_OFFSET	        0
#define GLB_CTL_M_RB_MCU_INT_TE_CNT_VAL_MASK    		0x3F

#define	GLB_CTL_M_RB_AON_DIAG_SEL_LEN	        5
#define	GLB_CTL_M_RB_AON_DIAG_SEL_OFFSET	        0
#define GLB_CTL_M_RB_AON_DIAG_SEL_MASK    		0x1F

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_ROM_CTL_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_AUDIO_ROM_CTL_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_AUDIO_ROM_CTL_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_BT_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_BT_ROM_CTL_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_BT_ROM_CTL_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_BT_ROM_CTL_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_COM_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MCU_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MCU_ROM_CTL_LEN	        7
#define	GLB_CTL_M_RB_CFG_GLBM_MCU_ROM_CTL_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MCU_ROM_CTL_MASK    		0x7F

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_WKUP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_WKUP_TIME_MASK    		0xFF00
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_WKUP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_WKUP_TIME_MASK    		0xFF

#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_WKUP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_WKUP_TIME_MASK    		0xFF00
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_WKUP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_WKUP_TIME_MASK    		0xFF

#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_WKUP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_WKUP_TIME_MASK    		0xFF00
#define	GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_WKUP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_WKUP_TIME_MASK    		0xFF

#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_SLP_TIME_LEN	        5
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_SLP_TIME_OFFSET	        11
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_CORE_PD_SLP_TIME_MASK    		0xF800
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_SLP_TIME_LEN	        6
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_SLP_TIME_OFFSET	        5
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_PD_SLP_TIME_MASK    		0x7E0
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_SLP_TIME_LEN	        5
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_SLP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_RC_RSTN_SLP_TIME_MASK    		0x1F

#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_SLP_TIME_LEN	        5
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_SLP_TIME_OFFSET	        11
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XO_FAST_LOOP_RSTN_SLP_TIME_MASK    		0xF800
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_SLP_TIME_LEN	        6
#define	GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_SLP_TIME_OFFSET	        5
#define GLB_CTL_M_RB_LP_DVFS_FSXO_XOCLKOUT3_EN_SLP_TIME_MASK    		0x7E0
#define	GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_SLP_TIME_LEN	        5
#define	GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_SLP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_TCXO_CLK_EN_SLP_TIME_MASK    		0x1F

#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_WKUP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_WKUP_TIME_OFFSET	        12
#define GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_WKUP_TIME_MASK    		0xF000
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_WKUP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_WKUP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_WKUP_TIME_MASK    		0xF00
#define	GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_WKUP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_WKUP_TIME_OFFSET	        4
#define GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_WKUP_TIME_MASK    		0xF0
#define	GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_WKUP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_WKUP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_WKUP_TIME_MASK    		0xF

#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_SLP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_SLP_TIME_OFFSET	        12
#define GLB_CTL_M_RB_LP_DVFS_RC_RC_RCRSTN_SLP_TIME_MASK    		0xF000
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_SLP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_SLP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_RC_RC_PD_SLP_TIME_MASK    		0xF00
#define	GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_SLP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_SLP_TIME_OFFSET	        4
#define GLB_CTL_M_RB_LP_DVFS_RC_RCCLK1_EN_SLP_TIME_MASK    		0xF0
#define	GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_SLP_TIME_LEN	        4
#define	GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_SLP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_RC_CLK_EN_SLP_TIME_MASK    		0xF

#define	GLB_CTL_M_RB_CFG_XO_RC_DVFS_SOFT_RST_N_LEN	        1
#define	GLB_CTL_M_RB_CFG_XO_RC_DVFS_SOFT_RST_N_OFFSET	        8
#define GLB_CTL_M_RB_CFG_XO_RC_DVFS_SOFT_RST_N_MASK    		0x100
#define	GLB_CTL_M_RB_XO_RC_DVFS_BYPASS_LEN	        1
#define	GLB_CTL_M_RB_XO_RC_DVFS_BYPASS_OFFSET	        4
#define GLB_CTL_M_RB_XO_RC_DVFS_BYPASS_MASK    		0x10
#define	GLB_CTL_M_RB_RC_XO_ACK_LEN	        1
#define	GLB_CTL_M_RB_RC_XO_ACK_OFFSET	        3
#define GLB_CTL_M_RB_RC_XO_ACK_MASK    		0x8
#define	GLB_CTL_M_RB_RC_XO_CUR_STS_LEN	        3
#define	GLB_CTL_M_RB_RC_XO_CUR_STS_OFFSET	        0
#define GLB_CTL_M_RB_RC_XO_CUR_STS_MASK    		0x7

#define	GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_WKUP_TIME_OFFSET	        8
#define GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_WKUP_TIME_MASK    		0xFF00
#define	GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_WKUP_TIME_LEN	        8
#define	GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_WKUP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_WKUP_TIME_MASK    		0xFF

#define	GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_SLP_TIME_LEN	        6
#define	GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_SLP_TIME_OFFSET	        5
#define GLB_CTL_M_RB_LP_DVFS_DCXO_XO_CKO_ISO_SLP_TIME_MASK    		0x7E0
#define	GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_SLP_TIME_LEN	        5
#define	GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_SLP_TIME_OFFSET	        0
#define GLB_CTL_M_RB_LP_DVFS_RC_CKO_ISO_SLP_TIME_MASK    		0x1F

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_2_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_2_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_3_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_3_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_SP_RAM_TMOD_3_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_NPU_TP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_0_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_0_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_1_LEN	        16
#define	GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_1_OFFSET	        0
#define GLB_CTL_M_RB_CFG_GLBM_MEM_TP_RAM_TMOD_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_VOL_DECT_LEN	        1
#define	GLB_CTL_M_RB_VOL_DECT_OFFSET	        1
#define GLB_CTL_M_RB_VOL_DECT_MASK    		0x2
#define	GLB_CTL_M_RB_VOL_TEMP_SENSE_N_LEN	        1
#define	GLB_CTL_M_RB_VOL_TEMP_SENSE_N_OFFSET	        0
#define GLB_CTL_M_RB_VOL_TEMP_SENSE_N_MASK    		0x1

#define	GLB_CTL_M_RB_VOL_IRQ_LEN	        1
#define	GLB_CTL_M_RB_VOL_IRQ_OFFSET	        3
#define GLB_CTL_M_RB_VOL_IRQ_MASK    		0x8
#define	GLB_CTL_M_RB_VOL_IRQ_RAW_LEN	        1
#define	GLB_CTL_M_RB_VOL_IRQ_RAW_OFFSET	        2
#define GLB_CTL_M_RB_VOL_IRQ_RAW_MASK    		0x4
#define	GLB_CTL_M_RB_VOL_IRQ_MASK_LEN	        1
#define	GLB_CTL_M_RB_VOL_IRQ_MASK_OFFSET	        1
#define GLB_CTL_M_RB_VOL_IRQ_MASK_MASK    		0x2
#define	GLB_CTL_M_RB_VOL_IRQ_CLR_LEN	        1
#define	GLB_CTL_M_RB_VOL_IRQ_CLR_OFFSET	        0
#define GLB_CTL_M_RB_VOL_IRQ_CLR_MASK    		0x1

#define	GLB_CTL_M_RB_VOL_ICOMP_REG_LEN	        8
#define	GLB_CTL_M_RB_VOL_ICOMP_REG_OFFSET	        0
#define GLB_CTL_M_RB_VOL_ICOMP_REG_MASK    		0xFF

#define	GLB_CTL_M_RB_T_SENSE_CFG_LEN	        9
#define	GLB_CTL_M_RB_T_SENSE_CFG_OFFSET	        6
#define GLB_CTL_M_RB_T_SENSE_CFG_MASK    		0x7FC0
#define	GLB_CTL_M_RB_T_DELAY_CFG_LEN	        6
#define	GLB_CTL_M_RB_T_DELAY_CFG_OFFSET	        0
#define GLB_CTL_M_RB_T_DELAY_CFG_MASK    		0x3F

#define	GLB_CTL_M_RB_ULP_AON_DIAG_SEL_LEN	        1
#define	GLB_CTL_M_RB_ULP_AON_DIAG_SEL_OFFSET	        1
#define GLB_CTL_M_RB_ULP_AON_DIAG_SEL_MASK    		0x2
#define	GLB_CTL_M_RB_AON_MCU_DIAG_SEL_LEN	        1
#define	GLB_CTL_M_RB_AON_MCU_DIAG_SEL_OFFSET	        0
#define GLB_CTL_M_RB_AON_MCU_DIAG_SEL_MASK    		0x1

#define	GLB_CTL_M_RB_GCPU_LOAD_OK_LEN	        4
#define	GLB_CTL_M_RB_GCPU_LOAD_OK_OFFSET	        7
#define GLB_CTL_M_RB_GCPU_LOAD_OK_MASK    		0x780
#define	GLB_CTL_M_RB_GCPU_PCLR_MODE_SEL_LEN	        1
#define	GLB_CTL_M_RB_GCPU_PCLR_MODE_SEL_OFFSET	        2
#define GLB_CTL_M_RB_GCPU_PCLR_MODE_SEL_MASK    		0x4
#define	GLB_CTL_M_RB_GCPU_LOAD_CLR_LEN	        1
#define	GLB_CTL_M_RB_GCPU_LOAD_CLR_OFFSET	        1
#define GLB_CTL_M_RB_GCPU_LOAD_CLR_MASK    		0x2
#define	GLB_CTL_M_RB_GCPU_LOAD_LEN	        1
#define	GLB_CTL_M_RB_GCPU_LOAD_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_LOAD_MASK    		0x1

#define	GLB_CTL_M_RB_GCPU_PCLR_EN_LEN	        5
#define	GLB_CTL_M_RB_GCPU_PCLR_EN_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_PCLR_EN_MASK    		0x1F

#define	GLB_CTL_M_RB_GCPU_PC_L_LEN	        16
#define	GLB_CTL_M_RB_GCPU_PC_L_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_PC_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GCPU_PC_H_LEN	        16
#define	GLB_CTL_M_RB_GCPU_PC_H_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_PC_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GCPU_LR_L_LEN	        16
#define	GLB_CTL_M_RB_GCPU_LR_L_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_LR_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GCPU_LR_H_LEN	        16
#define	GLB_CTL_M_RB_GCPU_LR_H_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_LR_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GCPU_SP_L_LEN	        16
#define	GLB_CTL_M_RB_GCPU_SP_L_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_SP_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_GCPU_SP_H_LEN	        16
#define	GLB_CTL_M_RB_GCPU_SP_H_OFFSET	        0
#define GLB_CTL_M_RB_GCPU_SP_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_LOAD_OK_LEN	        3
#define	GLB_CTL_M_RB_MCPU_LOAD_OK_OFFSET	        7
#define GLB_CTL_M_RB_MCPU_LOAD_OK_MASK    		0x380
#define	GLB_CTL_M_RB_MCPU_PCLR_MODE_SEL_LEN	        1
#define	GLB_CTL_M_RB_MCPU_PCLR_MODE_SEL_OFFSET	        2
#define GLB_CTL_M_RB_MCPU_PCLR_MODE_SEL_MASK    		0x4
#define	GLB_CTL_M_RB_MCPU_LOAD_CLR_LEN	        1
#define	GLB_CTL_M_RB_MCPU_LOAD_CLR_OFFSET	        1
#define GLB_CTL_M_RB_MCPU_LOAD_CLR_MASK    		0x2
#define	GLB_CTL_M_RB_MCPU_LOAD_LEN	        1
#define	GLB_CTL_M_RB_MCPU_LOAD_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_LOAD_MASK    		0x1

#define	GLB_CTL_M_RB_MCPU_PCLR_EN_LEN	        3
#define	GLB_CTL_M_RB_MCPU_PCLR_EN_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_PCLR_EN_MASK    		0x7

#define	GLB_CTL_M_RB_MCPU_PC_L_LEN	        16
#define	GLB_CTL_M_RB_MCPU_PC_L_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_PC_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_PC_H_LEN	        16
#define	GLB_CTL_M_RB_MCPU_PC_H_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_PC_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_LR_L_LEN	        16
#define	GLB_CTL_M_RB_MCPU_LR_L_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_LR_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_LR_H_LEN	        16
#define	GLB_CTL_M_RB_MCPU_LR_H_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_LR_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_SP_L_LEN	        16
#define	GLB_CTL_M_RB_MCPU_SP_L_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_SP_L_MASK    		0xFFFF

#define	GLB_CTL_M_RB_MCPU_SP_H_LEN	        16
#define	GLB_CTL_M_RB_MCPU_SP_H_OFFSET	        0
#define GLB_CTL_M_RB_MCPU_SP_H_MASK    		0xFFFF

#define	GLB_CTL_M_RB_DAP_LINK_EN_LEN	        3
#define	GLB_CTL_M_RB_DAP_LINK_EN_OFFSET	        0
#define GLB_CTL_M_RB_DAP_LINK_EN_MASK    		0x7

#define	GLB_CTL_M_RB_DAP_CFG_LOCK_LEN	        1
#define	GLB_CTL_M_RB_DAP_CFG_LOCK_OFFSET	        0
#define GLB_CTL_M_RB_DAP_CFG_LOCK_MASK    		0x1

#define	GLB_CTL_M_RB_SYS_TICK_STZ_GLOAB_LEN	        1
#define	GLB_CTL_M_RB_SYS_TICK_STZ_GLOAB_OFFSET	        5
#define GLB_CTL_M_RB_SYS_TICK_STZ_GLOAB_MASK    		0x20
#define	GLB_CTL_M_RB_SYS_TICK_CLR_M_VALID_LEN	        1
#define	GLB_CTL_M_RB_SYS_TICK_CLR_M_VALID_OFFSET	        4
#define GLB_CTL_M_RB_SYS_TICK_CLR_M_VALID_MASK    		0x10
#define	GLB_CTL_M_RB_SYS_TICK_STZ_M_LEN	        1
#define	GLB_CTL_M_RB_SYS_TICK_STZ_M_OFFSET	        1
#define GLB_CTL_M_RB_SYS_TICK_STZ_M_MASK    		0x2
#define	GLB_CTL_M_RB_SYS_TICK_FRZ_M_LEN	        1
#define	GLB_CTL_M_RB_SYS_TICK_FRZ_M_OFFSET	        0
#define GLB_CTL_M_RB_SYS_TICK_FRZ_M_MASK    		0x1

#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_0_LEN	        16
#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_0_OFFSET	        0
#define GLB_CTL_M_RB_SYS_TICK_VALUE_M_0_MASK    		0xFFFF

#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_1_LEN	        16
#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_1_OFFSET	        0
#define GLB_CTL_M_RB_SYS_TICK_VALUE_M_1_MASK    		0xFFFF

#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_2_LEN	        16
#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_2_OFFSET	        0
#define GLB_CTL_M_RB_SYS_TICK_VALUE_M_2_MASK    		0xFFFF

#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_3_LEN	        16
#define	GLB_CTL_M_RB_SYS_TICK_VALUE_M_3_OFFSET	        0
#define GLB_CTL_M_RB_SYS_TICK_VALUE_M_3_MASK    		0xFFFF

#endif // __3322_GLB_CTL_M_RB_REG_OFFSET_FIELD_H__
