/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_cfg_s_mgpio_mode_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_CFG_S_MGPIO_MODE_REG_OFFSET_FIELD_H__
#define __3322_CFG_S_MGPIO_MODE_REG_OFFSET_FIELD_H__

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO0_MODE_LEN	        1
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO0_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO0_MODE_MASK    		0x1

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO1_MODE_LEN	        1
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO1_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO1_MODE_MASK    		0x1

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO2_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO2_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO2_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO3_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO3_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO3_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO4_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO4_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO4_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO5_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO5_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO5_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO6_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO6_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO6_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO7_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO7_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO7_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO8_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO8_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO8_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO9_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO9_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO9_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO10_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO10_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO10_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO11_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO11_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO11_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO12_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO12_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO12_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO13_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO13_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO13_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO14_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO14_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO14_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO15_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO15_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO15_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO16_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO16_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO16_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO17_MODE_LEN	        1
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO17_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO17_MODE_MASK    		0x1

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO18_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO18_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO18_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO19_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO19_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO19_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO20_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO20_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO20_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO21_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO21_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO21_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO22_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO22_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO22_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO23_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO23_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO23_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO24_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO24_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO24_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO25_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO25_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO25_MODE_MASK    		0x3

#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO26_MODE_LEN	        2
#define	CFG_S_MGPIO_MODE_CFG_S_MGPIO26_MODE_OFFSET	        0
#define CFG_S_MGPIO_MODE_CFG_S_MGPIO26_MODE_MASK    		0x3

#endif // __3322_CFG_S_MGPIO_MODE_REG_OFFSET_FIELD_H__
