/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_bt_diag_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_BT_DIAG_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_BT_DIAG_CTL_RB_REG_OFFSET_FIELD_H__

#define	BT_DIAG_CTL_RB_BT_DIAG_CTL_ID_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_CTL_ID_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_CTL_ID_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG0_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG0_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_GP_REG0_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG1_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG1_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_GP_REG1_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG2_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG2_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_GP_REG2_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG3_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_GP_REG3_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_GP_REG3_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_CFG_B_RAM_SEL_ONEHOT_LEN	        3
#define	BT_DIAG_CTL_RB_CFG_B_RAM_SEL_ONEHOT_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_B_RAM_SEL_ONEHOT_MASK    		0x7

#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_SEL_LEN	        2
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_SEL_OFFSET	        8
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_SEL_MASK    		0x300
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_NODE_SEL_LEN	        6
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_NODE_SEL_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_NODE_SEL_MASK    		0x3F

#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_PULSE_SYNC_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_PULSE_SYNC_OFFSET	        9
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_PULSE_SYNC_MASK    		0x200
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_EN_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_EN_OFFSET	        8
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_EN_MASK    		0x100
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_MODE_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_MODE_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_MODE_MASK    		0x1

#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_LENGTH_LEN	        16
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_LENGTH_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_LENGTH_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_H_LEN	        3
#define	BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_BT_DIAG_SAMPLE_START_ADDR_H_MASK    		0x7

#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_H_LEN	        16
#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_ADDR_H_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BT_SAMPLE_MEM_WR_STS_LEN	        1
#define	BT_DIAG_CTL_RB_BT_SAMPLE_MEM_WR_STS_OFFSET	        1
#define BT_DIAG_CTL_RB_BT_SAMPLE_MEM_WR_STS_MASK    		0x2
#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_LEN	        1
#define	BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_OFFSET	        0
#define BT_DIAG_CTL_RB_BT_DIAG_SAMPLE_DONE_MASK    		0x1

#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_SEL_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_SEL_OFFSET	        8
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_SEL_MASK    		0x100
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_NODE_SEL_LEN	        6
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_NODE_SEL_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_NODE_SEL_MASK    		0x3F

#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_PULSE_SYNC_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_PULSE_SYNC_OFFSET	        9
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_PULSE_SYNC_MASK    		0x200
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_EN_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_EN_OFFSET	        8
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_EN_MASK    		0x100
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_MODE_LEN	        1
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_MODE_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_MODE_MASK    		0x1

#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_LENGTH_LEN	        16
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_LENGTH_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_LENGTH_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_H_LEN	        3
#define	BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_CFG_TEST_GEN_START_ADDR_H_MASK    		0x7

#define	BT_DIAG_CTL_RB_GEN_DONE_ADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_GEN_DONE_ADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_GEN_DONE_ADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_GEN_DONE_ADDR_H_LEN	        16
#define	BT_DIAG_CTL_RB_GEN_DONE_ADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_GEN_DONE_ADDR_H_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_GEN_DONE_LEN	        1
#define	BT_DIAG_CTL_RB_GEN_DONE_OFFSET	        0
#define BT_DIAG_CTL_RB_GEN_DONE_MASK    		0x1

#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_EMPTY_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_EMPTY_OFFSET	        1
#define BT_DIAG_CTL_RB_BFG_GEN_FIFO_EMPTY_MASK    		0x2
#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_EMPTY_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_EMPTY_OFFSET	        0
#define BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_EMPTY_MASK    		0x1

#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_STS_CLR_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_STS_CLR_OFFSET	        1
#define BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_STS_CLR_MASK    		0x2
#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_OVERFLOW_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_OVERFLOW_OFFSET	        0
#define BT_DIAG_CTL_RB_BFG_SAMPLE_FIFO_OVERFLOW_MASK    		0x1

#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_STS_CLR_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_STS_CLR_OFFSET	        1
#define BT_DIAG_CTL_RB_BFG_GEN_FIFO_STS_CLR_MASK    		0x2
#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_UNDERFLOW_LEN	        1
#define	BT_DIAG_CTL_RB_BFG_GEN_FIFO_UNDERFLOW_OFFSET	        0
#define BT_DIAG_CTL_RB_BFG_GEN_FIFO_UNDERFLOW_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_OFFSET	        2
#define BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_MASK    		0x4
#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_CLR_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_CLR_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_CLR_MASK    		0x2
#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_EN_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_EN_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_I_AHBBUS_ERR_INT_EN_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_I_HADDR_H_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_I_HADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_I_HADDR_H_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_I_HADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_I_HADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_I_HADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_I_HBURST_LEN	        4
#define	BT_DIAG_CTL_RB_BCPU_I_HBURST_OFFSET	        4
#define BT_DIAG_CTL_RB_BCPU_I_HBURST_MASK    		0xF0
#define	BT_DIAG_CTL_RB_BCPU_I_HSIZE_LEN	        3
#define	BT_DIAG_CTL_RB_BCPU_I_HSIZE_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_I_HSIZE_MASK    		0xE
#define	BT_DIAG_CTL_RB_BCPU_I_HWRITE_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_I_HWRITE_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_I_HWRITE_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_OFFSET	        2
#define BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_MASK    		0x4
#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_CLR_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_CLR_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_CLR_MASK    		0x2
#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_EN_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_EN_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_D_AHBBUS_ERR_INT_EN_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_D_HADDR_H_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_D_HADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_D_HADDR_H_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_D_HADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_D_HADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_D_HADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_D_HBURST_LEN	        4
#define	BT_DIAG_CTL_RB_BCPU_D_HBURST_OFFSET	        4
#define BT_DIAG_CTL_RB_BCPU_D_HBURST_MASK    		0xF0
#define	BT_DIAG_CTL_RB_BCPU_D_HSIZE_LEN	        3
#define	BT_DIAG_CTL_RB_BCPU_D_HSIZE_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_D_HSIZE_MASK    		0xE
#define	BT_DIAG_CTL_RB_BCPU_D_HWRITE_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_D_HWRITE_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_D_HWRITE_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_OFFSET	        2
#define BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_MASK    		0x4
#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_CLR_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_CLR_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_CLR_MASK    		0x2
#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_EN_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_EN_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_S_AHBBUS_ERR_INT_EN_MASK    		0x1

#define	BT_DIAG_CTL_RB_BCPU_S_HADDR_H_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_S_HADDR_H_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_S_HADDR_H_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_S_HADDR_L_LEN	        16
#define	BT_DIAG_CTL_RB_BCPU_S_HADDR_L_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_S_HADDR_L_MASK    		0xFFFF

#define	BT_DIAG_CTL_RB_BCPU_S_HBURST_LEN	        4
#define	BT_DIAG_CTL_RB_BCPU_S_HBURST_OFFSET	        4
#define BT_DIAG_CTL_RB_BCPU_S_HBURST_MASK    		0xF0
#define	BT_DIAG_CTL_RB_BCPU_S_HSIZE_LEN	        3
#define	BT_DIAG_CTL_RB_BCPU_S_HSIZE_OFFSET	        1
#define BT_DIAG_CTL_RB_BCPU_S_HSIZE_MASK    		0xE
#define	BT_DIAG_CTL_RB_BCPU_S_HWRITE_LEN	        1
#define	BT_DIAG_CTL_RB_BCPU_S_HWRITE_OFFSET	        0
#define BT_DIAG_CTL_RB_BCPU_S_HWRITE_MASK    		0x1

#endif // __3322_BT_DIAG_CTL_RB_REG_OFFSET_FIELD_H__
