/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_ulp_aon_fuse_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_FIELD_H__

#define	ULP_AON_FUSE_CTL_RB_EFUSE_CTL_ID_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE_CTL_ID_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE_CTL_ID_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG0_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG0_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG0_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG1_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG1_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE_ULP_GP_REG1_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_BOOT_DONE_STS_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_BOOT_DONE_STS_OFFSET	        3
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_BOOT_DONE_STS_MASK    		0x8
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_BOOT_DONE_STS_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_BOOT_DONE_STS_OFFSET	        2
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_BOOT_DONE_STS_MASK    		0x4
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_BOOT_DONE_STS_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_BOOT_DONE_STS_OFFSET	        1
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_BOOT_DONE_STS_MASK    		0x2
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_BOOT_DONE_STS_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_BOOT_DONE_STS_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_BOOT_DONE_STS_MASK    		0x1

#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_AUTO_RD_EN_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_AUTO_RD_EN_OFFSET	        3
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_SEC_AUTO_RD_EN_MASK    		0x8
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_AUTO_RD_EN_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_AUTO_RD_EN_OFFSET	        2
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_SEC_AUTO_RD_EN_MASK    		0x4
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_AUTO_RD_EN_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_AUTO_RD_EN_OFFSET	        1
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE1_AUTO_RD_EN_MASK    		0x2
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_AUTO_RD_EN_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_AUTO_RD_EN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_AON_SUB_EFUSE0_AUTO_RD_EN_MASK    		0x1

#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_MAN_OFFSET	        12
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_MAN_MASK    		0xF000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_MAN_MASK    		0xF00
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_MAN_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_MAN_MASK    		0xF0
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_MAN_MASK    		0xF

#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_MAN_OFFSET	        12
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_MAN_MASK    		0xF000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_MAN_MASK    		0xF00
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_MAN_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_MAN_MASK    		0xF0
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_MAN_MASK    		0xF

#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_MAN_MASK    		0xF00
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_MAN_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_MAN_MASK    		0xF0
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_MAN_MASK    		0xF

#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_SEL_OFFSET	        10
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK0_BUFFER_TRIM_SEL_MASK    		0x400
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_SEL_OFFSET	        9
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK1_BUFFER_TRIM_SEL_MASK    		0x200
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_SEL_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_BUCK2_BUFFER_TRIM_SEL_MASK    		0x100
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_SEL_OFFSET	        7
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO1_TRIM_SEL_MASK    		0x80
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_SEL_OFFSET	        6
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO1_TRIM_SEL_MASK    		0x40
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_SEL_OFFSET	        5
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO2_TRIM_SEL_MASK    		0x20
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_SEL_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO3_TRIM_SEL_MASK    		0x10
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_SEL_OFFSET	        3
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO5_TRIM_SEL_MASK    		0x8
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_SEL_OFFSET	        2
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO6_TRIM_SEL_MASK    		0x4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_SEL_OFFSET	        1
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_IOLDO7_TRIM_SEL_MASK    		0x2
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_SEL_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_CLDO2_TRIM_SEL_MASK    		0x1

#define	ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_SEL_OFFSET	        11
#define ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_SEL_MASK    		0x800
#define	ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVED_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVED_SEL_OFFSET	        10
#define ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVED_SEL_MASK    		0x400
#define	ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_SEL_OFFSET	        9
#define ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_SEL_MASK    		0x200
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_SEL_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_SEL_MASK    		0x100
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_SEL_OFFSET	        7
#define ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_SEL_MASK    		0x80
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_SEL_OFFSET	        6
#define ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_SEL_MASK    		0x40
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_SEL_OFFSET	        5
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_SEL_MASK    		0x20
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_SEL_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_SEL_MASK    		0x10
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_SEL_OFFSET	        3
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_SEL_MASK    		0x8
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_SEL_OFFSET	        2
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_SEL_MASK    		0x4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_SEL_OFFSET	        1
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_SEL_MASK    		0x2
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_SEL_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_SEL_MASK    		0x1

#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_MAN_OFFSET	        28
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_ANALDO0_TRIM_MAN_MASK    		0xF0000000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_MAN_OFFSET	        24
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_XLDO0_TRIM_MAN_MASK    		0xF000000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_MAN_OFFSET	        20
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_PALDO0_TRIM_MAN_MASK    		0xF00000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_MAN_LEN	        4
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_MAN_OFFSET	        16
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_INTLDO2_TRIM_MAN_MASK    		0xF0000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_MAN_LEN	        8
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_IBG_TRIM_MAN_MASK    		0xFF00
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_MAN_LEN	        8
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU_LNREF_VREF_TRIM_MAN_MASK    		0xFF

#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_MAN_LEN	        16
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_MAN_OFFSET	        16
#define ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_CTRIM_MAN_MASK    		0xFFFF0000
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_MAN_LEN	        16
#define	ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_PMU2_TRIM_RSV_MAN_MASK    		0xFFFF

#define	ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_MAN_LEN	        16
#define	ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_MAN_OFFSET	        16
#define ULP_AON_FUSE_CTL_RB_CFG_RC_TRIM_MAN_MASK    		0xFFFF0000
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_MAN_LEN	        16
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_XO_CORE_ITRIM_MAN_MASK    		0xFFFF

#define	ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_XO_RC_SEL_MAN_MASK    		0x100
#define	ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVE_MAN_LEN	        8
#define	ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVE_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_CMU_RESERVE_MAN_MASK    		0xFF

#define	ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_LEN	        5
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_OFFSET	        6
#define ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_MASK    		0x7C0
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_SEL_OFFSET	        5
#define ULP_AON_FUSE_CTL_RB_CFG_RF_ADCLDO_TRIM_MAN_SEL_MASK    		0x20
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_SEL_OFFSET	        4
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_SEL_MASK    		0x10
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_SEL_OFFSET	        3
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_SEL_MASK    		0x8
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_SEL_OFFSET	        2
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_SEL_MASK    		0x4
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_SEL_OFFSET	        1
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_SEL_MASK    		0x2
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_SEL_LEN	        1
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_SEL_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_SEL_MASK    		0x1

#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_LEN	        5
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_OFFSET	        23
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO7_TRIM_MAN_MASK    		0xF800000
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_LEN	        5
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_OFFSET	        18
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO5_TRIM_MAN_MASK    		0x7C0000
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_LEN	        5
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_OFFSET	        13
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO4_TRIM_MAN_MASK    		0x3E000
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_LEN	        5
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_OFFSET	        8
#define ULP_AON_FUSE_CTL_RB_CFG_RF_LDO3_TRIM_MAN_MASK    		0x1F00
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_LEN	        8
#define	ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_CFG_RF_PALDO_TRIM_MAN_MASK    		0xFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_0_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_0_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_0_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_1_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_1_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_1_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_2_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_2_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_2_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_3_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_3_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_3_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_4_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_4_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_4_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_5_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_5_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_5_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_6_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_6_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_6_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_7_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_7_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_7_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_8_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_8_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_8_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_9_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_9_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_9_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_10_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_10_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_BOOTDATA_RB_10_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_0_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_0_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_0_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_1_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_1_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_1_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_2_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_2_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_2_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_3_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_3_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_3_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_4_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_4_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_4_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_5_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_5_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_5_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_6_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_6_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_6_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_7_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_7_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_7_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_8_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_8_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_8_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_9_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_9_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_9_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_10_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_10_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_10_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_11_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_11_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_11_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_12_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_12_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_12_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_13_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_13_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_13_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_14_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_14_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_14_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_15_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_15_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_15_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_16_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_16_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_16_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_17_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_17_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_17_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_18_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_18_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_18_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_19_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_19_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_19_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_20_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_20_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_20_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_21_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_21_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_21_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_22_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_22_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_22_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_23_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_23_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_23_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_24_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_24_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_24_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_25_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_25_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_25_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_26_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_26_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_26_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_27_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_27_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_27_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_BOOTDATA_RB_12_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_BOOTDATA_RB_12_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_BOOTDATA_RB_12_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_0_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_0_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_0_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_1_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_1_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_1_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_2_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_2_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_2_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_3_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_3_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_3_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_4_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_4_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_4_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_5_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_5_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_5_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_6_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_6_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_6_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_7_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_7_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_7_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_8_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_8_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_8_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_9_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_9_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_9_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_10_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_10_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_10_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_11_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_11_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_11_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_12_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_12_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_12_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_13_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_13_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_13_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_14_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_14_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_14_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_15_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_15_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_15_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_16_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_16_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_16_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_17_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_17_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_17_MASK    		0xFFFFFFFF

#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_18_LEN	        32
#define	ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_18_OFFSET	        0
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_18_MASK    		0xFFFFFFFF

#endif // __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_FIELD_H__
