/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_bcpu_trace_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_BCPU_TRACE_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_BCPU_TRACE_CTL_RB_REG_OFFSET_FIELD_H__

#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_CTL_ID_LEN	        16
#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_CTL_ID_OFFSET	        0
#define BCPU_TRACE_CTL_RB_BCPU_TRACE_CTL_ID_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG0_LEN	        16
#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG0_OFFSET	        0
#define BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG0_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG1_LEN	        16
#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG1_OFFSET	        0
#define BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG1_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG2_LEN	        16
#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG2_OFFSET	        0
#define BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG2_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG3_LEN	        16
#define	BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG3_OFFSET	        0
#define BCPU_TRACE_CTL_RB_BCPU_TRACE_GP_REG3_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_TRACE_SAVE_SEL_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_TRACE_SAVE_SEL_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_TRACE_SAVE_SEL_MASK    		0x1

#define	BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_EN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_EN_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_EN_MASK    		0x1

#define	BCPU_TRACE_CTL_RB_CFG_TRACE_MEM_CLKEN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_TRACE_MEM_CLKEN_OFFSET	        4
#define BCPU_TRACE_CTL_RB_CFG_TRACE_MEM_CLKEN_MASK    		0x10
#define	BCPU_TRACE_CTL_RB_CFG_BCPU_CLKEN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_BCPU_CLKEN_OFFSET	        3
#define BCPU_TRACE_CTL_RB_CFG_BCPU_CLKEN_MASK    		0x8
#define	BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_CLKEN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_CLKEN_OFFSET	        2
#define BCPU_TRACE_CTL_RB_CFG_CPU_TRACE_CLKEN_MASK    		0x4
#define	BCPU_TRACE_CTL_RB_CFG_MONITOR_SRC_CLKEN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_MONITOR_SRC_CLKEN_OFFSET	        1
#define BCPU_TRACE_CTL_RB_CFG_MONITOR_SRC_CLKEN_MASK    		0x2
#define	BCPU_TRACE_CTL_RB_CFG_MONITOR_WR_CLKEN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_MONITOR_WR_CLKEN_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_MONITOR_WR_CLKEN_MASK    		0x1

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_SYNC_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_SYNC_OFFSET	        9
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_SYNC_MASK    		0x200
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_EN_LEN	        1
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_EN_OFFSET	        8
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_EN_MASK    		0x100
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_MODE_LEN	        2
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_MODE_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_MODE_MASK    		0x3

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_L_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_L_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_L_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_H_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_H_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_LENGTH_H_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_L_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_L_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_L_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_H_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_H_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_START_ADDR_H_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_L_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_L_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_L_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_H_LEN	        16
#define	BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_H_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CFG_SAMPLE_END_ADDR_H_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_L_LEN	        16
#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_L_OFFSET	        0
#define BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_L_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_H_LEN	        16
#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_H_OFFSET	        0
#define BCPU_TRACE_CTL_RB_SAMPLE_DONE_ADDR_H_MASK    		0xFFFF

#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_LEN	        1
#define	BCPU_TRACE_CTL_RB_SAMPLE_DONE_OFFSET	        0
#define BCPU_TRACE_CTL_RB_SAMPLE_DONE_MASK    		0x1

#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_EMPTY_LEN	        1
#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_EMPTY_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_EMPTY_MASK    		0x1

#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_STS_CLR_LEN	        1
#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_STS_CLR_OFFSET	        1
#define BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_STS_CLR_MASK    		0x2
#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_OVERFLOW_LEN	        1
#define	BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_OVERFLOW_OFFSET	        0
#define BCPU_TRACE_CTL_RB_CPU_TRACE_FIFO_OVERFLOW_MASK    		0x1

#endif // __3322_BCPU_TRACE_CTL_RB_REG_OFFSET_FIELD_H__
