/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_xip_cache_ctl_rb_reg_offset.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_XIP_CACHE_CTL_RB_REG_OFFSET_H__
#define __3322_XIP_CACHE_CTL_RB_REG_OFFSET_H__

/* XIP_CACHE_CTL_RB Base address of Module's Register */
#define XIP_CACHE_CTL_RB_BASE                       (0x520F1000)

/******************************************************************************/
/*                      XIP_CACHE_CTL_RB Registers' Definitions                            */
/******************************************************************************/

#define XIP_CACHE_CTL_RB_XIP_CACHE_CTL_ID_REG            (XIP_CACHE_CTL_RB_BASE + 0x0)   /* XIP CACHE CTL ID寄存器 */
#define XIP_CACHE_CTL_RB_XIP_GP_REG0_REG                 (XIP_CACHE_CTL_RB_BASE + 0x10)  /* 通用寄存器 */
#define XIP_CACHE_CTL_RB_XIP_GP_REG1_REG                 (XIP_CACHE_CTL_RB_BASE + 0x14)  /* 通用寄存器 */
#define XIP_CACHE_CTL_RB_XIP_GP_REG2_REG                 (XIP_CACHE_CTL_RB_BASE + 0x18)  /* 通用寄存器 */
#define XIP_CACHE_CTL_RB_XIP_GP_REG3_REG                 (XIP_CACHE_CTL_RB_BASE + 0x1C)  /* 通用寄存器 */
#define XIP_CACHE_CTL_RB_MEM_CLKEN0_REG                  (XIP_CACHE_CTL_RB_BASE + 0x20)  /* 时钟使能 */
#define XIP_CACHE_CTL_RB_MEM_CLKEN1_REG                  (XIP_CACHE_CTL_RB_BASE + 0x24)  /* 时钟使能 */
#define XIP_CACHE_CTL_RB_MEM_SOFT_RST_N_REG              (XIP_CACHE_CTL_RB_BASE + 0x30)
#define XIP_CACHE_CTL_RB_AXI_2TO1_MUX_SEL_REG            (XIP_CACHE_CTL_RB_BASE + 0x50)  /* 访问MEM_SUB权限选择 */
#define XIP_CACHE_CTL_RB_AUTO_CG_BYPASS_REG              (XIP_CACHE_CTL_RB_BASE + 0x60)  /* AUTO_CG配置 */
#define XIP_CACHE_CTL_RB_PSRAM_CTL_DDRCA_EN_REG          (XIP_CACHE_CTL_RB_BASE + 0x64)  /* PSRAM配置 */
#define XIP_CACHE_CTL_RB_PSRAM_RANDOM_REE0_REG           (XIP_CACHE_CTL_RB_BASE + 0x68)  /* PSRAM配置 */
#define XIP_CACHE_CTL_RB_PSRAM_RANDOM_REE1_REG           (XIP_CACHE_CTL_RB_BASE + 0x6C)  /* PSRAM配置 */
#define XIP_CACHE_CTL_RB_PSRAM_RANDOM_REE2_REG           (XIP_CACHE_CTL_RB_BASE + 0x70)  /* PSRAM配置 */
#define XIP_CACHE_CTL_RB_PSRAM_RANDOM_REE3_REG           (XIP_CACHE_CTL_RB_BASE + 0x74)  /* PSRAM配置 */
#define XIP_CACHE_CTL_RB_MEM_SUB_GATING_CONFIGURE_REG    (XIP_CACHE_CTL_RB_BASE + 0x700) /* 时钟门控配置寄存器 */
#define XIP_CACHE_CTL_RB_XIP_SUB_DIAG_EN_REG             (XIP_CACHE_CTL_RB_BASE + 0x710) /* XIP数采使能配置寄存器 */
#define XIP_CACHE_CTL_RB_XIP_SUB_DIAG_INFO_REG           (XIP_CACHE_CTL_RB_BASE + 0x714) /* XIP数采状态寄存器 */
#define XIP_CACHE_CTL_RB_XIP_SUB_DIAG_CLKEN_REG          (XIP_CACHE_CTL_RB_BASE + 0x718) /* XIP数采时钟使能配置寄存器 */
#define XIP_CACHE_CTL_RB_IO_MUX_SEL_REG                  (XIP_CACHE_CTL_RB_BASE + 0x720) /* PSRAM 数字模拟IO选择配置寄存器 */
#define XIP_CACHE_CTL_RB_MEM_IO_TEST0_REG                (XIP_CACHE_CTL_RB_BASE + 0x724) /* MEM IO test存器0 */
#define XIP_CACHE_CTL_RB_MEM_IO_TEST1_REG                (XIP_CACHE_CTL_RB_BASE + 0x728) /* MEM IO test存器1 */
#define XIP_CACHE_CTL_RB_MEM_IO_TEST2_REG                (XIP_CACHE_CTL_RB_BASE + 0x72C) /* MEM IO test存器2 */
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_0_REG            (XIP_CACHE_CTL_RB_BASE + 0x820) /* 内存监控开关寄存器 */
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_0_REG        (XIP_CACHE_CTL_RB_BASE + 0x824) /* 内存监控一级中断状态查询寄存器 */
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_MASK_0_REG   (XIP_CACHE_CTL_RB_BASE + 0x828)
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_STS_0_REG    (XIP_CACHE_CTL_RB_BASE + 0x82C)
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_CLR_0_REG    (XIP_CACHE_CTL_RB_BASE + 0x830)
#define XIP_CACHE_CTL_RB_MEM_REC_ADDR_L_0_REG            (XIP_CACHE_CTL_RB_BASE + 0x834)
#define XIP_CACHE_CTL_RB_MEM_REC_ADDR_H_0_REG            (XIP_CACHE_CTL_RB_BASE + 0x838)
#define XIP_CACHE_CTL_RB_MEM_REC_ID_0_REG                (XIP_CACHE_CTL_RB_BASE + 0x83C)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR_EN_0_REG   (XIP_CACHE_CTL_RB_BASE + 0x840)
#define XIP_CACHE_CTL_RB_MEM_PKT_MONITOR_INT_DLY_0_REG   (XIP_CACHE_CTL_RB_BASE + 0x844)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_L_0_REG (XIP_CACHE_CTL_RB_BASE + 0x848)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_H_0_REG (XIP_CACHE_CTL_RB_BASE + 0x84C)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_L_0_REG (XIP_CACHE_CTL_RB_BASE + 0x850)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_H_0_REG (XIP_CACHE_CTL_RB_BASE + 0x854)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_L_0_REG (XIP_CACHE_CTL_RB_BASE + 0x858)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_H_0_REG (XIP_CACHE_CTL_RB_BASE + 0x85C)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_L_0_REG (XIP_CACHE_CTL_RB_BASE + 0x860)
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_H_0_REG (XIP_CACHE_CTL_RB_BASE + 0x864)
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_2_REG            (XIP_CACHE_CTL_RB_BASE + 0xA20) /* 内存监控开关寄存器 */
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_2_REG            (XIP_CACHE_CTL_RB_BASE + 0xA24) /* 内存监控一级中断状态查询寄存器 */
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_2_REG       (XIP_CACHE_CTL_RB_BASE + 0xA28)
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_2_REG        (XIP_CACHE_CTL_RB_BASE + 0xA2C)
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_2_REG        (XIP_CACHE_CTL_RB_BASE + 0xA30)
#define XIP_CACHE_CTL_RB_REC_ADDR_L_2_REG                (XIP_CACHE_CTL_RB_BASE + 0xA34)
#define XIP_CACHE_CTL_RB_REC_ADDR_H_2_REG                (XIP_CACHE_CTL_RB_BASE + 0xA38)
#define XIP_CACHE_CTL_RB_REC_ID_2_REG                    (XIP_CACHE_CTL_RB_BASE + 0xA3C)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_2_REG       (XIP_CACHE_CTL_RB_BASE + 0xA40)
#define XIP_CACHE_CTL_RB_PKT_MONITOR_INT_DLY_2_REG       (XIP_CACHE_CTL_RB_BASE + 0xA44)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA48)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA4C)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA50)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA54)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA58)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA5C)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA60)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_2_REG     (XIP_CACHE_CTL_RB_BASE + 0xA64)
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_3_REG            (XIP_CACHE_CTL_RB_BASE + 0xA70) /* 内存监控开关寄存器 */
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_3_REG            (XIP_CACHE_CTL_RB_BASE + 0xA74) /* 内存监控一级中断状态查询寄存器 */
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_3_REG       (XIP_CACHE_CTL_RB_BASE + 0xA78)
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_3_REG        (XIP_CACHE_CTL_RB_BASE + 0xA7C)
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_3_REG        (XIP_CACHE_CTL_RB_BASE + 0xA80)
#define XIP_CACHE_CTL_RB_REC_ADDR_L_3_REG                (XIP_CACHE_CTL_RB_BASE + 0xA84)
#define XIP_CACHE_CTL_RB_REC_ADDR_H_3_REG                (XIP_CACHE_CTL_RB_BASE + 0xA88)
#define XIP_CACHE_CTL_RB_REC_ID_3_REG                    (XIP_CACHE_CTL_RB_BASE + 0xA8C)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_3_REG       (XIP_CACHE_CTL_RB_BASE + 0xA90)
#define XIP_CACHE_CTL_RB_PKT_MONITOR_INT_DLY_3_REG       (XIP_CACHE_CTL_RB_BASE + 0xA94)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xA98)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xA9C)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAA0)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAA4)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAA8)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAAC)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAB0)
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_3_REG     (XIP_CACHE_CTL_RB_BASE + 0xAB4)
#define XIP_CACHE_CTL_RB_BUS_PRIORITY_10_REG             (XIP_CACHE_CTL_RB_BASE + 0xD5C)
#define XIP_CACHE_CTL_RB_BUS_PRIORITY_11_REG             (XIP_CACHE_CTL_RB_BASE + 0xD60)
#define XIP_CACHE_CTL_RB_BUS_PRIORITY_12_REG             (XIP_CACHE_CTL_RB_BASE + 0xD64)
#define XIP_CACHE_CTL_RB_BUS_PRIORITY_13_REG             (XIP_CACHE_CTL_RB_BASE + 0xD68)
#define XIP_CACHE_CTL_RB_MEM_SHARE_CTRL_REG              (XIP_CACHE_CTL_RB_BASE + 0xD6C)
#define XIP_CACHE_CTL_RB_MEM_SHARE_CTRL_GT_REG           (XIP_CACHE_CTL_RB_BASE + 0xD70)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_0_REG          (XIP_CACHE_CTL_RB_BASE + 0xD74)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_1_REG          (XIP_CACHE_CTL_RB_BASE + 0xD78)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_2_REG          (XIP_CACHE_CTL_RB_BASE + 0xD7C)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_3_REG          (XIP_CACHE_CTL_RB_BASE + 0xD80)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_4_REG          (XIP_CACHE_CTL_RB_BASE + 0xD84)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_5_REG          (XIP_CACHE_CTL_RB_BASE + 0xD88)
#define XIP_CACHE_CTL_RB_MAIN_AXI_MONITOR_6_REG          (XIP_CACHE_CTL_RB_BASE + 0xD8C)
#define XIP_CACHE_CTL_RB_MEM_BUS_PKT_ADAPT_REG           (XIP_CACHE_CTL_RB_BASE + 0xD90)
#define XIP_CACHE_CTL_RB_MEM_SD_DS_DIAG_0_REG            (XIP_CACHE_CTL_RB_BASE + 0xD94)
#define XIP_CACHE_CTL_RB_MEM_SD_DS_DIAG_1_REG            (XIP_CACHE_CTL_RB_BASE + 0xD98)
#define XIP_CACHE_CTL_RB_MEM_SD_DS_DIAG_2_REG            (XIP_CACHE_CTL_RB_BASE + 0xD9C)
#define XIP_CACHE_CTL_RB_QSPI2_CUR_STS_REG               (XIP_CACHE_CTL_RB_BASE + 0xDA0) /* 时钟门控 */
#define XIP_CACHE_CTL_RB_MEM_X2X_A2X_CRTL_REG            (XIP_CACHE_CTL_RB_BASE + 0xDA4) /* AXI控制 */
#define XIP_CACHE_CTL_RB_MEM_X2X_A2X_CRTL1_REG           (XIP_CACHE_CTL_RB_BASE + 0xDA8) /* AXI控制 */
#define XIP_CACHE_CTL_RB_SFC_MEM_CTL_REG                 (XIP_CACHE_CTL_RB_BASE + 0xDAC) /* MEM控制 */

#endif // __3322_XIP_CACHE_CTL_RB_REG_OFFSET_H__
