/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_rf_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_RF_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_RF_CTL_RB_REG_OFFSET_FIELD_H__

#define	RF_CTL_RB_RF_SYS_CTL_ID_LEN	        16
#define	RF_CTL_RB_RF_SYS_CTL_ID_OFFSET	        0
#define RF_CTL_RB_RF_SYS_CTL_ID_MASK    		0xFFFF

#define	RF_CTL_RB_RF_GP_REG0_LEN	        16
#define	RF_CTL_RB_RF_GP_REG0_OFFSET	        0
#define RF_CTL_RB_RF_GP_REG0_MASK    		0xFFFF

#define	RF_CTL_RB_RF_GP_REG1_LEN	        16
#define	RF_CTL_RB_RF_GP_REG1_OFFSET	        0
#define RF_CTL_RB_RF_GP_REG1_MASK    		0xFFFF

#define	RF_CTL_RB_RF_GP_REG2_LEN	        16
#define	RF_CTL_RB_RF_GP_REG2_OFFSET	        0
#define RF_CTL_RB_RF_GP_REG2_MASK    		0xFFFF

#define	RF_CTL_RB_RF_GP_REG3_LEN	        16
#define	RF_CTL_RB_RF_GP_REG3_OFFSET	        0
#define RF_CTL_RB_RF_GP_REG3_MASK    		0xFFFF

#define	RF_CTL_RB_RF_BT_PLL_REG_CG_MOD_LEN	        1
#define	RF_CTL_RB_RF_BT_PLL_REG_CG_MOD_OFFSET	        3
#define RF_CTL_RB_RF_BT_PLL_REG_CG_MOD_MASK    		0x8
#define	RF_CTL_RB_RF_BT_PLL_REG_CLKEN_MAN_LEN	        1
#define	RF_CTL_RB_RF_BT_PLL_REG_CLKEN_MAN_OFFSET	        2
#define RF_CTL_RB_RF_BT_PLL_REG_CLKEN_MAN_MASK    		0x4
#define	RF_CTL_RB_RF_BT_REG_CG_MOD_LEN	        1
#define	RF_CTL_RB_RF_BT_REG_CG_MOD_OFFSET	        1
#define RF_CTL_RB_RF_BT_REG_CG_MOD_MASK    		0x2
#define	RF_CTL_RB_RF_BT_REG_CLKEN_MAN_LEN	        1
#define	RF_CTL_RB_RF_BT_REG_CLKEN_MAN_OFFSET	        0
#define RF_CTL_RB_RF_BT_REG_CLKEN_MAN_MASK    		0x1

#define	RF_CTL_RB_RF_BT_PLL_REG_SOFT_RSTN_LEN	        1
#define	RF_CTL_RB_RF_BT_PLL_REG_SOFT_RSTN_OFFSET	        1
#define RF_CTL_RB_RF_BT_PLL_REG_SOFT_RSTN_MASK    		0x2
#define	RF_CTL_RB_RF_BT_REG_SOFT_RSTN_LEN	        1
#define	RF_CTL_RB_RF_BT_REG_SOFT_RSTN_OFFSET	        0
#define RF_CTL_RB_RF_BT_REG_SOFT_RSTN_MASK    		0x1

#define	RF_CTL_RB_CBB_BT_PLL_REG_RD_DIS_LEN	        1
#define	RF_CTL_RB_CBB_BT_PLL_REG_RD_DIS_OFFSET	        3
#define RF_CTL_RB_CBB_BT_PLL_REG_RD_DIS_MASK    		0x8
#define	RF_CTL_RB_CBB_BT_PLL_REG_WR_DIS_LEN	        1
#define	RF_CTL_RB_CBB_BT_PLL_REG_WR_DIS_OFFSET	        2
#define RF_CTL_RB_CBB_BT_PLL_REG_WR_DIS_MASK    		0x4
#define	RF_CTL_RB_CBB_BT_RF_REG_RD_DIS_LEN	        1
#define	RF_CTL_RB_CBB_BT_RF_REG_RD_DIS_OFFSET	        1
#define RF_CTL_RB_CBB_BT_RF_REG_RD_DIS_MASK    		0x2
#define	RF_CTL_RB_CBB_BT_RF_REG_WR_DIS_LEN	        1
#define	RF_CTL_RB_CBB_BT_RF_REG_WR_DIS_OFFSET	        0
#define RF_CTL_RB_CBB_BT_RF_REG_WR_DIS_MASK    		0x1

#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_LOCK_STS_LEN	        1
#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_LOCK_STS_OFFSET	        2
#define RF_CTL_RB_BT_RF_LNA_SAT_DET_LOCK_STS_MASK    		0x4
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_LOCK_STS_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_LOCK_STS_OFFSET	        1
#define RF_CTL_RB_BT_RF_RX_DLNA_EOS_LOCK_STS_MASK    		0x2

#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_CLR_LEN	        1
#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_CLR_OFFSET	        2
#define RF_CTL_RB_BT_RF_LNA_SAT_DET_CLR_MASK    		0x4
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_CLR_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_CLR_OFFSET	        1
#define RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_CLR_MASK    		0x2

#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_RAW_STS_LEN	        1
#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_RAW_STS_OFFSET	        2
#define RF_CTL_RB_BT_RF_LNA_SAT_DET_RAW_STS_MASK    		0x4
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_RAW_STS_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_RAW_STS_OFFSET	        1
#define RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_RAW_STS_MASK    		0x2

#define	RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_OUT_SEL_LEN	        1
#define	RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_OUT_SEL_OFFSET	        3
#define RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_OUT_SEL_MASK    		0x8
#define	RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_VALID_SEL_LEN	        1
#define	RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_VALID_SEL_OFFSET	        2
#define RF_CTL_RB_RF_ONLY_BT_RF_TDC_TEST_VALID_SEL_MASK    		0x4

#define	RF_CTL_RB_RF_REG_PRT_CNT_LEN	        8
#define	RF_CTL_RB_RF_REG_PRT_CNT_OFFSET	        1
#define RF_CTL_RB_RF_REG_PRT_CNT_MASK    		0x1FE
#define	RF_CTL_RB_RF_REG_PRT_EN_LEN	        1
#define	RF_CTL_RB_RF_REG_PRT_EN_OFFSET	        0
#define RF_CTL_RB_RF_REG_PRT_EN_MASK    		0x1

#define	RF_CTL_RB_RF_PLL_REG_PRT_CNT_LEN	        8
#define	RF_CTL_RB_RF_PLL_REG_PRT_CNT_OFFSET	        1
#define RF_CTL_RB_RF_PLL_REG_PRT_CNT_MASK    		0x1FE
#define	RF_CTL_RB_RF_PLL_REG_PRT_EN_LEN	        1
#define	RF_CTL_RB_RF_PLL_REG_PRT_EN_OFFSET	        0
#define RF_CTL_RB_RF_PLL_REG_PRT_EN_MASK    		0x1

#define	RF_CTL_RB_RF_REG_PRT_INT_EN_LEN	        1
#define	RF_CTL_RB_RF_REG_PRT_INT_EN_OFFSET	        1
#define RF_CTL_RB_RF_REG_PRT_INT_EN_MASK    		0x2
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_EN_LEN	        1
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_EN_OFFSET	        0
#define RF_CTL_RB_RF_PLL_REG_PRT_INT_EN_MASK    		0x1

#define	RF_CTL_RB_RF_REG_PRT_INT_STS_LEN	        1
#define	RF_CTL_RB_RF_REG_PRT_INT_STS_OFFSET	        1
#define RF_CTL_RB_RF_REG_PRT_INT_STS_MASK    		0x2
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_STS_LEN	        1
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_STS_OFFSET	        0
#define RF_CTL_RB_RF_PLL_REG_PRT_INT_STS_MASK    		0x1

#define	RF_CTL_RB_RF_REG_PRT_INT_CLR_LEN	        1
#define	RF_CTL_RB_RF_REG_PRT_INT_CLR_OFFSET	        1
#define RF_CTL_RB_RF_REG_PRT_INT_CLR_MASK    		0x2
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_CLR_LEN	        1
#define	RF_CTL_RB_RF_PLL_REG_PRT_INT_CLR_OFFSET	        0
#define RF_CTL_RB_RF_PLL_REG_PRT_INT_CLR_MASK    		0x1

#define	RF_CTL_RB_ABB_BT_ADC_IQ_EXCHANGE_CDLNA_MODE_LEN	        2
#define	RF_CTL_RB_ABB_BT_ADC_IQ_EXCHANGE_CDLNA_MODE_OFFSET	        0
#define RF_CTL_RB_ABB_BT_ADC_IQ_EXCHANGE_CDLNA_MODE_MASK    		0x3

#define	RF_CTL_RB_D_BT_RF_PALDO1_OCP_LEN	        1
#define	RF_CTL_RB_D_BT_RF_PALDO1_OCP_OFFSET	        1
#define RF_CTL_RB_D_BT_RF_PALDO1_OCP_MASK    		0x2
#define	RF_CTL_RB_WUR_PLL_LOCK_INDICATOR_LEN	        1
#define	RF_CTL_RB_WUR_PLL_LOCK_INDICATOR_OFFSET	        0
#define RF_CTL_RB_WUR_PLL_LOCK_INDICATOR_MASK    		0x1

#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_FRM_LPEG_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_FRM_LPEG_MAN_OFFSET	        9
#define RF_CTL_RB_RF_EN_DELAY_RFLDO5_FRM_LPEG_MAN_MASK    		0x200
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_OFFSET	        8
#define RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_MASK    		0x100
#define	RF_CTL_RB_RF_EN_RFLDO7_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO7_MAN_OFFSET	        7
#define RF_CTL_RB_RF_EN_RFLDO7_MAN_MASK    		0x80
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_OFFSET	        6
#define RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_MASK    		0x40
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_MASK    		0x20
#define	RF_CTL_RB_RF_EN_RFLDO3_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO3_MAN_OFFSET	        4
#define RF_CTL_RB_RF_EN_RFLDO3_MAN_MASK    		0x10
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_OFFSET	        3
#define RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_MASK    		0x8
#define	RF_CTL_RB_RF_EN_RFLDO4_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO4_MAN_OFFSET	        2
#define RF_CTL_RB_RF_EN_RFLDO4_MAN_MASK    		0x4
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_OFFSET	        1
#define RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_MASK    		0x2
#define	RF_CTL_RB_RF_EN_RFLDO5_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO5_MAN_OFFSET	        0
#define RF_CTL_RB_RF_EN_RFLDO5_MAN_MASK    		0x1

#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_OFFSET	        3
#define RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_MASK    		0x8
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_OFFSET	        2
#define RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_MASK    		0x4
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_SEL_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_MAN_SEL_MASK    		0x1

#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_SEL_OFFSET	        8
#define RF_CTL_RB_RF_EN_DELAY_RFLDO7_MAN_SEL_MASK    		0x100
#define	RF_CTL_RB_RF_EN_RFLDO7_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO7_MAN_SEL_OFFSET	        7
#define RF_CTL_RB_RF_EN_RFLDO7_MAN_SEL_MASK    		0x80
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_SEL_OFFSET	        6
#define RF_CTL_RB_D_BT_ADC_LDO_EN_MAN_SEL_MASK    		0x40
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_SEL_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_MAN_SEL_MASK    		0x20
#define	RF_CTL_RB_RF_EN_RFLDO3_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO3_MAN_SEL_OFFSET	        4
#define RF_CTL_RB_RF_EN_RFLDO3_MAN_SEL_MASK    		0x10
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_SEL_OFFSET	        3
#define RF_CTL_RB_RF_EN_DELAY_RFLDO3_MAN_SEL_MASK    		0x8
#define	RF_CTL_RB_RF_EN_RFLDO4_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO4_MAN_SEL_OFFSET	        2
#define RF_CTL_RB_RF_EN_RFLDO4_MAN_SEL_MASK    		0x4
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_RF_EN_DELAY_RFLDO4_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_RF_EN_RFLDO5_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO5_MAN_SEL_OFFSET	        0
#define RF_CTL_RB_RF_EN_RFLDO5_MAN_SEL_MASK    		0x1

#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_STS_OFFSET	        7
#define RF_CTL_RB_RF_EN_DELAY_RFLDO5_STS_MASK    		0x80
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_STS_OFFSET	        6
#define RF_CTL_RB_D_BT_ADC_LDO_EN_STS_MASK    		0x40
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_STS_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_LDO_EN_DELAY_STS_MASK    		0x20
#define	RF_CTL_RB_RF_EN_RFLDO3_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO3_STS_OFFSET	        4
#define RF_CTL_RB_RF_EN_RFLDO3_STS_MASK    		0x10
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO3_STS_OFFSET	        3
#define RF_CTL_RB_RF_EN_DELAY_RFLDO3_STS_MASK    		0x8
#define	RF_CTL_RB_RF_EN_RFLDO4_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO4_STS_OFFSET	        2
#define RF_CTL_RB_RF_EN_RFLDO4_STS_MASK    		0x4
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO4_STS_OFFSET	        1
#define RF_CTL_RB_RF_EN_DELAY_RFLDO4_STS_MASK    		0x2
#define	RF_CTL_RB_RF_EN_RFLDO5_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO5_STS_OFFSET	        0
#define RF_CTL_RB_RF_EN_RFLDO5_STS_MASK    		0x1

#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_STS_LEN	        1
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_STS_OFFSET	        1
#define RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_STS_MASK    		0x2
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_STS_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_ISO_EN_CDLNA_STS_MASK    		0x1

#define	RF_CTL_RB_CBB_RF_EN_RFLDO5_FRM_LPEG_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_RF_EN_RFLDO5_FRM_LPEG_DISABLE_OFFSET	        1
#define RF_CTL_RB_CBB_RF_EN_RFLDO5_FRM_LPEG_DISABLE_MASK    		0x2
#define	RF_CTL_RB_CBB_RF_EN_RFLDO5_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_RF_EN_RFLDO5_DISABLE_OFFSET	        0
#define RF_CTL_RB_CBB_RF_EN_RFLDO5_DISABLE_MASK    		0x1

#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_LEN	        2
#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_OFFSET	        12
#define RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_MASK    		0x3000
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_OFFSET	        11
#define RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_MASK    		0x800
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_OFFSET	        10
#define RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_MASK    		0x400
#define	RF_CTL_RB_RF_LNA_SATDET_EN_MAN_LEN	        1
#define	RF_CTL_RB_RF_LNA_SATDET_EN_MAN_OFFSET	        9
#define RF_CTL_RB_RF_LNA_SATDET_EN_MAN_MASK    		0x200
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_LEN	        3
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_OFFSET	        6
#define RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_MASK    		0x1C0
#define	RF_CTL_RB_BT_LINE_RX_EN_MAN_LEN	        1
#define	RF_CTL_RB_BT_LINE_RX_EN_MAN_OFFSET	        5
#define RF_CTL_RB_BT_LINE_RX_EN_MAN_MASK    		0x20
#define	RF_CTL_RB_BT_LINE_TX_EN_MAN_LEN	        1
#define	RF_CTL_RB_BT_LINE_TX_EN_MAN_OFFSET	        4
#define RF_CTL_RB_BT_LINE_TX_EN_MAN_MASK    		0x10
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_LEN	        1
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_OFFSET	        3
#define RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_MASK    		0x8
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_LEN	        1
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_OFFSET	        2
#define RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_MASK    		0x4
#define	RF_CTL_RB_BT_SRC_TX_VLD_MAN_LEN	        1
#define	RF_CTL_RB_BT_SRC_TX_VLD_MAN_OFFSET	        1
#define RF_CTL_RB_BT_SRC_TX_VLD_MAN_MASK    		0x2
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_LEN	        1
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_OFFSET	        0
#define RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_MASK    		0x1

#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_OFFSET	        8
#define RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_MASK    		0x100
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_OFFSET	        7
#define RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_MASK    		0x80
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_OFFSET	        6
#define RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_MASK    		0x40
#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_MASK    		0x20
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_LEN	        2
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_OFFSET	        3
#define RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_MASK    		0x18
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_LEN	        3
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_OFFSET	        0
#define RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_MASK    		0x7

#define	RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_LEN	        8
#define	RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_OFFSET	        0
#define RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_MASK    		0xFF

#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_LEN	        8
#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_OFFSET	        0
#define RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_MASK    		0xFF

#define	RF_CTL_RB_BT_AGC_MAN_LEN	        8
#define	RF_CTL_RB_BT_AGC_MAN_OFFSET	        0
#define RF_CTL_RB_BT_AGC_MAN_MASK    		0xFF

#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_LEN	        14
#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_OFFSET	        0
#define RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_MASK    		0x3FFF

#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_LEN	        10
#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_OFFSET	        0
#define RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_MASK    		0x3FF

#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_SEL_OFFSET	        10
#define RF_CTL_RB_BT_RF_LNA_PWR_MODE_MAN_SEL_MASK    		0x400
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_SEL_OFFSET	        9
#define RF_CTL_RB_BT_LPF_VGA_I_EN_MAN_SEL_MASK    		0x200
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_SEL_OFFSET	        8
#define RF_CTL_RB_BT_LPF_VGA_Q_EN_MAN_SEL_MASK    		0x100
#define	RF_CTL_RB_RF_LNA_SATDET_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_LNA_SATDET_EN_MAN_SEL_OFFSET	        7
#define RF_CTL_RB_RF_LNA_SATDET_EN_MAN_SEL_MASK    		0x80
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_SEL_OFFSET	        6
#define RF_CTL_RB_BT_RF_RX_BW_SEL_MAN_SEL_MASK    		0x40
#define	RF_CTL_RB_BT_LINE_RX_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_LINE_RX_EN_MAN_SEL_OFFSET	        5
#define RF_CTL_RB_BT_LINE_RX_EN_MAN_SEL_MASK    		0x20
#define	RF_CTL_RB_BT_LINE_TX_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_LINE_TX_EN_MAN_SEL_OFFSET	        4
#define RF_CTL_RB_BT_LINE_TX_EN_MAN_SEL_MASK    		0x10
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_SEL_OFFSET	        3
#define RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_MAN_SEL_MASK    		0x8
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_SEL_OFFSET	        2
#define RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_MAN_SEL_MASK    		0x4
#define	RF_CTL_RB_BT_SRC_TX_VLD_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_SRC_TX_VLD_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_BT_SRC_TX_VLD_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_SEL_OFFSET	        0
#define RF_CTL_RB_BT_SRC_GFSK_RAMP_MAN_SEL_MASK    		0x1

#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_SEL_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_MAN_SEL_MASK    		0x20
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_SEL_OFFSET	        4
#define RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_MAN_SEL_MASK    		0x10
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_SEL_OFFSET	        3
#define RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_MAN_SEL_MASK    		0x8
#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_SEL_OFFSET	        2
#define RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_MAN_SEL_MASK    		0x4
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_SEL_OFFSET	        0
#define RF_CTL_RB_RF_ADPLL_TXRXPHY_MAN_SEL_MASK    		0x1

#define	RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_SEL_OFFSET	        4
#define RF_CTL_RB_BT_RF_RX_DCOC_I_MAN_SEL_MASK    		0x10
#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_SEL_OFFSET	        3
#define RF_CTL_RB_BT_RF_RX_DCOC_Q_MAN_SEL_MASK    		0x8
#define	RF_CTL_RB_BT_AGC_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_AGC_MAN_SEL_OFFSET	        2
#define RF_CTL_RB_BT_AGC_MAN_SEL_MASK    		0x4
#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_BT_RF_TX_PHI_DATA_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_SEL_LEN	        1
#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_SEL_OFFSET	        0
#define RF_CTL_RB_BT_RF_TX_AMP_DATA_MAN_SEL_MASK    		0x1

#define	RF_CTL_RB_RF_EN_RFLDO5_DELAY_CNT_LEN	        13
#define	RF_CTL_RB_RF_EN_RFLDO5_DELAY_CNT_OFFSET	        0
#define RF_CTL_RB_RF_EN_RFLDO5_DELAY_CNT_MASK    		0x1FFF

#define	RF_CTL_RB_BT_RF_TEST_SW_CTRL_LEN	        2
#define	RF_CTL_RB_BT_RF_TEST_SW_CTRL_OFFSET	        14
#define RF_CTL_RB_BT_RF_TEST_SW_CTRL_MASK    		0xC000
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_LEN	        1
#define	RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_OFFSET	        13
#define RF_CTL_RB_BT_RF_RX_DLNA_EOS_FLAG_MASK    		0x2000
#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_LEN	        1
#define	RF_CTL_RB_BT_RF_LNA_SAT_DET_OFFSET	        12
#define RF_CTL_RB_BT_RF_LNA_SAT_DET_MASK    		0x1000
#define	RF_CTL_RB_BT_RF_TDC_DUMP_EN_LEN	        1
#define	RF_CTL_RB_BT_RF_TDC_DUMP_EN_OFFSET	        11
#define RF_CTL_RB_BT_RF_TDC_DUMP_EN_MASK    		0x800
#define	RF_CTL_RB_BT_RF_PLL_DUMP_EN_LEN	        1
#define	RF_CTL_RB_BT_RF_PLL_DUMP_EN_OFFSET	        10
#define RF_CTL_RB_BT_RF_PLL_DUMP_EN_MASK    		0x400
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO3_LEN	        1
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO3_OFFSET	        9
#define RF_CTL_RB_RF_EN_HIZ_RFLDO3_MASK    		0x200
#define	RF_CTL_RB_RF_EN_SW_RFLDO3_LEN	        1
#define	RF_CTL_RB_RF_EN_SW_RFLDO3_OFFSET	        8
#define RF_CTL_RB_RF_EN_SW_RFLDO3_MASK    		0x100
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO3_LEN	        3
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO3_OFFSET	        5
#define RF_CTL_RB_RF_EN_ICTR_RFLDO3_MASK    		0xE0
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO3_LEN	        2
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO3_OFFSET	        3
#define RF_CTL_RB_RF_EN_RESERV_RFLDO3_MASK    		0x18
#define	RF_CTL_RB_RF_LOAD_RFLDO3_LEN	        2
#define	RF_CTL_RB_RF_LOAD_RFLDO3_OFFSET	        1
#define RF_CTL_RB_RF_LOAD_RFLDO3_MASK    		0x6
#define	RF_CTL_RB_RF_EN_TEST_RFLDO3_LEN	        1
#define	RF_CTL_RB_RF_EN_TEST_RFLDO3_OFFSET	        0
#define RF_CTL_RB_RF_EN_TEST_RFLDO3_MASK    		0x1

#define	RF_CTL_RB_RF_EN_HIZ_RFLDO4_LEN	        1
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO4_OFFSET	        15
#define RF_CTL_RB_RF_EN_HIZ_RFLDO4_MASK    		0x8000
#define	RF_CTL_RB_RF_EN_SW_RFLDO4_LEN	        1
#define	RF_CTL_RB_RF_EN_SW_RFLDO4_OFFSET	        14
#define RF_CTL_RB_RF_EN_SW_RFLDO4_MASK    		0x4000
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO4_LEN	        3
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO4_OFFSET	        11
#define RF_CTL_RB_RF_EN_ICTR_RFLDO4_MASK    		0x3800
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO4_LEN	        2
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO4_OFFSET	        9
#define RF_CTL_RB_RF_EN_RESERV_RFLDO4_MASK    		0x600
#define	RF_CTL_RB_RF_LOAD_RFLDO4_LEN	        2
#define	RF_CTL_RB_RF_LOAD_RFLDO4_OFFSET	        7
#define RF_CTL_RB_RF_LOAD_RFLDO4_MASK    		0x180
#define	RF_CTL_RB_RF_EN_TEST_RFLDO4_LEN	        1
#define	RF_CTL_RB_RF_EN_TEST_RFLDO4_OFFSET	        6
#define RF_CTL_RB_RF_EN_TEST_RFLDO4_MASK    		0x40
#define	RF_CTL_RB_RF_EN_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_PALDO1_OFFSET	        5
#define RF_CTL_RB_RF_EN_PALDO1_MASK    		0x20
#define	RF_CTL_RB_RF_EN_DELAY_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_PALDO1_OFFSET	        4
#define RF_CTL_RB_RF_EN_DELAY_PALDO1_MASK    		0x10
#define	RF_CTL_RB_RF_EN_HIZ_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_HIZ_PALDO1_OFFSET	        3
#define RF_CTL_RB_RF_EN_HIZ_PALDO1_MASK    		0x8
#define	RF_CTL_RB_RF_EN_SW_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_SW_PALDO1_OFFSET	        2
#define RF_CTL_RB_RF_EN_SW_PALDO1_MASK    		0x4
#define	RF_CTL_RB_RF_EN_ECO_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_ECO_PALDO1_OFFSET	        1
#define RF_CTL_RB_RF_EN_ECO_PALDO1_MASK    		0x2
#define	RF_CTL_RB_RF_EN_OCP_SET_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_OCP_SET_PALDO1_OFFSET	        0
#define RF_CTL_RB_RF_EN_OCP_SET_PALDO1_MASK    		0x1

#define	RF_CTL_RB_RF_EN_OCP_BYPASS_PALDO1_LEN	        1
#define	RF_CTL_RB_RF_EN_OCP_BYPASS_PALDO1_OFFSET	        15
#define RF_CTL_RB_RF_EN_OCP_BYPASS_PALDO1_MASK    		0x8000
#define	RF_CTL_RB_RF_EN_ICTR_PALDO1_LEN	        4
#define	RF_CTL_RB_RF_EN_ICTR_PALDO1_OFFSET	        11
#define RF_CTL_RB_RF_EN_ICTR_PALDO1_MASK    		0x7800
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO5_LEN	        1
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO5_OFFSET	        10
#define RF_CTL_RB_RF_EN_HIZ_RFLDO5_MASK    		0x400
#define	RF_CTL_RB_RF_EN_SW_RFLDO5_LEN	        1
#define	RF_CTL_RB_RF_EN_SW_RFLDO5_OFFSET	        9
#define RF_CTL_RB_RF_EN_SW_RFLDO5_MASK    		0x200
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO5_LEN	        3
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO5_OFFSET	        6
#define RF_CTL_RB_RF_EN_ICTR_RFLDO5_MASK    		0x1C0
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO5_LEN	        2
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO5_OFFSET	        4
#define RF_CTL_RB_RF_EN_RESERV_RFLDO5_MASK    		0x30
#define	RF_CTL_RB_RF_LOAD_RFLDO5_LEN	        2
#define	RF_CTL_RB_RF_LOAD_RFLDO5_OFFSET	        2
#define RF_CTL_RB_RF_LOAD_RFLDO5_MASK    		0xC
#define	RF_CTL_RB_RF_EN_TEST_RFLDO5_LEN	        1
#define	RF_CTL_RB_RF_EN_TEST_RFLDO5_OFFSET	        1
#define RF_CTL_RB_RF_EN_TEST_RFLDO5_MASK    		0x2
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_HIZ_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_HIZ_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_LDO_EN_HIZ_MASK    		0x1

#define	RF_CTL_RB_RF_EN_HIZ_RFLDO7_LEN	        1
#define	RF_CTL_RB_RF_EN_HIZ_RFLDO7_OFFSET	        13
#define RF_CTL_RB_RF_EN_HIZ_RFLDO7_MASK    		0x2000
#define	RF_CTL_RB_RF_EN_SW_RFLDO7_LEN	        1
#define	RF_CTL_RB_RF_EN_SW_RFLDO7_OFFSET	        12
#define RF_CTL_RB_RF_EN_SW_RFLDO7_MASK    		0x1000
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO7_LEN	        3
#define	RF_CTL_RB_RF_EN_ICTR_RFLDO7_OFFSET	        9
#define RF_CTL_RB_RF_EN_ICTR_RFLDO7_MASK    		0xE00
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_SW_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_SW_OFFSET	        8
#define RF_CTL_RB_D_BT_ADC_LDO_EN_SW_MASK    		0x100
#define	RF_CTL_RB_D_BT_ADC_LDO_ICTR_LEN	        3
#define	RF_CTL_RB_D_BT_ADC_LDO_ICTR_OFFSET	        5
#define RF_CTL_RB_D_BT_ADC_LDO_ICTR_MASK    		0xE0
#define	RF_CTL_RB_D_BT_ADC_LDO_RESERV_LEN	        2
#define	RF_CTL_RB_D_BT_ADC_LDO_RESERV_OFFSET	        3
#define RF_CTL_RB_D_BT_ADC_LDO_RESERV_MASK    		0x18
#define	RF_CTL_RB_D_BT_ADC_LDO_LOAD_LEN	        2
#define	RF_CTL_RB_D_BT_ADC_LDO_LOAD_OFFSET	        1
#define RF_CTL_RB_D_BT_ADC_LDO_LOAD_MASK    		0x6
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_TEST_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_LDO_EN_TEST_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_LDO_EN_TEST_MASK    		0x1

#define	RF_CTL_RB_BT_RF_RESEV_RB16_0_LEN	        16
#define	RF_CTL_RB_BT_RF_RESEV_RB16_0_OFFSET	        0
#define RF_CTL_RB_BT_RF_RESEV_RB16_0_MASK    		0xFFFF

#define	RF_CTL_RB_BT_RF_RESEV_RB16_1_LEN	        16
#define	RF_CTL_RB_BT_RF_RESEV_RB16_1_OFFSET	        0
#define RF_CTL_RB_BT_RF_RESEV_RB16_1_MASK    		0xFFFF

#define	RF_CTL_RB_RF_EN_VSET_PALDO1_LEN	        8
#define	RF_CTL_RB_RF_EN_VSET_PALDO1_OFFSET	        0
#define RF_CTL_RB_RF_EN_VSET_PALDO1_MASK    		0xFF

#define	RF_CTL_RB_RF_EN_RESERV_PALDO1_LEN	        8
#define	RF_CTL_RB_RF_EN_RESERV_PALDO1_OFFSET	        0
#define RF_CTL_RB_RF_EN_RESERV_PALDO1_MASK    		0xFF

#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_STS_LEN	        2
#define	RF_CTL_RB_BT_RF_LNA_PWR_MODE_STS_OFFSET	        12
#define RF_CTL_RB_BT_RF_LNA_PWR_MODE_STS_MASK    		0x3000
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_STS_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_I_EN_STS_OFFSET	        11
#define RF_CTL_RB_BT_LPF_VGA_I_EN_STS_MASK    		0x800
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_STS_LEN	        1
#define	RF_CTL_RB_BT_LPF_VGA_Q_EN_STS_OFFSET	        10
#define RF_CTL_RB_BT_LPF_VGA_Q_EN_STS_MASK    		0x400
#define	RF_CTL_RB_RF_LNA_SATDET_EN_STS_LEN	        1
#define	RF_CTL_RB_RF_LNA_SATDET_EN_STS_OFFSET	        9
#define RF_CTL_RB_RF_LNA_SATDET_EN_STS_MASK    		0x200
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_STS_LEN	        3
#define	RF_CTL_RB_BT_RF_RX_BW_SEL_STS_OFFSET	        6
#define RF_CTL_RB_BT_RF_RX_BW_SEL_STS_MASK    		0x1C0
#define	RF_CTL_RB_BT_LINE_RX_EN_STS_LEN	        1
#define	RF_CTL_RB_BT_LINE_RX_EN_STS_OFFSET	        5
#define RF_CTL_RB_BT_LINE_RX_EN_STS_MASK    		0x20
#define	RF_CTL_RB_BT_LINE_TX_EN_STS_LEN	        1
#define	RF_CTL_RB_BT_LINE_TX_EN_STS_OFFSET	        4
#define RF_CTL_RB_BT_LINE_TX_EN_STS_MASK    		0x10
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_STS_LEN	        1
#define	RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_STS_OFFSET	        3
#define RF_CTL_RB_BT_RF_ISDBB_CTRL_EOS_DLNA_STS_MASK    		0x8
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_STS_LEN	        1
#define	RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_STS_OFFSET	        2
#define RF_CTL_RB_RF_ADPLL_OPENLOOP_EN_STS_MASK    		0x4
#define	RF_CTL_RB_BT_SRC_TX_VLD_STS_LEN	        1
#define	RF_CTL_RB_BT_SRC_TX_VLD_STS_OFFSET	        1
#define RF_CTL_RB_BT_SRC_TX_VLD_STS_MASK    		0x2
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_STS_LEN	        1
#define	RF_CTL_RB_BT_SRC_GFSK_RAMP_STS_OFFSET	        0
#define RF_CTL_RB_BT_SRC_GFSK_RAMP_STS_MASK    		0x1

#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_STS_OFFSET	        2
#define RF_CTL_RB_D_BT_ADC_RSTN_CDLNA_STS_MASK    		0x4
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_STS_OFFSET	        1
#define RF_CTL_RB_D_BT_ADC_EN_I_CDLNA_STS_MASK    		0x2
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_STS_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_EN_Q_CDLNA_STS_MASK    		0x1

#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_STS_LEN	        1
#define	RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_STS_OFFSET	        12
#define RF_CTL_RB_D_BT_ADC_STANDBY_CDLNA_STS_MASK    		0x1000
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_STS_LEN	        2
#define	RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_STS_OFFSET	        10
#define RF_CTL_RB_RF_ADPLL_FRAME_HEADER_MODE_STS_MASK    		0xC00
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_STS_LEN	        3
#define	RF_CTL_RB_RF_ADPLL_TXRXPHY_STS_OFFSET	        7
#define RF_CTL_RB_RF_ADPLL_TXRXPHY_STS_MASK    		0x380
#define	RF_CTL_RB_RF_EN_RFLDO7_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO7_STS_OFFSET	        6
#define RF_CTL_RB_RF_EN_RFLDO7_STS_MASK    		0x40
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_STS_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO7_STS_OFFSET	        5
#define RF_CTL_RB_RF_EN_DELAY_RFLDO7_STS_MASK    		0x20
#define	RF_CTL_RB_RF_RFLDO7_TRIM_STS_LEN	        5
#define	RF_CTL_RB_RF_RFLDO7_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_RF_RFLDO7_TRIM_STS_MASK    		0x1F

#define	RF_CTL_RB_BT_RF_RX_DCOC_I_STS_LEN	        8
#define	RF_CTL_RB_BT_RF_RX_DCOC_I_STS_OFFSET	        0
#define RF_CTL_RB_BT_RF_RX_DCOC_I_STS_MASK    		0xFF

#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_STS_LEN	        8
#define	RF_CTL_RB_BT_RF_RX_DCOC_Q_STS_OFFSET	        0
#define RF_CTL_RB_BT_RF_RX_DCOC_Q_STS_MASK    		0xFF

#define	RF_CTL_RB_BT_AGC_STS_LEN	        8
#define	RF_CTL_RB_BT_AGC_STS_OFFSET	        0
#define RF_CTL_RB_BT_AGC_STS_MASK    		0xFF

#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_STS_LEN	        14
#define	RF_CTL_RB_BT_RF_TX_PHI_DATA_STS_OFFSET	        0
#define RF_CTL_RB_BT_RF_TX_PHI_DATA_STS_MASK    		0x3FFF

#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_STS_LEN	        10
#define	RF_CTL_RB_BT_RF_TX_AMP_DATA_STS_OFFSET	        0
#define RF_CTL_RB_BT_RF_TX_AMP_DATA_STS_MASK    		0x3FF

#define	RF_CTL_RB_D_BT_ADC_LDO_TRIM_STS_LEN	        5
#define	RF_CTL_RB_D_BT_ADC_LDO_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_D_BT_ADC_LDO_TRIM_STS_MASK    		0x1F

#define	RF_CTL_RB_RF_RFLDO3_TRIM_STS_LEN	        5
#define	RF_CTL_RB_RF_RFLDO3_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_RF_RFLDO3_TRIM_STS_MASK    		0x1F

#define	RF_CTL_RB_RF_RFLDO4_TRIM_STS_LEN	        5
#define	RF_CTL_RB_RF_RFLDO4_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_RF_RFLDO4_TRIM_STS_MASK    		0x1F

#define	RF_CTL_RB_RF_RFLDO5_TRIM_STS_LEN	        5
#define	RF_CTL_RB_RF_RFLDO5_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_RF_RFLDO5_TRIM_STS_MASK    		0x1F

#define	RF_CTL_RB_RF_PALDO1_TRIM_STS_LEN	        8
#define	RF_CTL_RB_RF_PALDO1_TRIM_STS_OFFSET	        0
#define RF_CTL_RB_RF_PALDO1_TRIM_STS_MASK    		0xFF

#define	RF_CTL_RB_RF_EN_RFLDO5_FRM_LPEG_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_RFLDO5_FRM_LPEG_MAN_OFFSET	        1
#define RF_CTL_RB_RF_EN_RFLDO5_FRM_LPEG_MAN_MASK    		0x2
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_MAN_LEN	        1
#define	RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_MAN_OFFSET	        0
#define RF_CTL_RB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_MAN_MASK    		0x1

#define	RF_CTL_RB_RF_EN_RESERV_RFLDO7_LEN	        2
#define	RF_CTL_RB_RF_EN_RESERV_RFLDO7_OFFSET	        3
#define RF_CTL_RB_RF_EN_RESERV_RFLDO7_MASK    		0x18
#define	RF_CTL_RB_RF_LOAD_RFLDO7_LEN	        2
#define	RF_CTL_RB_RF_LOAD_RFLDO7_OFFSET	        1
#define RF_CTL_RB_RF_LOAD_RFLDO7_MASK    		0x6
#define	RF_CTL_RB_RF_EN_TEST_RFLDO7_LEN	        1
#define	RF_CTL_RB_RF_EN_TEST_RFLDO7_OFFSET	        0
#define RF_CTL_RB_RF_EN_TEST_RFLDO7_MASK    		0x1

#define	RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_DISABLE_OFFSET	        5
#define RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_DISABLE_MASK    		0x20
#define	RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_DISABLE_OFFSET	        4
#define RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_DISABLE_MASK    		0x10
#define	RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_FRM_LPEG_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_FRM_LPEG_DISABLE_OFFSET	        3
#define RF_CTL_RB_CBB_RF_EN_DELAY_RFLDO5_FRM_LPEG_DISABLE_MASK    		0x8
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_OFFSET	        2
#define RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_MASK    		0x4
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_SEL_LEN	        1
#define	RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_SEL_OFFSET	        1
#define RF_CTL_RB_RF_EN_DELAY_RFLDO5_MAN_SEL_MASK    		0x2
#define	RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_DISABLE_LEN	        1
#define	RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_DISABLE_OFFSET	        0
#define RF_CTL_RB_CBB_D_BT_RF_LDO5_ISO_EN_FRM_LPEG_DISABLE_MASK    		0x1

#endif // __3322_RF_CTL_RB_REG_OFFSET_FIELD_H__
