/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_cfg_s_hgpio_pad_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_CFG_S_HGPIO_PAD_REG_OFFSET_FIELD_H__
#define __3322_CFG_S_HGPIO_PAD_REG_OFFSET_FIELD_H__

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO0_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO1_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO2_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO3_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO4_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO5_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO6_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO7_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO8_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO9_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO10_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO11_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO12_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO13_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO14_CTRL_PU_MASK    		0x1

#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS1_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS1_OFFSET	        5
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS1_MASK    		0x20
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS0_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS0_OFFSET	        4
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_DS0_MASK    		0x10
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_ST_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_ST_OFFSET	        3
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_ST_MASK    		0x8
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_IE_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_IE_OFFSET	        2
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_IE_MASK    		0x4
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PD_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PD_OFFSET	        1
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PD_MASK    		0x2
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PU_LEN	        1
#define	CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PU_OFFSET	        0
#define CFG_S_HGPIO_PAD_CFG_S_HGPIO15_CTRL_PU_MASK    		0x1

#endif // __3322_CFG_S_HGPIO_PAD_REG_OFFSET_FIELD_H__
