/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_b_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:12 Create file
 */

#ifndef __3322_B_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_B_CTL_RB_REG_OFFSET_FIELD_H__

#define	B_CTL_RB_B_CTL_ID_LEN	        16
#define	B_CTL_RB_B_CTL_ID_OFFSET	        0
#define B_CTL_RB_B_CTL_ID_MASK    		0xFFFF

#define	B_CTL_RB_B_GP_REG0_LEN	        16
#define	B_CTL_RB_B_GP_REG0_OFFSET	        0
#define B_CTL_RB_B_GP_REG0_MASK    		0xFFFF

#define	B_CTL_RB_B_GP_REG1_LEN	        16
#define	B_CTL_RB_B_GP_REG1_OFFSET	        0
#define B_CTL_RB_B_GP_REG1_MASK    		0xFFFF

#define	B_CTL_RB_B_GP_REG2_LEN	        16
#define	B_CTL_RB_B_GP_REG2_OFFSET	        0
#define B_CTL_RB_B_GP_REG2_MASK    		0xFFFF

#define	B_CTL_RB_B_GP_REG3_LEN	        16
#define	B_CTL_RB_B_GP_REG3_OFFSET	        0
#define B_CTL_RB_B_GP_REG3_MASK    		0xFFFF

#define	B_CTL_RB_B_CORE_ASYNC_EXCEPTION_PEND_LEN	        1
#define	B_CTL_RB_B_CORE_ASYNC_EXCEPTION_PEND_OFFSET	        8
#define B_CTL_RB_B_CORE_ASYNC_EXCEPTION_PEND_MASK    		0x100
#define	B_CTL_RB_B_CORE_IN_ASYNC_EXCEPTION_HDLR_LEN	        1
#define	B_CTL_RB_B_CORE_IN_ASYNC_EXCEPTION_HDLR_OFFSET	        7
#define B_CTL_RB_B_CORE_IN_ASYNC_EXCEPTION_HDLR_MASK    		0x80
#define	B_CTL_RB_B_CORE_STOP_TIMER_LEN	        1
#define	B_CTL_RB_B_CORE_STOP_TIMER_OFFSET	        6
#define B_CTL_RB_B_CORE_STOP_TIMER_MASK    		0x40
#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_LEN	        1
#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_OFFSET	        5
#define B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_MASK    		0x20
#define	B_CTL_RB_B_CORE_DOUBLE_EXCEPTIONS_LEN	        1
#define	B_CTL_RB_B_CORE_DOUBLE_EXCEPTIONS_OFFSET	        4
#define B_CTL_RB_B_CORE_DOUBLE_EXCEPTIONS_MASK    		0x10
#define	B_CTL_RB_B_CORE_MODE_LEN	        1
#define	B_CTL_RB_B_CORE_MODE_OFFSET	        3
#define B_CTL_RB_B_CORE_MODE_MASK    		0x8
#define	B_CTL_RB_B_CORE_DEBUG_MODE_LEN	        1
#define	B_CTL_RB_B_CORE_DEBUG_MODE_OFFSET	        2
#define B_CTL_RB_B_CORE_DEBUG_MODE_MASK    		0x4
#define	B_CTL_RB_B_CORE_SLEEP_MODE_LEN	        1
#define	B_CTL_RB_B_CORE_SLEEP_MODE_OFFSET	        1
#define B_CTL_RB_B_CORE_SLEEP_MODE_MASK    		0x2
#define	B_CTL_RB_B_CORE_IN_NMI_HDLR_LEN	        1
#define	B_CTL_RB_B_CORE_IN_NMI_HDLR_OFFSET	        0
#define B_CTL_RB_B_CORE_IN_NMI_HDLR_MASK    		0x1

#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_H_LEN	        16
#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_H_OFFSET	        0
#define B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_H_MASK    		0xFFFF

#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_L_LEN	        16
#define	B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_L_OFFSET	        0
#define B_CTL_RB_B_CORE_INT_EXCPT_REDIRECT_HDLR_PC_L_MASK    		0xFFFF

#define	B_CTL_RB_BT_FEM_CTRL_MAN_LEN	        5
#define	B_CTL_RB_BT_FEM_CTRL_MAN_OFFSET	        2
#define B_CTL_RB_BT_FEM_CTRL_MAN_MASK    		0x7C
#define	B_CTL_RB_BT_FEM_CTRL_MAN_SEL_LEN	        1
#define	B_CTL_RB_BT_FEM_CTRL_MAN_SEL_OFFSET	        1
#define B_CTL_RB_BT_FEM_CTRL_MAN_SEL_MASK    		0x2
#define	B_CTL_RB_BT_FEM_CTRL_EN_LEN	        1
#define	B_CTL_RB_BT_FEM_CTRL_EN_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_EN_MASK    		0x1

#define	B_CTL_RB_CLK_32K_DET_DONE_STS_MASK_LEN	        1
#define	B_CTL_RB_CLK_32K_DET_DONE_STS_MASK_OFFSET	        8
#define B_CTL_RB_CLK_32K_DET_DONE_STS_MASK_MASK    		0x100
#define	B_CTL_RB_BTOP0_WDT_RST_EN_LEN	        4
#define	B_CTL_RB_BTOP0_WDT_RST_EN_OFFSET	        4
#define B_CTL_RB_BTOP0_WDT_RST_EN_MASK    		0xF0
#define	B_CTL_RB_BTOP0_RST_SOFT_N_LEN	        4
#define	B_CTL_RB_BTOP0_RST_SOFT_N_OFFSET	        0
#define B_CTL_RB_BTOP0_RST_SOFT_N_MASK    		0xF

#define	B_CTL_RB_BWDT_CUR_STS_LEN	        1
#define	B_CTL_RB_BWDT_CUR_STS_OFFSET	        2
#define B_CTL_RB_BWDT_CUR_STS_MASK    		0x4
#define	B_CTL_RB_BTIMER_CUR_STS_LEN	        1
#define	B_CTL_RB_BTIMER_CUR_STS_OFFSET	        1
#define B_CTL_RB_BTIMER_CUR_STS_MASK    		0x2
#define	B_CTL_RB_BDMA_CUR_STS_LEN	        1
#define	B_CTL_RB_BDMA_CUR_STS_OFFSET	        0
#define B_CTL_RB_BDMA_CUR_STS_MASK    		0x1

#define	B_CTL_RB_CFG_B_BWDT_RST_N_DIS_LEN	        1
#define	B_CTL_RB_CFG_B_BWDT_RST_N_DIS_OFFSET	        0
#define B_CTL_RB_CFG_B_BWDT_RST_N_DIS_MASK    		0x1

#define	B_CTL_RB_CORE_DBG_WDT_HALT_EN_LEN	        1
#define	B_CTL_RB_CORE_DBG_WDT_HALT_EN_OFFSET	        0
#define B_CTL_RB_CORE_DBG_WDT_HALT_EN_MASK    		0x1

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_3_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_3_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_3_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_2_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_2_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_2_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_1_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_1_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_1_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_0_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_0_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_0_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_7_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_7_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_7_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_6_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_6_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_6_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_5_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_5_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_5_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_4_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_4_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_4_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_11_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_11_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_11_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_10_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_10_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_10_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_9_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_9_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_9_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_8_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_8_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_8_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_15_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_15_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_15_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_14_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_14_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_14_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_13_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_13_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_13_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_12_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_12_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_12_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_19_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_19_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_19_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_18_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_18_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_18_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_17_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_17_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_17_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_16_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_16_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_16_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_23_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_23_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_23_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_22_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_22_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_22_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_21_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_21_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_21_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_20_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_20_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_20_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_27_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_27_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_27_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_26_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_26_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_26_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_25_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_25_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_25_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_24_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_24_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_24_MASK    		0xF

#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_31_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_31_OFFSET	        12
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_31_MASK    		0xF000
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_30_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_30_OFFSET	        8
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_30_MASK    		0xF00
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_29_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_29_OFFSET	        4
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_29_MASK    		0xF0
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_28_LEN	        4
#define	B_CTL_RB_BT_FEM_CTRL_REG_CFG_28_OFFSET	        0
#define B_CTL_RB_BT_FEM_CTRL_REG_CFG_28_MASK    		0xF

#define	B_CTL_RB_BTOP_AHB_S2_ICM_PRIORITY_LEN	        8
#define	B_CTL_RB_BTOP_AHB_S2_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S2_ICM_PRIORITY_MASK    		0xFF

#define	B_CTL_RB_BTOP_AHB_S3_ICM_PRIORITY_LEN	        8
#define	B_CTL_RB_BTOP_AHB_S3_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S3_ICM_PRIORITY_MASK    		0xFF

#define	B_CTL_RB_BTOP_AHB_S1_ICM_PRIORITY_LEN	        8
#define	B_CTL_RB_BTOP_AHB_S1_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S1_ICM_PRIORITY_MASK    		0xFF

#define	B_CTL_RB_BTOP_AHB_S4_ICM_PRIORITY_LEN	        2
#define	B_CTL_RB_BTOP_AHB_S4_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S4_ICM_PRIORITY_MASK    		0x3

#define	B_CTL_RB_BTOP_AHB_S5_ICM_PRIORITY_LEN	        2
#define	B_CTL_RB_BTOP_AHB_S5_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S5_ICM_PRIORITY_MASK    		0x3

#define	B_CTL_RB_BTOP_AHB_S6_ICM_PRIORITY_LEN	        2
#define	B_CTL_RB_BTOP_AHB_S6_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_AHB_S6_ICM_PRIORITY_MASK    		0x3

#define	B_CTL_RB_BTOP_ICM2X1S7_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM2X1S7_ICM_AUTO_CG_BYPASS_OFFSET	        18
#define B_CTL_RB_BTOP_ICM2X1S7_ICM_AUTO_CG_BYPASS_MASK    		0x40000
#define	B_CTL_RB_BTOP_B2A_H2H_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_B2A_H2H_AUTO_CG_BYPASS_OFFSET	        17
#define B_CTL_RB_BTOP_B2A_H2H_AUTO_CG_BYPASS_MASK    		0x20000
#define	B_CTL_RB_BCPU_IRQ_SYNC_CLK_FORCE_ON_LEN	        1
#define	B_CTL_RB_BCPU_IRQ_SYNC_CLK_FORCE_ON_OFFSET	        16
#define B_CTL_RB_BCPU_IRQ_SYNC_CLK_FORCE_ON_MASK    		0x10000
#define	B_CTL_RB_BSUB_AHB_HREADY_MUX_LEN	        1
#define	B_CTL_RB_BSUB_AHB_HREADY_MUX_OFFSET	        15
#define B_CTL_RB_BSUB_AHB_HREADY_MUX_MASK    		0x8000
#define	B_CTL_RB_BT_MH2H_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BT_MH2H_AUTO_CG_BYPASS_OFFSET	        14
#define B_CTL_RB_BT_MH2H_AUTO_CG_BYPASS_MASK    		0x4000
#define	B_CTL_RB_BDMA_HRDATA_EN_BYPASS_LEN	        1
#define	B_CTL_RB_BDMA_HRDATA_EN_BYPASS_OFFSET	        13
#define B_CTL_RB_BDMA_HRDATA_EN_BYPASS_MASK    		0x2000
#define	B_CTL_RB_BSOC_DMA_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BSOC_DMA_AUTO_CG_BYPASS_OFFSET	        12
#define B_CTL_RB_BSOC_DMA_AUTO_CG_BYPASS_MASK    		0x1000
#define	B_CTL_RB_BSOC_UART_COEX_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BSOC_UART_COEX_AUTO_CG_BYPASS_OFFSET	        11
#define B_CTL_RB_BSOC_UART_COEX_AUTO_CG_BYPASS_MASK    		0x800
#define	B_CTL_RB_BTOP_PERP_APB_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_PERP_APB_AUTO_CG_BYPASS_OFFSET	        10
#define B_CTL_RB_BTOP_PERP_APB_AUTO_CG_BYPASS_MASK    		0x400
#define	B_CTL_RB_BTOP_ICM2X1S6_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM2X1S6_ICM_AUTO_CG_BYPASS_OFFSET	        9
#define B_CTL_RB_BTOP_ICM2X1S6_ICM_AUTO_CG_BYPASS_MASK    		0x200
#define	B_CTL_RB_BTOP_ICM2X1S5_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM2X1S5_ICM_AUTO_CG_BYPASS_OFFSET	        8
#define B_CTL_RB_BTOP_ICM2X1S5_ICM_AUTO_CG_BYPASS_MASK    		0x100
#define	B_CTL_RB_BTOP_ICM2X1S4_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM2X1S4_ICM_AUTO_CG_BYPASS_OFFSET	        7
#define B_CTL_RB_BTOP_ICM2X1S4_ICM_AUTO_CG_BYPASS_MASK    		0x80
#define	B_CTL_RB_BTOP_ICM4X1S3_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM4X1S3_ICM_AUTO_CG_BYPASS_OFFSET	        6
#define B_CTL_RB_BTOP_ICM4X1S3_ICM_AUTO_CG_BYPASS_MASK    		0x40
#define	B_CTL_RB_BTOP_ICM4X1S2_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM4X1S2_ICM_AUTO_CG_BYPASS_OFFSET	        5
#define B_CTL_RB_BTOP_ICM4X1S2_ICM_AUTO_CG_BYPASS_MASK    		0x20
#define	B_CTL_RB_BTOP_ICM4X1S1_ICM_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_ICM4X1S1_ICM_AUTO_CG_BYPASS_OFFSET	        4
#define B_CTL_RB_BTOP_ICM4X1S1_ICM_AUTO_CG_BYPASS_MASK    		0x10
#define	B_CTL_RB_BTOP_M45_AHB_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_M45_AHB_AUTO_CG_BYPASS_OFFSET	        3
#define B_CTL_RB_BTOP_M45_AHB_AUTO_CG_BYPASS_MASK    		0x8
#define	B_CTL_RB_BTOP_M3_AHB_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_M3_AHB_AUTO_CG_BYPASS_OFFSET	        2
#define B_CTL_RB_BTOP_M3_AHB_AUTO_CG_BYPASS_MASK    		0x4
#define	B_CTL_RB_BTOP_M2_AHB_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_M2_AHB_AUTO_CG_BYPASS_OFFSET	        1
#define B_CTL_RB_BTOP_M2_AHB_AUTO_CG_BYPASS_MASK    		0x2
#define	B_CTL_RB_BTOP_M1_AHB_AUTO_CG_BYPASS_LEN	        1
#define	B_CTL_RB_BTOP_M1_AHB_AUTO_CG_BYPASS_OFFSET	        0
#define B_CTL_RB_BTOP_M1_AHB_AUTO_CG_BYPASS_MASK    		0x1

#define	B_CTL_RB_BSOC_AHB_S1_OVERTIME_LEN	        1
#define	B_CTL_RB_BSOC_AHB_S1_OVERTIME_OFFSET	        2
#define B_CTL_RB_BSOC_AHB_S1_OVERTIME_MASK    		0x4
#define	B_CTL_RB_BSOC_DFS_S1_EN_LEN	        1
#define	B_CTL_RB_BSOC_DFS_S1_EN_OFFSET	        1
#define B_CTL_RB_BSOC_DFS_S1_EN_MASK    		0x2
#define	B_CTL_RB_BSOC_DFS_S1_CLEAR_LEN	        1
#define	B_CTL_RB_BSOC_DFS_S1_CLEAR_OFFSET	        0
#define B_CTL_RB_BSOC_DFS_S1_CLEAR_MASK    		0x1

#define	B_CTL_RB_BSOC_AHB_OT_DELAY_LEN	        16
#define	B_CTL_RB_BSOC_AHB_OT_DELAY_OFFSET	        0
#define B_CTL_RB_BSOC_AHB_OT_DELAY_MASK    		0xFFFF

#define	B_CTL_RB_BTOP_ICM2X1S7_ICM_ICM_PRIORITY_LEN	        2
#define	B_CTL_RB_BTOP_ICM2X1S7_ICM_ICM_PRIORITY_OFFSET	        0
#define B_CTL_RB_BTOP_ICM2X1S7_ICM_ICM_PRIORITY_MASK    		0x3

#define	B_CTL_RB_BT_CPU_TRACE_MEM_RET1N_LEN	        1
#define	B_CTL_RB_BT_CPU_TRACE_MEM_RET1N_OFFSET	        1
#define B_CTL_RB_BT_CPU_TRACE_MEM_RET1N_MASK    		0x2
#define	B_CTL_RB_BT_POLAR_MEM_RET1N_LEN	        1
#define	B_CTL_RB_BT_POLAR_MEM_RET1N_OFFSET	        0
#define B_CTL_RB_BT_POLAR_MEM_RET1N_MASK    		0x1

#define	B_CTL_RB_BWDT_INT_NMI_MASK_LEN	        1
#define	B_CTL_RB_BWDT_INT_NMI_MASK_OFFSET	        2
#define B_CTL_RB_BWDT_INT_NMI_MASK_MASK    		0x4
#define	B_CTL_RB_BLE_INT_NMI_MASK_LEN	        1
#define	B_CTL_RB_BLE_INT_NMI_MASK_OFFSET	        1
#define B_CTL_RB_BLE_INT_NMI_MASK_MASK    		0x2
#define	B_CTL_RB_BT_INT_NMI_MASK_LEN	        1
#define	B_CTL_RB_BT_INT_NMI_MASK_OFFSET	        0
#define B_CTL_RB_BT_INT_NMI_MASK_MASK    		0x1

#define	B_CTL_RB_BWDT_INT_STS_LEN	        1
#define	B_CTL_RB_BWDT_INT_STS_OFFSET	        2
#define B_CTL_RB_BWDT_INT_STS_MASK    		0x4
#define	B_CTL_RB_BLE_INT_STS_LEN	        1
#define	B_CTL_RB_BLE_INT_STS_OFFSET	        1
#define B_CTL_RB_BLE_INT_STS_MASK    		0x2
#define	B_CTL_RB_BT_INT_STS_LEN	        1
#define	B_CTL_RB_BT_INT_STS_OFFSET	        0
#define B_CTL_RB_BT_INT_STS_MASK    		0x1

#define	B_CTL_RB_BWDT_INT_MASK_STS_LEN	        1
#define	B_CTL_RB_BWDT_INT_MASK_STS_OFFSET	        2
#define B_CTL_RB_BWDT_INT_MASK_STS_MASK    		0x4
#define	B_CTL_RB_BLE_INT_MASK_STS_LEN	        1
#define	B_CTL_RB_BLE_INT_MASK_STS_OFFSET	        1
#define B_CTL_RB_BLE_INT_MASK_STS_MASK    		0x2
#define	B_CTL_RB_BT_INT_MASK_STS_LEN	        1
#define	B_CTL_RB_BT_INT_MASK_STS_OFFSET	        0
#define B_CTL_RB_BT_INT_MASK_STS_MASK    		0x1

#define	B_CTL_RB_BCPU_PCLR_OK_MASK_LEN	        1
#define	B_CTL_RB_BCPU_PCLR_OK_MASK_OFFSET	        0
#define B_CTL_RB_BCPU_PCLR_OK_MASK_MASK    		0x1

#define	B_CTL_RB_SEQ_STS_LEN	        32
#define	B_CTL_RB_SEQ_STS_OFFSET	        0
#define B_CTL_RB_SEQ_STS_MASK    		0xFFFFFFFF

#define	B_CTL_RB_BT_LPEG_INT_RAW_LEN	        12
#define	B_CTL_RB_BT_LPEG_INT_RAW_OFFSET	        12
#define B_CTL_RB_BT_LPEG_INT_RAW_MASK    		0xFFF000
#define	B_CTL_RB_BT_LPEG_INT_STS_LEN	        12
#define	B_CTL_RB_BT_LPEG_INT_STS_OFFSET	        0
#define B_CTL_RB_BT_LPEG_INT_STS_MASK    		0xFFF

#define	B_CTL_RB_B_TCXO_CNT_VALUE_VALID_LEN	        1
#define	B_CTL_RB_B_TCXO_CNT_VALUE_VALID_OFFSET	        4
#define B_CTL_RB_B_TCXO_CNT_VALUE_VALID_MASK    		0x10
#define	B_CTL_RB_B_TCXO_CNT_EN_LEN	        1
#define	B_CTL_RB_B_TCXO_CNT_EN_OFFSET	        2
#define B_CTL_RB_B_TCXO_CNT_EN_MASK    		0x4
#define	B_CTL_RB_B_TCXO_CNT_CLR_LEN	        1
#define	B_CTL_RB_B_TCXO_CNT_CLR_OFFSET	        1
#define B_CTL_RB_B_TCXO_CNT_CLR_MASK    		0x2
#define	B_CTL_RB_B_TCXO_CNT_REFRESH_LEN	        1
#define	B_CTL_RB_B_TCXO_CNT_REFRESH_OFFSET	        0
#define B_CTL_RB_B_TCXO_CNT_REFRESH_MASK    		0x1

#define	B_CTL_RB_B_TCXO_CNT_VALUE_0_LEN	        32
#define	B_CTL_RB_B_TCXO_CNT_VALUE_0_OFFSET	        0
#define B_CTL_RB_B_TCXO_CNT_VALUE_0_MASK    		0xFFFFFFFF

#define	B_CTL_RB_B_TCXO_CNT_VALUE_1_LEN	        32
#define	B_CTL_RB_B_TCXO_CNT_VALUE_1_OFFSET	        0
#define B_CTL_RB_B_TCXO_CNT_VALUE_1_MASK    		0xFFFFFFFF

#define	B_CTL_RB_D2B_INT1_EN_LEN	        1
#define	B_CTL_RB_D2B_INT1_EN_OFFSET	        3
#define B_CTL_RB_D2B_INT1_EN_MASK    		0x8
#define	B_CTL_RB_D2B_INT0_EN_LEN	        1
#define	B_CTL_RB_D2B_INT0_EN_OFFSET	        2
#define B_CTL_RB_D2B_INT0_EN_MASK    		0x4
#define	B_CTL_RB_M2B_INT1_EN_LEN	        1
#define	B_CTL_RB_M2B_INT1_EN_OFFSET	        1
#define B_CTL_RB_M2B_INT1_EN_MASK    		0x2
#define	B_CTL_RB_M2B_INT0_EN_LEN	        1
#define	B_CTL_RB_M2B_INT0_EN_OFFSET	        0
#define B_CTL_RB_M2B_INT0_EN_MASK    		0x1

#define	B_CTL_RB_D2B_INT1_LEN	        1
#define	B_CTL_RB_D2B_INT1_OFFSET	        3
#define B_CTL_RB_D2B_INT1_MASK    		0x8
#define	B_CTL_RB_D2B_INT0_LEN	        1
#define	B_CTL_RB_D2B_INT0_OFFSET	        2
#define B_CTL_RB_D2B_INT0_MASK    		0x4
#define	B_CTL_RB_M2B_INT1_LEN	        1
#define	B_CTL_RB_M2B_INT1_OFFSET	        1
#define B_CTL_RB_M2B_INT1_MASK    		0x2
#define	B_CTL_RB_M2B_INT0_LEN	        1
#define	B_CTL_RB_M2B_INT0_OFFSET	        0
#define B_CTL_RB_M2B_INT0_MASK    		0x1

#define	B_CTL_RB_D2B_INT1_STS_LEN	        1
#define	B_CTL_RB_D2B_INT1_STS_OFFSET	        3
#define B_CTL_RB_D2B_INT1_STS_MASK    		0x8
#define	B_CTL_RB_D2B_INT0_STS_LEN	        1
#define	B_CTL_RB_D2B_INT0_STS_OFFSET	        2
#define B_CTL_RB_D2B_INT0_STS_MASK    		0x4
#define	B_CTL_RB_M2B_INT1_STS_LEN	        1
#define	B_CTL_RB_M2B_INT1_STS_OFFSET	        1
#define B_CTL_RB_M2B_INT1_STS_MASK    		0x2
#define	B_CTL_RB_M2B_INT0_STS_LEN	        1
#define	B_CTL_RB_M2B_INT0_STS_OFFSET	        0
#define B_CTL_RB_M2B_INT0_STS_MASK    		0x1

#define	B_CTL_RB_D2B_INT1_CLR_LEN	        1
#define	B_CTL_RB_D2B_INT1_CLR_OFFSET	        3
#define B_CTL_RB_D2B_INT1_CLR_MASK    		0x8
#define	B_CTL_RB_D2B_INT0_CLR_LEN	        1
#define	B_CTL_RB_D2B_INT0_CLR_OFFSET	        2
#define B_CTL_RB_D2B_INT0_CLR_MASK    		0x4
#define	B_CTL_RB_M2B_INT1_CLR_LEN	        1
#define	B_CTL_RB_M2B_INT1_CLR_OFFSET	        1
#define B_CTL_RB_M2B_INT1_CLR_MASK    		0x2
#define	B_CTL_RB_M2B_INT0_CLR_LEN	        1
#define	B_CTL_RB_M2B_INT0_CLR_OFFSET	        0
#define B_CTL_RB_M2B_INT0_CLR_MASK    		0x1

#define	B_CTL_RB_B2D_INT1_CLR_STICK_STS_LEN	        1
#define	B_CTL_RB_B2D_INT1_CLR_STICK_STS_OFFSET	        3
#define B_CTL_RB_B2D_INT1_CLR_STICK_STS_MASK    		0x8
#define	B_CTL_RB_B2D_INT0_CLR_STICK_STS_LEN	        1
#define	B_CTL_RB_B2D_INT0_CLR_STICK_STS_OFFSET	        2
#define B_CTL_RB_B2D_INT0_CLR_STICK_STS_MASK    		0x4
#define	B_CTL_RB_B2M_INT1_CLR_STICK_STS_LEN	        1
#define	B_CTL_RB_B2M_INT1_CLR_STICK_STS_OFFSET	        1
#define B_CTL_RB_B2M_INT1_CLR_STICK_STS_MASK    		0x2
#define	B_CTL_RB_B2M_INT0_CLR_STICK_STS_LEN	        1
#define	B_CTL_RB_B2M_INT0_CLR_STICK_STS_OFFSET	        0
#define B_CTL_RB_B2M_INT0_CLR_STICK_STS_MASK    		0x1

#define	B_CTL_RB_B2D_INT1_SET_LEN	        1
#define	B_CTL_RB_B2D_INT1_SET_OFFSET	        3
#define B_CTL_RB_B2D_INT1_SET_MASK    		0x8
#define	B_CTL_RB_B2D_INT0_SET_LEN	        1
#define	B_CTL_RB_B2D_INT0_SET_OFFSET	        2
#define B_CTL_RB_B2D_INT0_SET_MASK    		0x4
#define	B_CTL_RB_B2M_INT1_SET_LEN	        1
#define	B_CTL_RB_B2M_INT1_SET_OFFSET	        1
#define B_CTL_RB_B2M_INT1_SET_MASK    		0x2
#define	B_CTL_RB_B2M_INT0_SET_LEN	        1
#define	B_CTL_RB_B2M_INT0_SET_OFFSET	        0
#define B_CTL_RB_B2M_INT0_SET_MASK    		0x1

#define	B_CTL_RB_B2D_INT1_SOFT_RST_N_LEN	        1
#define	B_CTL_RB_B2D_INT1_SOFT_RST_N_OFFSET	        3
#define B_CTL_RB_B2D_INT1_SOFT_RST_N_MASK    		0x8
#define	B_CTL_RB_B2D_INT0_SOFT_RST_N_LEN	        1
#define	B_CTL_RB_B2D_INT0_SOFT_RST_N_OFFSET	        2
#define B_CTL_RB_B2D_INT0_SOFT_RST_N_MASK    		0x4
#define	B_CTL_RB_B2M_INT1_SOFT_RST_N_LEN	        1
#define	B_CTL_RB_B2M_INT1_SOFT_RST_N_OFFSET	        1
#define B_CTL_RB_B2M_INT1_SOFT_RST_N_MASK    		0x2
#define	B_CTL_RB_B2M_INT0_SOFT_RST_N_LEN	        1
#define	B_CTL_RB_B2M_INT0_SOFT_RST_N_OFFSET	        0
#define B_CTL_RB_B2M_INT0_SOFT_RST_N_MASK    		0x1

#define	B_CTL_RB_B_CLK_DIAG_SEL_LEN	        2
#define	B_CTL_RB_B_CLK_DIAG_SEL_OFFSET	        4
#define B_CTL_RB_B_CLK_DIAG_SEL_MASK    		0x30
#define	B_CTL_RB_B_SOC_DIAG_SEL_LEN	        4
#define	B_CTL_RB_B_SOC_DIAG_SEL_OFFSET	        0
#define B_CTL_RB_B_SOC_DIAG_SEL_MASK    		0xF

#define	B_CTL_RB_BRAM_DIAG_EN_LEN	        3
#define	B_CTL_RB_BRAM_DIAG_EN_OFFSET	        5
#define B_CTL_RB_BRAM_DIAG_EN_MASK    		0xE0

#define	B_CTL_RB_CFG_B_FEM_CTRL_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_FEM_CTRL_CLKEN_OFFSET	        22
#define B_CTL_RB_CFG_B_FEM_CTRL_CLKEN_MASK    		0x400000
#define	B_CTL_RB_CFG_B_AHB_MONITOR_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_AHB_MONITOR_CLKEN_OFFSET	        21
#define B_CTL_RB_CFG_B_AHB_MONITOR_CLKEN_MASK    		0x200000
#define	B_CTL_RB_CFG_B_CLKTEST_BT_RF_ASSOCLK_32M_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_CLKTEST_BT_RF_ASSOCLK_32M_CLKEN_OFFSET	        20
#define B_CTL_RB_CFG_B_CLKTEST_BT_RF_ASSOCLK_32M_CLKEN_MASK    		0x100000
#define	B_CTL_RB_CFG_B_CLKTEST_BT_SRC_CLK_HADM_CK_SYNC_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_CLKTEST_BT_SRC_CLK_HADM_CK_SYNC_CLKEN_OFFSET	        19
#define B_CTL_RB_CFG_B_CLKTEST_BT_SRC_CLK_HADM_CK_SYNC_CLKEN_MASK    		0x80000
#define	B_CTL_RB_CFG_B_CLKTEST_BT_ADC_ASSOCLK_32M_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_CLKTEST_BT_ADC_ASSOCLK_32M_CLKEN_OFFSET	        18
#define B_CTL_RB_CFG_B_CLKTEST_BT_ADC_ASSOCLK_32M_CLKEN_MASK    		0x40000
#define	B_CTL_RB_CFG_B_LP_ENG_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_LP_ENG_CLKEN_OFFSET	        17
#define B_CTL_RB_CFG_B_LP_ENG_CLKEN_MASK    		0x20000
#define	B_CTL_RB_CFG_B_TWS_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_TWS_CLKEN_OFFSET	        16
#define B_CTL_RB_CFG_B_TWS_CLKEN_MASK    		0x10000
#define	B_CTL_RB_PERP_BWDT_CLKEN_LEN	        1
#define	B_CTL_RB_PERP_BWDT_CLKEN_OFFSET	        15
#define B_CTL_RB_PERP_BWDT_CLKEN_MASK    		0x8000
#define	B_CTL_RB_PERP_BTIMER_CLKEN_LEN	        1
#define	B_CTL_RB_PERP_BTIMER_CLKEN_OFFSET	        14
#define B_CTL_RB_PERP_BTIMER_CLKEN_MASK    		0x4000
#define	B_CTL_RB_CFG_B_TSENSOR_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_TSENSOR_CLKEN_OFFSET	        13
#define B_CTL_RB_CFG_B_TSENSOR_CLKEN_MASK    		0x2000
#define	B_CTL_RB_BWDT_CLKEN_LEN	        1
#define	B_CTL_RB_BWDT_CLKEN_OFFSET	        12
#define B_CTL_RB_BWDT_CLKEN_MASK    		0x1000
#define	B_CTL_RB_BTIMER_CLKEN_LEN	        1
#define	B_CTL_RB_BTIMER_CLKEN_OFFSET	        11
#define B_CTL_RB_BTIMER_CLKEN_MASK    		0x800
#define	B_CTL_RB_CFG_B_BT_CPU_TRACE_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_BT_CPU_TRACE_CLKEN_OFFSET	        10
#define B_CTL_RB_CFG_B_BT_CPU_TRACE_CLKEN_MASK    		0x400
#define	B_CTL_RB_CFG_B_BT_DIAG_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_BT_DIAG_CLKEN_OFFSET	        9
#define B_CTL_RB_CFG_B_BT_DIAG_CLKEN_MASK    		0x200
#define	B_CTL_RB_B_UART_CLKEN_LEN	        1
#define	B_CTL_RB_B_UART_CLKEN_OFFSET	        8
#define B_CTL_RB_B_UART_CLKEN_MASK    		0x100
#define	B_CTL_RB_B_DMA_CLKEN_LEN	        1
#define	B_CTL_RB_B_DMA_CLKEN_OFFSET	        7
#define B_CTL_RB_B_DMA_CLKEN_MASK    		0x80
#define	B_CTL_RB_CFG_B_BCBB_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_BCBB_CLKEN_OFFSET	        6
#define B_CTL_RB_CFG_B_BCBB_CLKEN_MASK    		0x40
#define	B_CTL_RB_CFG_B_BMEM_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_BMEM_CLKEN_OFFSET	        5
#define B_CTL_RB_CFG_B_BMEM_CLKEN_MASK    		0x20
#define	B_CTL_RB_CFG_B_RF_TEST_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_RF_TEST_CLKEN_OFFSET	        4
#define B_CTL_RB_CFG_B_RF_TEST_CLKEN_MASK    		0x10
#define	B_CTL_RB_CFG_B_CLK_B_UART_CLKSEL_LEN	        1
#define	B_CTL_RB_CFG_B_CLK_B_UART_CLKSEL_OFFSET	        3
#define B_CTL_RB_CFG_B_CLK_B_UART_CLKSEL_MASK    		0x8
#define	B_CTL_RB_CFG_B_GLUE_TRIGGER_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_GLUE_TRIGGER_CLKEN_OFFSET	        2
#define B_CTL_RB_CFG_B_GLUE_TRIGGER_CLKEN_MASK    		0x4
#define	B_CTL_RB_CFG_B_BCPU_HCLKEN_MAN_LEN	        1
#define	B_CTL_RB_CFG_B_BCPU_HCLKEN_MAN_OFFSET	        1
#define B_CTL_RB_CFG_B_BCPU_HCLKEN_MAN_MASK    		0x2
#define	B_CTL_RB_CFG_B_32M_2X_CLKSEL_LEN	        1
#define	B_CTL_RB_CFG_B_32M_2X_CLKSEL_OFFSET	        0
#define B_CTL_RB_CFG_B_32M_2X_CLKSEL_MASK    		0x1

#define	B_CTL_RB_CFG_B_B32M_2X_MX_CLKA_STS_LEN	        1
#define	B_CTL_RB_CFG_B_B32M_2X_MX_CLKA_STS_OFFSET	        1
#define B_CTL_RB_CFG_B_B32M_2X_MX_CLKA_STS_MASK    		0x2
#define	B_CTL_RB_CFG_B_B32M_2X_MX_CLKB_STS_LEN	        1
#define	B_CTL_RB_CFG_B_B32M_2X_MX_CLKB_STS_OFFSET	        0
#define B_CTL_RB_CFG_B_B32M_2X_MX_CLKB_STS_MASK    		0x1

#define	B_CTL_RB_CFG_B_SOFT_RST_PULSE_WIDTH_LEN	        8
#define	B_CTL_RB_CFG_B_SOFT_RST_PULSE_WIDTH_OFFSET	        4
#define B_CTL_RB_CFG_B_SOFT_RST_PULSE_WIDTH_MASK    		0xFF0
#define	B_CTL_RB_CFG_B_SOFTRST_BCPU_SYS_TRG_PULSE_LEN	        1
#define	B_CTL_RB_CFG_B_SOFTRST_BCPU_SYS_TRG_PULSE_OFFSET	        3
#define B_CTL_RB_CFG_B_SOFTRST_BCPU_SYS_TRG_PULSE_MASK    		0x8
#define	B_CTL_RB_CFG_B_SOFTRST_BCPU_POR_TRG_PULSE_LEN	        1
#define	B_CTL_RB_CFG_B_SOFTRST_BCPU_POR_TRG_PULSE_OFFSET	        2
#define B_CTL_RB_CFG_B_SOFTRST_BCPU_POR_TRG_PULSE_MASK    		0x4
#define	B_CTL_RB_CFG_B_SOFTRST_BBUS_TRG_PULSE_LEN	        1
#define	B_CTL_RB_CFG_B_SOFTRST_BBUS_TRG_PULSE_OFFSET	        0
#define B_CTL_RB_CFG_B_SOFTRST_BBUS_TRG_PULSE_MASK    		0x1

#define	B_CTL_RB_CFG_B_SOFT_RST_LP_ENG_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_LP_ENG_N_OFFSET	        9
#define B_CTL_RB_CFG_B_SOFT_RST_LP_ENG_N_MASK    		0x200
#define	B_CTL_RB_CFG_B_SOFT_RST_FEM_CTRL_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_FEM_CTRL_N_OFFSET	        8
#define B_CTL_RB_CFG_B_SOFT_RST_FEM_CTRL_N_MASK    		0x100
#define	B_CTL_RB_CFG_B_SOFT_RST_TSENSOR_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_TSENSOR_N_OFFSET	        7
#define B_CTL_RB_CFG_B_SOFT_RST_TSENSOR_N_MASK    		0x80
#define	B_CTL_RB_CFG_B_SOFT_RST_BCBB_CRG_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_BCBB_CRG_N_OFFSET	        6
#define B_CTL_RB_CFG_B_SOFT_RST_BCBB_CRG_N_MASK    		0x40
#define	B_CTL_RB_SOFT_RST_BT_SUB_N_LEN	        1
#define	B_CTL_RB_SOFT_RST_BT_SUB_N_OFFSET	        3
#define B_CTL_RB_SOFT_RST_BT_SUB_N_MASK    		0x8
#define	B_CTL_RB_SOFT_RST_CRG_BT_SUB_N_LEN	        1
#define	B_CTL_RB_SOFT_RST_CRG_BT_SUB_N_OFFSET	        2
#define B_CTL_RB_SOFT_RST_CRG_BT_SUB_N_MASK    		0x4
#define	B_CTL_RB_CFG_B_SOFT_RST_RF_TEST_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_RF_TEST_N_OFFSET	        0
#define B_CTL_RB_CFG_B_SOFT_RST_RF_TEST_N_MASK    		0x1

#define	B_CTL_RB_CFG_B_32M_DLL2_PH_SEL_LEN	        2
#define	B_CTL_RB_CFG_B_32M_DLL2_PH_SEL_OFFSET	        1
#define B_CTL_RB_CFG_B_32M_DLL2_PH_SEL_MASK    		0x6
#define	B_CTL_RB_CFG_B_32M_DLL2_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_32M_DLL2_CLKEN_OFFSET	        0
#define B_CTL_RB_CFG_B_32M_DLL2_CLKEN_MASK    		0x1

#define	B_CTL_RB_CFG_SOFT_BCPU_LPEG_CLKMUX_FORCE_SEL_LEN	        1
#define	B_CTL_RB_CFG_SOFT_BCPU_LPEG_CLKMUX_FORCE_SEL_OFFSET	        10
#define B_CTL_RB_CFG_SOFT_BCPU_LPEG_CLKMUX_FORCE_SEL_MASK    		0x400
#define	B_CTL_RB_CFG_B_32M_CG_MX_DIV_NUM_LEN	        6
#define	B_CTL_RB_CFG_B_32M_CG_MX_DIV_NUM_OFFSET	        4
#define B_CTL_RB_CFG_B_32M_CG_MX_DIV_NUM_MASK    		0x3F0
#define	B_CTL_RB_CFG_B_CPU_DOUBLE_ERR_RST_N_DIS_LEN	        1
#define	B_CTL_RB_CFG_B_CPU_DOUBLE_ERR_RST_N_DIS_OFFSET	        1
#define B_CTL_RB_CFG_B_CPU_DOUBLE_ERR_RST_N_DIS_MASK    		0x2
#define	B_CTL_RB_CFG_B_32M_CG_MX_LOAD_DIV_EN_LEN	        1
#define	B_CTL_RB_CFG_B_32M_CG_MX_LOAD_DIV_EN_OFFSET	        0
#define B_CTL_RB_CFG_B_32M_CG_MX_LOAD_DIV_EN_MASK    		0x1

#define	B_CTL_RB_CFG_B_CLK_BPERP_BUS_DIV_NUM_LEN	        4
#define	B_CTL_RB_CFG_B_CLK_BPERP_BUS_DIV_NUM_OFFSET	        4
#define B_CTL_RB_CFG_B_CLK_BPERP_BUS_DIV_NUM_MASK    		0xF0
#define	B_CTL_RB_CFG_B_CLK_BPERP_BUS_LOAD_DIV_EN_LEN	        1
#define	B_CTL_RB_CFG_B_CLK_BPERP_BUS_LOAD_DIV_EN_OFFSET	        0
#define B_CTL_RB_CFG_B_CLK_BPERP_BUS_LOAD_DIV_EN_MASK    		0x1

#define	B_CTL_RB_CFG_B_SOFT_RST_BCPU_POR_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_BCPU_POR_N_OFFSET	        1
#define B_CTL_RB_CFG_B_SOFT_RST_BCPU_POR_N_MASK    		0x2
#define	B_CTL_RB_CFG_B_SOFT_RST_BCPU_SYS_N_LEN	        1
#define	B_CTL_RB_CFG_B_SOFT_RST_BCPU_SYS_N_OFFSET	        0
#define B_CTL_RB_CFG_B_SOFT_RST_BCPU_SYS_N_MASK    		0x1

#define	B_CTL_RB_CFG_B_TSENSOR_CLK_DIV_EN_LEN	        1
#define	B_CTL_RB_CFG_B_TSENSOR_CLK_DIV_EN_OFFSET	        8
#define B_CTL_RB_CFG_B_TSENSOR_CLK_DIV_EN_MASK    		0x100
#define	B_CTL_RB_CFG_B_TSENSOR_DIV_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_TSENSOR_DIV_CLKEN_OFFSET	        7
#define B_CTL_RB_CFG_B_TSENSOR_DIV_CLKEN_MASK    		0x80
#define	B_CTL_RB_CFG_B_TSENSOR_DIV_NUM_LEN	        7
#define	B_CTL_RB_CFG_B_TSENSOR_DIV_NUM_OFFSET	        0
#define B_CTL_RB_CFG_B_TSENSOR_DIV_NUM_MASK    		0x7F

#define	B_CTL_RB_CFG_B_BCBB_ADC_RX_CLKEN_LEN	        1
#define	B_CTL_RB_CFG_B_BCBB_ADC_RX_CLKEN_OFFSET	        0
#define B_CTL_RB_CFG_B_BCBB_ADC_RX_CLKEN_MASK    		0x1

#define	B_CTL_RB_BT_MEM_PWER_MODE_OUT_LEN	        3
#define	B_CTL_RB_BT_MEM_PWER_MODE_OUT_OFFSET	        2
#define B_CTL_RB_BT_MEM_PWER_MODE_OUT_MASK    		0x1C
#define	B_CTL_RB_BT_MEM_BANK_CGEN_SEL_LEN	        1
#define	B_CTL_RB_BT_MEM_BANK_CGEN_SEL_OFFSET	        1
#define B_CTL_RB_BT_MEM_BANK_CGEN_SEL_MASK    		0x2
#define	B_CTL_RB_BT_MEM_BANK_CGEN_LEN	        1
#define	B_CTL_RB_BT_MEM_BANK_CGEN_OFFSET	        0
#define B_CTL_RB_BT_MEM_BANK_CGEN_MASK    		0x1

#define	B_CTL_RB_CFG_B_TCXO_CLK_DIV_EN_LEN	        1
#define	B_CTL_RB_CFG_B_TCXO_CLK_DIV_EN_OFFSET	        8
#define B_CTL_RB_CFG_B_TCXO_CLK_DIV_EN_MASK    		0x100
#define	B_CTL_RB_CFG_B_TCXO_LOAD_DIV_EN_LEN	        1
#define	B_CTL_RB_CFG_B_TCXO_LOAD_DIV_EN_OFFSET	        4
#define B_CTL_RB_CFG_B_TCXO_LOAD_DIV_EN_MASK    		0x10
#define	B_CTL_RB_CFG_B_TCXO_DIV_NUM_LEN	        3
#define	B_CTL_RB_CFG_B_TCXO_DIV_NUM_OFFSET	        0
#define B_CTL_RB_CFG_B_TCXO_DIV_NUM_MASK    		0x7

#define	B_CTL_RB_AHB_MONITOR_CLKEN_0_LEN	        1
#define	B_CTL_RB_AHB_MONITOR_CLKEN_0_OFFSET	        1
#define B_CTL_RB_AHB_MONITOR_CLKEN_0_MASK    		0x2
#define	B_CTL_RB_AHB_MONITOR_EN_0_LEN	        1
#define	B_CTL_RB_AHB_MONITOR_EN_0_OFFSET	        0
#define B_CTL_RB_AHB_MONITOR_EN_0_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_0_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_0_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_0_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_MASK_0_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_MASK_0_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_MASK_0_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_STS_0_LEN	        8
#define	B_CTL_RB_ACCESS_MEM_INT_STS_0_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_STS_0_MASK    		0xFF

#define	B_CTL_RB_ACCESS_MEM_INT_CLR_0_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_CLR_0_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_CLR_0_MASK    		0x1

#define	B_CTL_RB_REC_ADDR_L_0_LEN	        16
#define	B_CTL_RB_REC_ADDR_L_0_OFFSET	        0
#define B_CTL_RB_REC_ADDR_L_0_MASK    		0xFFFF

#define	B_CTL_RB_REC_ADDR_H_0_LEN	        16
#define	B_CTL_RB_REC_ADDR_H_0_OFFSET	        0
#define B_CTL_RB_REC_ADDR_H_0_MASK    		0xFFFF

#define	B_CTL_RB_REC_ID_0_LEN	        2
#define	B_CTL_RB_REC_ID_0_OFFSET	        8
#define B_CTL_RB_REC_ID_0_MASK    		0x300
#define	B_CTL_RB_REC_WR_0_LEN	        1
#define	B_CTL_RB_REC_WR_0_OFFSET	        0
#define B_CTL_RB_REC_WR_0_MASK    		0x1

#define	B_CTL_RB_MONITOR_MEM_ADDR_EN_0_LEN	        8
#define	B_CTL_RB_MONITOR_MEM_ADDR_EN_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR_EN_0_MASK    		0xFF

#define	B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_0_LEN	        16
#define	B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_0_OFFSET	        0
#define B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_L_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_L_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_H_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_H_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_L_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_L_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_H_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_H_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_L_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_L_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_H_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_H_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_L_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_L_H_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_L_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_L_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_H_L_0_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_H_0_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_H_0_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_H_H_0_MASK    		0xFFFF

#define	B_CTL_RB_AHB_MONITOR_CLKEN_1_LEN	        1
#define	B_CTL_RB_AHB_MONITOR_CLKEN_1_OFFSET	        1
#define B_CTL_RB_AHB_MONITOR_CLKEN_1_MASK    		0x2
#define	B_CTL_RB_AHB_MONITOR_EN_1_LEN	        1
#define	B_CTL_RB_AHB_MONITOR_EN_1_OFFSET	        0
#define B_CTL_RB_AHB_MONITOR_EN_1_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_1_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_1_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_1_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_MASK_1_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_MASK_1_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_MASK_1_MASK    		0x1

#define	B_CTL_RB_ACCESS_MEM_INT_STS_1_LEN	        8
#define	B_CTL_RB_ACCESS_MEM_INT_STS_1_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_STS_1_MASK    		0xFF

#define	B_CTL_RB_ACCESS_MEM_INT_CLR_1_LEN	        1
#define	B_CTL_RB_ACCESS_MEM_INT_CLR_1_OFFSET	        0
#define B_CTL_RB_ACCESS_MEM_INT_CLR_1_MASK    		0x1

#define	B_CTL_RB_REC_ADDR_L_1_LEN	        16
#define	B_CTL_RB_REC_ADDR_L_1_OFFSET	        0
#define B_CTL_RB_REC_ADDR_L_1_MASK    		0xFFFF

#define	B_CTL_RB_REC_ADDR_H_1_LEN	        16
#define	B_CTL_RB_REC_ADDR_H_1_OFFSET	        0
#define B_CTL_RB_REC_ADDR_H_1_MASK    		0xFFFF

#define	B_CTL_RB_REC_ID_1_LEN	        2
#define	B_CTL_RB_REC_ID_1_OFFSET	        8
#define B_CTL_RB_REC_ID_1_MASK    		0x300
#define	B_CTL_RB_REC_WR_1_LEN	        1
#define	B_CTL_RB_REC_WR_1_OFFSET	        0
#define B_CTL_RB_REC_WR_1_MASK    		0x1

#define	B_CTL_RB_MONITOR_MEM_ADDR_EN_1_LEN	        8
#define	B_CTL_RB_MONITOR_MEM_ADDR_EN_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR_EN_1_MASK    		0xFF

#define	B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_1_LEN	        16
#define	B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_1_OFFSET	        0
#define B_CTL_RB_CFG_PKT_MONITOR_INT_DLY_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_L_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_L_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_L_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_H_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR0_H_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR0_H_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_L_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_L_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_L_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_H_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR1_H_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR1_H_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_L_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_L_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_L_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_H_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR2_H_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR2_H_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_L_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_L_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_L_H_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_L_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_L_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_H_L_1_MASK    		0xFFFF

#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_H_1_LEN	        16
#define	B_CTL_RB_MONITOR_MEM_ADDR3_H_H_1_OFFSET	        0
#define B_CTL_RB_MONITOR_MEM_ADDR3_H_H_1_MASK    		0xFFFF

#define	B_CTL_RB_CFG_BT_H2H_SYNC_SEL_LEN	        1
#define	B_CTL_RB_CFG_BT_H2H_SYNC_SEL_OFFSET	        2
#define B_CTL_RB_CFG_BT_H2H_SYNC_SEL_MASK    		0x4
#define	B_CTL_RB_CFG_BT_H2H_TYPE_LEN	        1
#define	B_CTL_RB_CFG_BT_H2H_TYPE_OFFSET	        1
#define B_CTL_RB_CFG_BT_H2H_TYPE_MASK    		0x2
#define	B_CTL_RB_CFG_BT_H2H_FASL_SEL_LEN	        1
#define	B_CTL_RB_CFG_BT_H2H_FASL_SEL_OFFSET	        0
#define B_CTL_RB_CFG_BT_H2H_FASL_SEL_MASK    		0x1

#define	B_CTL_RB_BSOC_UART_COEX_TRX_CFG_LEN	        1
#define	B_CTL_RB_BSOC_UART_COEX_TRX_CFG_OFFSET	        0
#define B_CTL_RB_BSOC_UART_COEX_TRX_CFG_MASK    		0x1

#define	B_CTL_RB_SYS_TICK_FRZ_BSOC_LEN	        1
#define	B_CTL_RB_SYS_TICK_FRZ_BSOC_OFFSET	        0
#define B_CTL_RB_SYS_TICK_FRZ_BSOC_MASK    		0x1

#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_1_LEN	        16
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_1_OFFSET	        16
#define B_CTL_RB_SYS_TICK_VALUE_BSOC_1_MASK    		0xFFFF0000
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_0_LEN	        16
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_0_OFFSET	        0
#define B_CTL_RB_SYS_TICK_VALUE_BSOC_0_MASK    		0xFFFF

#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_3_LEN	        16
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_3_OFFSET	        16
#define B_CTL_RB_SYS_TICK_VALUE_BSOC_3_MASK    		0xFFFF0000
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_2_LEN	        16
#define	B_CTL_RB_SYS_TICK_VALUE_BSOC_2_OFFSET	        0
#define B_CTL_RB_SYS_TICK_VALUE_BSOC_2_MASK    		0xFFFF

#define	B_CTL_RB_RFLDO3_VSET_WORK_LEN	        5
#define	B_CTL_RB_RFLDO3_VSET_WORK_OFFSET	        24
#define B_CTL_RB_RFLDO3_VSET_WORK_MASK    		0x1F000000
#define	B_CTL_RB_RFLDO2_VSET_WORK_LEN	        8
#define	B_CTL_RB_RFLDO2_VSET_WORK_OFFSET	        16
#define B_CTL_RB_RFLDO2_VSET_WORK_MASK    		0xFF0000
#define	B_CTL_RB_RFLDO1_VSET_WORK_LEN	        8
#define	B_CTL_RB_RFLDO1_VSET_WORK_OFFSET	        8
#define B_CTL_RB_RFLDO1_VSET_WORK_MASK    		0xFF00
#define	B_CTL_RB_RFLDO0_VSET_WORK_LEN	        8
#define	B_CTL_RB_RFLDO0_VSET_WORK_OFFSET	        0
#define B_CTL_RB_RFLDO0_VSET_WORK_MASK    		0xFF

#define	B_CTL_RB_RFLDO7_VSET_WORK_LEN	        5
#define	B_CTL_RB_RFLDO7_VSET_WORK_OFFSET	        24
#define B_CTL_RB_RFLDO7_VSET_WORK_MASK    		0x1F000000
#define	B_CTL_RB_RFLDO6_VSET_WORK_LEN	        5
#define	B_CTL_RB_RFLDO6_VSET_WORK_OFFSET	        16
#define B_CTL_RB_RFLDO6_VSET_WORK_MASK    		0x1F0000
#define	B_CTL_RB_RFLDO5_VSET_WORK_LEN	        5
#define	B_CTL_RB_RFLDO5_VSET_WORK_OFFSET	        8
#define B_CTL_RB_RFLDO5_VSET_WORK_MASK    		0x1F00
#define	B_CTL_RB_RFLDO4_VSET_WORK_LEN	        5
#define	B_CTL_RB_RFLDO4_VSET_WORK_OFFSET	        0
#define B_CTL_RB_RFLDO4_VSET_WORK_MASK    		0x1F

#define	B_CTL_RB_RFLDO3_VSET_IDLE_LEN	        5
#define	B_CTL_RB_RFLDO3_VSET_IDLE_OFFSET	        24
#define B_CTL_RB_RFLDO3_VSET_IDLE_MASK    		0x1F000000
#define	B_CTL_RB_RFLDO2_VSET_IDLE_LEN	        8
#define	B_CTL_RB_RFLDO2_VSET_IDLE_OFFSET	        16
#define B_CTL_RB_RFLDO2_VSET_IDLE_MASK    		0xFF0000
#define	B_CTL_RB_RFLDO1_VSET_IDLE_LEN	        8
#define	B_CTL_RB_RFLDO1_VSET_IDLE_OFFSET	        8
#define B_CTL_RB_RFLDO1_VSET_IDLE_MASK    		0xFF00
#define	B_CTL_RB_RFLDO0_VSET_IDLE_LEN	        8
#define	B_CTL_RB_RFLDO0_VSET_IDLE_OFFSET	        0
#define B_CTL_RB_RFLDO0_VSET_IDLE_MASK    		0xFF

#define	B_CTL_RB_RFLDO7_VSET_IDLE_LEN	        5
#define	B_CTL_RB_RFLDO7_VSET_IDLE_OFFSET	        24
#define B_CTL_RB_RFLDO7_VSET_IDLE_MASK    		0x1F000000
#define	B_CTL_RB_RFLDO6_VSET_IDLE_LEN	        5
#define	B_CTL_RB_RFLDO6_VSET_IDLE_OFFSET	        16
#define B_CTL_RB_RFLDO6_VSET_IDLE_MASK    		0x1F0000
#define	B_CTL_RB_RFLDO5_VSET_IDLE_LEN	        5
#define	B_CTL_RB_RFLDO5_VSET_IDLE_OFFSET	        8
#define B_CTL_RB_RFLDO5_VSET_IDLE_MASK    		0x1F00
#define	B_CTL_RB_RFLDO4_VSET_IDLE_LEN	        5
#define	B_CTL_RB_RFLDO4_VSET_IDLE_OFFSET	        0
#define B_CTL_RB_RFLDO4_VSET_IDLE_MASK    		0x1F

#define	B_CTL_RB_RFLDO7_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO7_VSET_SEL_MAN_OFFSET	        7
#define B_CTL_RB_RFLDO7_VSET_SEL_MAN_MASK    		0x80
#define	B_CTL_RB_RFLDO6_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO6_VSET_SEL_MAN_OFFSET	        6
#define B_CTL_RB_RFLDO6_VSET_SEL_MAN_MASK    		0x40
#define	B_CTL_RB_RFLDO5_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO5_VSET_SEL_MAN_OFFSET	        5
#define B_CTL_RB_RFLDO5_VSET_SEL_MAN_MASK    		0x20
#define	B_CTL_RB_RFLDO4_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO4_VSET_SEL_MAN_OFFSET	        4
#define B_CTL_RB_RFLDO4_VSET_SEL_MAN_MASK    		0x10
#define	B_CTL_RB_RFLDO3_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO3_VSET_SEL_MAN_OFFSET	        3
#define B_CTL_RB_RFLDO3_VSET_SEL_MAN_MASK    		0x8
#define	B_CTL_RB_RFLDO2_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO2_VSET_SEL_MAN_OFFSET	        2
#define B_CTL_RB_RFLDO2_VSET_SEL_MAN_MASK    		0x4
#define	B_CTL_RB_RFLDO1_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO1_VSET_SEL_MAN_OFFSET	        1
#define B_CTL_RB_RFLDO1_VSET_SEL_MAN_MASK    		0x2
#define	B_CTL_RB_RFLDO0_VSET_SEL_MAN_LEN	        1
#define	B_CTL_RB_RFLDO0_VSET_SEL_MAN_OFFSET	        0
#define B_CTL_RB_RFLDO0_VSET_SEL_MAN_MASK    		0x1

#endif // __3322_B_CTL_RB_REG_OFFSET_FIELD_H__
