/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_cfg_s_egpio_mode_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_CFG_S_EGPIO_MODE_REG_OFFSET_FIELD_H__
#define __3322_CFG_S_EGPIO_MODE_REG_OFFSET_FIELD_H__

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO0_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO0_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO0_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO1_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO1_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO1_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO2_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO2_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO2_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO3_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO3_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO3_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO4_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO4_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO4_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO5_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO5_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO5_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO6_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO6_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO6_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO7_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO7_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO7_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO8_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO8_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO8_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO9_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO9_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO9_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO10_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO10_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO10_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO11_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO11_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO11_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO12_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO12_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO12_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO13_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO13_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO13_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO14_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO14_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO14_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO15_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO15_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO15_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO16_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO16_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO16_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO17_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO17_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO17_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO18_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO18_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO18_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO19_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO19_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO19_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO20_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO20_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO20_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO21_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO21_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO21_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO22_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO22_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO22_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO23_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO23_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO23_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO24_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO24_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO24_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO25_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO25_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO25_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO26_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO26_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO26_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO27_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO27_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO27_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO28_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO28_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO28_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO29_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO29_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO29_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO30_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO30_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO30_MODE_MASK    		0x1

#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO31_MODE_LEN	        1
#define	CFG_S_EGPIO_MODE_CFG_S_EGPIO31_MODE_OFFSET	        0
#define CFG_S_EGPIO_MODE_CFG_S_EGPIO31_MODE_MASK    		0x1

#endif // __3322_CFG_S_EGPIO_MODE_REG_OFFSET_FIELD_H__
