/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_ssi_master_regbank_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_SSI_MASTER_REGBANK_REG_OFFSET_FIELD_H__
#define __3322_SSI_MASTER_REGBANK_REG_OFFSET_FIELD_H__

#define	SSI_MASTER_REGBANK_SM_HBASE_ADDR_LEN	        16
#define	SSI_MASTER_REGBANK_SM_HBASE_ADDR_OFFSET	        0
#define SSI_MASTER_REGBANK_SM_HBASE_ADDR_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_AHB_SIZE_16_32_LEN	        1
#define	SSI_MASTER_REGBANK_AHB_SIZE_16_32_OFFSET	        0
#define SSI_MASTER_REGBANK_AHB_SIZE_16_32_MASK    		0x1

#define	SSI_MASTER_REGBANK_SM_BIAS_ADDR_LEN	        16
#define	SSI_MASTER_REGBANK_SM_BIAS_ADDR_OFFSET	        0
#define SSI_MASTER_REGBANK_SM_BIAS_ADDR_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_AHB_HRESP_ERR_LEN	        2
#define	SSI_MASTER_REGBANK_AHB_HRESP_ERR_OFFSET	        3
#define SSI_MASTER_REGBANK_AHB_HRESP_ERR_MASK    		0x18
#define	SSI_MASTER_REGBANK_AHB_HRESP_LEN	        2
#define	SSI_MASTER_REGBANK_AHB_HRESP_OFFSET	        1
#define SSI_MASTER_REGBANK_AHB_HRESP_MASK    		0x6
#define	SSI_MASTER_REGBANK_AHB_HREADY_LEN	        1
#define	SSI_MASTER_REGBANK_AHB_HREADY_OFFSET	        0
#define SSI_MASTER_REGBANK_AHB_HREADY_MASK    		0x1

#define	SSI_MASTER_REGBANK_SM_ERR_HADDR_LEN	        16
#define	SSI_MASTER_REGBANK_SM_ERR_HADDR_OFFSET	        0
#define SSI_MASTER_REGBANK_SM_ERR_HADDR_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_SM_ERR_LADDR_LEN	        16
#define	SSI_MASTER_REGBANK_SM_ERR_LADDR_OFFSET	        0
#define SSI_MASTER_REGBANK_SM_ERR_LADDR_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_CLEAR_LEN	        1
#define	SSI_MASTER_REGBANK_CLEAR_OFFSET	        0
#define SSI_MASTER_REGBANK_CLEAR_MASK    		0x1

#define	SSI_MASTER_REGBANK_SSI_AON_CLKSEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_AON_CLKSEL_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_AON_CLKSEL_MASK    		0x1

#define	SSI_MASTER_REGBANK_SSI_GRM_SEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_GRM_SEL_OFFSET	        4
#define SSI_MASTER_REGBANK_SSI_GRM_SEL_MASK    		0x10
#define	SSI_MASTER_REGBANK_SSI_RST_AON_CRG_SEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_AON_CRG_SEL_OFFSET	        3
#define SSI_MASTER_REGBANK_SSI_RST_AON_CRG_SEL_MASK    		0x8
#define	SSI_MASTER_REGBANK_SSI_RST_AON_LGC_SEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_AON_LGC_SEL_OFFSET	        2
#define SSI_MASTER_REGBANK_SSI_RST_AON_LGC_SEL_MASK    		0x4
#define	SSI_MASTER_REGBANK_SSI_RST_PMU_SEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_PMU_SEL_OFFSET	        1
#define SSI_MASTER_REGBANK_SSI_RST_PMU_SEL_MASK    		0x2
#define	SSI_MASTER_REGBANK_SSI_RST_SEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_SEL_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_RST_SEL_MASK    		0x1

#define	SSI_MASTER_REGBANK_SSI_GRM_CLKSEL_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_GRM_CLKSEL_OFFSET	        4
#define SSI_MASTER_REGBANK_SSI_GRM_CLKSEL_MASK    		0x10
#define	SSI_MASTER_REGBANK_SSI_RST_AON_CRG_N_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_AON_CRG_N_OFFSET	        3
#define SSI_MASTER_REGBANK_SSI_RST_AON_CRG_N_MASK    		0x8
#define	SSI_MASTER_REGBANK_SSI_RST_AON_LGC_N_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_AON_LGC_N_OFFSET	        2
#define SSI_MASTER_REGBANK_SSI_RST_AON_LGC_N_MASK    		0x4
#define	SSI_MASTER_REGBANK_SSI_RST_PMU_N_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_PMU_N_OFFSET	        1
#define SSI_MASTER_REGBANK_SSI_RST_PMU_N_MASK    		0x2
#define	SSI_MASTER_REGBANK_SSI_RST_N_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_RST_N_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_RST_N_MASK    		0x1

#define	SSI_MASTER_REGBANK_SSI_HGRANT_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_HGRANT_OFFSET	        1
#define SSI_MASTER_REGBANK_SSI_HGRANT_MASK    		0x2
#define	SSI_MASTER_REGBANK_SSI_HBUSREQ_LEN	        1
#define	SSI_MASTER_REGBANK_SSI_HBUSREQ_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_HBUSREQ_MASK    		0x1

#define	SSI_MASTER_REGBANK_SSI_SYS_CTL_ID_LEN	        16
#define	SSI_MASTER_REGBANK_SSI_SYS_CTL_ID_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_SYS_CTL_ID_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_SSI_GP_REG0_LEN	        16
#define	SSI_MASTER_REGBANK_SSI_GP_REG0_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_GP_REG0_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_SSI_GP_REG1_LEN	        16
#define	SSI_MASTER_REGBANK_SSI_GP_REG1_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_GP_REG1_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_SSI_GP_REG2_LEN	        16
#define	SSI_MASTER_REGBANK_SSI_GP_REG2_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_GP_REG2_MASK    		0xFFFF

#define	SSI_MASTER_REGBANK_SSI_GP_REG3_LEN	        16
#define	SSI_MASTER_REGBANK_SSI_GP_REG3_OFFSET	        0
#define SSI_MASTER_REGBANK_SSI_GP_REG3_MASK    		0xFFFF

#endif // __3322_SSI_MASTER_REGBANK_REG_OFFSET_FIELD_H__
