/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_sfc_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_SFC_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_SFC_CTL_RB_REG_OFFSET_FIELD_H__

#define	SFC_CTL_RB_SAMPLE_TEST_LEN	        5
#define	SFC_CTL_RB_SAMPLE_TEST_OFFSET	        6
#define SFC_CTL_RB_SAMPLE_TEST_MASK    		0x7C0
#define	SFC_CTL_RB_RD_DELAY_LEN	        3
#define	SFC_CTL_RB_RD_DELAY_OFFSET	        3
#define SFC_CTL_RB_RD_DELAY_MASK    		0x38
#define	SFC_CTL_RB_FLASH_ADDR_MODE_LEN	        1
#define	SFC_CTL_RB_FLASH_ADDR_MODE_OFFSET	        2
#define SFC_CTL_RB_FLASH_ADDR_MODE_MASK    		0x4
#define	SFC_CTL_RB_WP_EN_LEN	        1
#define	SFC_CTL_RB_WP_EN_OFFSET	        1
#define SFC_CTL_RB_WP_EN_MASK    		0x2
#define	SFC_CTL_RB_MODE_LEN	        1
#define	SFC_CTL_RB_MODE_OFFSET	        0
#define SFC_CTL_RB_MODE_MASK    		0x1

#define	SFC_CTL_RB_TCSH_LEN	        3
#define	SFC_CTL_RB_TCSH_OFFSET	        12
#define SFC_CTL_RB_TCSH_MASK    		0x7000
#define	SFC_CTL_RB_TCSS_LEN	        3
#define	SFC_CTL_RB_TCSS_OFFSET	        8
#define SFC_CTL_RB_TCSS_MASK    		0x700
#define	SFC_CTL_RB_TSHSL_LEN	        4
#define	SFC_CTL_RB_TSHSL_OFFSET	        0
#define SFC_CTL_RB_TSHSL_MASK    		0xF

#define	SFC_CTL_RB_DMA_DONE_INT_RAW_STATUS_LEN	        1
#define	SFC_CTL_RB_DMA_DONE_INT_RAW_STATUS_OFFSET	        1
#define SFC_CTL_RB_DMA_DONE_INT_RAW_STATUS_MASK    		0x2
#define	SFC_CTL_RB_CMD_OP_END_RAW_STATUS_LEN	        1
#define	SFC_CTL_RB_CMD_OP_END_RAW_STATUS_OFFSET	        0
#define SFC_CTL_RB_CMD_OP_END_RAW_STATUS_MASK    		0x1

#define	SFC_CTL_RB_DMA_DONE_INT_STATUS_LEN	        1
#define	SFC_CTL_RB_DMA_DONE_INT_STATUS_OFFSET	        1
#define SFC_CTL_RB_DMA_DONE_INT_STATUS_MASK    		0x2
#define	SFC_CTL_RB_CMD_OP_END_STATUS_LEN	        1
#define	SFC_CTL_RB_CMD_OP_END_STATUS_OFFSET	        0
#define SFC_CTL_RB_CMD_OP_END_STATUS_MASK    		0x1

#define	SFC_CTL_RB_DMA_DONE_INT_MASK_LEN	        1
#define	SFC_CTL_RB_DMA_DONE_INT_MASK_OFFSET	        1
#define SFC_CTL_RB_DMA_DONE_INT_MASK_MASK    		0x2
#define	SFC_CTL_RB_CMD_OP_END_INT_MASK_LEN	        1
#define	SFC_CTL_RB_CMD_OP_END_INT_MASK_OFFSET	        0
#define SFC_CTL_RB_CMD_OP_END_INT_MASK_MASK    		0x1

#define	SFC_CTL_RB_DMA_DONE_INT_CLR_LEN	        1
#define	SFC_CTL_RB_DMA_DONE_INT_CLR_OFFSET	        1
#define SFC_CTL_RB_DMA_DONE_INT_CLR_MASK    		0x2
#define	SFC_CTL_RB_CMD_OP_END_INT_CLR_LEN	        1
#define	SFC_CTL_RB_CMD_OP_END_INT_CLR_OFFSET	        0
#define SFC_CTL_RB_CMD_OP_END_INT_CLR_MASK    		0x1

#define	SFC_CTL_RB_SFC_BUS_SOFT_RST_MASK_LEN	        1
#define	SFC_CTL_RB_SFC_BUS_SOFT_RST_MASK_OFFSET	        0
#define SFC_CTL_RB_SFC_BUS_SOFT_RST_MASK_MASK    		0x1

#define	SFC_CTL_RB_VERSION_LEN	        32
#define	SFC_CTL_RB_VERSION_OFFSET	        0
#define SFC_CTL_RB_VERSION_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_VERSION_SEL_LEN	        1
#define	SFC_CTL_RB_VERSION_SEL_OFFSET	        0
#define SFC_CTL_RB_VERSION_SEL_MASK    		0x1

#define	SFC_CTL_RB_RD_ENABLE_LEN	        1
#define	SFC_CTL_RB_RD_ENABLE_OFFSET	        31
#define SFC_CTL_RB_RD_ENABLE_MASK    		0x80000000
#define	SFC_CTL_RB_WR_ENABLE_LEN	        1
#define	SFC_CTL_RB_WR_ENABLE_OFFSET	        30
#define SFC_CTL_RB_WR_ENABLE_MASK    		0x40000000
#define	SFC_CTL_RB_WR_INS_LEN	        8
#define	SFC_CTL_RB_WR_INS_OFFSET	        22
#define SFC_CTL_RB_WR_INS_MASK    		0x3FC00000
#define	SFC_CTL_RB_WR_DUMMY_BYTES_LEN	        3
#define	SFC_CTL_RB_WR_DUMMY_BYTES_OFFSET	        19
#define SFC_CTL_RB_WR_DUMMY_BYTES_MASK    		0x380000
#define	SFC_CTL_RB_WR_MEM_IF_TYPE_LEN	        3
#define	SFC_CTL_RB_WR_MEM_IF_TYPE_OFFSET	        16
#define SFC_CTL_RB_WR_MEM_IF_TYPE_MASK    		0x70000
#define	SFC_CTL_RB_RD_INS_LEN	        8
#define	SFC_CTL_RB_RD_INS_OFFSET	        8
#define SFC_CTL_RB_RD_INS_MASK    		0xFF00
#define	SFC_CTL_RB_RD_PREFETCH_CNT_LEN	        2
#define	SFC_CTL_RB_RD_PREFETCH_CNT_OFFSET	        6
#define SFC_CTL_RB_RD_PREFETCH_CNT_MASK    		0xC0
#define	SFC_CTL_RB_RD_DUMMY_BYTES_LEN	        3
#define	SFC_CTL_RB_RD_DUMMY_BYTES_OFFSET	        3
#define SFC_CTL_RB_RD_DUMMY_BYTES_MASK    		0x38
#define	SFC_CTL_RB_RD_MEM_IF_TYPE_LEN	        3
#define	SFC_CTL_RB_RD_MEM_IF_TYPE_OFFSET	        0
#define SFC_CTL_RB_RD_MEM_IF_TYPE_MASK    		0x7

#define	SFC_CTL_RB_SFC_DDR_TX_DELAY_ENABLE_LEN	        1
#define	SFC_CTL_RB_SFC_DDR_TX_DELAY_ENABLE_OFFSET	        12
#define SFC_CTL_RB_SFC_DDR_TX_DELAY_ENABLE_MASK    		0x1000
#define	SFC_CTL_RB_DDR_WR_DUMMY_BYTES_LEN	        4
#define	SFC_CTL_RB_DDR_WR_DUMMY_BYTES_OFFSET	        8
#define SFC_CTL_RB_DDR_WR_DUMMY_BYTES_MASK    		0xF00
#define	SFC_CTL_RB_DDR_RD_DUMMY_BYTES_LEN	        4
#define	SFC_CTL_RB_DDR_RD_DUMMY_BYTES_OFFSET	        4
#define SFC_CTL_RB_DDR_RD_DUMMY_BYTES_MASK    		0xF0
#define	SFC_CTL_RB_BUS_DDR_MODE_LEN	        1
#define	SFC_CTL_RB_BUS_DDR_MODE_OFFSET	        3
#define SFC_CTL_RB_BUS_DDR_MODE_MASK    		0x8
#define	SFC_CTL_RB_WIP_LOCATE_LEN	        3
#define	SFC_CTL_RB_WIP_LOCATE_OFFSET	        0
#define SFC_CTL_RB_WIP_LOCATE_MASK    		0x7

#define	SFC_CTL_RB_FLASH_SIZE_CS1_LEN	        4
#define	SFC_CTL_RB_FLASH_SIZE_CS1_OFFSET	        8
#define SFC_CTL_RB_FLASH_SIZE_CS1_MASK    		0xF00
#define	SFC_CTL_RB_FLASH_SIZE_CS0_LEN	        4
#define	SFC_CTL_RB_FLASH_SIZE_CS0_OFFSET	        0
#define SFC_CTL_RB_FLASH_SIZE_CS0_MASK    		0xF

#define	SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS0_LEN	        16
#define	SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS0_OFFSET	        16
#define SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS0_MASK    		0xFFFF0000

#define	SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS1_LEN	        16
#define	SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS1_OFFSET	        16
#define SFC_CTL_RB_BUS_BASE_ADDR_HIGH_CS1_MASK    		0xFFFF0000

#define	SFC_CTL_RB_FLASH_ALIAS_ADDR_LEN	        16
#define	SFC_CTL_RB_FLASH_ALIAS_ADDR_OFFSET	        16
#define SFC_CTL_RB_FLASH_ALIAS_ADDR_MASK    		0xFFFF0000

#define	SFC_CTL_RB_ALIAS_CS_LEN	        1
#define	SFC_CTL_RB_ALIAS_CS_OFFSET	        0
#define SFC_CTL_RB_ALIAS_CS_MASK    		0x1

#define	SFC_CTL_RB_DMA_SEL_CS_LEN	        1
#define	SFC_CTL_RB_DMA_SEL_CS_OFFSET	        4
#define SFC_CTL_RB_DMA_SEL_CS_MASK    		0x10
#define	SFC_CTL_RB_DMA_RW_LEN	        1
#define	SFC_CTL_RB_DMA_RW_OFFSET	        1
#define SFC_CTL_RB_DMA_RW_MASK    		0x2
#define	SFC_CTL_RB_DMA_START_LEN	        1
#define	SFC_CTL_RB_DMA_START_OFFSET	        0
#define SFC_CTL_RB_DMA_START_MASK    		0x1

#define	SFC_CTL_RB_DMA_MEM_SADDR_LEN	        32
#define	SFC_CTL_RB_DMA_MEM_SADDR_OFFSET	        0
#define SFC_CTL_RB_DMA_MEM_SADDR_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_DMA_FLASH_SADDR_LEN	        32
#define	SFC_CTL_RB_DMA_FLASH_SADDR_OFFSET	        0
#define SFC_CTL_RB_DMA_FLASH_SADDR_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_DMA_LEN_LEN	        30
#define	SFC_CTL_RB_DMA_LEN_OFFSET	        0
#define SFC_CTL_RB_DMA_LEN_MASK    		0x3FFFFFFF

#define	SFC_CTL_RB_INCR16_EN_LEN	        1
#define	SFC_CTL_RB_INCR16_EN_OFFSET	        2
#define SFC_CTL_RB_INCR16_EN_MASK    		0x4
#define	SFC_CTL_RB_INCR8_EN_LEN	        1
#define	SFC_CTL_RB_INCR8_EN_OFFSET	        1
#define SFC_CTL_RB_INCR8_EN_MASK    		0x2
#define	SFC_CTL_RB_INCR4_EN_LEN	        1
#define	SFC_CTL_RB_INCR4_EN_OFFSET	        0
#define SFC_CTL_RB_INCR4_EN_MASK    		0x1

#define	SFC_CTL_RB_CONTINU_READ_STATUS_LEN	        1
#define	SFC_CTL_RB_CONTINU_READ_STATUS_OFFSET	        0
#define SFC_CTL_RB_CONTINU_READ_STATUS_MASK    		0x1

#define	SFC_CTL_RB_M_BYTE_LEN	        8
#define	SFC_CTL_RB_M_BYTE_OFFSET	        0
#define SFC_CTL_RB_M_BYTE_MASK    		0xFF

#define	SFC_CTL_RB_MEM_IF_TYPE_LEN	        3
#define	SFC_CTL_RB_MEM_IF_TYPE_OFFSET	        17
#define SFC_CTL_RB_MEM_IF_TYPE_MASK    		0xE0000
#define	SFC_CTL_RB_DATA_CNT_LEN	        8
#define	SFC_CTL_RB_DATA_CNT_OFFSET	        9
#define SFC_CTL_RB_DATA_CNT_MASK    		0x1FE00
#define	SFC_CTL_RB_RW_LEN	        1
#define	SFC_CTL_RB_RW_OFFSET	        8
#define SFC_CTL_RB_RW_MASK    		0x100
#define	SFC_CTL_RB_DATA_EN_LEN	        1
#define	SFC_CTL_RB_DATA_EN_OFFSET	        7
#define SFC_CTL_RB_DATA_EN_MASK    		0x80
#define	SFC_CTL_RB_DUMMY_BYTE_CNT_LEN	        3
#define	SFC_CTL_RB_DUMMY_BYTE_CNT_OFFSET	        4
#define SFC_CTL_RB_DUMMY_BYTE_CNT_MASK    		0x70
#define	SFC_CTL_RB_ADDR_EN_LEN	        1
#define	SFC_CTL_RB_ADDR_EN_OFFSET	        3
#define SFC_CTL_RB_ADDR_EN_MASK    		0x8
#define	SFC_CTL_RB_SEL_CS_LEN	        1
#define	SFC_CTL_RB_SEL_CS_OFFSET	        1
#define SFC_CTL_RB_SEL_CS_MASK    		0x2
#define	SFC_CTL_RB_START_LEN	        1
#define	SFC_CTL_RB_START_OFFSET	        0
#define SFC_CTL_RB_START_MASK    		0x1

#define	SFC_CTL_RB_DDR_DUMMY_BYTE_CNT_LEN	        4
#define	SFC_CTL_RB_DDR_DUMMY_BYTE_CNT_OFFSET	        12
#define SFC_CTL_RB_DDR_DUMMY_BYTE_CNT_MASK    		0xF000
#define	SFC_CTL_RB_CMD_DDR_MODE_LEN	        1
#define	SFC_CTL_RB_CMD_DDR_MODE_OFFSET	        8
#define SFC_CTL_RB_CMD_DDR_MODE_MASK    		0x100
#define	SFC_CTL_RB_REG_INS_LEN	        8
#define	SFC_CTL_RB_REG_INS_OFFSET	        0
#define SFC_CTL_RB_REG_INS_MASK    		0xFF

#define	SFC_CTL_RB_CMD_ADDR_LEN	        30
#define	SFC_CTL_RB_CMD_ADDR_OFFSET	        0
#define SFC_CTL_RB_CMD_ADDR_MASK    		0x3FFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_0_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_0_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_1_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_1_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_2_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_2_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_3_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_3_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_4_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_4_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_4_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_5_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_5_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_5_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_6_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_6_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_6_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_7_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_7_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_7_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_8_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_8_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_8_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_9_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_9_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_9_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_10_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_10_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_10_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_11_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_11_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_11_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_12_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_12_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_12_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_13_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_13_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_13_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_14_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_14_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_14_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_DATABUF_N_15_LEN	        32
#define	SFC_CTL_RB_CMD_DATABUF_N_15_OFFSET	        0
#define SFC_CTL_RB_CMD_DATABUF_N_15_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_TEECPU_LOCK_FLAG_LEN	        1
#define	SFC_CTL_RB_TEECPU_LOCK_FLAG_OFFSET	        0
#define SFC_CTL_RB_TEECPU_LOCK_FLAG_MASK    		0x1

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_0_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_0_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_0_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_1_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_1_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_1_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_2_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_2_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_2_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_3_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_3_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_3_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_4_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_4_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_4_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_5_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_5_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_5_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_6_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_6_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_6_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_7_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_7_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_7_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_8_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_8_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_8_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_9_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_9_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_9_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_10_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_10_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_10_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_11_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_11_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_11_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_12_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_12_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_12_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_13_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_13_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_13_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_14_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_14_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_14_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_15_LEN	        24
#define	SFC_CTL_RB_APC_CFG_START_ADDR_N_15_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_START_ADDR_N_15_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_0_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_0_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_0_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_1_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_1_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_1_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_2_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_2_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_2_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_3_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_3_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_3_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_4_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_4_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_4_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_5_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_5_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_5_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_6_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_6_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_6_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_7_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_7_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_7_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_8_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_8_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_8_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_9_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_9_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_9_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_10_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_10_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_10_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_11_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_11_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_11_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_12_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_12_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_12_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_13_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_13_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_13_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_14_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_14_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_14_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_15_LEN	        24
#define	SFC_CTL_RB_APC_CFG_END_ADDR_N_15_OFFSET	        8
#define SFC_CTL_RB_APC_CFG_END_ADDR_N_15_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_0_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_0_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_1_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_1_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_2_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_2_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_3_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_3_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_4_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_4_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_4_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_5_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_5_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_5_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_6_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_6_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_6_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_7_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_7_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_7_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_8_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_8_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_8_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_9_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_9_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_9_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_10_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_10_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_10_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_11_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_11_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_11_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_12_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_12_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_12_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_13_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_13_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_13_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_14_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_14_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_14_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_15_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_15_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_RD_ID_N_15_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_0_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_0_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_1_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_1_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_2_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_2_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_3_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_3_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_4_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_4_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_4_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_5_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_5_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_5_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_6_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_6_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_6_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_7_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_7_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_7_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_8_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_8_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_8_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_9_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_9_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_9_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_10_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_10_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_10_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_11_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_11_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_11_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_12_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_12_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_12_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_13_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_13_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_13_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_14_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_14_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_14_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_15_LEN	        32
#define	SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_15_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_ALLOW_WR_ID_N_15_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_0_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_0_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_0_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_1_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_1_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_1_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_2_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_2_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_2_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_3_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_3_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_3_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_4_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_4_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_4_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_5_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_5_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_5_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_6_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_6_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_6_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_7_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_7_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_7_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_8_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_8_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_8_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_9_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_9_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_9_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_10_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_10_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_10_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_11_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_11_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_11_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_12_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_12_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_12_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_13_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_13_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_13_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_14_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_14_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_14_MASK    		0xF

#define	SFC_CTL_RB_APC_CFG_APC_EN_N_15_LEN	        4
#define	SFC_CTL_RB_APC_CFG_APC_EN_N_15_OFFSET	        0
#define SFC_CTL_RB_APC_CFG_APC_EN_N_15_MASK    		0xF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_0_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_0_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_1_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_1_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_2_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_2_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_3_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_3_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_4_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_4_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_4_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_5_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_5_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_5_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_6_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_6_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_6_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_7_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_7_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_7_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_8_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_8_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_8_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_9_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_9_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_9_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_10_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_10_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_10_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_11_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_11_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_11_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_12_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_12_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_12_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_13_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_13_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_13_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_14_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_14_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_14_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_15_LEN	        32
#define	SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_15_OFFSET	        0
#define SFC_CTL_RB_FAPC_AUTH_MAC_SADDR_N_15_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_FAPC_DEC_AUTH_CFG_LEN	        32
#define	SFC_CTL_RB_SFC_FAPC_DEC_AUTH_CFG_OFFSET	        0
#define SFC_CTL_RB_SFC_FAPC_DEC_AUTH_CFG_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_FAPC_SADDR_STATUS_LEN	        32
#define	SFC_CTL_RB_SFC_FAPC_SADDR_STATUS_OFFSET	        0
#define SFC_CTL_RB_SFC_FAPC_SADDR_STATUS_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_FAPC_EADDR_STATUS_LEN	        32
#define	SFC_CTL_RB_SFC_FAPC_EADDR_STATUS_OFFSET	        0
#define SFC_CTL_RB_SFC_FAPC_EADDR_STATUS_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_APC_ERR_INT_WITH_MASK_LEN	        1
#define	SFC_CTL_RB_SFC_APC_ERR_INT_WITH_MASK_OFFSET	        1
#define SFC_CTL_RB_SFC_APC_ERR_INT_WITH_MASK_MASK    		0x2
#define	SFC_CTL_RB_SFC_APC_ERR_INT_LEN	        1
#define	SFC_CTL_RB_SFC_APC_ERR_INT_OFFSET	        0
#define SFC_CTL_RB_SFC_APC_ERR_INT_MASK    		0x1

#define	SFC_CTL_RB_SFC_APC_CLR_LEN	        1
#define	SFC_CTL_RB_SFC_APC_CLR_OFFSET	        0
#define SFC_CTL_RB_SFC_APC_CLR_MASK    		0x1

#define	SFC_CTL_RB_SFC_APC_INT_MASK_LEN	        1
#define	SFC_CTL_RB_SFC_APC_INT_MASK_OFFSET	        0
#define SFC_CTL_RB_SFC_APC_INT_MASK_MASK    		0x1

#define	SFC_CTL_RB_SFC_FPAC_ONEWAY_LOCK_LEN	        16
#define	SFC_CTL_RB_SFC_FPAC_ONEWAY_LOCK_OFFSET	        0
#define SFC_CTL_RB_SFC_FPAC_ONEWAY_LOCK_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_APC_STATUS_LEN	        32
#define	SFC_CTL_RB_CMD_LUT0_APC_STATUS_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_APC_STATUS_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_APC_STATUS_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_APC_STATUS_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_APC_STATUS_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_RB_APC_STATUS_LEN	        32
#define	SFC_CTL_RB_CMD_RB_APC_STATUS_OFFSET	        0
#define SFC_CTL_RB_CMD_RB_APC_STATUS_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_FAPC_HIT_REGION_STATUS_LEN	        4
#define	SFC_CTL_RB_SFC_FAPC_HIT_REGION_STATUS_OFFSET	        0
#define SFC_CTL_RB_SFC_FAPC_HIT_REGION_STATUS_MASK    		0xF

#define	SFC_CTL_RB_LEA_LP_EN_LEN	        1
#define	SFC_CTL_RB_LEA_LP_EN_OFFSET	        0
#define SFC_CTL_RB_LEA_LP_EN_MASK    		0x1

#define	SFC_CTL_RB_LEA_DFX_INFO_LEN	        32
#define	SFC_CTL_RB_LEA_DFX_INFO_OFFSET	        0
#define SFC_CTL_RB_LEA_DFX_INFO_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_FLASH_VOTE_ACPU_LEN	        4
#define	SFC_CTL_RB_FLASH_VOTE_ACPU_OFFSET	        0
#define SFC_CTL_RB_FLASH_VOTE_ACPU_MASK    		0xF

#define	SFC_CTL_RB_FLASH_VOTE_PCPU_LEN	        4
#define	SFC_CTL_RB_FLASH_VOTE_PCPU_OFFSET	        0
#define SFC_CTL_RB_FLASH_VOTE_PCPU_MASK    		0xF

#define	SFC_CTL_RB_FLASH_VOTE_IOMCU_LEN	        4
#define	SFC_CTL_RB_FLASH_VOTE_IOMCU_OFFSET	        0
#define SFC_CTL_RB_FLASH_VOTE_IOMCU_MASK    		0xF

#define	SFC_CTL_RB_CMD_LUT0_INS_0_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_0_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_0_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_0_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_0_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_0_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_1_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_1_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_1_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_1_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_1_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_1_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_2_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_2_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_2_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_2_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_2_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_2_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_3_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_3_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_3_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_3_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_3_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_3_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_4_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_4_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_4_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_4_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_4_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_4_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_5_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_5_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_5_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_5_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_5_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_5_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_6_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_6_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_6_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_6_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_6_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_6_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_7_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_7_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_7_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_7_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_7_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_7_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_8_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_8_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_8_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_8_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_8_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_8_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_9_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_9_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_9_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_9_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_9_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_9_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_10_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_10_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_10_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_10_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_10_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_10_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_11_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_11_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_11_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_11_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_11_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_11_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_12_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_12_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_12_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_12_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_12_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_12_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_13_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_13_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_13_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_13_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_13_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_13_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_14_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_14_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_14_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_14_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_14_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_14_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT0_INS_15_LEN	        8
#define	SFC_CTL_RB_CMD_LUT0_INS_15_OFFSET	        24
#define SFC_CTL_RB_CMD_LUT0_INS_15_MASK    		0xFF000000
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_15_LEN	        16
#define	SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_15_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_ALLOW_IDS_15_MASK    		0xFFFF

#define	SFC_CTL_RB_CMD_LUT1_0_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_0_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_1_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_1_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_2_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_2_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_3_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_3_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_4_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_4_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_4_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_5_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_5_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_5_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_6_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_6_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_6_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_7_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_7_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_7_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_8_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_8_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_8_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_9_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_9_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_9_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_10_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_10_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_10_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_11_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_11_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_11_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_12_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_12_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_12_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_13_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_13_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_13_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_14_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_14_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_14_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_15_LEN	        32
#define	SFC_CTL_RB_CMD_LUT1_15_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_15_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_CMD_LUT1_EN_LEN	        1
#define	SFC_CTL_RB_CMD_LUT1_EN_OFFSET	        16
#define SFC_CTL_RB_CMD_LUT1_EN_MASK    		0x10000
#define	SFC_CTL_RB_CMD_LUT0_EN_LEN	        1
#define	SFC_CTL_RB_CMD_LUT0_EN_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT0_EN_MASK    		0x1

#define	SFC_CTL_RB_SFC_CMD_LUT_CFG_LOCK_LEN	        1
#define	SFC_CTL_RB_SFC_CMD_LUT_CFG_LOCK_OFFSET	        0
#define SFC_CTL_RB_SFC_CMD_LUT_CFG_LOCK_MASK    		0x1

#define	SFC_CTL_RB_CMD_LUT1_RW_LEN	        1
#define	SFC_CTL_RB_CMD_LUT1_RW_OFFSET	        0
#define SFC_CTL_RB_CMD_LUT1_RW_MASK    		0x1

#define	SFC_CTL_RB_LEA_IV_VLD_LEN	        1
#define	SFC_CTL_RB_LEA_IV_VLD_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_VLD_MASK    		0x1

#define	SFC_CTL_RB_LEA_IV_ACPU_0_LEN	        32
#define	SFC_CTL_RB_LEA_IV_ACPU_0_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_ACPU_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_ACPU_1_LEN	        32
#define	SFC_CTL_RB_LEA_IV_ACPU_1_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_ACPU_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_ACPU_2_LEN	        32
#define	SFC_CTL_RB_LEA_IV_ACPU_2_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_ACPU_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_ACPU_3_LEN	        32
#define	SFC_CTL_RB_LEA_IV_ACPU_3_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_ACPU_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_PCPU_0_LEN	        32
#define	SFC_CTL_RB_LEA_IV_PCPU_0_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_PCPU_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_PCPU_1_LEN	        32
#define	SFC_CTL_RB_LEA_IV_PCPU_1_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_PCPU_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_PCPU_2_LEN	        32
#define	SFC_CTL_RB_LEA_IV_PCPU_2_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_PCPU_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_PCPU_3_LEN	        32
#define	SFC_CTL_RB_LEA_IV_PCPU_3_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_PCPU_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_IV_START_ADDR_0_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_0_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_0_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_1_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_1_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_1_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_2_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_2_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_2_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_3_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_3_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_3_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_4_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_4_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_4_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_5_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_5_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_5_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_6_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_6_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_6_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_7_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_7_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_7_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_8_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_8_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_8_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_9_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_9_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_9_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_10_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_10_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_10_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_11_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_11_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_11_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_12_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_12_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_12_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_13_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_13_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_13_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_14_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_14_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_14_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_IV_START_ADDR_15_LEN	        24
#define	SFC_CTL_RB_IV_START_ADDR_15_OFFSET	        8
#define SFC_CTL_RB_IV_START_ADDR_15_MASK    		0xFFFFFF00

#define	SFC_CTL_RB_BUS_RD_INS_LUT_LEN	        32
#define	SFC_CTL_RB_BUS_RD_INS_LUT_OFFSET	        0
#define SFC_CTL_RB_BUS_RD_INS_LUT_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_BUS_WR_INS_LUT_LEN	        32
#define	SFC_CTL_RB_BUS_WR_INS_LUT_OFFSET	        0
#define SFC_CTL_RB_BUS_WR_INS_LUT_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_BUS_INS_LUT_APC_EN_LEN	        32
#define	SFC_CTL_RB_BUS_INS_LUT_APC_EN_OFFSET	        0
#define SFC_CTL_RB_BUS_INS_LUT_APC_EN_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_SCPU_0_LEN	        32
#define	SFC_CTL_RB_LEA_IV_SCPU_0_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_SCPU_0_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_SCPU_1_LEN	        32
#define	SFC_CTL_RB_LEA_IV_SCPU_1_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_SCPU_1_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_SCPU_2_LEN	        32
#define	SFC_CTL_RB_LEA_IV_SCPU_2_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_SCPU_2_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_LEA_IV_SCPU_3_LEN	        32
#define	SFC_CTL_RB_LEA_IV_SCPU_3_OFFSET	        0
#define SFC_CTL_RB_LEA_IV_SCPU_3_MASK    		0xFFFFFFFF

#define	SFC_CTL_RB_SFC_MODE_SEC_CTRL_LEN	        1
#define	SFC_CTL_RB_SFC_MODE_SEC_CTRL_OFFSET	        0
#define SFC_CTL_RB_SFC_MODE_SEC_CTRL_MASK    		0x1

#endif // __3322_SFC_CTL_RB_REG_OFFSET_FIELD_H__
