/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_ulp_fuse_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_ULP_FUSE_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_ULP_FUSE_CTL_RB_REG_OFFSET_FIELD_H__

#define	ULP_FUSE_CTL_RB_ULP_EFUSE_CTL_ID_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_EFUSE_CTL_ID_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_EFUSE_CTL_ID_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG0_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG0_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG0_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG1_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG1_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG1_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG2_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG2_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG2_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG3_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG3_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_EFUSE_GP_REG3_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_EFUSE_BOOT_DONE_LEN	        1
#define	ULP_FUSE_CTL_RB_EFUSE_BOOT_DONE_OFFSET	        0
#define ULP_FUSE_CTL_RB_EFUSE_BOOT_DONE_MASK    		0x1

#define	ULP_FUSE_CTL_RB_EFUSE_AUTO_RD_EN_LEN	        1
#define	ULP_FUSE_CTL_RB_EFUSE_AUTO_RD_EN_OFFSET	        0
#define ULP_FUSE_CTL_RB_EFUSE_AUTO_RD_EN_MASK    		0x1

#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_MAN_LEN	        8
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_MAN_OFFSET	        8
#define ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_MAN_MASK    		0xFF00
#define	ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_MAN_LEN	        8
#define	ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_MAN_OFFSET	        0
#define ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_MAN_MASK    		0xFF

#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_MAN_LEN	        4
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_MAN_OFFSET	        12
#define ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_MAN_MASK    		0xF000
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_MAN_LEN	        4
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_MAN_OFFSET	        8
#define ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_MAN_MASK    		0xF00
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_MAN_LEN	        8
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_MAN_OFFSET	        0
#define ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_MAN_MASK    		0xFF

#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_MAN_LEN	        6
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_MAN_OFFSET	        6
#define ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_MAN_MASK    		0xFC0
#define	ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_MAN_LEN	        6
#define	ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_MAN_OFFSET	        0
#define ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_MAN_MASK    		0x3F

#define	ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_MAN_LEN	        16
#define	ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_MAN_OFFSET	        0
#define ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_MAN_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_MAN_LEN	        6
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_MAN_OFFSET	        0
#define ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_MAN_MASK    		0x3F

#define	ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_SEL_OFFSET	        9
#define ULP_FUSE_CTL_RB_CFG_PMU1_TRIM_RSV_SEL_MASK    		0x200
#define	ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_SEL_OFFSET	        8
#define ULP_FUSE_CTL_RB_CFG_PMU_ULPREF_TRIM_SEL_MASK    		0x100
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_SEL_OFFSET	        7
#define ULP_FUSE_CTL_RB_CFG_PMU_LPREF_VREF_TRIM_SEL_MASK    		0x80
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_SEL_OFFSET	        6
#define ULP_FUSE_CTL_RB_CFG_PMU_LPREF_IBG_TRIM_SEL_MASK    		0x40
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_SEL_OFFSET	        5
#define ULP_FUSE_CTL_RB_CFG_PMU_IOLDO0_TRIM_SEL_MASK    		0x20
#define	ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_SEL_OFFSET	        4
#define ULP_FUSE_CTL_RB_CFG_PMU_RC_32K_LP_RES_TRIM_SEL_MASK    		0x10
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_SEL_OFFSET	        3
#define ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_CAP_TRIM_SEL_MASK    		0x8
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_SEL_OFFSET	        2
#define ULP_FUSE_CTL_RB_CFG_PMU_XO_32K_IBAIS_TRIM_SEL_MASK    		0x4
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_SEL_LEN	        1
#define	ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_SEL_OFFSET	        1
#define ULP_FUSE_CTL_RB_CFG_PMU_IOLDO4_TRIM_SEL_MASK    		0x2

#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_0_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_0_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_0_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_1_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_1_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_1_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_2_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_2_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_2_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_3_LEN	        16
#define	ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_3_OFFSET	        0
#define ULP_FUSE_CTL_RB_ULP_BOOTDATA_RB_3_MASK    		0xFFFF

#define	ULP_FUSE_CTL_RB_D_PMU_IOLDO4_TRIM_EFUSE_BOOT_VAL_LEN	        4
#define	ULP_FUSE_CTL_RB_D_PMU_IOLDO4_TRIM_EFUSE_BOOT_VAL_OFFSET	        0
#define ULP_FUSE_CTL_RB_D_PMU_IOLDO4_TRIM_EFUSE_BOOT_VAL_MASK    		0xF

#endif // __3322_ULP_FUSE_CTL_RB_REG_OFFSET_FIELD_H__
