/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_cfg_s_agpio_mode_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_CFG_S_AGPIO_MODE_REG_OFFSET_FIELD_H__
#define __3322_CFG_S_AGPIO_MODE_REG_OFFSET_FIELD_H__

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO0_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO0_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO0_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO1_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO1_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO1_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO2_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO2_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO2_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO3_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO3_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO3_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO4_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO4_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO4_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO5_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO5_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO5_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO6_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO6_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO6_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO7_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO7_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO7_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO8_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO8_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO8_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO9_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO9_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO9_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO10_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO10_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO10_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO11_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO11_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO11_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO12_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO12_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO12_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO13_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO13_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO13_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO14_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO14_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO14_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO15_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO15_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO15_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO16_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO16_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO16_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO17_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO17_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO17_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO18_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO18_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO18_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO19_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO19_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO19_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO20_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO20_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO20_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO21_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO21_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO21_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO22_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO22_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO22_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO23_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO23_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO23_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO24_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO24_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO24_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO25_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO25_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO25_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO26_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO26_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO26_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO27_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO27_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO27_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO28_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO28_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO28_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO29_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO29_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO29_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO30_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO30_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO30_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO31_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO31_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO31_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO32_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO32_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO32_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO33_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO33_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO33_MODE_MASK    		0x3

#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO34_MODE_LEN	        2
#define	CFG_S_AGPIO_MODE_CFG_S_AGPIO34_MODE_OFFSET	        0
#define CFG_S_AGPIO_MODE_CFG_S_AGPIO34_MODE_MASK    		0x3

#endif // __3322_CFG_S_AGPIO_MODE_REG_OFFSET_FIELD_H__
