/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_mcu_diag_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_MCU_DIAG_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_MCU_DIAG_CTL_RB_REG_OFFSET_FIELD_H__

#define	MCU_DIAG_CTL_RB_MCU_DIAG_CTL_ID_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CTL_ID_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_CTL_ID_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG0_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG0_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG0_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG1_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG1_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG1_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG2_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG2_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG2_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG3_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG3_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_GP_REG3_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MONITOR_TRACE_SEL_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MONITOR_TRACE_SEL_OFFSET	        1
#define MCU_DIAG_CTL_RB_CFG_MONITOR_TRACE_SEL_MASK    		0x2
#define	MCU_DIAG_CTL_RB_CFG_MONITOR_SEL_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MONITOR_SEL_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MONITOR_SEL_MASK    		0x1

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_SAVE_SEL_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_SAVE_SEL_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_SAVE_SEL_MASK    		0x1

#define	MCU_DIAG_CTL_RB_MCPU_TRACE_ENABLE_LEN	        1
#define	MCU_DIAG_CTL_RB_MCPU_TRACE_ENABLE_OFFSET	        1
#define MCU_DIAG_CTL_RB_MCPU_TRACE_ENABLE_MASK    		0x2
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_EN_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_EN_MASK    		0x1

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_LMI_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_LMI_CLKEN_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_LMI_CLKEN_MASK    		0x100
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MON2LMI_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MON2LMI_CLKEN_OFFSET	        7
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MON2LMI_CLKEN_MASK    		0x80
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_MEM_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_MEM_CLKEN_OFFSET	        6
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_TRACE_MEM_CLKEN_MASK    		0x40
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MCPU_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MCPU_CLKEN_OFFSET	        5
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MCPU_CLKEN_MASK    		0x20
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_CLKEN_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_CPU_TRACE_CLKEN_MASK    		0x10
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_SRC_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_SRC_CLKEN_OFFSET	        3
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_SRC_CLKEN_MASK    		0x8
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_WR_CLKEN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_WR_CLKEN_OFFSET	        1
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_MONITOR_WR_CLKEN_MASK    		0x2

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SEL_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SEL_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SEL_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SYNC_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SYNC_OFFSET	        9
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_SYNC_MASK    		0x200
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_EN_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_EN_MASK    		0x100
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_EN_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_EN_MASK    		0x10
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_MODE_LEN	        2
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_MODE_OFFSET	        2
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_MODE_MASK    		0xC
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_MODE_LEN	        2
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_MODE_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_MODE_MASK    		0x3

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_LENGTH_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_START_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_MCU_DIAG_SAMPLE_END_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_SAMPLE_DONE_MASK    		0x1

#define	MCU_DIAG_CTL_RB_CFG_AUX_ADC_SAMPLE_PERIOD_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_ADC_SAMPLE_PERIOD_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_ADC_SAMPLE_PERIOD_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_LENGTH_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_START_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_AUX_CAPS_SAMPLE_END_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_ADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_LEN	        1
#define	MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_OFFSET	        0
#define MCU_DIAG_CTL_RB_AUX_CAPS_SAMPLE_DONE_MASK    		0x1

#define	MCU_DIAG_CTL_RB_CFG_DIAG_MUX_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_DIAG_MUX_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_DIAG_MUX_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_3_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_3_OFFSET	        12
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_3_MASK    		0xF000
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_2_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_2_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_2_MASK    		0xF00
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_1_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_1_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_1_MASK    		0xF0
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_0_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_0_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_0_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_7_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_7_OFFSET	        12
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_7_MASK    		0xF000
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_6_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_6_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_6_MASK    		0xF00
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_5_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_5_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_5_MASK    		0xF0
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_4_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_4_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_4_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_11_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_11_OFFSET	        12
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_11_MASK    		0xF000
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_10_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_10_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_10_MASK    		0xF00
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_9_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_9_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_9_MASK    		0xF0
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_8_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_8_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_8_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_15_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_15_OFFSET	        12
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_15_MASK    		0xF000
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_14_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_14_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_14_MASK    		0xF00
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_13_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_13_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_13_MASK    		0xF0
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_12_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_PIN_SEL_12_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_PIN_SEL_12_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_SEL_LEN	        6
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_SEL_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_SEL_MASK    		0x3F00
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_SEL_LEN	        6
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_SEL_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_SEL_MASK    		0x3F

#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_EN_OFFSET	        12
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_EN_MASK    		0x1000
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_DIV_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_DIV_OFFSET	        8
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST2_DIV_MASK    		0xF00
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_EN_OFFSET	        4
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_EN_MASK    		0x10
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_DIV_LEN	        4
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_DIV_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_DIV_MASK    		0xF

#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_GATE_EN_LEN	        16
#define	MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_GATE_EN_OFFSET	        0
#define MCU_DIAG_CTL_RB_CFG_CLOCK_TEST_GATE_EN_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_EMPTY_LEN	        1
#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_EMPTY_OFFSET	        2
#define MCU_DIAG_CTL_RB_CAP_SEN_FIFO_EMPTY_MASK    		0x4
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_EMPTY_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_EMPTY_OFFSET	        1
#define MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_EMPTY_MASK    		0x2
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_EMPTY_LEN	        1
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_EMPTY_OFFSET	        0
#define MCU_DIAG_CTL_RB_AUX_ADC_FIFO_EMPTY_MASK    		0x1

#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_STS_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_STS_CLR_OFFSET	        7
#define MCU_DIAG_CTL_RB_CAP_SEN_FIFO_STS_CLR_MASK    		0x80
#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_OVERFLOW_LEN	        1
#define	MCU_DIAG_CTL_RB_CAP_SEN_FIFO_OVERFLOW_OFFSET	        6
#define MCU_DIAG_CTL_RB_CAP_SEN_FIFO_OVERFLOW_MASK    		0x40
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_STS_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_STS_CLR_OFFSET	        5
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_STS_CLR_MASK    		0x20
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_OVERFLOW_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_OVERFLOW_OFFSET	        4
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_OVERFLOW_MASK    		0x10
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_STS_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_STS_CLR_OFFSET	        3
#define MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_STS_CLR_MASK    		0x8
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_OVERFLOW_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_OVERFLOW_OFFSET	        2
#define MCU_DIAG_CTL_RB_MCU_DIAG_CPU_TRACE_FIFO_OVERFLOW_MASK    		0x4
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_STS_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_STS_CLR_OFFSET	        1
#define MCU_DIAG_CTL_RB_AUX_ADC_FIFO_STS_CLR_MASK    		0x2
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_OVERFLOW_LEN	        1
#define	MCU_DIAG_CTL_RB_AUX_ADC_FIFO_OVERFLOW_OFFSET	        0
#define MCU_DIAG_CTL_RB_AUX_ADC_FIFO_OVERFLOW_MASK    		0x1

#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_STS_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_STS_CLR_OFFSET	        3
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_STS_CLR_MASK    		0x8
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_UNDERFLOW_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_UNDERFLOW_OFFSET	        2
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_RFIFO_UNDERFLOW_MASK    		0x4

#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WRITE_DONE_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WRITE_DONE_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WRITE_DONE_MASK    		0x1

#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_CNT_LEN	        6
#define	MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_CNT_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_DIAG_MON2LMI_WFIFO_CNT_MASK    		0x3F

#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_LEN	        1
#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_OFFSET	        2
#define MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_MASK    		0x4
#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_CLR_LEN	        1
#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_CLR_OFFSET	        1
#define MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_CLR_MASK    		0x2
#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_EN_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCPU_AHBBUS_ERR_INT_EN_MASK    		0x1

#define	MCU_DIAG_CTL_RB_MCPU_HADDR_H_LEN	        16
#define	MCU_DIAG_CTL_RB_MCPU_HADDR_H_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCPU_HADDR_H_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCPU_HADDR_L_LEN	        16
#define	MCU_DIAG_CTL_RB_MCPU_HADDR_L_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCPU_HADDR_L_MASK    		0xFFFF

#define	MCU_DIAG_CTL_RB_MCPU_HBURST_LEN	        4
#define	MCU_DIAG_CTL_RB_MCPU_HBURST_OFFSET	        4
#define MCU_DIAG_CTL_RB_MCPU_HBURST_MASK    		0xF0
#define	MCU_DIAG_CTL_RB_MCPU_HSIZE_LEN	        3
#define	MCU_DIAG_CTL_RB_MCPU_HSIZE_OFFSET	        1
#define MCU_DIAG_CTL_RB_MCPU_HSIZE_MASK    		0xE
#define	MCU_DIAG_CTL_RB_MCPU_HWRITE_LEN	        1
#define	MCU_DIAG_CTL_RB_MCPU_HWRITE_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCPU_HWRITE_MASK    		0x1

#define	MCU_DIAG_CTL_RB_MCU_CLOCK_TEST_EN_LEN	        1
#define	MCU_DIAG_CTL_RB_MCU_CLOCK_TEST_EN_OFFSET	        0
#define MCU_DIAG_CTL_RB_MCU_CLOCK_TEST_EN_MASK    		0x1

#endif // __3322_MCU_DIAG_CTL_RB_REG_OFFSET_FIELD_H__
