/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_lp_ctl_ulp_a_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_LP_CTL_ULP_A_RB_REG_OFFSET_FIELD_H__
#define __3322_LP_CTL_ULP_A_RB_REG_OFFSET_FIELD_H__

#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_ID_LEN	        16
#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_ID_OFFSET	        0
#define LP_CTL_ULP_A_RB_LP_CTL_ULP_A_ID_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG1_LEN	        16
#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG1_OFFSET	        0
#define LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG1_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_PP_REG2_LEN	        16
#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_PP_REG2_OFFSET	        0
#define LP_CTL_ULP_A_RB_LP_CTL_ULP_A_PP_REG2_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG3_LEN	        16
#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG3_OFFSET	        0
#define LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG3_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG4_LEN	        16
#define	LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG4_OFFSET	        0
#define LP_CTL_ULP_A_RB_LP_CTL_ULP_A_GP_REG4_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_MODE_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_MODE_OFFSET	        0
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_MODE_MASK    		0x1

#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_MODE_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_MODE_OFFSET	        0
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_MODE_MASK    		0x1

#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS1_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS1_OFFSET	        5
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS1_MASK    		0x20
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS0_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS0_OFFSET	        4
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_DS0_MASK    		0x10
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_ST_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_ST_OFFSET	        3
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_ST_MASK    		0x8
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_IE_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_IE_OFFSET	        2
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_IE_MASK    		0x4
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PD_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PD_OFFSET	        1
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PD_MASK    		0x2
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PU_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PU_OFFSET	        0
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO0_CTRL_PU_MASK    		0x1

#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS1_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS1_OFFSET	        5
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS1_MASK    		0x20
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS0_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS0_OFFSET	        4
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_DS0_MASK    		0x10
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_ST_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_ST_OFFSET	        3
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_ST_MASK    		0x8
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_IE_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_IE_OFFSET	        2
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_IE_MASK    		0x4
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PD_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PD_OFFSET	        1
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PD_MASK    		0x2
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PU_LEN	        1
#define	LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PU_OFFSET	        0
#define LP_CTL_ULP_A_RB_CFG_S_UGPIO1_CTRL_PU_MASK    		0x1

#define	LP_CTL_ULP_A_RB_ULP_DIAG_SEL_LEN	        3
#define	LP_CTL_ULP_A_RB_ULP_DIAG_SEL_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULP_DIAG_SEL_MASK    		0x7

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_STS_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_STS_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_STS_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_STS_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_STS_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_STS_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_STS_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_INT_STS_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_STS_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_STS_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_STS_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_STS_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_STS_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_STS_MASK    		0x1

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_CLR_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_CLR_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_CLR_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_CLR_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_CLR_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_CLR_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_CLR_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_INT_CLR_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_CLR_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_CLR_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_CLR_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_CLR_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_CLR_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_CLR_MASK    		0x1

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_STS_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_STS_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_STS_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_STS_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_STS_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_STS_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_STS_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_STS_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_STS_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_STS_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_STS_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_STS_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_STS_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_STS_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_STS_MASK    		0x1

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_CLR_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EVT_CLR_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_CLR_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EVT_CLR_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_CLR_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EVT_CLR_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_CLR_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_EVT_CLR_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_CLR_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EVT_CLR_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_CLR_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EVT_CLR_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_CLR_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_CLR_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EVT_CLR_MASK    		0x1

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EN_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_EN_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EN_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_EN_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EN_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_EN_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_EN_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_EN_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EN_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_EN_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EN_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_EN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EN_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_EN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_EN_OFFSET	        6
#define LP_CTL_ULP_A_RB_PWRON_DIS_WKUP_INT_EN_MASK    		0x40
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_EN_OFFSET	        5
#define LP_CTL_ULP_A_RB_VBUS_SENSE_DIS_WKUP_INT_EN_MASK    		0x20
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_EN_OFFSET	        4
#define LP_CTL_ULP_A_RB_VBUS_SENSE_WKUP_INT_EN_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_INT_EN_OFFSET	        3
#define LP_CTL_ULP_A_RB_PWRON_WKUP_INT_EN_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_EN_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_INT_EN_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_EN_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_INT_EN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_EN_OFFSET	        0
#define LP_CTL_ULP_A_RB_PWRON_WKUP_SHIP_INT_EN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_ULP_PMU_ABNORMAL_SIGNAL_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_PMU_ABNORMAL_SIGNAL_WKUP_BYPASS_OFFSET	        5
#define LP_CTL_ULP_A_RB_ULP_PMU_ABNORMAL_SIGNAL_WKUP_BYPASS_MASK    		0x20
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_BYPASS_OFFSET	        4
#define LP_CTL_ULP_A_RB_ULP_GPIO_INT_WKUP_BYPASS_MASK    		0x10
#define	LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_V_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_V_WKUP_BYPASS_OFFSET	        3
#define LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_V_WKUP_BYPASS_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_BYPASS_OFFSET	        2
#define LP_CTL_ULP_A_RB_SYS_TICK_ALARM_INT_WKUP_BYPASS_MASK    		0x4
#define	LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_WKUP_BYPASS_OFFSET	        1
#define LP_CTL_ULP_A_RB_PMU_ULP_RST_REQ_WKUP_BYPASS_MASK    		0x2
#define	LP_CTL_ULP_A_RB_VBUS_DIS_WKUP_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_VBUS_DIS_WKUP_BYPASS_OFFSET	        0
#define LP_CTL_ULP_A_RB_VBUS_DIS_WKUP_BYPASS_MASK    		0x1

#define	LP_CTL_ULP_A_RB_BUCK0_SCP_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK0_SCP_GRM_BYPASS_OFFSET	        6
#define LP_CTL_ULP_A_RB_BUCK0_SCP_GRM_BYPASS_MASK    		0x40
#define	LP_CTL_ULP_A_RB_BUCK0_OCP_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK0_OCP_GRM_BYPASS_OFFSET	        5
#define LP_CTL_ULP_A_RB_BUCK0_OCP_GRM_BYPASS_MASK    		0x20
#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_FILTER_OUT_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_FILTER_OUT_GRM_BYPASS_OFFSET	        4
#define LP_CTL_ULP_A_RB_D_PMU_UVLO_FILTER_OUT_GRM_BYPASS_MASK    		0x10
#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_OUT_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_OUT_GRM_BYPASS_OFFSET	        3
#define LP_CTL_ULP_A_RB_D_PMU_UVLO_OUT_GRM_BYPASS_MASK    		0x8
#define	LP_CTL_ULP_A_RB_D_PMU_OVP_OUT_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_OVP_OUT_GRM_BYPASS_OFFSET	        2
#define LP_CTL_ULP_A_RB_D_PMU_OVP_OUT_GRM_BYPASS_MASK    		0x4
#define	LP_CTL_ULP_A_RB_BUCK1_SCP_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK1_SCP_GRM_BYPASS_OFFSET	        1
#define LP_CTL_ULP_A_RB_BUCK1_SCP_GRM_BYPASS_MASK    		0x2
#define	LP_CTL_ULP_A_RB_BUCK1_OCP_GRM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK1_OCP_GRM_BYPASS_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK1_OCP_GRM_BYPASS_MASK    		0x1

#define	LP_CTL_ULP_A_RB_ULP_RB_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_RB_BYPASS_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULP_RB_BYPASS_MASK    		0x2
#define	LP_CTL_ULP_A_RB_ULP_RB_SYSTEM_BYPASS_LEN	        1
#define	LP_CTL_ULP_A_RB_ULP_RB_SYSTEM_BYPASS_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULP_RB_SYSTEM_BYPASS_MASK    		0x1

#define	LP_CTL_ULP_A_RB_RC_XO_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_RC_XO_SEL_OFFSET	        1
#define LP_CTL_ULP_A_RB_RC_XO_SEL_MASK    		0x2
#define	LP_CTL_ULP_A_RB_XO_32K_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_XO_32K_EN_OFFSET	        0
#define LP_CTL_ULP_A_RB_XO_32K_EN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_BUCK0_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_BUCK0_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK0_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_BUCK0_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_BUCK0_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK0_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_BUCK1_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_BUCK1_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK1_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_BUCK1_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_BUCK1_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK1_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_OVP_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_OVP_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_OVP_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_OVP_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_OVP_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_OVP_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_ULVO_EN_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_ULVO_EN_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULVO_EN_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_ULVO_EN_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_ULVO_EN_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULVO_EN_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_RST_DBB_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_RST_DBB_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_RST_DBB_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_RST_DBB_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_RST_DBB_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_RST_DBB_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_ULP_BOOT_COMPLETE_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_ULP_BOOT_COMPLETE_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULP_BOOT_COMPLETE_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_ULP_SAV_COMPLETE_TIME_SOC_LEN	        9
#define	LP_CTL_ULP_A_RB_ULP_SAV_COMPLETE_TIME_SOC_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULP_SAV_COMPLETE_TIME_SOC_MASK    		0x1FF

#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_VAL_OFFSET	        11
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_SAV_VAL_MASK    		0x800
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_VAL_OFFSET	        10
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_BOOT_VAL_MASK    		0x400
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_VAL_OFFSET	        9
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_SAV_VAL_MASK    		0x200
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_VAL_OFFSET	        8
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_BOOT_VAL_MASK    		0x100
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_VAL_OFFSET	        7
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_SAV_VAL_MASK    		0x80
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_VAL_OFFSET	        6
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_BOOT_VAL_MASK    		0x40
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_SEL_OFFSET	        5
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_SEL_MASK    		0x20
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_IBG_EN_MAN_OFFSET	        4
#define LP_CTL_ULP_A_RB_LPREF_IBG_EN_MAN_MASK    		0x10
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_SEL_OFFSET	        3
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_SEL_MASK    		0x8
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BUF_EN_MAN_OFFSET	        2
#define LP_CTL_ULP_A_RB_LPREF_BUF_EN_MAN_MASK    		0x4
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_SEL_OFFSET	        1
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_SEL_MASK    		0x2
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_LPREF_BG_EN_MAN_OFFSET	        0
#define LP_CTL_ULP_A_RB_LPREF_BG_EN_MAN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SEL_OFFSET	        1
#define LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_SEL_MASK    		0x2
#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_MAN_OFFSET	        0
#define LP_CTL_ULP_A_RB_IOLDO4_EN_ECO_MAN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_BUCK1_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK1_EN_SEL_OFFSET	        3
#define LP_CTL_ULP_A_RB_BUCK1_EN_SEL_MASK    		0x8
#define	LP_CTL_ULP_A_RB_BUCK1_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK1_EN_MAN_OFFSET	        2
#define LP_CTL_ULP_A_RB_BUCK1_EN_MAN_MASK    		0x4
#define	LP_CTL_ULP_A_RB_BUCK0_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK0_EN_SEL_OFFSET	        1
#define LP_CTL_ULP_A_RB_BUCK0_EN_SEL_MASK    		0x2
#define	LP_CTL_ULP_A_RB_BUCK0_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_BUCK0_EN_MAN_OFFSET	        0
#define LP_CTL_ULP_A_RB_BUCK0_EN_MAN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_OVP_EN_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_OVP_EN_SAV_VAL_OFFSET	        7
#define LP_CTL_ULP_A_RB_OVP_EN_SAV_VAL_MASK    		0x80
#define	LP_CTL_ULP_A_RB_OVP_EN_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_OVP_EN_BOOT_VAL_OFFSET	        6
#define LP_CTL_ULP_A_RB_OVP_EN_BOOT_VAL_MASK    		0x40
#define	LP_CTL_ULP_A_RB_ULVO_EN_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_ULVO_EN_SAV_VAL_OFFSET	        5
#define LP_CTL_ULP_A_RB_ULVO_EN_SAV_VAL_MASK    		0x20
#define	LP_CTL_ULP_A_RB_ULVO_EN_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_ULVO_EN_BOOT_VAL_OFFSET	        4
#define LP_CTL_ULP_A_RB_ULVO_EN_BOOT_VAL_MASK    		0x10
#define	LP_CTL_ULP_A_RB_OVP_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_OVP_EN_MAN_OFFSET	        3
#define LP_CTL_ULP_A_RB_OVP_EN_MAN_MASK    		0x8
#define	LP_CTL_ULP_A_RB_OVP_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_OVP_EN_SEL_OFFSET	        2
#define LP_CTL_ULP_A_RB_OVP_EN_SEL_MASK    		0x4
#define	LP_CTL_ULP_A_RB_ULVO_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_ULVO_EN_MAN_OFFSET	        1
#define LP_CTL_ULP_A_RB_ULVO_EN_MAN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_ULVO_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_ULVO_EN_SEL_OFFSET	        0
#define LP_CTL_ULP_A_RB_ULVO_EN_SEL_MASK    		0x1

#define	LP_CTL_ULP_A_RB_RST_DBB_TMP_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_RST_DBB_TMP_MAN_OFFSET	        1
#define LP_CTL_ULP_A_RB_RST_DBB_TMP_MAN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_RST_DBB_TMP_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_RST_DBB_TMP_SEL_OFFSET	        0
#define LP_CTL_ULP_A_RB_RST_DBB_TMP_SEL_MASK    		0x1

#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_MAN_OFFSET	        1
#define LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_MAN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_SEL_OFFSET	        0
#define LP_CTL_ULP_A_RB_AON_TO_ULP_ISO_EN_SEL_MASK    		0x1

#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_VAL_OFFSET	        3
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SAV_VAL_MASK    		0x8
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_VAL_LEN	        1
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_VAL_OFFSET	        2
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_BOOT_VAL_MASK    		0x4
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_MAN_LEN	        1
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_MAN_OFFSET	        1
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_MAN_MASK    		0x2
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SEL_LEN	        1
#define	LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SEL_OFFSET	        0
#define LP_CTL_ULP_A_RB_SHIP_MODE_FLAG_SEL_MASK    		0x1

#define	LP_CTL_ULP_A_RB_D_PMU1_RSV_LEN	        16
#define	LP_CTL_ULP_A_RB_D_PMU1_RSV_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU1_RSV_MASK    		0xFFFF

#define	LP_CTL_ULP_A_RB_D_PMU_RC_32K_LP_RESERVE_LEN	        6
#define	LP_CTL_ULP_A_RB_D_PMU_RC_32K_LP_RESERVE_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU_RC_32K_LP_RESERVE_MASK    		0x3F

#define	LP_CTL_ULP_A_RB_D_PMU_XO_32K_ICTR_LEN	        6
#define	LP_CTL_ULP_A_RB_D_PMU_XO_32K_ICTR_OFFSET	        1
#define LP_CTL_ULP_A_RB_D_PMU_XO_32K_ICTR_MASK    		0x7E
#define	LP_CTL_ULP_A_RB_D_PMU_XO_32K_LP_EN_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_XO_32K_LP_EN_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU_XO_32K_LP_EN_MASK    		0x1

#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_ICTR_LEN	        4
#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_ICTR_OFFSET	        8
#define LP_CTL_ULP_A_RB_D_PMU_SYSLDO_ICTR_MASK    		0xF00
#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_RESERV_LEN	        4
#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_RESERV_OFFSET	        4
#define LP_CTL_ULP_A_RB_D_PMU_SYSLDO_RESERV_MASK    		0xF0
#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_VSET_LEN	        4
#define	LP_CTL_ULP_A_RB_D_PMU_SYSLDO_VSET_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU_SYSLDO_VSET_MASK    		0xF

#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_BIT0_RSV_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_BIT0_RSV_OFFSET	        13
#define LP_CTL_ULP_A_RB_D_PMU_IOLDO4_BIT0_RSV_MASK    		0x2000
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_EN_HIZ_LEN	        1
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_EN_HIZ_OFFSET	        12
#define LP_CTL_ULP_A_RB_D_PMU_IOLDO4_EN_HIZ_MASK    		0x1000
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_ICTR_LEN	        4
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_ICTR_OFFSET	        8
#define LP_CTL_ULP_A_RB_D_PMU_IOLDO4_ICTR_MASK    		0xF00
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_VSET_LEN	        8
#define	LP_CTL_ULP_A_RB_D_PMU_IOLDO4_VSET_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU_IOLDO4_VSET_MASK    		0xFF

#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_SET_LEN	        4
#define	LP_CTL_ULP_A_RB_D_PMU_UVLO_SET_OFFSET	        0
#define LP_CTL_ULP_A_RB_D_PMU_UVLO_SET_MASK    		0xF

#endif // __3322_LP_CTL_ULP_A_RB_REG_OFFSET_FIELD_H__
