/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_ulp_aon_fuse_ctl_rb_reg_offset.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_H__
#define __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_H__

/* ULP_AON_FUSE_CTL_RB Base address of Module's Register */
#define ULP_AON_FUSE_CTL_RB_BASE                       (0x57022000)

/******************************************************************************/
/*                      ULP_AON_FUSE_CTL_RB Registers' Definitions                            */
/******************************************************************************/

#define ULP_AON_FUSE_CTL_RB_EFUSE_RF_SYS_CTL_ID_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x0)   /* SYS CTL ID寄存器 */
#define ULP_AON_FUSE_CTL_RB_EFUSE_RF_GP_REG0_REG           (ULP_AON_FUSE_CTL_RB_BASE + 0x4)   /* 通用寄存器 */
#define ULP_AON_FUSE_CTL_RB_EFUSE_RF_GP_REG1_REG           (ULP_AON_FUSE_CTL_RB_BASE + 0x8)   /* 通用寄存器 */
#define ULP_AON_FUSE_CTL_RB_EFUSE_BOOT_DONE_REG            (ULP_AON_FUSE_CTL_RB_BASE + 0x20)  /* 通用寄存器 */
#define ULP_AON_FUSE_CTL_RB_EFUSE_AUTO_RD_EN_REG           (ULP_AON_FUSE_CTL_RB_BASE + 0x30)  /* 通用寄存器 */
#define ULP_AON_FUSE_CTL_RB_PMU1_TRIM_AON_CFG0_REG         (ULP_AON_FUSE_CTL_RB_BASE + 0x34)
#define ULP_AON_FUSE_CTL_RB_PMU1_TRIM_AON_CFG1_REG         (ULP_AON_FUSE_CTL_RB_BASE + 0x38)
#define ULP_AON_FUSE_CTL_RB_PMU1_TRIM_AON_CFG2_REG         (ULP_AON_FUSE_CTL_RB_BASE + 0x3C)
#define ULP_AON_FUSE_CTL_RB_PMU1_TRIM_SEL_AON_CFG0_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x40)
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_34_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x250) /* FUSE_CTL_AUTO_RD_34 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_35_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x254) /* FUSE_CTL_AUTO_RD_35 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_36_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x258) /* FUSE_CTL_AUTO_RD_36 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_37_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x25C) /* FUSE_CTL_AUTO_RD_37 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_38_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x260) /* FUSE_CTL_AUTO_RD_38 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_39_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x264) /* FUSE_CTL_AUTO_RD_39 */
#define ULP_AON_FUSE_CTL_RB_FUSE_CTL_AUTO_RD_40_REG        (ULP_AON_FUSE_CTL_RB_BASE + 0x268) /* FUSE_CTL_AUTO_RD_40 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_0_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x300) /* EFUSE0_CTL_BOOT_DATA_0 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_1_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x304) /* EFUSE0_CTL_BOOT_DATA_1 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_2_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x308) /* EFUSE0_CTL_BOOT_DATA_2 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_3_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x30C) /* EFUSE0_CTL_BOOT_DATA_3 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_4_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x310) /* EFUSE0_CTL_BOOT_DATA_4 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_5_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x314) /* EFUSE0_CTL_BOOT_DATA_5 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_6_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x318) /* EFUSE0_CTL_BOOT_DATA_6 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_7_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x31C) /* EFUSE0_CTL_BOOT_DATA_7 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_8_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x320) /* EFUSE0_CTL_BOOT_DATA_8 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_9_REG     (ULP_AON_FUSE_CTL_RB_BASE + 0x324) /* EFUSE0_CTL_BOOT_DATA_9 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_CTL_BOOT_DATA_10_REG    (ULP_AON_FUSE_CTL_RB_BASE + 0x328) /* EFUSE0_CTL_BOOT_DATA_10 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_0_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x330) /* EFUSE0_RB_REG_FULL_DATA_0 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_1_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x334) /* EFUSE0_RB_REG_FULL_DATA_1 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_2_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x338) /* EFUSE0_RB_REG_FULL_DATA_2 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_3_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x33C) /* EFUSE0_RB_REG_FULL_DATA_3 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_4_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x340) /* EFUSE0_RB_REG_FULL_DATA_4 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_5_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x344) /* EFUSE0_RB_REG_FULL_DATA_5 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_6_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x348) /* EFUSE0_RB_REG_FULL_DATA_6 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_7_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x34C) /* EFUSE0_RB_REG_FULL_DATA_7 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_8_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x350) /* EFUSE0_RB_REG_FULL_DATA_8 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_9_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x354) /* EFUSE0_RB_REG_FULL_DATA_9 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_10_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x358) /* EFUSE0_RB_REG_FULL_DATA_10 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_11_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x35C) /* EFUSE0_RB_REG_FULL_DATA_11 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_12_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x360) /* EFUSE0_RB_REG_FULL_DATA_12 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_13_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x364) /* EFUSE0_RB_REG_FULL_DATA_13 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_14_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x368) /* EFUSE0_RB_REG_FULL_DATA_14 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_15_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x36C) /* EFUSE0_RB_REG_FULL_DATA_15 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_16_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x370) /* EFUSE0_RB_REG_FULL_DATA_16 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_17_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x374) /* EFUSE0_RB_REG_FULL_DATA_17 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_18_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x378) /* EFUSE0_RB_REG_FULL_DATA_18 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_19_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x37C) /* EFUSE0_RB_REG_FULL_DATA_19 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_20_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x380) /* EFUSE0_RB_REG_FULL_DATA_20 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_21_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x384) /* EFUSE0_RB_REG_FULL_DATA_21 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_22_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x388) /* EFUSE0_RB_REG_FULL_DATA_22 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_23_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x38C) /* EFUSE0_RB_REG_FULL_DATA_23 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_24_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x390) /* EFUSE0_RB_REG_FULL_DATA_24 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_25_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x394) /* EFUSE0_RB_REG_FULL_DATA_25 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_26_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x398) /* EFUSE0_RB_REG_FULL_DATA_26 */
#define ULP_AON_FUSE_CTL_RB_EFUSE0_RB_REG_FULL_DATA_27_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x39C) /* EFUSE0_RB_REG_FULL_DATA_27 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_CTL_BOOT_DATA_12_REG    (ULP_AON_FUSE_CTL_RB_BASE + 0x3A4) /* EFUSE1_CTL_BOOT_DATA_12 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_0_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3A8) /* EFUSE1_RB_REG_FULL_DATA_0 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_1_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3AC) /* EFUSE1_RB_REG_FULL_DATA_1 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_2_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3B0) /* EFUSE1_RB_REG_FULL_DATA_2 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_3_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3B4) /* EFUSE1_RB_REG_FULL_DATA_3 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_4_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3B8) /* EFUSE1_RB_REG_FULL_DATA_4 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_5_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3BC) /* EFUSE1_RB_REG_FULL_DATA_5 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_6_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3C0) /* EFUSE1_RB_REG_FULL_DATA_6 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_7_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3C4) /* EFUSE1_RB_REG_FULL_DATA_7 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_8_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3C8) /* EFUSE1_RB_REG_FULL_DATA_8 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_9_REG  (ULP_AON_FUSE_CTL_RB_BASE + 0x3CC) /* EFUSE1_RB_REG_FULL_DATA_9 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_10_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3D0) /* EFUSE1_RB_REG_FULL_DATA_10 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_11_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3D4) /* EFUSE1_RB_REG_FULL_DATA_11 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_12_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3D8) /* EFUSE1_RB_REG_FULL_DATA_12 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_13_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3DC) /* EFUSE1_RB_REG_FULL_DATA_13 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_14_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3E0) /* EFUSE1_RB_REG_FULL_DATA_14 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_15_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3E4) /* EFUSE1_RB_REG_FULL_DATA_15 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_16_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3E8) /* EFUSE1_RB_REG_FULL_DATA_16 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_17_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3EC) /* EFUSE1_RB_REG_FULL_DATA_17 */
#define ULP_AON_FUSE_CTL_RB_EFUSE1_RB_REG_FULL_DATA_18_REG (ULP_AON_FUSE_CTL_RB_BASE + 0x3F0) /* EFUSE1_RB_REG_FULL_DATA_18 */

#endif // __3322_ULP_AON_FUSE_CTL_RB_REG_OFFSET_H__
