/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2025-2025. All rights reserved.
 * File name     :  3322_xip_cache_ctl_rb_reg_offset_field.h
 * Project line  :  Platform And Key Technologies Development
 * Department    :  CAD Development Department
 * Author        :  l00444884
 * Version       :  1.0
 * Date          :  2025/10/09
 * Description   :  The description of xxx project
 * Others        :  Generated automatically by nManager V5.1
 * History       :  l00444884 2025/03/05 17:25:13 Create file
 */

#ifndef __3322_XIP_CACHE_CTL_RB_REG_OFFSET_FIELD_H__
#define __3322_XIP_CACHE_CTL_RB_REG_OFFSET_FIELD_H__

#define	XIP_CACHE_CTL_RB_XIP_CACHE_CTL_ID_LEN	        16
#define	XIP_CACHE_CTL_RB_XIP_CACHE_CTL_ID_OFFSET	        0
#define XIP_CACHE_CTL_RB_XIP_CACHE_CTL_ID_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_XIP_GP_REG0_LEN	        15
#define	XIP_CACHE_CTL_RB_XIP_GP_REG0_OFFSET	        1
#define XIP_CACHE_CTL_RB_XIP_GP_REG0_MASK    		0xFFFE
#define	XIP_CACHE_CTL_RB_FUNC_BIST_CLK_SEL_LEN	        1
#define	XIP_CACHE_CTL_RB_FUNC_BIST_CLK_SEL_OFFSET	        0
#define XIP_CACHE_CTL_RB_FUNC_BIST_CLK_SEL_MASK    		0x1

#define	XIP_CACHE_CTL_RB_XIP_GP_REG1_LEN	        16
#define	XIP_CACHE_CTL_RB_XIP_GP_REG1_OFFSET	        0
#define XIP_CACHE_CTL_RB_XIP_GP_REG1_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_XIP_GP_REG2_LEN	        16
#define	XIP_CACHE_CTL_RB_XIP_GP_REG2_OFFSET	        0
#define XIP_CACHE_CTL_RB_XIP_GP_REG2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_XIP_GP_REG3_LEN	        16
#define	XIP_CACHE_CTL_RB_XIP_GP_REG3_OFFSET	        0
#define XIP_CACHE_CTL_RB_XIP_GP_REG3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_OPI0_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_OPI0_CLKEN_OFFSET	        11
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_OPI0_CLKEN_MASK    		0x800
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_NPU2MEM_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_NPU2MEM_CLKEN_OFFSET	        10
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_NPU2MEM_CLKEN_MASK    		0x400
#define	XIP_CACHE_CTL_RB_QSPI2_1CS_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_QSPI2_1CS_CLKEN_OFFSET	        1
#define XIP_CACHE_CTL_RB_QSPI2_1CS_CLKEN_MASK    		0x2

#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_PINMUX_CTL_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_PINMUX_CTL_CLKEN_OFFSET	        2
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_PINMUX_CTL_CLKEN_MASK    		0x4
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_XIP_SUB_DIAG_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_XIP_SUB_DIAG_CLKEN_OFFSET	        1
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_XIP_SUB_DIAG_CLKEN_MASK    		0x2
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_GMMU_RAM_CLKEN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_GMMU_RAM_CLKEN_OFFSET	        0
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_GMMU_RAM_CLKEN_MASK    		0x1

#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_PINMUX_CTL_N_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_PINMUX_CTL_N_OFFSET	        6
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_PINMUX_CTL_N_MASK    		0x40
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_XIP_SUB_DIAG_N_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_XIP_SUB_DIAG_N_OFFSET	        5
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_XIP_SUB_DIAG_N_MASK    		0x20
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_OPI0_XIP_N_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_OPI0_XIP_N_OFFSET	        3
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_OPI0_XIP_N_MASK    		0x8
#define	XIP_CACHE_CTL_RB_QSPI2_RST_SOFT_N_LEN	        1
#define	XIP_CACHE_CTL_RB_QSPI2_RST_SOFT_N_OFFSET	        1
#define XIP_CACHE_CTL_RB_QSPI2_RST_SOFT_N_MASK    		0x2
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_QSPI0_XIP_N_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_QSPI0_XIP_N_OFFSET	        0
#define XIP_CACHE_CTL_RB_CFG_XIPCACHE_SOFT_RST_QSPI0_XIP_N_MASK    		0x1

#define	XIP_CACHE_CTL_RB_AXI_2TO1_MUX_SEL_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_2TO1_MUX_SEL_OFFSET	        0
#define XIP_CACHE_CTL_RB_AXI_2TO1_MUX_SEL_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS2_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS2_OFFSET	        12
#define XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS2_MASK    		0x1000
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS1_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS1_OFFSET	        11
#define XIP_CACHE_CTL_RB_MEM_QSPI2_AUTO_CG_BYPASS1_MASK    		0x800
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_AUTO_CG_BYPASS_OFFSET	        10
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_AUTO_CG_BYPASS_MASK    		0x400
#define	XIP_CACHE_CTL_RB_MEM_BUS_ADAPT_CLK_AUTO_CG_BYPASS0_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_BUS_ADAPT_CLK_AUTO_CG_BYPASS0_OFFSET	        9
#define XIP_CACHE_CTL_RB_MEM_BUS_ADAPT_CLK_AUTO_CG_BYPASS0_MASK    		0x200
#define	XIP_CACHE_CTL_RB_PSRAM1_AXI_CLK_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_PSRAM1_AXI_CLK_AUTO_CG_BYPASS_OFFSET	        8
#define XIP_CACHE_CTL_RB_PSRAM1_AXI_CLK_AUTO_CG_BYPASS_MASK    		0x100
#define	XIP_CACHE_CTL_RB_PSRAM0_AXI_CLK_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_PSRAM0_AXI_CLK_AUTO_CG_BYPASS_OFFSET	        7
#define XIP_CACHE_CTL_RB_PSRAM0_AXI_CLK_AUTO_CG_BYPASS_MASK    		0x80
#define	XIP_CACHE_CTL_RB_SFC_CFG_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_SFC_CFG_AUTO_CG_BYPASS_OFFSET	        6
#define XIP_CACHE_CTL_RB_SFC_CFG_AUTO_CG_BYPASS_MASK    		0x40
#define	XIP_CACHE_CTL_RB_SFC_BUS_CLK_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_SFC_BUS_CLK_CG_BYPASS_OFFSET	        5
#define XIP_CACHE_CTL_RB_SFC_BUS_CLK_CG_BYPASS_MASK    		0x20
#define	XIP_CACHE_CTL_RB_SFC_WORK_CLK_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_SFC_WORK_CLK_CG_BYPASS_OFFSET	        4
#define XIP_CACHE_CTL_RB_SFC_WORK_CLK_CG_BYPASS_MASK    		0x10
#define	XIP_CACHE_CTL_RB_MEM_QSPI_X2H_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI_X2H_AUTO_CG_BYPASS_OFFSET	        3
#define XIP_CACHE_CTL_RB_MEM_QSPI_X2H_AUTO_CG_BYPASS_MASK    		0x8
#define	XIP_CACHE_CTL_RB_DSP_SHARE_AUTO_CG_BYPASS_EN_LEN	        1
#define	XIP_CACHE_CTL_RB_DSP_SHARE_AUTO_CG_BYPASS_EN_OFFSET	        2
#define XIP_CACHE_CTL_RB_DSP_SHARE_AUTO_CG_BYPASS_EN_MASK    		0x4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_AUTO_CG_BYPASS_EN_LEN	        1
#define	XIP_CACHE_CTL_RB_MAIN_AXI_AUTO_CG_BYPASS_EN_OFFSET	        1
#define XIP_CACHE_CTL_RB_MAIN_AXI_AUTO_CG_BYPASS_EN_MASK    		0x2
#define	XIP_CACHE_CTL_RB_SENSOR2MEM_X2X_AUTO_CG_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_SENSOR2MEM_X2X_AUTO_CG_BYPASS_OFFSET	        0
#define XIP_CACHE_CTL_RB_SENSOR2MEM_X2X_AUTO_CG_BYPASS_MASK    		0x1

#define	XIP_CACHE_CTL_RB_DDRCA_EN_LEN	        4
#define	XIP_CACHE_CTL_RB_DDRCA_EN_OFFSET	        1
#define XIP_CACHE_CTL_RB_DDRCA_EN_MASK    		0x1E
#define	XIP_CACHE_CTL_RB_DDRCA_ALGO_SEC_FLAG_DISABLE_LEN	        1
#define	XIP_CACHE_CTL_RB_DDRCA_ALGO_SEC_FLAG_DISABLE_OFFSET	        0
#define XIP_CACHE_CTL_RB_DDRCA_ALGO_SEC_FLAG_DISABLE_MASK    		0x1

#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE0_LEN	        16
#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE0_OFFSET	        0
#define XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE1_LEN	        16
#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE1_OFFSET	        0
#define XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE1_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE2_LEN	        16
#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE2_OFFSET	        0
#define XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE3_LEN	        16
#define	XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE3_OFFSET	        0
#define XIP_CACHE_CTL_RB_DDRCA_RANDOM_REE3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_CFG_WRITE_READ_EN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_WRITE_READ_EN_OFFSET	        2
#define XIP_CACHE_CTL_RB_CFG_WRITE_READ_EN_MASK    		0x4
#define	XIP_CACHE_CTL_RB_CFG_FIRST_32K_DATA_EN_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_FIRST_32K_DATA_EN_OFFSET	        1
#define XIP_CACHE_CTL_RB_CFG_FIRST_32K_DATA_EN_MASK    		0x2

#define	XIP_CACHE_CTL_RB_XIP_DIAG_MEMORY_FULL_LEN	        1
#define	XIP_CACHE_CTL_RB_XIP_DIAG_MEMORY_FULL_OFFSET	        11
#define XIP_CACHE_CTL_RB_XIP_DIAG_MEMORY_FULL_MASK    		0x800
#define	XIP_CACHE_CTL_RB_MONITOR_WADDR_LEN	        11
#define	XIP_CACHE_CTL_RB_MONITOR_WADDR_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_WADDR_MASK    		0x7FF

#define	XIP_CACHE_CTL_RB_RXDS_SEL_LEN	        16
#define	XIP_CACHE_CTL_RB_RXDS_SEL_OFFSET	        0
#define XIP_CACHE_CTL_RB_RXDS_SEL_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_OEN_LEN	        12
#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_OEN_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_IO_TEST_OEN_MASK    		0xFFF

#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_OUT_LEN	        12
#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_OUT_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_IO_TEST_OUT_MASK    		0xFFF

#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_IN_LEN	        12
#define	XIP_CACHE_CTL_RB_MEM_IO_TEST_IN_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_IO_TEST_IN_MASK    		0xFFF

#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_0_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_0_OFFSET	        1
#define XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_0_MASK    		0x2
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_0_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_0_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_MASK_0_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_MASK_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_MASK_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_STS_0_LEN	        4
#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_STS_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_STS_0_MASK    		0xF

#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_CLR_0_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_CLR_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_ACCESS_MEM_INT_CLR_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_REC_ADDR_L_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_REC_ADDR_L_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_REC_ADDR_L_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_REC_ADDR_H_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_REC_ADDR_H_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_REC_ADDR_H_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_REC_ID_0_LEN	        15
#define	XIP_CACHE_CTL_RB_MEM_REC_ID_0_OFFSET	        1
#define XIP_CACHE_CTL_RB_MEM_REC_ID_0_MASK    		0xFFFE
#define	XIP_CACHE_CTL_RB_MEM_REC_WR_0_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_REC_WR_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_REC_WR_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR_EN_0_LEN	        4
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR_EN_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR_EN_0_MASK    		0xF

#define	XIP_CACHE_CTL_RB_MEM_CFG_PKT_MONITOR_INT_DLY_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_CFG_PKT_MONITOR_INT_DLY_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_CFG_PKT_MONITOR_INT_DLY_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_L_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_L_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_L_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_H_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_H_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_L_H_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_L_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_L_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_L_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_H_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_H_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR0_H_H_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_L_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_L_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_L_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_H_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_H_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_L_H_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_L_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_L_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_L_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_H_0_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_H_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MONITOR_MEM_ADDR1_H_H_0_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_2_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_2_OFFSET	        1
#define XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_2_MASK    		0x2
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_2_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_2_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_2_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_2_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_2_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_2_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_2_LEN	        4
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_2_MASK    		0xF

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_2_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_2_MASK    		0x1

#define	XIP_CACHE_CTL_RB_REC_ADDR_L_2_LEN	        16
#define	XIP_CACHE_CTL_RB_REC_ADDR_L_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_ADDR_L_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_REC_ADDR_H_2_LEN	        16
#define	XIP_CACHE_CTL_RB_REC_ADDR_H_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_ADDR_H_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_REC_ID_2_LEN	        15
#define	XIP_CACHE_CTL_RB_REC_ID_2_OFFSET	        1
#define XIP_CACHE_CTL_RB_REC_ID_2_MASK    		0xFFFE
#define	XIP_CACHE_CTL_RB_REC_WR_2_LEN	        1
#define	XIP_CACHE_CTL_RB_REC_WR_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_WR_2_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_2_LEN	        4
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_2_MASK    		0xF

#define	XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_2_LEN	        16
#define	XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_2_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_2_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_2_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_3_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_3_OFFSET	        1
#define XIP_CACHE_CTL_RB_AXI_MONITOR_CLKEN_3_MASK    		0x2
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_3_LEN	        1
#define	XIP_CACHE_CTL_RB_AXI_MONITOR_EN_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_AXI_MONITOR_EN_3_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_3_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_3_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_3_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_MASK_3_MASK    		0x1

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_3_LEN	        4
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_STS_3_MASK    		0xF

#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_3_LEN	        1
#define	XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_ACCESS_MEM_INT_CLR_3_MASK    		0x1

#define	XIP_CACHE_CTL_RB_REC_ADDR_L_3_LEN	        16
#define	XIP_CACHE_CTL_RB_REC_ADDR_L_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_ADDR_L_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_REC_ADDR_H_3_LEN	        16
#define	XIP_CACHE_CTL_RB_REC_ADDR_H_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_ADDR_H_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_REC_ID_3_LEN	        15
#define	XIP_CACHE_CTL_RB_REC_ID_3_OFFSET	        1
#define XIP_CACHE_CTL_RB_REC_ID_3_MASK    		0xFFFE
#define	XIP_CACHE_CTL_RB_REC_WR_3_LEN	        1
#define	XIP_CACHE_CTL_RB_REC_WR_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_REC_WR_3_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_3_LEN	        4
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR_EN_3_MASK    		0xF

#define	XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_3_LEN	        16
#define	XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_CFG_PKT_MONITOR_INT_DLY_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_L_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_L_H_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_L_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR0_H_H_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_L_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_L_H_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_L_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_3_LEN	        16
#define	XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_3_OFFSET	        0
#define XIP_CACHE_CTL_RB_MONITOR_MEM_ADDR1_H_H_3_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S4_LEN	        4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S4_OFFSET	        12
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S4_MASK    		0xF000
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S3_LEN	        4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S3_OFFSET	        8
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S3_MASK    		0xF00
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S2_LEN	        4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S2_OFFSET	        4
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S2_MASK    		0xF0
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S1_LEN	        4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S1_OFFSET	        0
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S1_MASK    		0xF

#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S5_LEN	        4
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S5_OFFSET	        0
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_S5_MASK    		0xF

#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M5_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M5_OFFSET	        12
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M5_MASK    		0x7000
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M4_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M4_OFFSET	        9
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M4_MASK    		0xE00
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M3_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M3_OFFSET	        6
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M3_MASK    		0x1C0
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M2_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M2_OFFSET	        3
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M2_MASK    		0x38
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M1_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M1_OFFSET	        0
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M1_MASK    		0x7

#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M8_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M8_OFFSET	        8
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M8_MASK    		0x700
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M7_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M7_OFFSET	        5
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M7_MASK    		0xE0
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M6_LEN	        3
#define	XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M6_OFFSET	        2
#define XIP_CACHE_CTL_RB_MAIN_AXI_PRIORITY_M6_MASK    		0x1C

#define	XIP_CACHE_CTL_RB_DSP_SHARE_MODE_LEN	        4
#define	XIP_CACHE_CTL_RB_DSP_SHARE_MODE_OFFSET	        0
#define XIP_CACHE_CTL_RB_DSP_SHARE_MODE_MASK    		0xF

#define	XIP_CACHE_CTL_RB_DSP_SHARE_MODE_GT_LEN	        1
#define	XIP_CACHE_CTL_RB_DSP_SHARE_MODE_GT_OFFSET	        0
#define XIP_CACHE_CTL_RB_DSP_SHARE_MODE_GT_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AR_ERR_INT_CLR_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AR_ERR_INT_CLR_OFFSET	        3
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AR_ERR_INT_CLR_MASK    		0x8
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AW_ERR_INT_CLR_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AW_ERR_INT_CLR_OFFSET	        2
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_CFG_AW_ERR_INT_CLR_MASK    		0x4
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AXI_ERR_MINITOR_ENABLE_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AXI_ERR_MINITOR_ENABLE_OFFSET	        1
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AXI_ERR_MINITOR_ENABLE_MASK    		0x2
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_GLB_AXI_MINITOR_ENABLE_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_GLB_AXI_MINITOR_ENABLE_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_GLB_AXI_MINITOR_ENABLE_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_L_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_L_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_L_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_H_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_H_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWADDR_ERR_STS_H_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_L_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_L_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_L_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_H_LEN	        16
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_H_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARADDR_ERR_STS_H_MASK    		0xFFFF

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_INT_RAW_STATUS_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_INT_RAW_STATUS_OFFSET	        13
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_INT_RAW_STATUS_MASK    		0x2000
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_STS_VLD_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_STS_VLD_OFFSET	        12
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AR_ERR_STS_VLD_MASK    		0x1000
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARID_ERR_STS_LEN	        9
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARID_ERR_STS_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_ARID_ERR_STS_MASK    		0x1FF

#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_INT_RAW_STATUS_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_INT_RAW_STATUS_OFFSET	        13
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_INT_RAW_STATUS_MASK    		0x2000
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_STS_VLD_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_STS_VLD_OFFSET	        12
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AW_ERR_STS_VLD_MASK    		0x1000
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWID_ERR_STS_LEN	        9
#define	XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWID_ERR_STS_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_MAIN_AXI_AWID_ERR_STS_MASK    		0x1FF

#define	XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_BYPASS_LEN	        1
#define	XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_BYPASS_OFFSET	        7
#define XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_BYPASS_MASK    		0x80
#define	XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_XID0_LEN	        3
#define	XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_XID0_OFFSET	        4
#define XIP_CACHE_CTL_RB_CFG_PKT_ADAPT_XID0_MASK    		0x70
#define	XIP_CACHE_CTL_RB_CFG_MATCH_CNT0_LEN	        4
#define	XIP_CACHE_CTL_RB_CFG_MATCH_CNT0_OFFSET	        0
#define XIP_CACHE_CTL_RB_CFG_MATCH_CNT0_MASK    		0xF

#define	XIP_CACHE_CTL_RB_GMMU_RLUT_DSO_LEN	        1
#define	XIP_CACHE_CTL_RB_GMMU_RLUT_DSO_OFFSET	        13
#define XIP_CACHE_CTL_RB_GMMU_RLUT_DSO_MASK    		0x2000
#define	XIP_CACHE_CTL_RB_GMMU_RLUT_SDO_LEN	        1
#define	XIP_CACHE_CTL_RB_GMMU_RLUT_SDO_OFFSET	        12
#define XIP_CACHE_CTL_RB_GMMU_RLUT_SDO_MASK    		0x1000
#define	XIP_CACHE_CTL_RB_GMMU_WLUT_DSO_LEN	        1
#define	XIP_CACHE_CTL_RB_GMMU_WLUT_DSO_OFFSET	        11
#define XIP_CACHE_CTL_RB_GMMU_WLUT_DSO_MASK    		0x800
#define	XIP_CACHE_CTL_RB_GMMU_WLUT_SDO_LEN	        1
#define	XIP_CACHE_CTL_RB_GMMU_WLUT_SDO_OFFSET	        10
#define XIP_CACHE_CTL_RB_GMMU_WLUT_SDO_MASK    		0x400
#define	XIP_CACHE_CTL_RB_DIAG_MEM_DSO_LEN	        1
#define	XIP_CACHE_CTL_RB_DIAG_MEM_DSO_OFFSET	        9
#define XIP_CACHE_CTL_RB_DIAG_MEM_DSO_MASK    		0x200
#define	XIP_CACHE_CTL_RB_DIAG_MEM_SDO_LEN	        1
#define	XIP_CACHE_CTL_RB_DIAG_MEM_SDO_OFFSET	        8
#define XIP_CACHE_CTL_RB_DIAG_MEM_SDO_MASK    		0x100
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_1_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_1_OFFSET	        7
#define XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_1_MASK    		0x80
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_1_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_1_OFFSET	        6
#define XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_1_MASK    		0x40
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_1_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_1_OFFSET	        5
#define XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_1_MASK    		0x20
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_1_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_1_OFFSET	        4
#define XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_1_MASK    		0x10
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_0_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_0_OFFSET	        3
#define XIP_CACHE_CTL_RB_PSR_WS_MEM_DSO_0_MASK    		0x8
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_0_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_0_OFFSET	        2
#define XIP_CACHE_CTL_RB_PSR_WS_MEM_SDO_0_MASK    		0x4
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_0_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_0_OFFSET	        1
#define XIP_CACHE_CTL_RB_PSR_RP_MEM_DSO_0_MASK    		0x2
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_0_LEN	        1
#define	XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_0_OFFSET	        0
#define XIP_CACHE_CTL_RB_PSR_RP_MEM_SDO_0_MASK    		0x1

#define	XIP_CACHE_CTL_RB_L2M_GMMU_MEM_DSO_LEN	        3
#define	XIP_CACHE_CTL_RB_L2M_GMMU_MEM_DSO_OFFSET	        3
#define XIP_CACHE_CTL_RB_L2M_GMMU_MEM_DSO_MASK    		0x38
#define	XIP_CACHE_CTL_RB_L2M_GMMU_MEM_SDO_LEN	        3
#define	XIP_CACHE_CTL_RB_L2M_GMMU_MEM_SDO_OFFSET	        0
#define XIP_CACHE_CTL_RB_L2M_GMMU_MEM_SDO_MASK    		0x7

#define	XIP_CACHE_CTL_RB_L2M_DSP_MEM_DSO_LEN	        7
#define	XIP_CACHE_CTL_RB_L2M_DSP_MEM_DSO_OFFSET	        8
#define XIP_CACHE_CTL_RB_L2M_DSP_MEM_DSO_MASK    		0x7F00
#define	XIP_CACHE_CTL_RB_L2M_DSP_MEM_SDO_LEN	        7
#define	XIP_CACHE_CTL_RB_L2M_DSP_MEM_SDO_OFFSET	        0
#define XIP_CACHE_CTL_RB_L2M_DSP_MEM_SDO_MASK    		0x7F

#define	XIP_CACHE_CTL_RB_QSPI2_CUR_STS_LEN	        1
#define	XIP_CACHE_CTL_RB_QSPI2_CUR_STS_OFFSET	        0
#define XIP_CACHE_CTL_RB_QSPI2_CUR_STS_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSREQ_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSREQ_OFFSET	        9
#define XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSREQ_MASK    		0x200
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSREQ_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSREQ_OFFSET	        8
#define XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSREQ_MASK    		0x100
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSACK_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSACK_OFFSET	        7
#define XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CSYSACK_MASK    		0x80
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CACTIVE_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CACTIVE_OFFSET	        6
#define XIP_CACHE_CTL_RB_MEM_NPU2MEM_X2X_CACTIVE_MASK    		0x40
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSACK_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSACK_OFFSET	        5
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSACK_MASK    		0x20
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CACTIVE_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CACTIVE_OFFSET	        4
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CACTIVE_MASK    		0x10
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_BUSY_STATUS_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_BUSY_STATUS_OFFSET	        3
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_BUSY_STATUS_MASK    		0x8
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSACK_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSACK_OFFSET	        2
#define XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CSYSACK_MASK    		0x4
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CACTIVE_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CACTIVE_OFFSET	        1
#define XIP_CACHE_CTL_RB_MEM_QSPI2_X2P_CACTIVE_MASK    		0x2
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSREQ_LEN	        1
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSREQ_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_CSYSREQ_MASK    		0x1

#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_WBCNT_LEN	        4
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_WBCNT_OFFSET	        4
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_WBCNT_MASK    		0xF0
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_RBCNT_LEN	        4
#define	XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_RBCNT_OFFSET	        0
#define XIP_CACHE_CTL_RB_MEM_COM2MEM_A2X_RBCNT_MASK    		0xF

#define	XIP_CACHE_CTL_RB_SFC_RAM_RET1N_LEN	        1
#define	XIP_CACHE_CTL_RB_SFC_RAM_RET1N_OFFSET	        0
#define XIP_CACHE_CTL_RB_SFC_RAM_RET1N_MASK    		0x1

#endif // __3322_XIP_CACHE_CTL_RB_REG_OFFSET_FIELD_H__
