/*
 * Copyright (c) HiSilicon (Shanghai) Technologies Co., Ltd. 2021-2023. All rights reserved.
 *
 * Description: Common header file of the SOC register
 *
 */

#ifndef __SOC_REG_H__
#define __SOC_REG_H__

/* soc version: v0.281  date:2024/06/21  */
#include "3322_b_ctl_rb_reg_offset.h"
#include "3322_b_ctl_rb_reg_offset_field.h"
#include "3322_bcpu_trace_ctl_rb_reg_offset.h"
#include "3322_bcpu_trace_ctl_rb_reg_offset_field.h"
#include "3322_bt_diag_ctl_rb_reg_offset.h"
#include "3322_bt_diag_ctl_rb_reg_offset_field.h"
#include "3322_cfg_s_agpio_mode_reg_offset.h"
#include "3322_cfg_s_agpio_mode_reg_offset_field.h"
#include "3322_cfg_s_agpio_pad_reg_offset.h"
#include "3322_cfg_s_agpio_pad_reg_offset_field.h"
#include "3322_cfg_s_egpio_mode_reg_offset.h"
#include "3322_cfg_s_egpio_mode_reg_offset_field.h"
#include "3322_cfg_s_egpio_pad_reg_offset.h"
#include "3322_cfg_s_egpio_pad_reg_offset_field.h"
#include "3322_cfg_s_hgpio_mode_reg_offset.h"
#include "3322_cfg_s_hgpio_mode_reg_offset_field.h"
#include "3322_cfg_s_hgpio_pad_reg_offset.h"
#include "3322_cfg_s_hgpio_pad_reg_offset_field.h"
#include "3322_cfg_s_mgpio_mode_reg_offset.h"
#include "3322_cfg_s_mgpio_mode_reg_offset_field.h"
#include "3322_cfg_s_mgpio_pad_reg_offset.h"
#include "3322_cfg_s_mgpio_pad_reg_offset_field.h"
#include "3322_com_ctl_rb_reg_offset.h"
#include "3322_com_ctl_rb_reg_offset_field.h"
#include "3322_dp_reg_offset.h"
#include "3322_dp_reg_offset_field.h"
#include "3322_glb_ctl_b_rb_reg_offset.h"
#include "3322_glb_ctl_b_rb_reg_offset_field.h"
#include "3322_glb_ctl_d_rb_reg_offset.h"
#include "3322_glb_ctl_d_rb_reg_offset_field.h"
#include "3322_glb_ctl_m_rb_reg_offset.h"
#include "3322_glb_ctl_m_rb_reg_offset_field.h"
#include "3322_hs_ctl_rb_reg_offset.h"
#include "3322_hs_ctl_rb_reg_offset_field.h"
#include "3322_lp_ctl_audio_rb_reg_offset.h"
#include "3322_lp_ctl_audio_rb_reg_offset_field.h"
#include "3322_lp_ctl_bt_rb_reg_offset.h"
#include "3322_lp_ctl_bt_rb_reg_offset_field.h"
#include "3322_lp_ctl_glb_rb_reg_offset.h"
#include "3322_lp_ctl_glb_rb_reg_offset_field.h"
#include "3322_lp_ctl_mcu_rb_reg_offset.h"
#include "3322_lp_ctl_mcu_rb_reg_offset_field.h"
#include "3322_lp_ctl_ulp_a_rb_reg_offset.h"
#include "3322_lp_ctl_ulp_a_rb_reg_offset_field.h"
#include "3322_lp_ctl_ulp_b_rb_reg_offset.h"
#include "3322_lp_ctl_ulp_b_rb_reg_offset_field.h"
#include "3322_sfc_ctl_rb_reg_offset.h"
#include "3322_sfc_ctl_rb_reg_offset_field.h"
#include "3322_m_ctl_rb_reg_offset.h"
#include "3322_m_ctl_rb_reg_offset_field.h"
#include "3322_mcu_diag_ctl_rb_reg_offset.h"
#include "3322_mcu_diag_ctl_rb_reg_offset_field.h"
#include "3322_pmu2_cmu_ctl_rb_reg_offset.h"
#include "3322_pmu2_cmu_ctl_rb_reg_offset_field.h"
#include "3322_rf_ctl_rb_reg_offset.h"
#include "3322_rf_ctl_rb_reg_offset_field.h"
#include "3322_ssi_master_regbank_reg_offset.h"
#include "3322_ssi_master_regbank_reg_offset_field.h"
#include "3322_tee_ctl_rb_reg_offset.h"
#include "3322_tee_ctl_rb_reg_offset_field.h"
#include "3322_ulp_aon_fuse_ctl_rb_reg_offset.h"
#include "3322_ulp_aon_fuse_ctl_rb_reg_offset_field.h"
#include "3322_ulp_fuse_ctl_rb_reg_offset.h"
#include "3322_ulp_fuse_ctl_rb_reg_offset_field.h"
#include "3322_video_ctl_rb_reg_offset.h"
#include "3322_video_ctl_rb_reg_offset_field.h"
#include "3322_xip_cache_ctl_rb_reg_offset.h"
#include "3322_xip_cache_ctl_rb_reg_offset_field.h"


#endif  // __HAL_3322_SOC_REG_H__
