# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_VO_ARCH)/hal/drv_vo.c
SRCS += $(CBB_VO_ARCH)/hal/drv_vo_dev.c
SRCS += $(CBB_VO_ARCH)/hal/drv_vo_video.c

# Enum the C files of hal level
SRCS += $(CBB_VO_ARCH)/hal/hal_vo.c
SRCS += $(CBB_VO_ARCH)/hal/hal_vo_dev.c
SRCS += $(CBB_VO_ARCH)/hal/hal_vo_video.c
