obj-y += hi3403_disp.o

ccflags-y += \
    -I$(srctree)/drivers/hdf/framework/model/display/driver \
    -I$(srctree)/drivers/hdf/framework/include/utils \
    -I$(srctree)/drivers/hdf/framework/include/core \
    -I$(srctree)/drivers/hdf/framework/core/common/include/host \
    -I$(srctree)/drivers/hdf/framework/include \
    -I$(srctree)/drivers/hdf/framework/include/osal \
    -I$(srctree)/drivers/hdf/framework/include/platform \
    -I$(srctree)/drivers/hdf/framework/include/config \
    -I$(srctree)/drivers/hdf/inner_api/osal/shared \
    -I$(srctree)/drivers/hdf/inner_api/utils \
    -I$(srctree)/drivers/hdf/inner_api/core \
    -I$(srctree)/drivers/hdf/inner_api/host/shared \
    -I$(srctree)/drivers/hdf/khdf/osal/include \
    -I$(srctree)/include/linux \
    -I$(srctree)/include/drm \
    -I$(srctree)/bounds_checking_function/include
