# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_VO_ARCH_COMM_SRC)/drv_vo_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/drv_vo_dev_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/drv_vo_layer_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/drv_vo_video_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/drv_vo_coef_org_comm.c

# Enum the C files of hal level
SRCS += $(CBB_VO_ARCH_COMM_SRC)/hal_vo_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/hal_vo_dev_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/hal_vo_layer_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/hal_vo_video_comm.c
SRCS += $(CBB_VO_ARCH_COMM_SRC)/hal_vo_gfx_comm.c

