# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_VO_ROOT)/mkp/src/common/mkp_vo_comm.c
SRCS += $(CBB_VO_ROOT)/mkp/src/common/mkp_vo_proc.c
SRCS += $(CBB_VO_ROOT)/mkp/src/common/mkp_vo_init.c
SRCS += $(CBB_VO_ROOT)/mkp/src/common/mkp_vo_ioctl.c
SRCS += $(CBB_VO_ROOT)/mkp/src/dev/mkp_vo_dev.c
SRCS += $(CBB_VO_ROOT)/mkp/src/dev/mkp_vo_cascade.c
SRCS += $(CBB_VO_ROOT)/mkp/src/intf/mkp_vo_intf.c
SRCS += $(CBB_VO_ROOT)/mkp/src/intf/mkp_vo_intf_detect.c
