# Copyright (C) 2021 HiSilicon (Shanghai) Technologies CO., LIMITED.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

INC_PATH += -I$(CUR_DIR)/drm_hal
INC_PATH += -I$(MPP_PATH)/cbb/include
INC_PATH += -I$(MPP_PATH)/cbb/vo/vo_dev/drm_hal
INC_PATH += -I$(KERNEL_ROOT)/drivers/gpu/drm/hisilicon/hismart

HDMI_SRC += drm_hal/drm_hal_hdmitx.c
