#!/bin/bash
# gen_c4_fixture.sh — regenerate the on-board C4 image-compat fixture.
#
# Runs the fbb mkyaffs2image tool over a small deterministic sample tree
# (hello.txt + 3-chunk pattern.bin + subdir/nested.txt) and emits a C header
# with the raw image pages plus the expected file contents. The on-board
# test (fmc/yaffs/nand_yaffs_c4.c) writes these pages into the /boot volume
# via the mtd free-stream interface and lets the CLOSED archive mount them —
# the C4-② leg of YAFFS2_BINARY_LIB_PORTING_PLAN.md (fbb-image → NAND →
# closed-archive mount → content compare).
#
# Usage: bash gen_c4_fixture.sh <fbb-root> <out-header>
set -e
FBB=${1:?usage: gen_c4_fixture.sh <fbb-root> <out-header>}
OUT=${2:?usage: gen_c4_fixture.sh <fbb-root> <out-header>}
OUT=$(readlink -m "$OUT")
TOOL=$FBB/hs-fbb/src/tools/bin/platform_tool/mkyaffs2image/mkyaffs2image

WORK=$(mktemp -d /tmp/c4fix.XXXX)
trap 'rm -rf "$WORK"' EXIT
cd "$WORK"
mkdir -p src/subdir
printf 'hello yaffs c4\n' > src/hello.txt
python3 -c "open('src/pattern.bin','wb').write(bytes((i * 13 + 7) & 0xff for i in range(4608)))"
printf 'nested\n' > src/subdir/nested.txt

# 1 = 2K page, 2 = 64B oob (fbb mk_fs_image config: cfg_page_size/cfg_obb_size)
"$TOOL" src c4.img 1 2 > tool.log 2>&1 || { cat tool.log >&2; exit 1; }

python3 - "$OUT" <<'PYEOF'
import sys

out = sys.argv[1]
img = open('c4.img', 'rb').read()
hello = open('src/hello.txt', 'rb').read()
pattern = open('src/pattern.bin', 'rb').read()
nested = open('src/subdir/nested.txt', 'rb').read()
PAGE = 2112
assert len(img) % PAGE == 0, "image not page aligned"
npages = len(img) // PAGE

def arr(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i+16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)

with open(out, 'w') as f:
    f.write("""/*
 * AUTO-GENERATED by third_party/yaffs2/tools/gen_c4_fixture.sh — DO NOT EDIT.
 * On-board C4 image-compat fixture: fbb mkyaffs2image sample volume
 * (hello.txt + pattern.bin 3 chunks + subdir/nested.txt).
 * Tool args: <dir> <img> 1 2 (2048B page + 64B oob), fbb mk_fs_image config.
 */
#ifndef YAFFS2_C4_FIXTURE_H
#define YAFFS2_C4_FIXTURE_H

#define C4_IMAGE_PAGES %d
#define C4_PAGE_SIZE %d
#define C4_HELLO_LEN %d
#define C4_PATTERN_LEN %d
#define C4_NESTED_LEN %d

""" % (npages, PAGE, len(hello), len(pattern), len(nested)))
    f.write(arr("g_c4_image", img))
    f.write("\n\n")
    f.write(arr("g_c4_hello", hello))
    f.write("\n\n")
    f.write(arr("g_c4_pattern", pattern))
    f.write("\n\n")
    f.write(arr("g_c4_nested", nested))
    f.write("\n\n#endif /* YAFFS2_C4_FIXTURE_H */\n")

print(f"wrote {out}: {npages} pages ({len(img)}B), hello={len(hello)}B, "
      f"pattern={len(pattern)}B, nested={len(nested)}B")
PYEOF
