# Describe the include path, using the full path

# Enum the C files needed to be compiled, using the relative path
SRCS += $(CBB_BASE_ROOT)/mkp/src/video_buf.c
SRCS += $(CBB_BASE_ROOT)/mkp/src/cmpi_log.c
SRCS += $(CBB_BASE_ROOT)/mkp/src/cmpi_mod.c
SRCS += $(CBB_BASE_ROOT)/mkp/src/vb_supplement.c
